### ISSUE TITLE
`use` of submodule insufficient to `import` it

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15632] opened 2020-05-04 19:10 UTC
### Summary of Problem

A `use` of a module typically makes both its symbols and the module symbol itself visible within a given scope.  However, when `use`-ing a submodule, it seems that the identifier does not become resolvable for a sub-module as it does for other similar patterns (see https://github.com/Cray/chapel-private/issues/938 for related examples).

### Steps to Reproduce

**Associated Future Test(s):**
[`test/visibility/import/withUse/useImportSubmodule.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/visibility/import/withUse/useImportSubmodule.chpl
          ) #15631
[`test/visibility/import/withUse/useImportSubmodule2.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/visibility/import/withUse/useImportSubmodule2.chpl
          ) #15631

### Configuration Information

- Output of `chpl --version`: `1.23.0 pre-release (8f6e8e98d0)`

**Comment by lydia-duncan** [comment] 2020-06-18 16:06
Okay, so slight hiccup here.  The code that fails with the update that I currently have looks like this:
```chapel
module LongName {
  var x: int;
}
module L {
  var y: bool;
}
module User {
  use LongName as L; // Either fail on this line
  use L;

  proc main() {
    writeln(L.x); // Or fail on this line, L is ambiguous
    writeln(x);
  }
}
```
Basically, the problem is that the rename to L in the first use statement now causes the second use statement to refer to the same module (LongName) rather than the defined L.  Previously, this use resolved to the defined L and that caused a naming conflict when resolving L.x, and it still does if you reverse the order of the use statements.

This behavior changed because our resolution when importing modules and using modules shares the same code.

I'm not certain what to do about it.  I think we want to maintain the previous behavior for use statements?  Does that imply that:
- we should back away from this change?
  - I think this would mean updating documentation and/or double checking that it's consistent with behavior w.r.t. importing modules
- we should make it so directly used modules take lower precedence even than modules at outer scopes?
  - This seems like a bandaid and like it would be harder to notice when code behavior has changed in ways we don't want
- we should split it so that import statements can look at directly used modules but use statements can't?
  - Arguably this would be consistent, since import statements already have different semantics w.r.t. what can or cannot be referred to directly, but it will make the code more complex/spread out and potentially harder to maintain as a result.

I think I favor the last option, but maybe there's a better one I'm not thinking of?

**Comment by lydia-duncan** [comment] 2020-06-18 16:14
Actually, I'm realizing that this is also the reason behind Cray/chapel-private#889, so maybe the last option isn't great either . . .

**Comment by bradcray** [comment] 2020-06-18 16:59
At first blush, in your example, it seems reasonable to me to have the reference to `L` in `use L;` resolve to the `L` introduced by `use LongName as L;` much as it makes sense to me that in the following program:

```chapel
module M {
  proc foo() {
    writeln("In M.foo()");
  }
}

module N {
  record R {
    proc foo() {
      writeln("In R.foo()");
    }
  }
  proc main() {
    var M: R;
    use M;
    M.foo();
  }
}
```

the `use M;` resolves to the local variable `M` rather than the module `M`.  I.e., I think we have (and probably continue to want) resolved identifiers referenced by `use` statements similarly to other identifiers rather than treating them as special, and think that consistency is beneficial.

**Comment by lydia-duncan** [comment] 2020-06-18 20:50
Apparently the PR merge didn't close this, closing it manually

**Closed by lydia-duncan** 2020-06-18 20:50 UTC
Labels: area: Compiler, type: Bug
