### ISSUE TITLE
Leaks from DateTime standard module

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7894] opened 2017-11-29 23:47 UTC
### Summary of Problem
Usage of the DateTime module can lead to leaking ``TZInfo``-inheriting classes. Existing tests allocate a ``TZInfo`` and pass it to some ``DateTime`` method or initializer. Should ``DateTime`` records be responsible for deleting these classes? What if the record is copied?

The following tests leak:
- [ ] [testDatetimeTZ.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/standard/DateTime/testDatetimeTZ.chpl)
- [ ] [testTimezone.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/standard/DateTime/testTimezone.chpl)
- [ ] [testTimezoneConversions.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/standard/DateTime/testTimezoneConversions.chpl)

**Comment by bradcray** [comment] 2017-11-30 00:28
I've been looking for cases where we could put more weight on our `Owned`/`Shared` type in order to gain confidence that they're working as we'd like and will work for users.  If this is such a case, I'd love to see them used here.

Also, tagging @daviditen on this since he was the author of the module.

**Comment by mppf** [comment] 2018-02-26 16:14
testTimezone.chpl seems to no longer leak.
@daviditen - are you able to characterize the reason the remaining 2 still leak?

**Comment by daviditen** [comment] 2018-02-26 18:19
The leaks started happening on 2/15/2018 after PR #8417 was merged.

**Comment by ben-albrecht** [comment] 2018-06-26 20:49
> I've been looking for cases where we could put more weight on our Owned/Shared type in order to gain confidence that they're working as we'd like and will work for users. If this is such a case, I'd love to see them used here.

👍

**Comment by bradcray** [comment] 2018-07-10 20:13
@mppf: Any insights into what might be going wrong w.r.t. David's simplified test case above?

**Comment by mppf** [comment] 2018-08-03 15:13
I wonder if this is related to the memory leak reported by classes/ferguson/delete-free/owned-shared-fields2.chpl

**Comment by mppf** [comment] 2018-08-10 19:31
@daviditen - you'll never believe it.. but this patch fixes the leak:

```
diff --git a/modules/standard/DateTime.chpl b/modules/standard/DateTime.chpl
index 9a221e29fb..74ed922de7 100644
--- a/modules/standard/DateTime.chpl
+++ b/modules/standard/DateTime.chpl
@@ -1679,7 +1679,7 @@ module DateTime {
     }
 
     /* Convert a `time` in UTC to this time zone */
-    proc fromutc(in dt: datetime): datetime {
+    proc fromutc(dt: datetime): datetime {
       HaltWrappers.pureVirtualMethodHalt();
       return new datetime(0,0,0);
     }
```

The issue is that fromutc had `in` intent in the TZInfo class but was overridden to use default intent. That confused the compiler, since the `in` intent now happens at the call site. The compiler ran the copy at the call site (per the `in` intent) but the virtual method chosen didn't delete the formal temp, leading to the memory leak. The compiler TODO here is to check that intents in overrides.

**Comment by daviditen** [comment] 2018-08-10 19:47
Wow, good find @mppf, thanks!  A compiler check on the intents definitely sounds like a good idea.

**Closed** 2018-08-13 20:50 UTC
Labels: area: Modules, type: Bug
