### ISSUE TITLE
catastrophic error: cannot open source file "ISO_Fortran_binding.h"

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#12556] opened 2019-03-09 05:33 UTC
We run CI with various C/C++ compilers, including weekly runs with the latest Intel compilers.  
Somewhere between our Feb 21 and Feb 28 runs, something changed such that all builds of Chapel applications die with a message about ISO_Fortan_binding.h not being found.

One example is visible at http://upc-bugs.lbl.gov/upc_tests/detail.php?testname=external-chapel/fft&date=2019-03-07&config=EX-dirac-ibv-intel&branch=EX

CC: @bonachea

**Comment by bradcray** [comment] 2019-03-09 06:07
Hi Paul — Thanks for reporting this.  For context, this header is used to provide Chapel-Fortran interoperability.  I would've expected it only to be attempted to be `#include`d when we were actually compiling a library for use in Fortran interop, but instead it seems to be happening on every compilation due to its `use` in the DefaultRectangular module.  Tagging @daviditen and @lydia-duncan on this as the implementer and reviewer who added this.

**Comment by bradcray** [comment] 2019-03-09 06:34
Following up: I've got a proposed fix in PR #12557.  Our code freeze is coming up Monday, so I may merge speculatively tonight to get an additional night of testing on it.

**Comment by bradcray** [comment] 2019-03-09 08:24
My PR seems to be passing testing, but I didn't get it in in time for tonight's test run.  Will try again tomorrow.

**Comment by bradcray** [comment] 2019-03-09 21:29
@PHHargrove, @bonachea : If either of you are online this weekend, when would a run occur that would verify that this fixed the issue for you?  (put another way, when would I need to merge by to get verification that it's fixed, ideally before Monday's code freeze for Chapel 1.19?)

**Comment by bradcray** [comment] 2019-03-09 22:09
I've now merged the fix, but will leave this issue open until we've confirmed that it fixes it.

**Comment by PHHargrove** [comment] 2019-03-09 22:41
I will see if I can get a run in within the next few hours.

**Comment by PHHargrove** [comment] 2019-03-09 23:52
Tests on master at e87691f8 look good to me!

**Comment by bradcray** [comment] 2019-03-10 01:17
Great, thanks for the confirmation, Paul!

**Closed by bradcray** 2019-03-10 01:17 UTC

**Comment by ronawho** [comment] 2019-03-11 19:12
Presumably this means our Fortran interop doesn't work with the latest intel compilers. 19.0.0.117 is the latest I currently have access to to test with. I'll see if I can get my hands on 19.0.2.187 (version used in the failed gasnet config)

**Comment by PHHargrove** [comment] 2019-03-11 19:43
@ronawho our testing is on a system with a license only for Intel C/C++, but not Intel Fortran.  
I suspect that is a key part of the original problem.

**Comment by lydia-duncan** [comment] 2019-03-11 19:43
If that's the case, then that's concerning

**Comment by ronawho** [comment] 2019-03-11 19:58
Ah, that makes sense. Thanks Paul
