### ISSUE TITLE
List standard module `last()` method modifies the list.

### ISSUE THREAD

**Issue by OmarElawady** [chapel-lang/chapel#15366] opened 2020-03-27 17:42 UTC
### Summary of Problem

Calling the list `last` method returns a reference to the first element and assigns the value of the last element to it.

### Steps to Reproduce

**Source Code:**

```chapel
use List;
use List;
var l = new list(int);
l.append(1);
l.append(2);
ref x = l.last();
writeln(x);
writeln(l);// prints [2, 2]
x = 6;
writeln(l); // prints [6, 2]
```

**Compile command:**
`chpl list.chpl`

**Execution command:**
`./list`

### Configuration Information

- Output of `chpl --version`: chpl version 1.21.0 pre-release (2f36c637a4)
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by bradcray** [comment] 2020-03-27 18:34
The root cause of the bug is a misunderstanding that `ref` declarations in Chapel can be re-pointed at things when in fact once they are initialized, they always refer to the same thing (so appearing on the LHS of an assignment constitutes an assignment to the original thing pointed to).

**Comment by dlongnecke-cray** [comment] 2020-03-27 19:06
Fix for this on the way! https://github.com/chapel-lang/chapel/pull/15369

**Closed** 2020-03-27 19:57 UTC
Labels: area: Libraries / Modules, type: Bug
