### ISSUE TITLE
Determine eltType from "most general type" for all array elements

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8196] opened 2018-01-15 18:33 UTC
It appears I have to take all my integers in an array and put either a `.0` or at least `.` after the number.  For instance

```chapel
var d = Matrix([3.0 , 7, 4.3], [4.7 , 9, 22.8]);
> pginsert.chpl:29: error: Array literal element 2 expected to be of type real(64) but is of type int(64)
```

I think Chapel arrays assume `reals`, so why not just take that 7 at `7.0`?

**Comment by ben-albrecht** [comment] 2018-01-15 19:01
An even more distilled example of this:

```chpl
var A = [1, 2.0];
```

```bash
> chpl a.chpl
a.chpl:1: error: Array literal element 2 expected to be of type int(64) but is of type real(64)
```

**Comment by buddha314** [comment] 2018-01-15 19:03
it's like your shooting for the "everclear of array examples".  Gotta have goals in life.

**Comment by bradcray** [comment] 2018-01-15 19:11
> I think Chapel arrays assume reals

To help prevent the spread of misinformation: this statement isn't accurate—Chapel arrays can be of any type and no assumption is made about what the type is when looking at an array literal.

That said, the request is completely reasonable and appropriate.  I'd describe it as:  Try to find a unified "most general type" for all array elements, similar to how we do so for `return` statements that return different types:

```chapel
config var flag = true;

proc foo() {
  if flag then
    return 1;
  else
    return 2.3;
}

var a =	foo();
writeln(a.type:string);
```

**Comment by ben-albrecht** [comment] 2018-01-15 19:15
I believe what @buddha314 meant was that `LinearAlgebra.Matrix()` assumes `eltType=real` when no type is specified.

**Comment by ghbrown** [comment] 2022-08-30 00:40
I've had similar issues which I'll pile on here.

Type inference doesn't work quite like [the docs](https://chapel-lang.org/docs/modules/packages/LinearAlgebra.html) say. Docs say type is inferred from first array (row), but it seems to be inferred from the **first element** of each array, meaning there are `n_row` types and you'll get an error if they aren't the same.

```chapel
var A = Matrix([0,1.0],[0,0]) // gives error about expecting int but got real
var B = Matrix([0.0,1],[0,0]) // gives error about expecting float but got int
var C = Matrix([0.0,1.0],[0,0]) // gives error about dealing with matrix made from two arrays of different type
```
```
error for A:
scratch.chpl:6: error: Array literal element 1 expected to be of type int(64) but is of type real(64)

error for B:
scratch.chpl:6: error: Array literal element 1 expected to be of type real(64) but is of type int(64)

error for C:
scratch.chpl:6: error: unresolved call 'Matrix([domain(1,int(64),false)] real(64), [domain(1,int(64),false)] int(64))'
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:547: note: this candidate did not match: Matrix(rows, cols, type eltType = real)
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:547: note: because where clause evaluated to false
scratch.chpl:6: note: other candidates are:
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:610: note:   Matrix(const Arrays: ?t ...?n)
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:554: note:   Matrix(space: range, type eltType = real)
note: and 7 other candidates, use --print-all-candidates to see them
```
I at least expected that the `B` example would work since you can forgo the decimal on the left of `var a : real = XXXXX;`, but no luck.

Supplying `eltType` doesn't solve the problem either. For example,
```chapel
var A = Matrix([0,1],[0,0],real); // compiles as matrix full of reals
var B = Matrix([0.0,1],[0,0],real); // compilation error like B above
```

I haven't looked into it all, but it's behaving like `eltType` is getting used to to a post-parse cast, but what we want is that the value of `eltType` impacts how the elements are parsed. 

I'm compiling with `--set blasImpl=off`, my version is 1.28.0 pre-release (52662dacfb) built with LLVM version 14.0.6.

> I believe what @buddha314 meant was that LinearAlgebra.Matrix() assumes eltType=real when no eltType argument is specified.

Is this true? Maybe it used to be, but I'm not seeing it here.

**Comment by bradcray** [comment] 2022-08-30 01:16
@ghbrown : I think there are a few things going on here:

The first relates to what Chapel does w.r.t. type inference for array literals.  This is what Ben was distilling this issue down to in [his comment above](https://github.com/chapel-lang/chapel/issues/8196#issuecomment-357764408).  This is a language-level problem, and one that I agree we should address (specifically, I think it should use the same algorithm as is used for unifying `return` statements into a single type if possible, and generating an error otherwise).  In this context ("What's the type of this array literal?"), you're right that Chapel currently just infers the array literal type based on the first element, and then assumes/hopes that all the rest are the same.

Note that this first point is independent of the LinearAlgebra module because when we see patterns like `Matrix([0,1.0],[0,0])`, you're basically saying "Create these two 1D Chapel arrays" (as arguments) and then "pass them to the routine called `Matrix`.  So it's not really the Linear Algebra module's fault, which is what Ben was trying to show in his comment.

This first point is the cause of your first two errpors:

```chapel
var A = Matrix([0,1.0],[0,0]) // gives error about expecting int but got real
var B = Matrix([0.0,1],[0,0]) // gives error about expecting float but got int
```

The second thing is that when the documentation in the LinearAlgebra module refers to inferring types from things, it's assuming that these arrays already have well-defined types, and is just referring to the arguments it knows about.  So, for example in this case:

> ```
> procMatrix(const Arrays: ?t ...?n, type eltType)
> ```
> If type is omitted, it will be inferred from the first array.

it is saying that the type will be inferred from `Arrays[0].eltType`, not `Arrays[1].eltType` (i.e., the first of several arrays passed in).  That said, it doesn't explain why your third example, in which each of the Chapel arrays had a well-defined type, worked as it did:

```chapel
var C = Matrix([0.0,1.0],[0,0]) // gives error about dealing with matrix made from two arrays of different type
```

I'm timing out for this evening, but believe that the answer is much less interesting and that the routine simply wasn't written to be as flexible as you're hoping (though the documentation doesn't specify that either), and assumes that all the array rows passed in will have the same type.  Specifically, the formal argument  `Arrays: ?t... ?n` suggests to me that it'll take `n` arguments, all with the same type `t`.  But if each of the arrays has a different element type, that constraint won't hold true.  I'll try to take another look at this tomorrow to make sure I've got that straight.

**Comment by ghbrown** [comment] 2022-08-30 20:29
Thanks for the notes. I didn't piece together that my issue was a compound one from Ben's example, but that makes a lot of sense now.

I assume this means that the `eltType` argument doesn't/can't change how the elements are read from the source file. For my money this would be the biggest improvement, even if it didn't totally solve all the issues I listed.

**Comment by bradcray** [comment] 2022-08-31 00:21
> I assume this means that the eltType argument doesn't/can't change how the elements are read from the source file.

Unfortunately, that's correct.  The main issue you're hitting with mixed array element types is in the language and its implementation rather than this specific library routine (i.e., where the eltType argument comes in).

However, taking a quick look, I'm seeing a couple of modest adjustments I might be able make that would improve the situation (assuming no surprises turn up in regression testing them):

* the first is almost trivial and would cause an array literal like `[expr1, expr2, expr3]` to infer the array's element type based on the initial element, so long as all subsequent elements could be assigned to that first type.  Thus `[1.0, 2]` would be a legal way to write an array of reals, but `[1, 2.0]` would still cause problems since it would infer "array of int" but the real element can't legally be assigned to int (and of course it wouldn't be what you'd want anyway).  This would give more flexibility, but would still require you to be careful about the type of each initial element.

* the second is only slightly more complex, but could increase compile times (and generate worse error messages when the array elements weren't of a unifiable type), but uses some Chapel meta-programming to try and determine the "common type" of the elements in the array.  This causes both `[1.0, 2]` and [1, 2.0]` to be inferred to be arrays of real, for example.

We're working on cutting off changes for our next release this Thursday, and I could see trying to put the first into the release if it would be helpful to you.  If it doesn't go far enough or is still too annoying, that would be completely understandable.  The second feels like a big enough change that I'd feel gun-shy about putting it into the release without spending more time with it than I probably have this week.  That said, independent of the release, either change is a fairly minor patch to one of our internal modules, so something I could send you and you could try out locally to see whether it moved your work forward without blowing up compile times.

Longer-term, there is a better light on the horizon, though it's a little ways off yet.  Specifically (as you may already know), we're working on drastically refactoring our compiler to improve its speed and capabilities (the 'dyno' effort), and as part of that, we've written a new type unification analysis that is currently being used to infer the common type of multiple return statements (which is related to the second approach I used above).  However, we would also expect it to be applicable to situations like this "What's the common type of these array elements?" case.

Though that code is written, it's also something of a dead-end now, in that it doesn't lead back to the production compiler and back-end, which is what you'd need to make use of it—but that's what we're working towards.  I'm tagging @DanilaFe here who I believe has done most of this type unification work to date, with a question for each of you:

* Daniel, if we restricted ourselves to array literals whose elements were literals themselves (say, mixes of ints and reals, as in this example), would that be simpler to get working early in the dyno front-end since it wouldn't require full function resolution, as a case like `[fn1(), fn2(), fn3()]` might?  I realize in asking that that there's a slippery slope here since `-1` technically isn't an integer literal, but the unary operator `-` applied to the integer literal `1`... but users would likely think of it as an array literal).
* And then Gabriel: Are your array literals made up of literal values as in the examples here, or are you using richer expressions (like function calls or math operators) to compute the values?

**Comment by bradcray** [comment] 2022-08-31 16:45
@ghbrown: Following up on this, I believe I have a branch that would actually permit the user to choose between "infer array element types based on the first element" vs. "infer array element types based on a unified element type (inspecting all elements)" using a compile-time setting.  This would allow me to get both into the next release, and for users to choose how aggressive they wanted to be the compiler to be (where the downside of the "unified element type" approach is that I think it could blow up compile-times based on the approach taken since I'm doing this all outside of the compiler).  Testing last night looked good on both options, so I'm just trying to get it into a shape that I think it would be release-worthy and double-checking that there are no surprises.

**Comment by ghbrown** [comment] 2022-08-31 17:16
> I could see trying to put the first into the release if it would be helpful to you

I personally work from `main` or at least somewhat more recent than the release as needed, so it's not critical whether this makes it into the release or not as far as I'm concerned. If the first fix is easy enough and won't cause possible problems this close to release it might be a "nice to have" for others who only work from releases. It would actually solve my specific issue and give users a bit more control over this sort of thing, but I agree that a more complete solution would be even better.

> Are your array literals made up of literal values as in the examples here, or are you using richer expressions (like function calls or math operators) to compute the values?

Just literal values, though I agree at least "properly" supporting `-` is important.

**Comment by bradcray** [comment] 2022-09-01 00:13
@ghbrown: My solution is in #20563, if you're willing to download it and have the chance to try it out (with or without the optional flag to see how either mode works for you).  I've put it up in front of the team to see how people feel about it going into the release, though the fact that you're willing to work from `main` is definitely good to know.

Also, I wanted to mention that in poking through the LinearAlgebra `Matrix` code the other day, I found some minor things that  seem as though they could potentially be problematic (but I'm going to look at those in a separate effort).  I'm cautiously optimistic that this fix will help you dodge any further issues in `Matrix`, but don't feel certain (and haven't found the time to try and look at it again since opening up the PR).

**Closed** 2022-09-23 05:00 UTC
Labels: type: Feature Request, area: Language, user issue

**Comment by bradcray** [comment] 2022-09-24 00:21
@ghbrown: Following up on our conversation on #20563:

* I've verified that the example in the OP and BenA's first comment now work on `main`
* I've found that examples like the three in your first comment don't work due to the issues I thought I saw last month when I was first looking at this.  I'm currently surprised that almost anything of that "supply the rows of your arrays" as varargs worked.  I'll see whether I can get it into a better shape with a minimal amount of effort.

**Comment by bradcray** [comment] 2022-09-24 00:48
OK, I've got a fix that makes the five examples in [your comment](https://github.com/chapel-lang/chapel/issues/8196#issuecomment-1231012776) work.  I need to get it passing testing and reviewed, but am cautiously optimistic we will get it merged faster than the previous fix now that we're not in release mode.

**Comment by bradcray** [comment] 2022-09-27 17:22
@ghbrown: The fix I mentioned above is merged now.  I believe array literals and matrix factories are working about as well as they can until the compiler takes over the type unification work (and potentially improves it), but definitely let us know if you find other cases that aren't working as you'd expect or hope.  Thanks for drawing attention back to this long-neglected issue.

**Comment by ghbrown** [comment] 2022-09-27 17:47
Thanks for your work on this, I think it's a great improvement!
