### ISSUE TITLE
Cannot define param-sized int from within a module

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#11645] opened 2018-11-14 22:34 UTC
This code does not work when it feels like it should. Using a param `x` to define an `int(x)` *from within a module*.
```chapel
config param Value1: uint = 10;
config param Size1: uint = 64;

record MyUint1 {
  var value: uint = Value1;
  var data: uint(Size1); // Okay
}

// From within a module.
module M2 {
  config param Value2: uint = 10;
  config param Size2: uint = 64;
  record MyUint2 {
    var value: uint = Value2;
    var data: uint(Size2); // error: use of 'Size2' before encountering its definition, type unknown
  }

  // From within a submodule
  module SM {
    record MyUint3 {
      var value: uint = Value2;
      var data: uint(Size2); // error: use of 'Size2' before encountering its definition, type unknown
    }
  }
}

// Type alias
module M3 {
  param Size = 64;
  type Type = uint(Size); // internal error: COD-TYP-0050
}

module M4 {
  type Type = uint(Size1); // Okay
}
```

`config` does not change behavior of error.

Only workaround is to place these type-defining params at file-level module.

`chpl version 1.19.0 pre-release (03b75e298e)`

**Comment by DanilaFe** [comment] 2024-07-15 17:39
The code here works on `main` today. When I was writing logic to print the values of the various param constants, I tried to add logic to the outermost module to print the type in `M4`, which did not go over well, because that type depends on the value of the outermost module (as a result, there's a cyclic dependency `Outer -> M4 -> Outer`). However,  there are no issues about param-sized ints present, so I will be opening a regression test PR and closing this.

**Closed** 2024-07-15 18:13 UTC
Labels: type: Bug, area: Compiler, user issue
