### ISSUE TITLE
Clarify the construction of parallel iterators

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8364] opened 2018-02-02 21:04 UTC
Looks like [Parallel Iterators](https://chapel-lang.org/docs/master/primers/parIters.html#count-standalone-parallel) are pretty damn important.  In trying to follow the tutorial, I got a bit lost.  Now, it is most likely my fault, but here are some things that I was wondering.

1. What is a `tag`?  Why is it useful? What does it really do here?  When I think "tag", I think of a way to index something for later.  Like "tag this as inappropriate".
1. What are the values and subsequent impacts of the `iterKind` enum?
1. So a parallel iterator can be a leader OR a follower or does it have to be BOTH?
1. It would be good to show the full code, it feels like the examples are broken up.
   1. In there, point to exactly where "leading" and "following" occurs
1. I could not imagine how to abstract `computeChunk` into other problems.

My habit is to find a small chunk of code I can compile and run, then refer back to the docs to see where it breaks.

I don't want to be all negative.  The colors on the page are really nice.

Thanks for your patience.

**Comment by ben-albrecht** [comment] 2018-02-02 21:10
> 5. I could not imagine how to abstract computeChunk into other problems.

On that note, this primer should probably be updated to use [RangeChunk](https://chapel-lang.org/docs/master/modules/packages/RangeChunk.html) instead of a custom chunking function.

**Comment by bradcray** [comment] 2018-02-02 21:23
I think a big problem with the current parallel iterators primers is that it starts with leader-follower iterators (the complicated case) before going to standalone parallel iterators.  This reflects the order in which the features were added to the language, and hence the primer.  I think the more natural way to approach it would be to start with the standalone case (easier to understand, and arguably the common / simpler case) and then expand to leader-follower as an advanced topic "for those users who want to write parallel iterators that support zippering".

**Comment by ronawho** [comment] 2018-10-22 19:34
Can/should we close this as a duplicate of https://github.com/chapel-lang/chapel/issues/6343?

**Comment by ben-albrecht** [comment] 2018-10-22 19:47
Probably, but I think @buddha314's feedback as a user should be taken into account when closing #6343

**Comment by bradcray** [comment] 2018-10-22 20:10
I cross-linked to this issue in my description of #6343 and am closing this one as a duplicate.

**Closed** 2018-10-22 22:48 UTC
Labels: area: Docs, stat: Duplicate, type: Feature Request, user issue

**Comment by bradcray** [comment] 2018-10-22 23:14
Or maybe Elliot is... (could've sworn I hit the close button... :) ).
