### ISSUE TITLE
Initializers allow initializing a param field with a non-param value

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#8406] opened 2018-02-08 06:24 UTC
### Summary of Problem

```chapel
class C {
  param p: int;
  proc init() {
    var x = 7;
    p = x;
    super.init();
  }
}

var c = new C();
writeln(c);
delete c;
```

[edit 2/9 cassella -- simplify test case to no longer use a record. ]

```
fortytwo@magrathea:~/src/chpl/tfn$ chpl param-from-record.chpl 
In file included from /tmp/chpl-fortytwo-8306.deleteme/_main.c:28:0:
/tmp/chpl-fortytwo-8306.deleteme/ChapelIO.c: In function ‘writeThisFieldsDefaultImpl’:
/tmp/chpl-fortytwo-8306.deleteme/ChapelIO.c:237:13: error: ‘call_tmp_chpl’ undeclared (first use in this function)
 call_tmp7 = call_tmp_chpl;
             ^
/tmp/chpl-fortytwo-8306.deleteme/ChapelIO.c:237:13: note: each undeclared identifier is reported only once for each function it appears in
/home/fortytwo/src/chapel/runtime/etc/Makefile.exe:27: recipe for target '/tmp/chpl-fortytwo-8306.deleteme/param-from-record.tmp' failed
make: *** [/tmp/chpl-fortytwo-8306.deleteme/param-from-record.tmp] Error 1
error: compiling generated source
```

I'd have expected an error on the ``p = x`` line since ``x`` isn't a param.

[ edit again 2/9 cassella -- adjust the expected behavior too. ]

**Associated Future Test(s):**
None yet.

### Configuration Information

```
fortytwo@magrathea:~/src/chpl/tfn$ chpl --version
chpl version 1.17.0 pre-release (ee5378d)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

fortytwo@magrathea:~/src/chpl/tfn$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

fortytwo@magrathea:~/src/chpl/tfn$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
```

**Comment by lydia-duncan** [comment] 2018-02-08 23:02
Sigh.  I think this is because field initialization is the only time we try to assign into a param on a different line from where it was declared, which fools our param validation.  Thanks for pointing it out, I'm not sure we'll get to this right away.  If you could file a test against it, that would be handy.

**Comment by cassella** [comment] 2018-02-09 06:14
I wrote the .future in #8421 with an ``int`` instead of the ``record R``.

**Comment by cassella** [comment] 2018-02-09 06:23
Is the following a different case?  It results in the same behavior.

```chapel
config var x = 42;

class C {
  param r = x;
  proc init() { }
}
```

(I didn't think of it until after submitting that other future.)

**Comment by lydia-duncan** [comment] 2018-02-09 16:18
> Is the following a different case?

Yes, since omitted initialization follows a slightly different path than explicit initialization in an initializer.  Anyone resolving this bug would want to ensure both worked and might need to do extra work to get both instead of just one.  So it would be useful to submit both, but you don't have to.

**Comment by lydia-duncan** [comment] 2018-02-09 16:25
Is this issue now a duplicate of #8422 and #8423?

**Comment by cassella** [comment] 2018-02-09 16:33
I think there are three problems.  The code above contains two of them.  I should have cleaned it up once I figured that out.  In my mind, this one is for the issue in the new future: you can write an initializer that initializes a param field with a non-param value.  I think the three issues are separate.

**Closed** 2018-02-13 21:18 UTC
Labels: area: Compiler, type: Error Message
