### ISSUE TITLE
Calling functions that capture outer variables in `cobegin`s doesn't work

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#18138] opened 2021-07-29 00:18 UTC
... well not exactly.

```chapel
proc foo(multiplier) {
  /* works

  forall i in 1..2 {
    multiplier.multiply(i);
  }

  */

  cobegin { // doesn't work
    multiplier.multiply(1);
    multiplier.multiply(2);
  }
}

proc main() {
  var a = [1,2,3];

  record Multiplier {
    proc multiply(i: int) {
      writeln(a*i);
    }
  }

  foo(new Multiplier());
}
```

The function that we call must be a method on an object that's passed to this function. Also the outer-variable that was captured mustn't be a global variable. i.e. if you don't have an explicit `main` in the reproducer, it works fine.

The error comes from the backend compiler:

```
/var/folders/66/q9t7c6ks1172pm1401tzz8rw000ynq/T//chpl-ekayraklio.deleteme-31chBd/prasanth2.c:72:43: error: 
      use of undeclared identifier 'a_chpl'
multiply_chpl(multiplier_chpl, INT64(1), &a_chpl);
                                          ^
/var/folders/66/q9t7c6ks1172pm1401tzz8rw000ynq/T//chpl-ekayraklio.deleteme-31chBd/prasanth2.c:90:43: error: 
      use of undeclared identifier 'a_chpl'
multiply_chpl(multiplier_chpl, INT64(2), &a_chpl);
```

This was initially reported by @prashanth018. What he's hitting is this new `cobegin` that was added here https://github.com/chapel-lang/chapel/commit/453aefc46348b281f092cc20e81dcc69c5a47fb0. That `cobegin` should be reverted if the solution to the actual problem isn't too easy.

**Comment by e-kayrakli** [comment] 2021-07-29 00:19
Pinging @mppf as one of the reviewers of that PR on the Sort module.

**Comment by mppf** [comment] 2021-07-29 13:34
This is a duplicate of #17623.

**Comment by mppf** [comment] 2021-07-29 13:38
A workaround is to move the `record Multiplier` outside of `proc main`.

**Closed** 2021-09-08 17:58 UTC
Labels: type: Bug, area: Compiler
