### ISSUE TITLE
Local module `use` breaks visibility of copy initializers?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8231] opened 2018-01-17 23:42 UTC
### Summary of Problem

It appears that a local `use` of a module that defines a copy initializer can break compilation
due to the copy initializer not being visible, even within that same scope.  I ran into this when
converting the `DateTime` module over to initializers (in PR #8141) which broke @benharsh's
elegant CoMD test due to its local `use` of DateTime.  Moving the `use` to module scope
fixed the issue and is a workaround we applied to make forward progress (but one that should
be reverted once this issue is fixed).

I reproduced this in a simpler standalone test in:
[`test/types/records/init/copy/localUseNoCopy.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/records/init/copy/localUseNoCopy.chpl
          ) #8141

With a minimal effort, I was not able to reproduce it in a standalone test that didn't rely
on the `DateTime` issue (but timed out before trying very hard).

### Configuration Information

- Output of `chpl --version`: `chpl Version 1.17.0 pre-release (14176f2)`

**Comment by benharsh** [comment] 2018-01-19 00:49
I will be opening a PR soon to update this .future with a smaller reproducer.

This all starts during 'resolveAutoCopies', and we eventually end up in 'fixupDefaultInitCopy'. This function appears to try and implement ``chpl__initCopy`` in terms of a copy initializer if one is available. To test if one is available, we insert a call that looks like a copy initializer and try to resolve the new call.

We will soon attempt to find the list of visible functions and walk up the scope. The instantiation point of the ``chpl__initCopy`` call guides the scope to the module in which ``chpl_gen_main`` resides. In a simple program like the one I'm about to submit, this is the same module as the user-defined ``main``.

If I have globally ``use``'d the module that defines the type we're trying to init-copy, then our visible-function-finding logic will see the use-statement and all is well. If the use-statement is within another function, like ``main``, then we will not find the copy initializer.

Later in resolution (probably during callDestructors) we may run into a problematic pattern. If we return the type from a function, the compiler may attempt to insert an initCopy. Because we could not resolve the copy initializer, this initCopy is flagged as erroneous and will cause a fatal error towards the end of callDestructors.

I did a quick experiment and observed that this is the case even when the copy initializer is resolved. I also tried calling ``hasCopyConstructor(ct)`` within ``fixupDefaultInitCopy`` and it returned true, despite the 'init' call failing to resolve.

@noakesmichael and @lydia-duncan : Any thoughts on how to fix this issue?

**Comment by lydia-duncan** [comment] 2018-01-19 17:43
@mppf may also have some insights into this problem.

For the first part of the problem (`chpl__initCopy` not finding the use that would lead it to the copy initializer), it seems to me that initCopy is looking to see if we can the initializer generally, but it is only visible when a `use` has occurred.  We could solve that problem by having `chpl__initCopy` resolve in the same scope as the type was declared - however, since callDestructors does not use resolution to find the initCopy it calls, if a call was inserted at a scope that did not have a `use`, that would cause the generated C compilation to fail (because it couldn't actually find the copy initializer).

> I did a quick experiment and observed that this is the case even when the copy initializer is resolved. 
To make sure I'm understanding correctly - does this mean that the copy initializer has been resolved in other contexts but wasn't found for the initCopy, or that the initCopy call worked but was still marked as erroneous?

**Comment by benharsh** [comment] 2018-01-19 19:01
The copy initializer was resolved and used in other contexts, but was not found for the initCopy.

**Comment by mppf** [comment] 2018-01-19 21:50
I believe I have a fix for this issue in PR #8256.

**Closed** 2018-02-05 14:48 UTC
Labels: area: Compiler, type: Bug
