### ISSUE TITLE
Coercions from integers to real(32)?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7740] opened 2017-11-03 14:39 UTC
PR #7659 will enable coercions from params/literals to `real(32)` when they fit. But it leaves open the question of whether or not we wish to allow implicit conversion for non-param values from `int(32)` to `real(32)`, which is currently disallowed. Or, for that matter, from `int(64)` to `real(32)`. Another way to ask this question is if the following program should compile:

``` chapel
var i:int(32) = 7;
var y:real(32) = i;
```

The language specification describes in section 9.1.1 that we allow conversion from `int(64)` to `real(64)` as a convenience even though there is a possible loss of precision:

>Rationale.  We allow these additional conversions because they are an important convenience for application programmers. Therefore we are willing to lose precision in these cases. The largest real and complex types are chosen to retain precision as often as as possible.

Should we do the same for `int(32)` for `real(32)`? What about `uint(32)`? Or `int(64)`?

**Comment by mppf** [comment] 2017-11-03 14:42
Here is a comment from @bradcray (from issue #5922) reproduced here to seed the discussion a little bit:

> Looking at the code, I don't think "oversight" covers our failure to support int->real(32) coercions, because we very explicitly exclude it.  But that's not to say that we made the right decision.  I'm currently exploring what implications might be if we were to relax this.
>
> Here's my best guess as to why we disallowed it when this was implemented:
>
> 1) We generally wanted to create a language that would only support coercions when the original value would not be compromised by the conversion (e.g., we don't support int(64)->int(32) coercions, except when the int(64) value is known to the compiler and can be represented by int(32)).
> 2) We understood that there are integer values which can't be represented as floating point values without loss of accuracy which would suggest not permitting ints to coerce to floats by principle 1 unless the int's legal range of values completely fit within the float's mantissa.
> 3) At the same time, we knew that we wanted ints to coerce to some sort of floating point type because requiring casts for -every_ int(64)->real(64) coercion would be too counterproductive.
> 4) As a result, I think we only opened the door to coercions to real(64) and not real(32) figuring that the number of int value cases that could lose accuracy would be less.
>
> That said, I'm not prepared to argue that this was the right decision -- I think we made it conservatively, figuring it would be easier to relax it later than to try and put the cows back in the barn.  See also my disclaimer above about not having floating point expertise on the team at that time.  Perhaps int->float conversions should always be permitted without worrying about losing accuracy.
>
> Interestingly, we often went to C# as a reference point in questions of coercions, and I'm noting that they permit both ints and longs to coerce to floats and doubles which also suggests we were being unduly cautious:  https://msdn.microsoft.com/en-us/library/y5b434w4.aspx

**Comment by mppf** [comment] 2017-11-03 14:45
According to Brad's C# reference, they allow the equivalent of `int(64)`, `uint(64)` both coercible to `real(32)`.

**Comment by damianmoz** [comment] 2017-11-21 15:28
If the issue is wanting to be able to do
.......................var x : real(32) = 123456789;
what is wrong with
.......................var x : 123456789:real(32);
and not allowing implicit coercions at all, i.e. all such coercions must be explicit. So not even int(64) to real(64).
Normally I find default coercions stab me in the back because I have done something wrong in the first place. And I forget the default coercion rules anyway.  I like caution. Also if you are trying to do some sort of generic programming, you can really twist yourself in knots.

Why not a compiler flag --cautious=N where N in (0..9) where 0 is laissez-faire and 9 paranoid. Maybe that is a lot of work in that, not sure.

And finally, paraphrasing Michael, do programmers really understand how much of an approximation there is in going from a larger integer to a floating point representation?

**Comment by mppf** [comment] 2022-04-22 20:53
See in particular https://github.com/chapel-lang/chapel/issues/19194#issuecomment-1037909843 and https://github.com/chapel-lang/chapel/issues/19194#issuecomment-1039222219 which discuss a case where allowing `int(32)` -> `real(32)` would be less surprising.

**Comment by bradcray** [comment] 2022-05-16 18:37
@mppf: I was thinking we could close this due to #19749 being merged, but noticed that the OP touches on the question of whether `int(64)` should coerce to `real(32)`.  My instinct is "no", and I don't feel as though this is a case users have asked for, but let me know whether you want to leave this issue open to keep that question open, or to open a new issue specifically about that question, or to let it fall by the wayside until someone requests it.

**Comment by damianmoz** [comment] 2022-05-16 19:39
The impact of Chapel's unique and distinct way of handling integral values within a floating point expression is certainly reduced with #19749.

However, because Chapel does coerce int(64) to real(64), it will be a source of error when refactoring Fortran and C/C++ expressions when **real**(64) is not the dominant **real**(w) type. It will happen with any other language for that matter unless that language follows the same rule as Chapel and I know of none.. Even standalone, this type of coercion totally destroys the whole mathematics behind an error analysis of a floating point expression and provides the wrong answer to what a good numerical analyst would expect in that same situation.. So, at the very least, such a coercion when **real**(64) is not the dominant real(w) type should be able to be flagged with an optional warning.message from the compiler as the problem can easily go undetected and become a ticking time bomb sitting inside a chunk of seemingly innocent Chapel code. Thanks.

**Comment by damianmoz** [comment] 2022-05-16 20:06
This coercion can also be a major source of error even when trying to write truly generic code for a floating point algorithm, further evidence that this warning message is needed to help avoid the problems it raises.

**Comment by bradcray** [comment] 2022-05-16 22:18
Hi Damian —

>  ...it will be a source of error...
> It will happen with...

Can you clarify what the source of error you're referring to is here?  Maybe with an example?  Since C/C++ also permit `int64_t` to coerce to `double`, I've got to assume it's something other than that, yet am not able to guess what.  Thanks.

**Comment by damianmoz** [comment] 2022-05-17 02:44
It was asked
>Can you clarify what the source of error you're referring to is here?
See here the attached file for the mathematics behind this.

If that is unclear, please read any numerical analysis text if you need an answer today and do the mathematics. You need to go looking at an operation like say
```chapel
fl ( a * x )   OR   fl (a * x + b * y)
```
where `a` and `b` are **real**(32), `x`  and `y` are **int**(64) and `fl` is the act of performing a floating point operation. Expand out the `fl` function. Even with the first, you end up proving that the error as computed by Chapel for the majority of floating point expressions could be a factor of 2**29 different than that in C/C++ or Fortran or Pascal or Algol or ...

Also, it was noted:
> Since C/C++ also permit int64_t to coerce to double
Permit, yes, but perform by default, definitely not. Let me know if you need the clause in the standard on what the language does. I think it is 6.3 something, and maybe 6.3.1.8, but I could be wrong. In C/C++ the coercion (and hence precision of the arithmetic operation) is dictated by the highest precision **real**(w) operand in the expression, not by the precision of the **int**(?) operand. And Fortran and others do the same as C/C++.

I am not suggesting a change to the behaviour, just that it be noted so that it can be explicitly corrected where it occurs to get the behaviour that conventional numerical analysis expects and just about every other useful language on the planet delivers. Mind you, C took over 20 years to sort out the similar mess that was introduced by doing floating point computations to at least 64 bit precision. So maybe we are condemned to the same duration of time to fix this issue. I hope not.

[numerical-errors.pdf](https://github.com/chapel-lang/chapel/files/8704679/numerical-errors.pdf)

**Comment by mppf** [comment] 2022-05-17 11:34
@damianmoz - thanks for clearly explaining this difference from C/C++/Fortran for us. I don't think I had understood it yet. I wanted to verify and also was curious about how it interacted with 16-bit floating point types so I wrote a little C program to demonstrate. I also verified that the C# follows the C behavior here, FWIW. See the details below if you are curious.

<details>

Here is a little program I used to verify C's behavior here:

``` c
// compile with clang on an ARM system

#include <stdio.h>

int main() {
  int myInt32 = 4;
  long myInt64 = 4;
  _Float16 myReal16;
  float myReal32 = 32.1;
  double myReal64 = 32.1;
  printf("sizeof(myInt32) = %li\n", sizeof(myInt32));
  printf("sizeof(myInt64) = %li\n", sizeof(myInt64));
  printf("sizeof(myReal16) = %li\n", sizeof(myReal16));
  printf("sizeof(myReal32) = %li\n", sizeof(myReal32));
  printf("sizeof(myReal64) = %li\n", sizeof(myReal64));
  printf("\n");

  printf("sizeof(myInt32 + myReal16) = %li\n", sizeof(myInt32 + myReal16));
  printf("sizeof(myInt32 + myReal32) = %li\n", sizeof(myInt32 + myReal32));
  printf("sizeof(myInt32 + myReal64) = %li\n", sizeof(myInt32 + myReal64));
  printf("sizeof(myInt64 + myReal16) = %li\n", sizeof(myInt64 + myReal16));
  printf("sizeof(myInt64 + myReal32) = %li\n", sizeof(myInt64 + myReal32));
  printf("sizeof(myInt64 + myReal64) = %li\n", sizeof(myInt64 + myReal64));

  return 0;
}
```

```
sizeof(myInt32) = 4
sizeof(myInt64) = 8
sizeof(myReal16) = 2
sizeof(myReal32) = 4
sizeof(myReal64) = 8

sizeof(myInt32 + myReal16) = 2
sizeof(myInt32 + myReal32) = 4
sizeof(myInt32 + myReal64) = 8
sizeof(myInt64 + myReal16) = 2
sizeof(myInt64 + myReal32) = 4
sizeof(myInt64 + myReal64) = 8
```

Interestingly, C# also follows the same rules:

``` c#
// to run this on linux
// sudo apt-get install mono-complete
// csharp program.cs

int myInt32;
long myInt64;
float myReal32;
double myReal64;

Console.WriteLine("myInt32 type " + myInt32.GetType());
Console.WriteLine("myInt64 type " + myInt64.GetType());
Console.WriteLine("myReal32 type " + myReal32.GetType());
Console.WriteLine("myReal64 type " + myReal64.GetType());
Console.WriteLine();

Console.WriteLine("myInt32 + myReal32 type " + (myInt32 + myReal32).GetType());
Console.WriteLine("myInt32 + myReal64 type " + (myInt32 + myReal64).GetType());
Console.WriteLine("myInt64 + myReal32 type " + (myInt64 + myReal32).GetType());
Console.WriteLine("myInt64 + myReal64 type " + (myInt64 + myReal64).GetType());
```

```
myInt32 type System.Int32
myInt64 type System.Int64
myReal32 type System.Single
myReal64 type System.Double

myInt32 + myReal32 type System.Single
myInt32 + myReal64 type System.Double
myInt64 + myReal32 type System.Single
myInt64 + myReal64 type System.Double
```

</details>

@damianmoz - one question I have for you is - do you think this behavior (always go with the floating point type when choosing what type to use for the operation) makes sense for smaller floating point types (e.g. `real(16)` or even `real(8)`)? Of course Chapel does not have these types now but I would imagine that we are likely to add them at some point. From my C example above, I can see that even `myInt64 + myReal16` produces a 16-bit real. Anyway, I would suppose that they can be rationalized with the theory that a floating point somehow approximates all numbers.

I imagine that arranging for `myInt64 * myReal32` to end up with a `real(32)` is something that we could do without causing a lot of problems (and Brad's PR already changes the behavior of programs working with `int(32)` and `real(32)` so I am not too worried about breaking compatibility here since we have already done so). Furthermore this is an area where it's probably better for Chapel to be similar to previous languages rather than having a different rule. So far, I am not aware of any benefit we are enjoying from this difference from C/C++/Fortran/C#/... .

As far as how exactly to achieve that with language rules / compiler changes, I am less certain. I would imagine that the implementation changes would be similar to #19749, though, so I think trying to implement it would be a reasonable next step.

**Comment by damianmoz** [comment] 2022-05-21 01:54
Some thoughts attached.

[MixedModeII.pdf](https://github.com/chapel-lang/chapel/files/8746138/MixedModeII.pdf)

I tried to keep it to one page so I apologize if it is too brief or curt. Happy to elaborate.

**Comment by damianmoz** [comment] 2022-05-22 00:23
The mathematics of numerical errors is more complex than my two small PDFs, each one page or less., might make out. But I hope I have covered the general drift. If it is perceived that I have not made a strong enough case, it is more than my own words were sadly inadequate rather than that the case is not extremely strong for a change to Chapel's default behaviour when dealing with mixed mode arithmetic..

**Comment by bradcray** [comment] 2022-06-02 00:22
Sorry for dropping the line here, and thanks for the additional explanations @damianmoz.  I also did a little test (in C++) and came to a similar conclusion to @mppf—that we're more of an outlier here than I realized (and I appreciate Michael looking at C# in this regard as that was what we'd been relying on for certain type/sizing questions in the early days, though apparently we missed this aspect somewhere along the way).

I'd be very comfortable having `int` of any size coerce to `real(32)` and prefer it based on this conversation.

Here's my C++ code for reference (where it's basically C code that's taking advantage of C++ to get overloading):

```cpp
#include <cstdint>
#include <cstdio>

void op(float x, float y) {
  printf("In float op()\n");
}

void op(double x, double y) {
  printf("In double op()\n");
}

int main() {
  int64_t x;
  float y;
  op(x, y);
  op(y, x);
}
```

Output is `In float op()` x 2.

**Comment by damianmoz** [comment] 2022-06-02 01:12
Thanks for the feedback. Urgency was not crucial.

Sorry, I had not realised that you were basing your discussions of C#.. My comments were based on Fortran, C and C++ which dominate the numerical application space. C# is not even on my radar for such things.

You mention
> I'd be very comfortable having int of any size coerce to real(32) and prefer it based on this conversation.

Is that really the rule we want? That still disagrees with Fortran,, C/C++, and even C#. What happens when you have the half-floats, the _Float16s? In those other languages, the integral types are coerced to the dominant floating point type within an expression. I think I have quoted the paragraph in the C standard for its rule. The compiler should feel free to warn about any loss of accuracy that it thinks is introduced by such a coercion.

**Comment by bradcray** [comment] 2022-06-02 01:15
Yeah, sorry, in talking in terms of `real(32)`, I was only speaking in terms of the immediate set of types and changes we'd need to make, not the rule for a future in which we had other, narrower `real` types.

**Comment by mppf** [comment] 2022-06-02 11:21
> Sorry, I had not realised that you were basing your discussions of C#.. My comments were based on Fortran, C and C++ which dominate the numerical application space. C# is not even on my radar for such things.

We try to understand the precedent from multiple languages. It is not a problem that you were focused on C/C++/Fortran.

> Is that really the rule we want? ... In those other languages, the integral types are coerced to the dominant floating point type within an expression.

Yes, I think we are talking about the same thing here, and some specific cases are:

* myInt64 + myReal32 produces a 32-bit real (and similarly for other operators)
* myInt64 + myReal16 produces a 16-bit real (in a future when we have 16-bit reals)

It turns out that these rules are determined by the overload disambiguation rules (rather than something about `+`), at least today. I think that when @bradcray said:

> I'd be very comfortable having `int` of any size coerce to `real(32)` and prefer it based on this conversation.

the "prefer it" part is about which overload of `+` is chosen. But anyway, like I said, I think we are on the same page here.

**Comment by damianmoz** [comment] 2022-06-02 12:34
Yes. all on the same page.

**Closed** 2022-08-31 21:04 UTC
Labels: type: Design, area: Language
