### ISSUE TITLE
Internal compilation error EXP1163 encountered for function typed to return tuple with array

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#8140] opened 2018-01-06 01:13 UTC
### Summary of Problem
Internal compilation error EXP1163 encountered when compiling code where a function is explicitly typed to return a tuple containing an array:

```chapel
proc foo( input_array : [?dom] real ) : ([dom] real,) {
  return (input_array,);
}
```

However, there is no error when the function is untyped:
```chapel
proc foo( input_array : [?dom] real ) {
  return (input_array,);
}
```

### Steps to Reproduce

**Source Code:**

```chapel
proc foo( input_array : [?dom] real ) : ([dom] real,) {
  return (input_array,);
}

proc main(){
  var input_array : [1..10] real;
  var tuple = foo( input_array );
  // Below also produces the error
  // var (array,) = foo( input_array );
}
```

**Compile command:**
`chpl foo.chpl`

### Configuration Information

- Output of `chpl --version`:
```
chpl Version 1.16.0.e43acc7
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version`:
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mppf** [comment] 2018-01-08 15:25
The resolve pass is creating a call to _parloopexpr2 in the body of proc foo but the function itself is being removed from the AST and pruned.

**Comment by mppf** [comment] 2018-01-08 16:27
I created a branch to fix the immediate issue but I'm seeing problems with recursive parallel iterators. Maybe @vasslitvinov can help?

**Comment by benharsh** [comment] 2018-10-10 23:29
Closing this because the reproducer seems to be compiling and running successfully now, possibly due to various loop-expr improvements or improvements to arrays-as-return-types.

**Closed by benharsh** 2018-10-10 23:29 UTC
Labels: area: Compiler, type: Bug, user issue

**Comment by mppf** [comment] 2018-10-11 12:55
@benharsh - has the problematic code been added to the test system? If not, could you add it somewhere, so we'll know if it happens again? Might be nice to put the issue number in a comment in the test.

**Comment by benharsh** [comment] 2018-10-11 15:53
Looks like you beat me to it back in March: ``users/ibertolacc/specified-return-type-tuple-array.chpl``
