### ISSUE TITLE
parallelism disappears when value returned from a promoted function is ignored

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#11203] opened 2018-09-20 18:54 UTC
I am observing no parallelism upon `PLUS2(A,B)` below.
Whereas `PLUS1(A,B)` is computed in parallel.
PLUS2(A,B) should be computed in parallel, too.

```chpl
config const n = 4;
var A, B: [1..n, 1..n] int;
proc PLUS1(a:int, b:int) { writeln(a + b); }
proc PLUS2(a:int, b:int) { writeln(a + b); return 0; }

PLUS1(A,B);
PLUS2(A,B);
```

[Updated] developer notes:
* Elliot nails down the cause in his [comment below](#issuecomment-424533378).
* Alas we do not want to resort to `buildForallLoopStmt()` because it uses tryToken.
* Turns out: no wonder.  The promoted PLUS2 is fed into this:
```chpl
  inline proc _statementLevelSymbol(ir: _iteratorRecord) {
    iter _ir_copy_recursive(ir) {
      for e in ir do
        yield chpl__initCopy(e);
    }
    pragma "no copy" var irc = _ir_copy_recursive(ir);
    for e in irc { }
  }
```

See also lack of parallelism with forall-expressions: #11622.

Tests:
```
test/parallel/forall/vass/performance/promo-value-unused--arrays.chpl
test/parallel/forall/vass/performance/promo-value-unused--iterators.chpl
```

**Comment by vasslitvinov** [comment] 2018-09-20 20:17
I verified parallelism is present in a promoted-stream-like program:

```chpl
config const m = 100,
             alpha = 3.0;

const ProblemSpace = {1..m};
var A, B, C: [ProblemSpace] real;

proc main {
  writeln("start");
  A = B + alpha * C;
  writeln("end");
}
```

**Comment by ronawho** [comment] 2018-09-25 22:27
@vasslitvinov do you see parallelism if you change `PLUS2(A,B);` to `var C = PLUS2(A,B);`?

The latter should trigger `=` on arrays, which will go to `chpl__transferArray()`, which should explicitly do a `forall (c, ab) in zip(C, ir_AB) do c = ab` and we'll build up an ir that can operate in parallel in the compiler. I'm not sure what code paths are taken for just the `PLUS2(A,B);` case, but I can confirm that seems to be serial from the generated code.

**Comment by vasslitvinov** [comment] 2018-09-25 23:01
@ronawho - yes, I see parallelism in `var C = PLUS2(A,B);`

Good to know that you see plain `PLUS2(A,B);` to be serial.

**Comment by ronawho** [comment] 2018-09-25 23:20
As far as why `PLUS1` is parallel, but `PLUS2` isn't, I suspect that's from:

https://github.com/chapel-lang/chapel/blob/4da4e81886ce5123228c4788f397034ca6597ddd/compiler/resolution/wrappers.cpp#L2222-L2235

This code has changed a lot since I last looked at it, so I don't quite understand the logic there. I suspect we're either not building up the parallel loop for the non-void case or it's building incorrectly and getting covered over by a `tryToken` resolving the serial case or something.

**Comment by bradcray** [comment] 2018-09-25 23:31
> getting covered over by a tryToken resolving the serial case or something.

Now you're just making me salivate thinking that putting in an effort to get rid of tryToken would've helped avoid this surprise / a potential backslide.

**Comment by ronawho** [comment] 2018-09-25 23:45
Oh, or maybe we're just invoking a serial loop. In the `var C =` case, there's an explicit forall in module code that will invoke the parallel iters, but maybe in this case we're just calling a serial loop by default. Not sure if this is right (and I'm just looking at this issue briefly to distract myself from slides), but the following seems to work at least for the small reproducer. 

```diff
diff --git a/compiler/resolution/wrappers.cpp b/compiler/resolution/wrappers.cpp
index e6d3124d00..97858fcf78 100644
--- a/compiler/resolution/wrappers.cpp
+++ b/compiler/resolution/wrappers.cpp
@@ -2290,7 +2290,7 @@ static BlockStmt* buildPromotionLoop(PromotionInfo& promotion,
   // Save the wrapCall to adjust it later
   promotion.wrapCalls.push_back(wrapCall);

-  return ForLoop::buildForLoop(indices, iterator, yieldBlock, false, zippered);
+  return   buildForallLoopStmt(indices, iterator, NULL, yieldBlock,  zippered);
 }

 static void buildLeaderIterator(FnSymbol* wrapFn,
```

@vasslitvinov could you add the reproducer as a test/future. You can probably add a correctness tests that throws `debugDataPar` or one of the debug flags to capture if parallelism is created. There are other tests that do this that I would try to model after. Maybe test/distributions/sungeun/dataPar2.chpl

**Closed** 2019-02-07 03:10 UTC
Labels: area: Compiler, type: Performance
