### ISSUE TITLE
Argument parsing errors with start_test

### ISSUE THREAD

**Issue by sungeunchoi** [chapel-lang/chapel#4949] opened 2016-12-06 01:37 UTC
### Summary of Problem
I found a few issues with argument parsing:

- The `--compopts` and `--execopts` flags do not work when using `=` (a space must be used).  It appears as though the first character is truncated.
- Using shortened versions of the above flags, e.g., `--compo` or `--execo`, with a space and an argument, results in a start_test usage: error:
```
start_test: error: argument -compopts/--compopts: expected one argument
```
- Certain styles of invalid flags results in the flags being interpreted as test names (e.g., `--compt="--fast --static"` does so, but not `--compt="--fast"` (correctly returns usage message), `--numx="2 x"` but not `--numx=2`)

### Steps to Reproduce

**Source Code:**

N/A

**Compile command:**

N/A

**Execution command:**

N/A

### Configuration Information

- Output of `chpl --version`:
chpl Version 1.14.0.a10da81
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
N/A
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
N/A
- (For Cray systems only) Output of `module list`:
N/A

**Comment by ben-albrecht** [comment] 2016-12-06 23:41
> The --compopts and --execopts flags do not work when using = (a space must be used). It appears as though the first character is truncated.

This is caused by lines [633](https://github.com/chapel-lang/chapel/blob/ad6e21921762629950c97c4a914fdd22730577d8/util/start_test#L633) and [640](https://github.com/chapel-lang/chapel/blob/ad6e21921762629950c97c4a914fdd22730577d8/util/start_test#L640) of `start_test`.

Not sure what purpose this truncation serves. Will have to look into it more.

**Comment by ben-albrecht** [comment] 2016-12-07 23:09
> Using shortened versions of the above flags, e.g., --compo or --execo, with a space and an argument, results in a start_test usage ...

I reproduced this in a [toy program](https://gist.github.com/ben-albrecht/f73bf354bdea4f021e8d3bad926140a3).

Out of all the combinations I tried, I found only`--compo=--fast` works as expected.

As far as I can tell, this is an issue with Python's argparse. Our best bet might be to  recommend against using abbreviated flags (offering single character abbreviations of our own, instead maybe?) Sadly, disabling abbreviations isn't supported until Python 3.5.

**Comment by ben-albrecht** [comment] 2017-08-11 22:15
In summary:

> The --compopts and --execopts flags do not work when using = (a space must be used). It appears as though the first character is truncated.

I think this can be fixed by adding an `arg.replace('=', ' ')` in `preprocess_options()`.

> Using shortened versions of the above flags, e.g., --compo or --execo, with a space and an argument, results in a start_test usage error.

This is an issue with argparse. Not much we can do.

**Comment by bradcray** [comment] 2018-03-21 00:14
@ben-albrecht: From your comment above, I'm tempted to close this one, but can you verify?

**Comment by ben-albrecht** [comment] 2018-03-21 12:37
> The --compopts and --execopts flags do not work when using = (a space must be used). It appears as though the first character is truncated.

This part of the issue could still be resolved IMO. It's an unexpected behavior in the python command line interface, due to something odd we're doing.

I believe the string truncation we're doing [here](https://github.com/chapel-lang/chapel/blob/ad6e21921762629950c97c4a914fdd22730577d8/util/start_test#L633) is that odd thing, and still am not sure why we do it exactly. @ronawho || @benharsh - do either of you recall?

----

For the shortened flags issue, there's not much we can do. We can kind of resolve it by disabling abbreviations for support python 3 for `start_test` (#8784).

**Comment by ronawho** [comment] 2018-03-21 16:15
Yeah, we wrap `--compopts` and `--execopts` with quotes:

https://github.com/chapel-lang/chapel/blob/ad6e21921762629950c97c4a914fdd22730577d8/util/start_test#L1352-L1358

We do this because argparse likes to treat any `--` (such as `--fast`) as an argument to argparse. So for something like `--compopts --fast` argparse would try to treat `--fast` as an option and fail because that's not an option start_test supports, so we preprocess to make it `--compopts "--fast"` and then at some point we have to strip the quotes off:

https://github.com/chapel-lang/chapel/blob/ad6e21921762629950c97c4a914fdd22730577d8/util/start_test#L632-L643

I think our handling of that just didn't consider `--compopts=--fast`. In that case we probably aren't adding quotes to it, but are still trying to strip quotes (that aren't there) off, which truncates the option

I think the issue with the abbreviated options is similar. We only only recognize `[-]-compopts` and `[-]-execopts` as things to preprocess, not abbreviated forms, but we still try to strip the quotes off of args.compopts and args.execopts.

For that we could just expand the our preprocessing to handle the abbreviated forms as well.

**Comment by ben-albrecht** [comment] 2018-03-22 15:00
> Fix handling of compopts/execopts in start_test #8906 

Looks like I pinged the right person!

**Closed** 2018-04-26 17:29 UTC
Labels: area: BTR, type: Bug
