### ISSUE TITLE
Numerical instability in LCALS IF_QUAD kernel

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11336] opened 2018-10-10 21:36 UTC
The LCALS IF_QUAD kernel produces very different results for different compilers because it is numerically unstable. The program below - which is based on the LCALS benchmark code in test/release/examples/benchmarks/lcals - produces very different output for `--fast` vs `--no-fast` in a manner that is machine dependent. The below code has been modified to print out the number of `sqrt` calls made and additionally to print out the latter portion of the input arrays. It can be observed that the number of `sqrt` as well as the checksum total can be wildly different. The particular values of the input arrays chosen make the comparison very numerically unstable.

What can be done about this? I recommend that we simply disable the checksumming for this particular test. Changing the kernel or its input would impact comparisons to the C LCALS code.

Reproducer below.

``` chapel
config const num_samples = 3000; // "long"
config const len = 44217; // "long"

proc main() {
  var RealArray_1D: [0..10][0..#len] real;

  for i in 1..5 do
    initData(RealArray_1D[i-1], i);

  ref a  = RealArray_1D[0];
  ref b  = RealArray_1D[1];
  ref c  = RealArray_1D[2];
  ref x1 = RealArray_1D[3];
  ref x2 = RealArray_1D[4];

  writeln(a[44000..44004]);
  writeln(b[44000..44004]);
  writeln(c[44000..44004]);

  var nsqrts = 0;

  for 0..#num_samples {
    for i in 0..#len {
      var s = b[i]*b[i] - 4.0*a[i]*c[i];
      if s >= 0.0 {
        nsqrts += 1;
	s = sqrt(s);
	x2[i] = (-b[i]+s) / (2.0*a[i]);
	x1[i] = (-b[i]-s) / (2.0*a[i]);
      } else {
	x2[i] = 0.0;
	x1[i] = 0.0;
      }
    }
  }

  var expect = -1954669733.3743642342742532491684;

  var chksum: real = 0.0;
  updateChksum(chksum, len, RealArray_1D[3]);
  updateChksum(chksum, len, RealArray_1D[4]);

  writeln("Got checksum ", chksum, " expected ", expect);
  writeln("nsqrts is ", nsqrts);
}

proc initData(ra: [] real, id: int) {
  const factor: real = if id % 2 != 0 then 0.1 else 0.2;
  for (r,j) in zip(ra, 0..) {
    r = factor*(j + 1.1)/(j + 1.12345);
  }
}

proc updateChksum(ref chksum:real, length: int, 
                  ra: [] real, scale_factor: real = 1.0) {
  use LongDouble;

  ref data = ra;
  var len = ra.numElements;

  var tchk: longdouble = chksum;
  for (j, dat) in zip(0..#len, data) {
    tchk += (j+1)*dat*scale_factor;
  }
  chksum = tchk:real;
}

```

**Comment by mppf** [comment] 2018-10-30 13:16
I'm not sure.

@daviditen - could we still see checksum mismatches in performance runs?

**Comment by mppf** [comment] 2018-11-07 17:49
I think that's a problem.

**Comment by ronawho** [comment] 2019-04-16 00:28
FYI here's a simpler reproducer for this:

```chpl
proc main() {
  var RealArray_1D: [0..2][0..#1] real;

  for i in 1..3 do
    initData(RealArray_1D[i-1], i);

  var a = RealArray_1D[0][0];
  var b = RealArray_1D[1][0];
  var c = RealArray_1D[2][0];

  var s = b*b - 4.0*a*c;
  writeln("s >= 0: " +  (s >= 0.0));
  writeln(s);
}

proc initData(ra: [] real, id: int) {
  const factor: real = if id % 2 != 0 then 0.1 else 0.2;
  for (r,j) in zip(ra, 0..) {
    r = factor*(j + 1.1)/(j + 1.12345);
  }
}
```

Where `s` is effectively `( .2x * .2x) - 4.0 * ( .1x * .1x)` and with infinite precision that would be `s = 0.0`. We don't have infinite precision, so depending on the instructions being used `s` can be less than 0, which means the sqrt path won't be taken in the original example.

On chapcs without `--fast`, `s` will be 0.0, however with `--fast`, `s` will be less than 0.0. If you disable specialization (`--fast --no-specialize`), `s` will also be 0.0. 

If you add `march=native` to the reference version you see the same "problem"

I'm guessing this a result of FMA having higher precision, and compiling with `--fast --ccflags -mno-fused-madd` also results in `s=0.0`

In terms of how this impacts what we do for LCALS, we could throw `--no-specialize` since the reference version doesn't seem to be throwing `-march=native`. That won't fix the instability on Crays since the cc driver will specialize based on the cpu-targetting module loaded, so for `IF_QUAD` we could see what the reference checksum is like w/ and w/o FMA and allow either value to pass the checksum?

**Comment by mppf** [comment] 2019-04-16 13:10
I think we should just remove this test from consideration (including in performance runs). Once I learned about this problem, my conclusion was that this benchmark kernel is not useful (in any language).

**Closed** 2019-04-16 21:07 UTC
