### ISSUE TITLE
Implementation of sync variable unwrapping in initialization

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#8496] opened 2018-02-16 01:08 UTC
Consider the following:
```chpl
// 'x$' is a 'sync int'
var a = x$;
```

The language states that this will transform into something like:
```chpl
var a = x$.readFE();
```

The variable ``a`` will be an integer. We currently leverage ``chpl__initCopy`` on master to implement this behavior. I don't think we can leverage initializers in any way to implement this behavior, because the initializer would have to be called on ``a`` whose type we do not know.

We have a similar pattern with arrays:
```chpl
var A : [1..10] int;
var B = A[1..5];
```

In this case, ``B`` is a default rectangular array and not an array view.

How should we implement this in the impending initializer world?

Should this functionality be exposed to users?

Other things to consider:
- How might this interact with ``chpl__unref`` and ``chpl__unalias`` ?

**Comment by benharsh** [comment] 2018-02-16 01:09
@lydia-duncan , @noakesmichael : Do you have any initial thoughts?

@mppf : Any opinions given your history with unref/unalias?

@bradcray : here's the issue we discussed.

**Comment by noakesmichael** [comment] 2018-02-16 01:34
I am a little confused about this thread.  I am having a hard time
seeing this as being an initializer question.  I think there are two
use cases for "initializers"; 

1) Overriding the behavior for a "new" expression for classes and records

2) Overriding the behavior when initializing a variable with record
type using an object of a supported type for that record aka
"copy initializer".




In your example there is no "new" expression.

Syncs can only wrap "primitive types", enum types, and
class types and so there isn't a copy initializer.

I don't pretend to have any idea what an init_copy or auto_copy
really is and so I am not sure what to make of the role that
init_copy plays in the transformation of

var val = $syncVar;

to 

var val = $syncVar.readFe();

but the whole thing seems fishy to me. 



It's debatable whether a sync is really a record.  I recognize that we
use record syntax, and two constructors, as a portion of the internal
implementation but there are pragmas and special compiler behaviors
that we rely on in the full implementation.  But the constructors are
for making a sync var, not for unwrapping a sync var.

**Comment by mppf** [comment] 2018-02-16 11:22
I think it's likely that we could merge chpl__unref and chpl__unalias into one thing and have that thing be user-facing. It would be something like "Now adjust this record value to be returned or stored into a separate user variable". (Where we historically differentiated between the return/variable cases for arrays, which is partly why we have 2 things).

**Comment by lydia-duncan** [comment] 2018-02-16 16:23
Couldn't we handle this case by overloading the assignments and coercions involving atomics, independent of init/auto copy?  Like, define them to include the readFE() in place, skipping the middle man?

**Comment by mppf** [comment] 2018-02-16 16:37
@lydia-duncan -

The pattern
``` chapel
var a = x$;
```

where x$ is a sync variable - doesn't actually run an assignment function. It runs copy-initialization. But we want the type to change (from sync int to int, presumably). So it's not *really* copy initialization.

I view this as an oddity of the language, but I think there are some benefits especially with arrays and array copies.

Another case that @benharsh's initial issue message doesn't include is how the compiler translates iterator records into arrays, e.g.:
``` chapel
var A = [i in 1..10] i;
```

results in A being an array, rather than A being an iterator.

**Comment by mppf** [comment] 2018-02-16 18:54
I think this is related to #8242, in terms of language design direction.

**Comment by bradcray** [comment] 2018-02-16 20:02
> I am having a hard time seeing this as being an initializer question.

Mike: I think you're right that it's not an initializer question in the sense that the solution may not be to "call something named `proc init()` but I do think it's an _initialization_ question in the sense that it's saying "how does the language determine the type of a variable being initialized, but whose type is inferred?"  which _could_ be considered similar to supporting an initializer for a variable whose type is unknown.

To Lydia's question and Michael's reference to issue #8242, I think the potential reason that this is a little different is that assignment and coercion both typically know both the source and destination type at present (right?).  I.e., in such cases, it makes sense to ask questions like "Do I have an assignment operator between these two types?" or "Can I coerce from this type to that type?"  But the type-inferred case is different in that it's essentially saying "if I just read this variable while initializing another one, what should happen / what should the new variable's type be?"

The obvious answer would be "the same type" but for array views and sync variables, I think it would be weird (and definitely very different from what we have today) to have such initialization expressions literally create a copy of the array view or the sync variable when normal assignments don't do that.  I.e., I think there's productivity value in making these initializations act more like assignment in terms of the resulting type and less like "make something just like me."

To Ben's questions:

> Should this functionality be exposed to users?

My guess is "yes" by the standard "if we need to do it, some fancy record designer will eventually want to be able to as well."

> How should we implement this in the impending initializer world?

My best guess at present would be to have the user define some sort of procedure with a well-defined name (where my name here is intentionally terrible to motivate creative thinking):

```chapel
proc myRecordType.howToReadMe() {
  return ...;
}
```

then the compiler would translate code from:

```chapel
var x: myRecordType = ...;
var y = x;
```

to:

```chapel
var x: myRecordType = ...;
var y = x.howToReadMe();
```

where if no such method existed, the statement would instead become the equivalent of:

```chapel
var x: myRecordType = ...;
var y: x.type;  // this line and the next are supposed to be roughly sketching out "call the copy init" though that's hard to write as Chapel code...
y.init(x);
```

That said, I worry that this approach looks a bit too much like "call assignment" rather than "initialize" which might run into standard "does assignment assume more about the LHS than we can guarantee?" types of concerns...  This also makes me wonder if thinking that the solution to issue #8242 was "coercions" was naive/premature.

**Comment by noakesmichael** [comment] 2018-02-16 20:22
Re: clarification by @bradcray 

Duoh.  I have been so focussed on "initializers" that I completely missed the care that
@benharsh took in saying "initialization".  Thanks.

**Comment by bradcray** [comment] 2018-02-16 22:05
After a lunchtime conversation with @benharsh and @noakesmichael , I'm going to backpedal a bit and agree with @mppf that this issue is more related to #8242 than I had originally thought.  The reason I thought it was different is that, at least in writing #8242, I was (mostly) focused on the case where we know the type of the new LHS variable/field, whereas here part of the challenge is that we don't know the type.

That said, the lunch conversation made me realize that once we do know the type, the two really become quite similar ("I'm trying to create/initialize this new variable of one type with this expression of another").

From there, the lunchtime thinking was that given:

```chapel
var x = y;
```

we'd (1) evaluate the type of `y.howToReadMe()` and use that as `x`s type, then (2) invoke an initializer on `x` that took the result of `y.howToReadMe()` as its input argument.  In my latest post on #8242, this would be an `init=` initializer.

* For the case of a sync var, `y.howToReadMe()` would return `this.readFE()` causing `x` to be inferred to be the base type of the sync var (say, an `int`).  Then we'd use the copy initializer for `int`s to initialize `y` with the specific value returned by `y.howToReadMe()`.

* For the case of an array, `y.howToReadMe()` would declare a local array of the appropriate type and size, populate it, and return it, causing `x` to be inferred to be of that array type.  Then we'd use the `_array` record's copy constructor to initialize `y` with the array value returned by `y.howToReadMe()`.

In this array case, @benharsh had appropriate concerns about eliminating the copies of expiring values to avoid multiple deep copies of arrays—we don't literally want to copy an array on return from `y.howToReadMe()` or in `_array`'s copy initializer, we really just want to steal it into the final field.  He was asking whether this was a user-level concern or the compiler's concern to optimize away, and I said I hoped it was the latter.  This seems related to @mppf's December deep-dive and related thinking on `in` and `out` intents.

**Comment by mppf** [comment] 2018-02-20 14:01
> * For the case of an array, `y.howToReadMe()` would declare a local array of the appropriate type and size, populate it, and return it, causing `x` to be inferred to be of that array type.  Then we'd use the `_array` record's copy constructor to initialize `y` with the array value returned by `y.howToReadMe()`.
>
> In this array case, @benharsh had appropriate concerns about eliminating the copies of expiring values to avoid multiple deep copies of arrays—we don't literally want to copy an array on return from `y.howToReadMe()` or in `_array`'s copy initializer, we really just want to steal it into the final field.

In fact we don't want to run the copy-initializer at all, if `howToReadMe` is already returning an array.
I think this situation pretty clearly describes what we are currently getting out of `initCopy` being a function and not a method:
 1. `initCopy` can resolve when only the LHS type is known.
 2. The returned type of `initCopy` can control the inferred type for the new variable in these situations.
 3. It can do so while minimizing copies without adding any new rules to the compiler.

This leads me to believe that I'd prefer the compiler continue to use a method, whether we change the name or not. For example, here's something based on Brad's ongoing example & pinata naming scheme:
``` chapel
proc howToReadMe(RHS:sync ?t) {
  return RHS.readFE();
}
```

``` chapel
var x = y;
```

would just turn into
``` chapel
var x = howToReadMe(y);
```

Anyway, an alternative viewpoint here is that the only new information here is what the compiler should infer as the type of the new variable. In that viewpoint, the construction of `x` in the above example might simply be initialization with the RHS argument or it might simply be the result of a cast.

For example, in the below, I'm assuming typeForLHS (again an intentionally horrible name) returns only the *type* that the compiler should use when inferring. (Note that it can work just as well if `typeForLHS` is a method, unlike the previous `initCopy` like approach).

``` chapel
proc _syncvar.typeForLHS() type {
  return this.valType;
}
```

Now

``` chapel
var x = y;
```

would just turn into
``` chapel
var x:typeForLHS(y);
x.init(y);
```

(and here I'm assuming that types doing this would have a 1-argument initializer accepting the type to "initialize from", but this initializer isn't necessarily something we call a "copy initializer", though we could choose to call it that or not).

Summarizing this comment:
 * I don't like the idea of both having `howToReadMe` return a value (vs a type) *and* running the copy initializer.
 * I presented two alternative strategies:
    1. something conceptually similar to the current `initCopy` situation
    2. adding a method/function that returns the inferred type only

**Comment by bradcray** [comment] 2018-08-01 14:39
@benharsh:  Following up on our discussion yesterday and the proposal in issue #10615 (assuming we accept it), it seems to me that we could potentially expose this capability to users cleanly by using a standalone `init=` procedure.  For instance, given a scenario like this:

```chapel
record R { ... };
record S  { ... };
var myR: R;
var x = myR;  // I want/need x's type to be something other than R, as with syncs or array slices, say `S`
```

Option 1: Maybe I can enable the last line by creating:

```chapel
// Used to define the type of the LHS when an `init=` is used to define a new variable initialized by an `R`
proc init=(r: R) type {  
  return S;
}
```

where I'd also  need to make sure to have:

```chapel
proc S.init=(r: R) {
  // how I create a new S from an R
}
```

which we'd also presumably want in order to support these typed declarations:

```chapel
var myS: S = R;
var myS2: S = new S(R);
```

Option 2: Or maybe by creating:

```chapel
proc init=(r: R) {
  return new S(R);
}
```

The first approach seems slightly cleaner to me because it has essentially no duplicated code with anything else and would/could presumably transform the original declaration into:

```chapel
var x: S = myR;
```

Whereas the second approach seems less clean in that it relies more explicitly on a pre-existing initializer (i.e., there's likely to be a fairly consistent pattern for it), could lead to typed and untyped declarations having different behaviors (if I didn't follow the pattern and put some other arbitrary code into it that behaved completely differently from `proc S.init=(r: R)`), or could lead to redundant code (if I didn't follow the pattern but reimplemented `proc S.init=(r: R)` within this standalone version.

OTOH, the second approach is much closer to what we have in the compiler today.  And for cases like `sync int`s turning into `int`s, it would require something a bit special to happen (e.g., maybe we'd need to support defining `init=` methods on integers, or maybe we'd need to fall back on assignment overloads in the absence of them?)

**Comment by bradcray** [comment] 2018-08-01 14:45
Refreshing my memory about previous comments on this issue, I see that my latest one closely mirrors the two alternatives proposed in [the last one](https://github.com/chapel-lang/chapel/issues/8496#issuecomment-366986062) by @mppf, simply unifying its name with the proposed `init=` name used for assignment-based initialization.  I'm considering this a good thing (coming at the question from slightly different angles at different times, we arrived at similar conclusions).

**Comment by benharsh** [comment] 2018-08-01 16:26
Generally I prefer option 1 (return a type). I'm not wild about re-using ``init=`` for this, but I can't think of a more appropriate name, and it's at least thematically consistent.

**Comment by benharsh** [comment] 2018-08-01 16:52
Another downside to option 1 is that it requires an init= to already exist on the LHS type, which the author of the RHS type may not have access to. And the author of the RHS type may simply want to initialize the LHS with some internal data:

```chpl
proc init=(r: R) {
  // S knows about r.wrapped_data.type, but not R
  return new S(r.wrapped_data);
}
```

**Comment by bradcray** [comment] 2018-08-01 20:59
> it requires an init= to already exist on the LHS type, which the author of the RHS type may not have access to.

Could they write one as a secondary method?

> And the author of the RHS type may simply want to initialize the LHS with some internal data:

That's an interesting point.  FWIW, my assumption is that it's the author of the RHS type who's providing these routines, not the author of the LHS type, which also might suggest that your arguments favor option 2 since it'd support using the public interfaces for creating S's that already exist while accessing whatever R-dependent data necessary to write the routine.  So that might suggest that option 2 isn't just expedient but also more appropriate while also being more powerful (for both better and worse).

I think most types won't / shouldn't use this feature most of the time, so maybe am not terribly worried about the downsides of option 2.

**Comment by mppf** [comment] 2020-07-31 19:57
This issue is also related to #11222 which proposes having some strings that are "views" that borrow pointers to other strings. We might want such a string, when returned, to copy the buffer (like an array does). (So having a user-facing capability for that is more called for).

**Comment by mppf** [comment] 2020-11-13 20:30
issue #14213 asks about this more generally than for sync variables

**Comment by bradcray** [comment] 2020-11-20 20:33
@mppf: Do you think we should close this in favor of #14213 given that they seem somewhat duplicative of one another?  (where that one seems more general and the sync variable case may become less of an issue once we complete #16193.

**Comment by mppf** [comment] 2020-11-20 20:54
It'd be fine with me to close it now or when we complete #16193.

**Comment by bradcray** [comment] 2020-11-25 01:55
Closing this as a duplicate of #14213.

**Closed by bradcray** 2020-11-25 01:55 UTC
Labels: area: Language, type: Design
