### ISSUE TITLE
chpl__gpu.fatbin not generated

### ISSUE THREAD

**Issue by Eifoen** [chapel-lang/chapel#18850] opened 2021-12-13 12:44 UTC
## Summary of Problem
The .fatbin with the CUDA-Kernel is not compiled

### Chapel Build
Commit: 236ab577ff0042cca70b77c66f98b541bd470bb5

#### Env (as printed by configure)
Compiling Python scripts in util/

  Currently selected Chapel configuration:

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: unknown
CHPL_LOCALE_MODEL: gpu *
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads *
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc *
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none *
CHPL_HWLOC: bundled
CHPL_RE2: none *
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none

additionally (not printed by configure):
CHPL_RT_NUM_THREADS_PER_LOCALE=1

#### CUDA Version (as printed by nvidia-smi):
==============NVSMI LOG==============

Timestamp                           : Mon Dec 13 12:20:14 2021
Driver Version                      : 430.50
CUDA Version                        : 10.1

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce GTX 1060 6GB
    Product Brand                   : GeForce
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled

### Source Code:

[hello6-taskpar-dist.chpl](https://github.com/chapel-lang/chapel/blob/236ab577ff0042cca70b77c66f98b541bd470bb5/test/release/examples/hello6-taskpar-dist.chpl) as of 5eae51fa912754cf77a9586ddb5c4839ef4e05b1

aswell as the jacobi example from the doc
```chpl
config const nSteps = 10;
config const n = 10;

writeln("on GPU:");
jacobi(here.getChild(1));
writeln("on CPU:");
jacobi(here);

proc jacobi(loc) {
  on loc {
    var A, B: [0..n+1] real;

    A[0] = 1; A[n+1] = 1;
    forall i in 1..n { A[i] = i:real; }

    for step in 1..nSteps {
      forall i in 1..n { B[i] = 0.33333 * (A[i-1] + A[i] + A[i+1]); }
      forall i in 1..n { A[i] = 0.33333 * (B[i-1] + B[i] + B[i+1]); }
    }
    writeln(A);
  }
}
```

### Compile command
`make check`

`chpl ./jacobi.chpl -o jacobi`

### Execution Command
_does not apply_

### Configuration Information

**chpl --version:**
```txt
warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
chpl version 1.26.0 pre-release (0)
  built with LLVM version 11.0.1
Copyright 2020-2021 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
**printchplenv:**
as described above

**gcc --version:**
```txt
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### Expected

- passing `make check`
- compiled `jacobi` and `jacobi_real` aswell as a `jacobi_gpu_files` folder with `chpl__gpu.fatbin`

### Actual
**make check output:**
```txt
make check is not passing at:

[Info] Running minimal test script: $CHPL_HOME/util/test/checkChplInstall
[Info] Found executable chpl in /tmp/chapel-main//bin/linux64-x86_64/chpl.
[Info] Found $CHPL_HOME directory: /tmp/chapel-main
[Info] /home/user/.chpl does not exist. Creating it.
[Info] Temporary test job directory: /home/user/.chpl/chapel-test-Her2V
[Info] Compiling $CHPL_HOME/test/release/examples/hello6-taskpar-dist.chpl
[Info] Compiling with CHPL_TARGET_COMPILER=llvm
[Fail] Test job failed to compile - Chapel is not installed correctly
[Fail] Compilation output:
warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
internal error: UTI-MIS-0923 chpl version 1.26.0 pre-release (0)

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

error: opening /tmp/chpl-user.deleteme-V8blce/chpl__gpu.fatbin: No such file or directory
Makefile:210: recipe for target 'check' failed
make: *** [check] Error 1
```

**jacobi.chpl output:**
```txt
warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
internal error: UTI-MIS-0923 chpl version 1.26.0 pre-release (0)

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

error: opening /tmp/chpl-user.deleteme-hGAojs/chpl__gpu.fatbin: No such file or directory
```

no binaries to be found. Even with the hello.chpl example, which still complains about the missing chpl_gpu.fatbin .

**Comment by bradcray** [comment] 2021-12-13 18:46
Hi @Eifoen — I'm not expert here, but am tagging @stonea who is. Note that the fatbin file was merged into the executable in https://github.com/chapel-lang/chapel/pull/18628 and the docs were updated to reflect this in https://github.com/chapel-lang/chapel/pull/18692.  So I think the lack of a fatbin is as expected given the SHA you quote.  That said, I don't think you should be getting an internal error, so am hoping Andy will have more insight there.

**Comment by e-kayrakli** [comment] 2021-12-13 19:15
Let me respond as this may be a bit more general issue than Andy's recent work in embedding the GPU binary.

@Eifoen -- can you try either:

1. compile with `--local`
2. or, `export CHPL_COMM=none` first and then rebuild your Chapel and try with that?

As you may already know, the GPU support is still in the very early stages. One of the things that we want to support but we don't yet is communication from GPU kernels. As such, our current implementation efforts is focused on single-node, single-gpu setups. With your setup (i.e., `CHPL_COMM=gasnet`) the compiler will generate binaries that are geared towards handling potential communication. But that's not something our GPU support is ready to handle.

Arguably, we should issue a warning about it and impose `--local` just like we impose `--no-checks`. It is something we should do in the short term, if you confirm this to be your issue.

I can reproduce the internal error you are seeing if I compile with the same setup as you (Well, technically I have `CHPL_COMM=none`, but when I compile jacobi with `--no-local`, I can see the same error)

---

More nuts-and-bolts for devs and interested parties:

- We analyze loops and create kernels after `deadCodeElimination`, but that's earlier than `insertWideReferences`. I think eventually we need to move GPU transformations after `insertWideReferences`.
- Getting to that point without some prototype comm from GPU is probably pointless, because everything will have wide pointers in it, and that would probably mean we won't be able to outline any loops because checker will not like those wide pointers.
- Until that point, we should adjust the ergonomics around this by imposing `--local` and issuing a warning about it. We should also probably update the docs if this isn't clear.

**Comment by Eifoen** [comment] 2021-12-14 10:24
Thanks for your fast responses!

@e-kayrakli 
1. The compiled chpl binary with --local worked fine with -nl 1 - no Internal Error notice
2. same for the CHPL_COMM=none compiled version

At this Point my problem is resolved. Thanks a lot for your help.

You were right, I did know about the stage of GPU development. What I did not know though was that comm is currently not supported in CUDA-Kernels. Did I miss that somewhere in the doc? Otherwise it would be great to have a notice about that in [Setup and Compilation](https://github.com/chapel-lang/chapel/blob/main/doc/rst/technotes/gpu.rst#setup-and-compilation).

If you'd like I can propose a PR containing some words about what you've described above.
Also +1 on the imposing of --local

**Comment by stonea** [comment] 2021-12-14 17:57
Hi @Eifoen.

> You were right, I did know about the stage of GPU development. What I did not know though was that comm is currently not supported in CUDA-Kernels. Did I miss that somewhere in the doc? Otherwise it would be great to have a notice about that in Setup and Compilation.

We must have missed putting this in the tech report.

> If you'd like I can propose a PR containing some words about what you've described above.
Also +1 on the imposing of --local

If you'd be up for it we'd appreciate that; just add me or Engin (@e-kayrakli) as a reviewer. Otherwise I'll add a PR to update the text.


> If I compiled a binary without any forall loop in 1.25.0 this lead to a _gpu_files folder not containing any chpl__gpu.fatbin file. Which in turn was not expected by the resulting x86 binary. This lead to a working non-GPU binary even though the compiler had GPU support enabled.

> This does not work anymore and fails with the same "chpl__gpu.fatbin not found" mentioned above. Might this be considered a regression? Maybe introduced in #18628 because the chpl__gpu.fatbin is now expected to be availble because the compiler wants it to be copied over to the TEXT section of the binary itself?

Yes this is essentially what happens.  On our working branch when you compile with `CHPL_LOCALE_MODEL=gpu` you'll get a directory created somewhere in /tmp where we'll produce the `.fatbin` file. Once that's made we read it in and then attach it to the binary itself (and then remove the directory under `tmp`).

I believe now if the `.fatbin` file doesn't get created you'll get an error message at compile time stating that, but let me confirm that.

Ideally we should probably have a check if `CHPL_COMM` is not none and present a better error
message (or produce a warning as Engin suggested).  I've created an issue about this here that I'll work on:

https://github.com/chapel-lang/chapel/issues/18858

Thanks for letting us know you ran into trouble (so we know what we need to improve).

**Comment by bradcray** [comment] 2021-12-14 18:01
Thanks for the quick responses here, Engin and Andy.  I'm wondering what all we should do to consider this issue closed.  I hear @Eifoen saying that their problem is resolved, but also understand that we may want to keep this issue open as a placeholder for clean-ups to documentation and/or code to avoid having people step into traps.  #18858 is obviously part of that—is it the whole thing?  If there's more, maybe we could spawn those off into separate issues?  (or maybe resolving them is just as easy as filing the issue?).  Thanks for your thoughts here.

**Comment by e-kayrakli** [comment] 2021-12-14 18:12
Thanks Andy for https://github.com/chapel-lang/chapel/issues/18858. I said what I wanted to go on record on that issue. And from that perspective, I think we can close this issue personally as long as @Eifoen is also fine with it.

@Eifoen -- thanks for offering to fix the docs! The GPU support is far from getting prime time attention, but please let us know about your further experiences kicking the tires.

**Comment by stonea** [comment] 2021-12-14 18:12
> I'm wondering what all we should do to consider this issue closed

I think so. At least as it relates to `CHPL_COMM` I think #18858 should have us covered.

> If there's more, maybe we could spawn those off into separate issues? (or maybe resolving them is just as easy as filing the issue?).

It may be worth brainstorming if there's other configurations \ limitations to GPU support that we failed to document.  I can't think of any off the top of my head but I think we should bring up this topic at Thursday's GPU meeting just to make sure no one else is aware of something we missed.

**Comment by e-kayrakli** [comment] 2021-12-14 18:13
> It may be worth brainstorming if there's other configurations \ limitations to GPU support that we failed to document. I can't think of any off the top of my head but I think we should bring up this topic at Thursday's GPU meeting just to make sure no one else is aware of something we missed.

`CHPL_LLVM=none` is an obvious one. I don't know what would happen today in that config. But yeah, let's discuss.

**Comment by e-kayrakli** [comment] 2021-12-14 18:35
> If I compiled a binary without any forall loop in 1.25.0 this lead to a _gpu_files folder not containing any chpl__gpu.fatbin file. Which in turn was not expected by the resulting x86 binary. This lead to a working non-GPU binary even though the compiler had GPU support enabled.

https://github.com/chapel-lang/chapel/pull/18762 may help with this indirectly. It'll create kernels for internal foralls, and I think there should be at least some that's compiled even with a simple "Hello world".

**Comment by Eifoen** [comment] 2021-12-15 10:00
> `CHPL_LLVM=none` is an obvious one. I don't know what would happen today in that config. But yeah, let's discuss.

As obvious as it might seem to your team I acutally ran into that one about a week ago.
We mainly use gcc/gnu in our lab, so in our default chapel build `CHPL_LLVM=none` is set 😆

> Thanks Andy for #18858. I said what I wanted to go on record on that issue. And from that perspective, I think we can close this issue personally as long as @Eifoen is also fine with it.
> 
> @Eifoen -- thanks for offering to fix the docs! The GPU support is far from getting prime time attention, but please let us know about your further experiences kicking the tires.

@e-kayrakli 
This issue can be closed in favour of #18858 imho.
We're currently fiddling around a lot with the GPU-support, got a bunch of pascal cards and some A100s around with diffrent CUDA-Versions. I'll create another issue if we find odd behaviour in our future testing.



**Thanks to everyone for your help, insights and quick replies. Very much appreciated!**

**Comment by e-kayrakli** [comment] 2021-12-15 18:58
> As obvious as it might seem to your team I acutally ran into that one about a week ago.
We mainly use gcc/gnu in our lab, so in our default chapel build CHPL_LLVM=none is set 😆

I didn't mean to say "users should know that it works only with LLVM, it is obvious". I am sorry if it came across that way :)


> We're currently fiddling around a lot with the GPU-support, got a bunch of pascal cards and some A100s around with diffrent CUDA-Versions. I'll create another issue if we find odd behaviour in our future testing.

Ah. Nice to have A100s. We have been working on P100s pretty heavily, but will have access to A100s in January, I hope.

Looking forward to hearing about your experiences and potentially a PR to fix the docs.

**Closed by e-kayrakli** 2021-12-15 18:58 UTC
Labels: type: Bug, area: Compiler, user issue

**Comment by stonea** [comment] 2022-01-25 02:08
Hi @Eifoen,

Just following up on this:

> If you'd like I can propose a PR containing some words about what you've described above.

I see you've forked the Chapel repos and added a commit here:

https://github.com/Eifoen/chapel/commit/68b673d435ecc5f9a97d14d5d503b99f1a2fcde9

If you're interested in submitting this as a PR you can follow the directions
here on how to contribute your changes (https://chapel-lang.org/docs/developer/bestPractices/ContributorInfo.html#contributing-changes).

In your case this would involve:

  * Creating a new branch name for your commit, for example: `git checkout -b update_gpu_tech_report_chpl_comm`
  * Adding your DCO signature into the commit (for legal reasons we need you to "sign the commit".  More information about the DCO is here: https://github.com/chapel-lang/chapel/blob/main/.github/CONTRIBUTING.md) Essentially, what it boils down to is you need to amend your commit message (e.g. run `git commit --amend`) to include a line like this at the bottom (substituting your name and email address in as shown on your Github account): `Signed-off-by: Random J Developer <random@developer.example.org>`
  * Pushing the commit to your forked repos
  * Then in githb create a PR (as described here: https://chapel-lang.org/docs/developer/bestPractices/git.html#how-to-open-a-pr)
  * Adding me as a reviewer so I can then approve and merge the changes.

I know there's a bit of hoops here (apologies for that).  If you don't have time\interest in doing that, that's fine (let me know and I can submit a PR myself, we appreciate the feedback you've already given us). That said, if you think you might make future contributions to the Chapel project it's not a bad idea to familiarize yourself with the process (so I think I'd reach out before I take any further action).

Thanks,
-Andy
