### ISSUE TITLE
[design] Should try! apply to an expression without needing braces?

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#18859] opened 2021-12-14 19:01 UTC
## Summary
Thinking of the use cases that I have seen for `try!` (e.g., `try! createStringWithNewBuffer(...);`), I was under the impression that `try!` could be applied in the same way as, for example, `for i in 0..1 do for j in 2..3 do ...`, where you are able to nest the expressions, as long as they are a single line (not sure if this is a hard rule, but it is how I think of it at least. The main idea here is to enable `try!` to be applied to any expression without braces, similar to `for ... do` and `if .. then`.

## Problem
```
try! for i in 0..1 do writeln(i); // gives error

try! { for i in 0..1 do writeln(i); } // no error

for i in 0..1 do for j in 2..3 do writeln(i, j); // seems the same as the first example

if true then for i in 0..1 do writeln(i); // seems the same as the first example
```
The first line of this snippet does not work, even though it seems to be the same as the brace-less lines 3 and 4.

Additionally, the code on the first line in this snippet will give this error: `illegal use of function that does not return a value: 'writeln'`, which does not seem intuitive/helpful to debug why this does not work.

## Proposal
With this in mind, I would like to propose that `try! for i in 0..1 do writeln(i);` should work in the same way that`for i in 0..1 do for j in 2..3 do writeln(i, j);` works: it is a single expression, so it should not need braces.

**Comment by e-kayrakli** [comment] 2021-12-14 19:23
> With this in mind, I would like to propose that try! for i in 0..1 do writeln(i); should work in the same way thatfor i in 0..1 do for j in 2..3 do writeln(i, j); works: it is a single expression, so it should not need braces.

Shouldn't it be `try! do for i in 0..1 do writeln(i)` ? Which I was expecting to work but it doesn't parse.

There's a `try!` statement and [`try!` expression](https://chapel-lang.org/docs/master/language/spec/error-handling.html#try-expressions), where I've seen the latter as a syntactic sugar to be able to do things like `foo(a, try! throwingFunction())`. What you are suggesting is a statement, though. So it needs to be consistent with other statements in the sense that it needs a delimiter. `try! for` looks like `if flag for`, to me.

**Comment by bmcdonald3** [comment] 2021-12-14 19:33
> Shouldn't it be try! do

If it should be, I think it would be nice to have a better error message that indicates that; I never would have guessed that is what should have been added intuitively with the error message I was seeing.

I don't really see the need to have the `do` though or I think we should decide upon just one, either `try! do` or just `try!` for both the expression and statement, like C++, which allows the `if(flag) for` style that you mention. What seems different to me about `if`/`for` and `try!` is that `try!` does not take an expression like `if`/`for` does; I think of it like`if expr then doSomething` vs `try! doSomething`, which seem different to me.

**Comment by e-kayrakli** [comment] 2021-12-14 20:55
> If it should be, I think it would be nice to have a better error message that indicates that; I never would have guessed that is what should have been added intuitively with the error message I was seeing.

Totally agree.

> I don't really see the need to have the do though or I think we should decide upon just one, either try! do or just try! for both the expression and statement, like C++, which allows the if(flag) for style that you mention. What seems different to me about if/for and try! is that try! does not take an expression like if/for does; I think of it likeif expr then doSomething vs try! doSomething, which seem different to me.

I was going to argue against this with `begin`, but it looks like you can do `begin writeln("Hello");` which is surprising to me as I was expecting that it would require `do`. But you cannot do `local writeln("Hello");`. Maybe `begin foo()` was expected to be a common idiom, so we did away with `do`, there?

`try! for` still feels wrong to me, and as does `begin for`. But maybe what caused `begin for` to be allowed can also be used to argue for `try! for`?

**Comment by bradcray** [comment] 2021-12-14 22:41
>  But maybe what caused begin for to be allowed can also be used to argue for try! for?

I think that the historical rule was that we'd only use `do` in cases that didn't immediately follow a keyword (since requiring two keywords in a row doesn't seem strictly necessary / valuable.  Put another way, for the single-statement form of `for...` loops, the `do` tells the parser "this is where the header of the for loop stops and where the single-statement body begins" (and similarly for `then` with `for`).  All that said (a) it seems as though we haven't been consistent about it, as `local` demonstrates, and (b) there've been feature requests from time to time to support the optional `do` after keywords that don't require it so that you can use them if you prefer it (in which case any of `try`, `begin`, `local` could either take `do` or not.

> What you are suggesting is a statement, though.

I think that the reason that this works (today at least) is that we support expression-level `for` loops and the `try_stmt` production permits expressions to follow it rather than just statements.  It'd be interesting to replace `expr` in

```
  TTRY     expr            TSEMI         { $$ = TryStmt::build(false, $2); }
| TTRYBANG expr            TSEMI         { $$ = TryStmt::build(true,  $2); }
```

with `stmt_level_expr` (which is intended to be "those statements which can occur at the statement level") and see what breaks and what happens with Ben's test program.  I think it would be a syntax error and that curly brackets would need to be applied to make it work again.


The part that sounded odd to me, and that encouraged me to suggest that Ben file this issue, is that the error he was getting wasn't a syntax error (Where we've been focused here) but something deeper.  That said, I hadn't tried it myself until now, where I see that the issue is exactly the expression vs. statement issue:

```
testit.chpl:1: error: illegal use of function that does not return a value: 'writeln'
```

Specifically, a for loop in an expression context is generating something, like the values to be passed to the outer routine or assigned to the variable:

```chapel
for A = for i in 0..1 do i;
foo(for i in 0..1 do i);
```

so in this case, we're expecting the for loop to be generating/returning things and it's not, hence the error.

> as long as they are a single line

Just as a slight course correction, Ben:  Chapel doesn't care about whitespace, so whether or not it's on a line or not is a question of style, not meaning or impact.

**Comment by e-kayrakli** [comment] 2021-12-15 00:15
Ah good point about for expressions.

In that case, should `do` be required to make the distinction between an expression and a statement? I think parsing and generating the right AST as a result are probably two separate discussions for this though.

I vaguely remember a discussion about `begin` expressions, but can't find it quickly. If that's in our radar, that can also play a part in this discussion, I think.

**Comment by bradcray** [comment] 2021-12-15 00:59
> should do be required to make the distinction between an expression and a statement?

I think we need `do` and `then` to disambiguate syntactically at the expression level as well for `for` and `if` respectively.

> but can't find it quickly. 

Huh, me neither.  I could've sworn I'd filed an issue on this.

**Comment by bradcray** [comment] 2021-12-15 01:01
I didn't have any tests running, so am trying the change to the parser I proposed to see what happens in paratest.  I'm not optimistic, but curious.

**Comment by bradcray** [comment] 2021-12-15 07:24
Looks like it came back clean.  I opened a draft PR here:  https://github.com/chapel-lang/chapel/pull/18869

**Closed** 2022-01-08 01:05 UTC
