### ISSUE TITLE
Cannot copy array of `c_array` on GPU using promoted expression

### ISSUE THREAD

**Issue by Guillaume-Helbecque** [chapel-lang/chapel#22519] opened 2023-06-08 13:38 UTC
### Summary of Problem

When I tried to copy an array of `c_array` on GPU memory, I noticed that the code breaks with the following error: `internal error: gpu-cuda.c:246: Error calling CUDA function: invalid argument (Code: 1)`. To compare, I tried to copy an array of arrays and a `c_array` of `c_array`, and it works. I'm interested to know what's wrong in the first case (array of `c_array`). 

```chapel
use CTypes;

proc main()
{
  var t1: [0..9] [0..9] c_int;
  var t2: c_array(c_array(c_int, 9), 9);
  var t3: [0..9] c_array(c_int, 9);

  for i in 0..9 {
    for j in 0..9 {
      t1[i][j] = i:c_int;
      t2[i][j] = i:c_int;
      t3[i][j] = i:c_int;
    }
  }

  on here.gpus[0] {
    var t1_c = t1; writeln("t1_c = ", t1_c); // OK
    var t2_c = t2; writeln("t2_c = ", t2_c); // OK
    var t3_c = t3; writeln("t3_c = ", t3_c); // ERROR
  }

  return 0;
}
```

**Compile command:**
`chpl test.chpl -o test.o --fast`

**Execution command:**
`./test.o`

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.30.0
  built with LLVM version 14.0.6
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: gpu *
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: `gcc (Spack GCC) 12.2.0`

**Comment by stonea** [comment] 2023-06-21 22:35
I suspect what's happening is that the `t3_c = t3` assignment ends up lowering to something like this:

```chpl
var t3_c : [0..9] c_array(c_int, 9);
forall i in 0..9 {
  t3_c[i] = t3[i];
}
```

Which ends up causing a kernel launch and Chapel doesn't currently support a GET of memory from within a kernel.

There's a few things here:

- Ideally, we should support the GET,
- even if we don't, we should fail to make the loop gpu eligible rather than causing a CUDA error,
- but really we should probably be lowering to something else to do this data transfer for the GPU

So definitely this is a bug in Chapel. As a workaround you can do the copy manually with a `for` loop like this:

```chpl
var t3_c : [0..9] c_array(c_int, 9);
for i in 0..9 {
  t3_c[i] = t3[i];
}
```

As an internal note: it looks like the culprit in our module code is the loop generated from `[ (aa,bb) in zip(a,b) ]` [here in ChapelArray](https://github.com/chapel-lang/chapel/blob/main/modules/internal/ChapelArray.chpl#L2696). Changing it into `for (aa,bb) in zip(a,b) {...` causes the issue to go away.

**Comment by Guillaume-Helbecque** [comment] 2023-07-03 16:01
Actually this workaround has allowed me to continue my research. However, I'm now facing a performance issue. Evidently, the manual and sequential copying process leads to inefficient CPU-GPU data transfer in terms of processing time, especially when dealing with large arrays being copied thousands of times. I'm curious if there might be an alternative GPU-parallel approach to address this issue...

I attempted to re-implement certain aspects in order to obtain a copy of `c_array` of `c_array` or array of arrays, which work in GPU-parallel, as demonstrated previously. However, I encountered roadblocks that prevented me from proceeding further. Are there any other approaches I could explore to achieve a GPU-parallel implementation for this manual copy operation?

**Comment by e-kayrakli** [comment] 2023-07-05 21:29
Hi @Guillaume-Helbecque -- sorry this is turning into a headache. Is it possible at all to use a tuple instead of a c_array here?

`c_array` is not a plain-old-data. That makes it ineligible for bulk transfer. As Andy pointed out, that makes things fall into an internal `forall` that results in a GPU kernel launch, which then has illegal memory access. We should probably allow array of `c_array`s to be bulk transferred, but I can't come up with a workaround you can add as the user.

Tuples have a very similar layout in memory, but are also plain-old-data. On a simple test, I confirmed that the data is bulk transferred, so it should not result in invalid kernel launches and single copy for the data.

---

An alternative is to use `forall` for the data copy instead of `for`, but to make sure that it won't turn into a GPU kernel. A simple example is:

```chpl
use GpuDiagnostics;

inline proc thwartGpu() {
  var i: int(8);
  if i==2**16 then  halt("Something must be wrong");
}

on here.gpus[0] {
  var A: [1..10] int;

  startVerboseGpu();
  forall i in A.domain {
    thwartGpu();

    A[i] = i;
  }
  stopVerboseGpu();

}
```

Note that this is still going to be one-by-one copy but in parallel. So, still not as efficient as tuple bulk copy.

**Comment by e-kayrakli** [comment] 2023-07-05 22:03
https://github.com/chapel-lang/chapel/pull/22670 is the likely solution. I need to test it a bit more before being certain that it is safe to do what it is doing, though.

**Comment by e-kayrakli** [comment] 2023-07-10 19:16
@Guillaume-Helbecque -- this issue has been auto-closed with that PR merged. Please let us know if it falls short of addressing issues with your real use-case. Thanks for reporting the bug!

**Comment by Guillaume-Helbecque** [comment] 2023-07-12 08:25
Thank you for the PR @e-kayrakli. I've tested it on the toy-code provided above, and I unfortunately still observe the reported error, as if there is still a kernel launch behind. That's not the case in your tests? I simply patched 1.31.0 with your PR, is this sufficient?

**Comment by e-kayrakli** [comment] 2023-07-12 16:57
We've captured the problem in nightly testing and I just merged a fix for that. I was hoping that I could do that before you try it out, but you get to it faster than I thought! Sorry about the churn. You can wait for another night (US time) to nightlies to run on the `main` branch before giving it a go to avoid additional back-and-forth.

Since you're willing to test it on `main`, I am reopening this issue until you confirm that it is resolved (and to avoid github sending fewer notifications because an issue is closed).

**Comment by Guillaume-Helbecque** [comment] 2023-07-13 08:08
I just tested your fix and I confirm that it works! Thanks!

**Comment by Guillaume-Helbecque** [comment] 2023-07-13 08:38
I was curious to see if the code below could work, and for now, it doesn't. I noticed that you opened issue #22696 for this, and I'm keeping a close watch on it.

```chapel
use CTypes;

config const arrSize = 5;
config param cArrSize = 3;

record R {
  var c_arr: c_array(int, cArrSize);
}

proc main()
{
  var t4: [0..#arrSize] R;

  for i in 0..#arrSize {
    for j in 0..#cArrSize {
      t4[i].c_arr[j] = i;
    }
  }

  on here.gpus[0] {
    var t4_c = t4; writeln("t4_c = ", t4_c); // ERROR
  }

  return 0;
}
```

**Comment by e-kayrakli** [comment] 2023-07-13 17:01
Oh, thanks for checking that! Above I recommended using a tuple instead of a `c_array`. Is that an option for you to work around these issues?

This topic seems to be thornier than I expected. We could consider putting more band-aids, but unless this is a show-stopper for you, I want to stop doing that and find a more principled solution. https://github.com/chapel-lang/chapel/issues/22743 is a summary of what all this means, and the issue that you pointed is only part of it.

**Comment by Guillaume-Helbecque** [comment] 2023-07-14 08:19
Yes, I think I can work around this issue by using tuples instead of `c_array`. In addition, I could also investigate the possibility to refactor my record to put all the data in the `c_array`.

I agree with you, and I think we can close this issue.

**Comment by e-kayrakli** [comment] 2023-07-14 17:48
> Yes, I think I can work around this issue by using tuples instead of c_array

Another positive side of using tuples is that they are first-class citizens of the language and generally more stable in terms of interface. `c_array` is just part of the standard library, and definitely the path less travelled compared to tuples.

Closing this issue. https://github.com/chapel-lang/chapel/issues/22743 is the best successor for this.

**Closed by e-kayrakli** 2023-07-14 17:48 UTC
Labels: type: Bug, user issue, area: GPU Support
