### ISSUE TITLE
Internal error on config vars

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8471] opened 2018-02-14 16:52 UTC
This error leaves me nowhere to go.  The program compiled and I have lots of configuration variables.  Hopefully there is a way to identify which variable has a problem.  This occurs when I go to run it.

```
internal error: unknown config var case not handled appropriately
make: *** [run-listen] Error 2
```

**Comment by ben-albrecht** [comment] 2018-02-14 17:31
The conditional for this error message in `runtime/src/config.c` is:

```C
  if (configVar == NULL || configVar == ambiguousConfigVar) {
    chpl_internal_error("unknown config var case not handled appropriately");
  }
```

The `ambiguousConfigVar` case could occur if you have the same `config` variable listed twice - that might be helpful in your case. Aside from that, I agree the error message could be clearer.

**Comment by bradcray** [comment] 2018-02-14 19:36
This is an internal error, so not intended for the end-user -- more like an assertion failure / bug on our part.

**Comment by bradcray** [comment] 2018-02-14 19:45
Feeling responsible for this code, I took the obvious step of creating a program with two modules with a config of the same name and of one module with two configs of the same name, but they don't result in this behavior (as I'd hoped).

To help narrow down what's causing the error, if you would be willing to edit the line in runtime/src/config.c that @ben-albrecht refers to above to read:

```c
    chpl_internal_error("unknown config var case for '%s:%s' not handled appropriately", moduleName, varName);
```

I think this would help you / us understand what's going wrong and create a reproducer (or just point us to the full-blown source if that's easy and possible to do).

**Comment by buddha314** [comment] 2018-02-14 19:46
could it happen if a config file provides a variable the program is not expecting?

**Comment by bradcray** [comment] 2018-02-14 19:51
I seem to get a different / clearer error message for that case.

**Comment by bradcray** [comment] 2018-02-16 23:28
@buddha314 : I'm still very interested in tracking this one down, and suspect the fix would be easy, but haven't been able to guess how to reproduce it.  If you can still reproduce it yourself and would try applying the above patch, re-`make`-ing your build, and re-running to see which variable is being complained about, that'd be really helpful.  Otherwise, I'm not sure how to proceed.  Thanks.

**Comment by buddha314** [comment] 2018-02-16 23:32
I dropped the ball on this one.  Let me see if I can make it happen again. Once I get past an error, I tend to forget about it.  Apologies.

**Comment by bradcray** [comment] 2018-02-27 08:42
Closing this as a duplicate of #8600 where we made better progress on it.

**Closed by bradcray** 2018-02-27 08:42 UTC
Labels: stat: Duplicate, type: Error Message, user issue
