### ISSUE TITLE
Calling the attributes of externally defined C structs outside of the module namespace results in strange behavior

### ISSUE THREAD

**Issue by astatide** [chapel-lang/chapel#14830] opened 2020-01-29 00:37 UTC
In an attempt to have the compiler build Chapel records out of C structs for me, I compiled Chapel with llvm support so that I could create an extern block where C structs are defined or instantiated.

It seems to work, with the caveat that I am free to access the struct's attributes so long as I am accessing them from within the module; however, attempting to access them outside of the module gives me some results.

I have a reproducer here: https://gist.github.com/astatide/65f3867a50bebe40348422837c489383

It gives the following error:

```
externtest.chpl:16: error: unresolved call 'mystruct.a'
externtest.chpl:16: note: because no functions named a found in scope
```

I'm attempting to write a module that would be compatible with a large variety of structs (that would be defined in includes), and I'd like to interact with said structs outside of the module without necessarily needing to know the struct's, uh, structure, beforehand.  Is this possible?

@mppf suggested I create a reproducer and post an issue, and said "feel free to tag me", so here he is, tagged.

**Comment by mppf** [comment] 2020-01-29 14:45
@astatide - thanks for creating this issue. I'm looking in to it. At the moment I suspect it is a compiler bug. I have identified a workaround for the moment. See below for a standalone version of the reproducer that shows the workaround:

``` chapel
module Test {
  module C {
    extern {
      // Declare a struct
      struct mystruct
      {
        int a;
        int b;
      };

      // Declare a test function
      static int foo(int x) { return x + 1; }

      // Declare a test global variable
      struct mystruct globalFromC;
    }
    proc tryMe() {
      writeln(globalFromC.a);
      return foo(3);
    }
  }

  writeln(C.tryMe()); // works
  writeln(C.foo(3));  // works

  // Depending on the form of use C, C.globalFromC.a will or won't work
  // no use C       -> doesn't work (may not work in future - see #13536)
  use C only; // -> doesn't work
  //private use C; // -> works
  //        use C; // -> works

  writeln(C.globalFromC.a);   // ?
}
```

**Comment by mppf** [comment] 2020-01-29 14:52
@lydia-duncan - I think this is actually a duplicate of #11868 and #10397 - and something that's in your court.

**Comment by lydia-duncan** [comment] 2020-01-29 16:08
Yeah, that sounds right.  I really need to get to that issue

**Comment by mppf** [comment] 2020-02-05 18:14
Note that this is also related to #14407

**Comment by bradcray** [comment] 2021-01-13 21:14
@mppf / @lydia-duncan : I'm finding that all the issues this links to have been closed.  Is there any chance that this is resolved as well?

**Comment by mppf** [comment] 2021-01-13 21:32
@bradcray - it seems to function now. I'll prepare a PR adding the bug reported here as a test have that close this issue.

**Closed** 2021-01-13 21:55 UTC
Labels: area: Compiler, area: Language, stat: Duplicate, user issue

**Comment by bradcray** [comment] 2021-01-13 22:25
Thanks!
