### ISSUE TITLE
Array passed by ref not autoCopied when returned, but still destroyed

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7079] opened 2017-08-22 23:52 UTC
### Summary of Problem
In the associated future test, an array is passed by reference and returned
by blank return-intent. The returned array is not autoCopied but is still
autoDestroyed, which destroys the original array. Surprisingly, this test
passes if we pass the array by blank intent.

**Associated Future Test(s):**
[`test/arrays/bharshbarg/returnRefArray.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/arrays/bharshbarg/returnRefArray.chpl)

**Comment by benharsh** [comment] 2017-08-22 23:52
@mppf : @ben-albrecht ran into this during development. Any thoughts?

**Comment by mppf** [comment] 2017-08-23 14:05
Actually this is a known issue. It's a duplicate of this test:
```
test/types/records/ferguson/missing-auto-copy.chpl
```

Clearly, we should fix this bug... but I'm personally feeling busy enough with error handling at the moment. Last time I looked at this, it looked like the implementation of in/out/inout intents would interfere with a straightforward solution.

**Comment by benharsh** [comment] 2017-08-23 16:18
Darn, do you want me to remove the test I added?

**Comment by mppf** [comment] 2017-08-23 16:20
I think it's fine to have another test for it. We just need to move it to the top of somebody's list at some point.

**Closed** 2017-08-23 22:53 UTC
Labels: area: Compiler, stat: Work in Progress, type: Bug
