### ISSUE TITLE
Unable to pass const arrays to external routines

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#18790] opened 2021-12-02 23:17 UTC
### Summary of Problem

Arrays declared as `const` cannot be passed to C functions via `c_ptrTo`. Having such functionality feels natural since C routines can expect `const` pointers and Chapel is const-correct.

Currently, Chapel fails with the following error message:
```
chpl -o error error.chpl
error.chpl:5: In function 'main':
error.chpl:9: error: const actual is passed to 'ref' formal 'arr' of c_ptrTo()
note: to formal of type [domain(1,int(64),false)] real(64)
```

### Steps to Reproduce

**Source Code:**

```chapel
use CPtr;

proc external(arg : c_ptr(real)) { }

proc main()
{
  const x = [1.1, 2.2, 3.3];
  var y = x;
  external(c_ptrTo(x)); // fails
  external(c_ptrTo(y)); // works
}
```

**Compile command:**

```
chpl -o error error.chpl
```

### Configuration Information

- Output of `chpl --version`: 1.25.0

**Comment by bradcray** [comment] 2021-12-03 20:37
Hi Tom —

I put together https://github.com/chapel-lang/chapel/pull/18792 to address this, but in asking for feedback, @mppf pointed out that what I was interpreting as "bug" may actually have been "intention."  Specifically, our `c_ptrTo(myArrayOfReals)` routine returns `double*` pointers (say) rather than `const double*` pointers, which would be the right thing to do for safety if the actual was a `const` array.

But the problem is that we don't currently have a Chapel type for "pointer to const" (see https://github.com/chapel-lang/chapel/issues/14214), raising the dilemma "Do we merge this PR to enable this pattern in the short-term, knowing that it will likely break/change later once we do?  Or do we just hold off on this PR until we add support pointer-to-const?" [potentially using this issue / your use case as incentive to prioritize it].

In the meantime, you could grab this diff and apply it to your copy of Chapel if you wanted to use it as a workaround.  Or, I suspect, you could create your own clone of these modified routines in your code, giving them different names to avoid ambiguities/conflicts, and get away with using them until we have a better solution.

**Comment by riftEmber** [comment] 2023-03-16 21:08
This will be resolved by the [pending addition of const C pointers](https://github.com/chapel-lang/chapel/pull/21913). Updating the originally provided source code, it will be possible to do the following:
```chapel
use CTypes;

proc external(arg : c_ptrConst(real)) { }

proc main()
{
  const x = [1.1, 2.2, 3.3];
  var y = x;
  external(c_ptrToConst(x)); // now works! respecting constness
  external(c_ptrTo(y)); // still allowed as well
}
```

**Comment by bradcray** [comment] 2023-04-19 20:55
@twesterhout : I wanted to make sure you were aware that Anna has added support for const C pointers in https://github.com/chapel-lang/chapel/pull/21913.

@riftEmber , do you think we could close this issue now?  Did your PR happen to add a test like the one in your comment above to the test system to lock the behavior in?

**Comment by twesterhout** [comment] 2023-04-19 20:58
> I wanted to make sure you were aware that Anna has added support for const C pointers in https://github.com/chapel-lang/chapel/pull/21913.

I was aware of the PR, but missed the fact that it got merged. Thanks @riftEmber, this is great news!

**Comment by riftEmber** [comment] 2023-04-24 18:23
@bradcray It didn't add a test for this specifically, but I think that's a good idea, so I've just done it in https://github.com/chapel-lang/chapel/pull/22139. With that I definitely think this can be closed.

**Closed by riftEmber** 2023-04-24 18:23 UTC

**Comment by bradcray** [comment] 2023-04-24 18:41
Thanks Anna!
