### ISSUE TITLE
Should Chapel support compile-time ops on floating point params?

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#7692] opened 2017-10-31 15:26 UTC
Today, assigning a param to a real literal expression results in a compiler error, as shown below.

```chapel
// error: Initializing parameter 'twenty' to value not known at compile time
param twenty = 10.0 + 10.0;

// int case works fine
param thirty = 10 + 20;
```

Should Chapel support these compile-time operations on floating point params?

**Comment by ben-albrecht** [comment] 2017-10-31 15:27
This issue was previously known and is being investigated by @mppf.

**Comment by bradcray** [comment] 2017-10-31 19:34
This is yet another instance of the "Chapel currently doesn't support compile-time operations on floating point params" rationale that comes up in every issue mentioning params and floating point.

**Comment by bradcray** [comment] 2017-10-31 20:38
The reason we backed away from supporting compile-time param operations was for fear that the compile-time floating point semantics (e.g., rounding mode?) would somehow differ from those of the execution-time environment, resulting in confusion.

A counterargument might be "Well, what did you expect when you invoked this compile-time function?"

Of course, the counter-counter-argument is "I didn't know I was invoking a compile-time function, I just wrote "1.0 / 3.0" somewhere in my code and didn't expect the compiler to do anything about it.

I don't have a strong enough grasp on floating point semantics nor what serious floating point users would want/expect in order to know how to resolve this standoff.

**Comment by damianmoz** [comment] 2017-11-20 11:32
One possible answer to the first paragraph is a compiler flag or a warning. That way, if you don't like it, you can change it.

If you warn the user, they can change it to a const if they don't like it. That sort of answers the 2nd paragraph.

As far as constant-expressions-in-the-wild, this is quite different. f you want 1.0/3.0 as a compile time or a run-time constant, then use
.................................  param onethird = 1.0:real(32)/3.0:real(32)
.................................  const onethird = 1.0:real(32)/3.0:real(32);
I would normally prefer to handle real expressions out in the wild at run-time unless the user explicitly uses a param declaration to pull it out. But you could have a compiler flag to treat them as params or consts.

I think expecting optimizing compilers not to do anything is fanciful in this day and age. But I delude myself that I am a numerical analyst, not a compiler writer. so it shows you how much I know about compilers.

I am not sure I have a strong grasp on anything! However, reals need to be in params as first class items like ints/uints. And coercing from a real literal to another width should also be a compile time option for anything. As far as I know, the C statement
...............................   float x = 1.567898765432f;
...............................   float x = (float) 1.567898765432;
inserts the 32-bit version of the the longer valued literal into x at compile time. Ditto with a Fortran DATA statement.

**Comment by damianmoz** [comment] 2017-11-20 14:17
If you are really worried about your 1.0/3.0, you quickly dig into the recessed of your brain and remind youself that, in 64-bit floating hexadecimal, that constant is
................................ param onethird_take1 =  0x1.5555555555555p-2:real(64);
and from this it should be pretty obvious what the rest of it is for infinite precision. The above is exact for a 52-bit significand of a real(64) because the 53rd bit is a '0'. If you want real(32),  you probably need to mess with the rounding to get what you want want. The next digit after the end of a 23-bit significand of a real(32), is as '1'. Think, think. You have 2 choices which differ only in the last bit, i.e.
................................ param onethird_take2 = 0x1.555555p-2:real(32) // if you want truncated
................................ param onethird_take3 = 0x1.555556p-2:real(32) // if you want rounded
It is up to the analyst to figure out what s/he desires in the scheme of things. You could do
................................ param onethird_take4 =  0x1.5555555555555p-2:real(32)
which likely evaluates to onethird_take3 but I could not be sure so I would use the explicit form.

I think you are worried solving the numerical analysts problems automatically, rather than providing the tools/features. There are tools for the former, including the grey matter inside the skull so I think Chapel should do the latter. No other pearls of wisdom left on this one I think. Maybe somebody else has a take on this apparent dilemma.

**Comment by damianmoz** [comment] 2019-02-03 07:00
It was mentioned by @bradcray  that ... I don't have a strong enough grasp on floating point semantics nor what serious floating point users would want/expect in order to know how to resolve this standoff.

How do we move this forward? What do you want to know?  What sort of things? What should I throw up for discussion?

For example, I am trying to write a generic routine to replace exp(x) (say) working on floating point of type R (say) where I need 4 constants, i.e. the last 4 below.

```chapel
param ln2 = ln_2:R;
param quarter = 0.25:R;
param p = fpSigSize(R);
param lnGiant = ln2 * (fpEmax(R) + 1);
param lnDwarf = ln2 * (fpEmin(R) - p - 1);
param lnSmall = quarter / (1:uint(numBits(R)) << (p >> 1));
param lnSmax = ln2 * fpSafe(R);
```
The above gives me 4 values, one above which exp(x) overflows, one under which exp(x) underflows, and a numeric range between which a polynomial approximation will work without problems. I want my
code to work for real(w), w = 16, 32, 64 and 128. All of this will work if R is real(64).

There are so real inaccuracy issues with the above which I can discuss but it is all predicated on having the ability to parameterize the above based on type. Every RHS above has a floating point number multiplied/divided by an integral expression which could be deduced at compile time

Something like a #define in C
```C
...define myLn2(R)     ((R) M_LN2)
...define quarter(R)   ((R) 0.25)
```
would do the job. Sorry I used dots because Github kept trying to grab my hash symbol! Actually the above won't work for real(128) in C but that is another issue with C, not Chapel.

Chapel nominally has all the features to make it work but they break when anything other than real(64) is used. It is just going to get worse if you have to support real(16) and real(128).

There was a mention of this having been resolved in #5122 but I think it was actually some very specific part of this problem.

**Comment by damianmoz** [comment] 2019-02-04 05:00
Chapel just needs to replicate the C preprocessor functionality below. It already has the (not yet working) features to do this way more elegantly that the stuff you see below. The out is obtuse but it should, for doubles, give something like 2^(-28), 0.69....,  -745.13..., 709.08..., 708.39...., 

My use of the word Giant and Dwarf was technically incorrect in terms of their strict meaning for a mathematical model. So I will replace then with Upper and Lower.
```C
#define Uint32      unsigned int
#define Uint64      unsigned long
#define SigSize(R)  (sizeof(R) == 8 ? 53 : 24)
#define fpEmin(R)   ((sizeof(R) == 8 ? (-1022) : (-126)))
#define fpEmax(R)   (1 - fpEmin(R))
#define fpEsafe(R)  (-fpEmin(R))
#define conLn2(R)   ((R) 0.6931471805599453094172321214581766L)
#define con_1_2(R)  ((R) 0.5l)
#define con_1_4(R)  (con_1_2(R) * con_1_2(R))
#define lnUpper(R)  (conLn2(R) * (fpEmax(R)))
#define lnLower(R)  (conLn2(R) * (fpEmin(R) - SigSize(R)))
#define lnVsafe(R)  (conLn2(R) * (fpEsafe(R)))
#define OneBit(R)   (sizeof(R) == 8 ? ((Uint64) 1) : ((Uint32) 1))
#define Small(R)    (con_1_4(R) / ((R) (OneBit(R) << (SigSize(R) >> 1))))

#include    <stdio.h>

#define param   static const

main()
{
    typedef float Real; // change float to double to play with this

    param Real ln2 = conLn2(Real);
    param Real small = Small(Real);
    param Real lower = lnLower(Real);
    param Real upper = lnUpper(Real);
    param Real safe = lnVsafe(Real);

    printf("%.8e\n", small);
    printf("%.8e\n", ln2);
    printf("%10.4f\n", lower);
    printf("%10.4f\n", upper);
    printf("%10.4f\n", safe);
    return(0);
}
```
I have no idea what rounding mode is used by the C/C++ preprocessors but at worst, you add a compiler flag. Another one.

**Comment by mppf** [comment] 2019-02-25 14:56
@damianmoz - I think that's a good point - that C/C++ supports evaluation of floating point constant expressions at compile time.

``` c
#include <stdio.h>
int main() {
   
  printf("%lf\n", 1.0/2.0);
  return 0;
}
```

Looking at the assembly generated, there is no floating point division.

I think that we can support floating point operations on params at compile time. I think we merely need to make sure that they are always IEEE compliant (i.e. no relaxed floating point semantics here). However given the relatively unoptimized manner in which the compiler currently evaluates param expressions... I don't see this as any real challenge.

We could worry that some floating point operations might use 80 bits internally on Intel processors, but this should be expressed with a different floating point type (e.g. `real(80)`). As we discussed in #11335, it's not common practice today to upgrade operations to 80 bits if they were written on 64 bit numbers (and C compilers do 64-bit floating point operations rather than 80 bits today on x86-64, unless you opt in to 80-bits with `long double`).

I have an old branch that implements the compile-time operations on real/imag/complex here:
 https://github.com/mppf/chapel/tree/param-real

Once we are satisfied that the answer to this question is "yes", I expect that I could get that branch ready to merge pretty quickly.

**Comment by gbtitus** [comment] 2019-02-26 20:48
Just a historical note: besides differing settings such as rounding mode at compile and execution time, the other thing that can be a problem is differing FP architectures on the compile-time processor and the execution-time one.  Nowadays with the triumph of IEEE-754 this is rare-to-nonexistent, but it wasn't always so and it's not implausible that hardware specialization for application areas could cause it not to be so in the future.

As an example, the Cray classic parallel-vector systems (through roughly the year 2000) used a proprietary floating point format but the compilers ran on IEEE-754 compliant systems (SPARCs, MIPSs, etc.).  Nevertheless, those compilers folded compile-time constant FP expressions, using bit manipulations to reproduce what the proprietary processors would have done at execution time with the same operands.  And in the compiler for Fortran, with its math library defined by the language standard, they even folded math functions (`LOG()`, `SIN()`, etc.) with constant operands, by "executing" the target processor library code in a little ISA simulator.

But certainly for now, we should be safe just doing the folding natively on the compile-time architecture.

**Closed** 2019-02-28 20:04 UTC
Labels: area: Compiler, area: Language, area: Libraries / Modules, gating issue, stat: Needs Design Review, type: Feature Request, user issue
