### ISSUE TITLE
Cannot multiply sparse matrix with derived vector

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8056] opened 2017-12-17 16:14 UTC
Almost certainly related to https://github.com/chapel-lang/chapel/issues/8023 but I don't want presume.

Once again our story begins with a matrix `A`.  It is sparse.  I want to multiply this matrix with a `1` vector.  

```chapel
use LinearAlgebra, LayoutCS;

var nv: int = 8,
    D: domain(2) = {1..nv, 1..nv},
    SD: sparse subdomain(D),
    A: [SD] real;

SD += (1,2); A[1,2] = 1;
SD += (1,3); A[1,3] = 1;
SD += (1,4); A[1,4] = 1;
SD += (2,2); A[2,2] = 1;
SD += (2,4); A[2,4] = 1;
SD += (3,4); A[3,4] = 1;
SD += (4,5); A[4,5] = 1;
SD += (5,6); A[5,6] = 1;
SD += (6,7); A[6,7] = 1;
SD += (6,8); A[6,8] = 1;
SD += (7,8); A[7,8] = 1;

writeln(A);
writeln(diag(A));
writeln(diag(diag(A)));
```

Good so far.  But wait, there is a villain in this story as well.

```
> chpl -I/usr/local/Cellar/openblas/0.2.20/include -L/usr/local/Cellar/openblas/0.2.20/lib -lblas digs.chpl
digs.chpl:26: error: unresolved call '[DefaultSparseDom(2,int(64),domain(2,int(64),false))] real(64).dot([domain(2,int(64),false)] real(64))'
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:435: note: candidates are: dot(A: [?Adom] ?eltType, B: [?Bdom] eltType)
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:445: note:                 _array.dot(A: [] )
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:452: note:                 dot(A: [?Adom] ?eltType, b)
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:460: note:                 dot(a, B: [] )
$CHPL_HOME/modules/packages/BLAS.chpl:2074: note:                 dot(X: [?xD] ?eltType, Y: [?yD] eltType, incY: c_int = 1, incX: c_int = 1)
```

I cannot multiply this matrix with it's own diagonal. Why would I want to?  Because I'm crazy that way.  Next, I can't multiply it with a `1` vector.

```
 chpl -I/usr/local/Cellar/openblas/0.2.20/include -L/usr/local/Cellar/openblas/0.2.20/lib -lblas digs.chpl
digs.chpl:26: error: unresolved call '[DefaultSparseDom(2,int(64),domain(2,int(64),false))] real(64).dot([domain(2,int(64),false)] real(64))'
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:435: note: candidates are: dot(A: [?Adom] ?eltType, B: [?Bdom] eltType)
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:445: note:                 _array.dot(A: [] )
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:452: note:                 dot(A: [?Adom] ?eltType, b)
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:460: note:                 dot(a, B: [] )
$CHPL_HOME/modules/packages/BLAS.chpl:2074: note:                 dot(X: [?xD] ?eltType, Y: [?yD] eltType, incY: c_int = 1, incX: c_int = 1)
```

What is the proper way to do this?

**Comment by ben-albrecht** [comment] 2017-12-17 23:10
I see 2 problems with your example:

1. `LinearAlgebra.Sparse` only works with `CSR` layout. 

`var SD: sparse subdomain(D)` corresponds to `COO` layout. 

You will need `var SD: sparse subdomain(D) dmapped CS(compressRows=true)` to specify `CSR` layout.

2. `LinearAlgebra.Sparse` only supports a subset of `LinearAlgebra` procedures. `diag()` is unfortunately not yet supported as part of that subset.

I'll interpret this issue as a feature request for `LinearAlgebra.Sparse.diag()`.

See [LinearAlgebra.Sparse docs](https://chapel-lang.org/docs/master/modules/packages/LinearAlgebra/Sparse.html#sparse) for more info.

**Comment by buddha314** [comment] 2017-12-18 17:18
Thanks for the update, can you think of a way to fake `diag()` on a sparse matrix?  If I created a new domain as a sparse sub-domain of `D` and added all the `(i,i)`'s would I be able to multiply them?

**Comment by ben-albrecht** [comment] 2017-12-18 17:50
>  If I created a new domain as a sparse sub-domain of D and added all the (i,i)'s would I be able to multiply them?

Yes, this should work, assuming you're using CSR layout.

**Comment by buddha314** [comment] 2017-12-18 17:52
Building on the example above, I tried this:

```
var diagDom: sparse subdomain(D)  dmapped CS(compressRows=true);
for i in 1..nv {
  diagDom += (i,i);
}
writeln(A[diagDom]);
```

And it spat venom during compilation:
```
 chpl -I/usr/local/Cellar/openblas/0.2.20/include -L/usr/local/Cellar/openblas/0.2.20/lib -lblas digs.chpl
digs.chpl:31: error: unresolved call 'CSDom(2,int(64),domain(2,int(64),false),true,false).dsiGetIndices()'
$CHPL_HOME/modules/internal/DefaultRectangular.chpl:115: note: candidates are: DefaultRectangularDom.dsiGetIndices()
$CHPL_HOME/modules/internal/DefaultOpaque.chpl:95: note:                 DefaultOpaqueDom.dsiGetIndices()
```

**Comment by ben-albrecht** [comment] 2017-12-18 18:12
The venom is from trying to slice a sparse array by a sparse subdomain. That's not supported (at least today).

This is a little more verbose, but gets the job done:

```chpl
var B: [diagDom] int;

forall i in sD.dim(1) {
  if SD.member((i,i)) {
    B[i, i] = A[i, i];
  }
}

writeln(B);
```

**Comment by buddha314** [comment] 2017-12-18 18:43
Okay, now I can get `B`, but then....

```
writeln("\nA.dot(B)\n", A.dot(B));
```
on compilation this violently expectorates

```
chpl -I/usr/local/Cellar/openblas/0.2.20/include -L/usr/local/Cellar/openblas/0.2.20/lib -lblas digs.chpl
digs.chpl:41: error: unresolved call '[CSDom(2,int(64),domain(2,int(64),false),true,false)] real(64).dot([CSDom(2,int(64),domain(2,int(64),false),true,false)] real(64))'
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:435: note: candidates are: dot(A: [?Adom] ?eltType, B: [?Bdom] eltType)
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:445: note:                 _array.dot(A: [] )
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:452: note:                 dot(A: [?Adom] ?eltType, b)
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:460: note:                 dot(a, B: [] )
$CHPL_HOME/modules/packages/BLAS.chpl:2074: note:                 dot(X: [?xD] ?eltType, Y: [?yD] eltType, incY: c_int = 1, incX: c_int = 1)

```

**Comment by ben-albrecht** [comment] 2017-12-18 18:55
I can't determine the origin of your expectoration without seeing the full example.

[Here](https://gist.github.com/ben-albrecht/98df054b389e4b07004ccbbb6cefa7c4) is a working example derived from your original question.

**Comment by buddha314** [comment] 2017-12-18 19:13
Right, that works for me, too. It has a few patterns I haven't been using, so I'll have to work those in.  For instance, I've been calling `dmapped CS()` instead of `CSRDomain()`.  Yours is much cleaner!

**Comment by buddha314** [comment] 2017-12-18 19:22
Also, I don't understand how this bit works

```
const nv = 8;
var SD = CSRDomain(1..nv),
     A = CSRMatrix(SD);
```

`1..nv` is one dimensional, so isn't `SD` one dimensional as well?

**Comment by buddha314** [comment] 2017-12-18 19:30
All right!  This is much cleaner!

What if I don't know the number of rows/columns to begin with?

**Comment by ben-albrecht** [comment] 2018-09-07 21:33
This issue seems to boil down to a feature request for supporting dynamically bounded sparse arrays, which is the focus of issue #7544. I'm going to close this issue as duplicate of that one. 

Let me know if you disagree with that observation.

**Closed by ben-albrecht** 2018-09-07 21:33 UTC
Labels: area: Modules, type: Feature Request, user issue
