### ISSUE TITLE
Cannot compile forwarding class with type variable

### ISSUE THREAD

**Issue by marcoscleison** [chapel-lang/chapel#7840] opened 2017-11-20 21:20 UTC
### Summary of Problem

I have one class A that has a type variable.
I have another class B that forwards methods to A.
I want B using forwarding to A and pass itself (B type)  a parameter. 

### Steps to Reproduce

I have two classes with forwarding and type variable.

```chapel
module Main{

class A{
type selfType;
    proc print(){
        writeln("hi, from A");
    }

}
class B{
    forwarding var a: A;
}
proc main(){
    var b = new B(new A(B));
    b.print();
    writeln("End");
}
}
```
When I try to compile it results in error:

```bash
teste.chpl:15: error: unresolved type specifier 'A()'
teste.chpl:3: note: candidates are: A(type selfType)
```
If I specify the Parameter type i get more errors:

```chapel
module Main{

class A{
type selfType;
    proc print(){
        writeln("hi, from A");
    }
}
class B{
    forwarding var a:A(B);// Chenged here
}
    proc main(){
        var b = new B(new A(B));
        b.print();
        writeln("End");
    }
}
```
```bash
teste.chpl:13: In function 'main':
teste.chpl:15: error: unresolved call 'B.print()'
teste.chpl:6: note: candidates are: A.print()
teste.chpl:11: note:                 B.print()
```

### Configuration Information

- Output of `chpl --version`:
```bash
chpl Version 1.16.0.e43acc7b31
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

```bash
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_REGEXP: none *
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```bash
gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ben-albrecht** [comment] 2017-11-20 23:17
Might be good for @mppf to take a look at this.

**Comment by mppf** [comment] 2018-07-18 17:38
The declaration `forwarding var a: A;` makes `class B` generic. As a result, it can't be used to set `selfType` in `new B(new A(B));`. Chapel doesn't currently support type fields that refer to generic types.

This issue has nothing to do with forwarding. The following variant still fails to compile:

``` chapel
module Main {
  class A {
    type selfType;
    proc print(){
        writeln("hi, from A");
    }
  }
  class B {
    var a: A;
  }
  proc main(){
    var b = new B(new A(B));
    b.a.print();
    writeln("End");
  }
}
```

**Comment by mppf** [comment] 2018-07-18 21:13
You can't call a type function with a generic type. I'm not sure this has its own issue but it probably should. It could be feature request.

**Comment by DanilaFe** [comment] 2024-07-09 18:54
The first piece of code seems to be working on `main` today. The second seems problematic due to the inner `B` being generic / of potentially a different type than the "outer" B:

```
forwarding var a: A(B);
```

**Comment by mppf** [comment] 2024-07-11 15:06
I think the problem currently in the second one is that `a` is declared with a class type with generic management. It could use `forwarding var a: owned A(B);` or perhaps `forwarding var a: owned A(owned B);` and I would expect it to work.

**Comment by DanilaFe** [comment] 2024-07-11 23:49
I will try it. If it works, I'll close the issue and add regression tests.

**Comment by DanilaFe** [comment] 2024-07-12 00:22
The remaining error is https://github.com/chapel-lang/chapel/issues/20500, which is unrelated to forwarding, so I will close this when the regression test PR merges.

**Closed** 2024-07-12 00:44 UTC
Labels: type: Bug, area: Compiler, user issue
