### ISSUE TITLE
make test failed in chapel@1.24.1

### ISSUE THREAD

**Issue by Tom-python0121** [chapel-lang/chapel#18066] opened 2021-07-14 02:12 UTC
I meet a problem:make test failed in chapel@1.24.1.
### Steps to reproduce the issue

```console
[root@localhost ~]# spack install --keep-stage -v chapel@1.24.1
[root@localhost spack-src]# spack cd chapel@1.24.1
[root@localhost spack-src]#spack load chapel@1.24.1
[root@localhost spack-src]# . ../spack-build-env.txt
[root@localhost spack-src]# make test-venv
[root@localhost spack-src]# make test
……
[Done with tests - 210714.094908]
[Log file: /home/all_spack_env/spack_stage/root/spack-stage-chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn/spack-src/test/Logs/root.linux64.log ]

[Test Summary - 210714.094908]
[Error matching compiler output for compflags/bradc/printstuff/version]
[Error matching compiler output for compflags/bradc/printstuff/zall]
[Error matching compiler output for compflags/bradc/printstuff/zcopyvers]
[Error matching compiler output for compflags/bradc/printstuff/zhelpvers]
[Error matching compiler output for compflags/bradc/printstuff/zlicevers]
[Error matching --print-chpl-home home 0a (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 0a (got  but expected /tmp/OpFelaMVGC/chplhome/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home home 0b (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 0b (got  but expected /tmp/OpFelaMVGC/chplhome/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home home 0c (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 0c (got  but expected /tmp/OpFelaMVGC/chplhome/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home home 0d (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 0d (got  but expected /tmp/OpFelaMVGC/chplhome/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home home 0e (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 0e (got  but expected /tmp/OpFelaMVGC/chplhome/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home home 0f (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 0f (got  but expected /tmp/OpFelaMVGC/chplhome/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home home 1a (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 1a (got  but expected /tmp/OpFelaMVGC/chplhome2/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home home 3a (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 3a (got  but expected /tmp/OpFelaMVGC/bin/chpl)]
[Error matching --print-chpl-home home 3b (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 3b (got  but expected /tmp/OpFelaMVGC/bin/chpl)]
[Error matching --print-chpl-home home 3c (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 3c (got  but expected /tmp/OpFelaMVGC/bin/chpl)]
[Error matching --print-chpl-home home 4a (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 4a (got  but expected /tmp/OpFelaMVGC/chplhome/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home home 4b (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 4b (got  but expected /tmp/OpFelaMVGC/chplhome2/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home home 4c (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 4c (got  but expected /tmp/OpFelaMVGC/chplhome/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home home 4d (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 4d (got  but expected /tmp/OpFelaMVGC/chplhome/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home home 4e (got # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn but expected /tmp/OpFel
[Error matching --print-chpl-home exe 4e (got  but expected /tmp/OpFelaMVGC/chplhome/bin/linux64-aarch64/chpl)]
[Error matching --print-chpl-home errs 5a did not find CHPL_HOME must be set in /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn/share/chapen/chpl # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn ]
[Error matching --print-chpl-home errs 5b did not find CHPL_HOME must be set in /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn/share/chapen/chpl # configured prefix  /home/all_spack_env/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/chapel-1.24.1-ry3pnitwnegepioh4srbwtshkogi5wrn ]
[Error matching compiler output for compflags/link/sungeun/static_dynamic (compopts: 1)]
[Error matching compiler output for compflags/link/sungeun/static_dynamic (compopts: 2)]
[Error matching compiler output for compflags/link/sungeun/static_dynamic (compopts: 3)]
[Error matching program output for library/standard/FileSystem/chmod/chmod_noprivilege]
[Error matching program output for library/standard/FileSystem/fsouza/chown/permission_error]
[Error matching program output for library/standard/Prefetch/prefetch]
[Error matching man page(s) with compiler environment]
[Error matching program output for memory/shannon/outofmemory/mallocOutOfMemory]
[Error matching program output for parallel/cobegin/gbt/cobegin-stacksize (execopts: 1)]
[Error matching program output for parallel/taskPool/figueroa/TooManyThreads]
[Error matching program output for param/ferguson/param-inf]
[Error matching compiler output for regexp/elliot/I-fail-without-re2]
[Error matching program output for studies/colostate/Jacobi1D-DiamondByHand-OMP_dyn]
[Error matching program output for studies/colostate/Jacobi1D-DiamondByHand-OMP_static]
[Error matching program output for studies/colostate/Jacobi1D-NaiveParallel-OMP_static]
[Error matching program output for studies/colostate/Jacobi1D-Serial-C]
[Error matching program output for studies/colostate/Jacobi2D-DiamondByHandParam-OMP_dyn]
[Error matching program output for studies/colostate/Jacobi2D-DiamondByHandParam-OMP_static]
[Error matching program output for studies/colostate/Jacobi2D-NaiveParallel-OMP_dyn]
[Error matching program output for studies/colostate/Jacobi2D-NaiveParallel-OMP_static]
[Error matching program output for studies/colostate/Jacobi2D-NaiveParallelSpaceTiled-OMP]
[Error matching program output for studies/colostate/Jacobi2D-Serial-C]
[Error matching program output for trivial/bradc/savecInNonWriteableDir]
Suppress () [Error matching program output for users/engin/partial_reduction_support/unit_tests/partialDomainBlock]
Suppress () [Error matching program output for users/engin/partial_reduction_support/unit_tests/partialDomainCyclic]
Suppress () [Error matching program output for users/engin/sparse_bulk_dist/diags (compopts: 1)]
Suppress () [Error matching program output for users/engin/sparse_bulk_dist/diags (compopts: 2)]
Suppress () [Error matching program output for users/engin/sparse_bulk_dist/distCSCBulkAdd]
Suppress () [Error matching program output for users/engin/sparse_bulk_dist/sparseBulkAddHere]
[Warning: Could not find chpldoc, skipping test chpldoc/enum.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/extern-block.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/intents.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/iterators.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/multifile.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/returnTypeExpression.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/variableArguments.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/basics/disconnectedComment.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/basics/empty.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/basics/fullyCommented.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/basics/hello.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/basics/interruptingComment.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/basics/interruptingSingleComment.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/basics/longerComments.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/basics/main.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/basics/nestFunctions.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/basics/parenthesesLess.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/basics/sparselyCommented.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/basic.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/fieldInheritance.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/fields.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/forwards-generic.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/inheritance.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/init-deinit.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/lifetimeChecking-generic.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/lifetimeChecking-notype.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/lifetimeChecking.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/methodOutsideClassDef.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/methods.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/multipleInheritance.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/override-doc.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/paramFields.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/this.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/classes/typeMethods.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/author/basic/author.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/author/withSpace/withSpace.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/author/withSpecialChar/withSpecialChar.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/author/withoutAuthor/withoutAuthor.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/comment/badClose.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/comment/basic.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/comment/incorrectLabel.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/comment/incorrectLabel2.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/comment/loseComments.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/comment/specifiedDefault.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/folder/failToCreateDir.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/folder/oneWord.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/folder/withHyphen.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/folder/withUnderscore.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/folder/save-sphinx/deepNestModules.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/folder/save-sphinx/save-sphinx.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/textonly/disconnectedComment.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/textonly/empty.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/textonly/fullyCommented.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/textonly/hello.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/textonly/interruptingComment.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/textonly/interruptingSingleComment.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/textonly/longerComments.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/textonly/main.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/textonly/nestFunctions.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/textonly/parenthesesLess.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/textonly/sparselyCommented.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/compflags/version/projectVersion.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/enum/docConstants.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/errhandling/throwing.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/extensions/mathjax.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/functions/functionArgDefaultOneTuple.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/functions/functionArgDefaultWithParens.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/functions/functionArgDefaults.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/arrayLiteral.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/arrayTypeAlias.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/atomics.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/calls.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/constants.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/dmappedArr.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/domains.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/enums.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/globalOrdering.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/ifParamCondition.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/lifetimeChecking.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/paramVars.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/typeVars.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/variableDefaultValues.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/variablePrecedence.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/variablepatterns.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/globals/variables.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/include/test-Include.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/linkage-spec/exportTest.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/linkage-spec/externTest.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/linkage-spec/inlineTest.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/module/config.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/module/defaultModule.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/module/modDeinit.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/module/module.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/module/nestModules.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/module/nestWithFns.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/module/ordering.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/module/sameName.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/module/sameName2.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/module/surroundingModule.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/nodoc/nestedBlocks.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/nodoc/noDocPlease.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/nodoc/privateClasses.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/nodoc/privatePlease.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/nodoc/privateTypeAlias.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/paramMethod.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/arguments/arrays.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/arguments/domains.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/arguments/enums.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/arguments/explicitImplicit.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/arguments/methodCall.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/arguments/queried.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/arguments/recordsAndClasses.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/arguments/tuples.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/config/basic.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/arrays.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/basic.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/complexes.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/domains.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/enums.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/fieldDefaultValues.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/imags.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/rangesAndDomains.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/reals.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/recordsAndClasses.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/tuples.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/typevar.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/fields/usesTypeVar.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/returns/arrays.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/returns/basic.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/returns/domains.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/returns/enums.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/returns/recordsAndClasses.doc]
[Warning: Could not find chpldoc, skipping test chpldoc/types/returns/tuples.doc]
[Warning: Could not find chpldoc, skipping test compflags/thomasvandoren/chpldoc.doc]
[Warning: Could not find chpldoc, skipping test compflags/thomasvandoren/chpldoc/copyright.doc]
[Warning: Could not find chpldoc, skipping test compflags/thomasvandoren/chpldoc/license.doc]
[Warning: Could not find chpldoc, skipping test compflags/thomasvandoren/chpldoc/version.doc]
[Warning: Could not find chpldoc, skipping test compflags/thomasvandoren/chpldoc/z_copy_help.doc]
[Warning: Could not find chpldoc, skipping test compflags/thomasvandoren/chpldoc/z_copy_license.doc]
[Warning: Could not find chpldoc, skipping test compflags/thomasvandoren/chpldoc/z_copy_version.doc]
[Warning: Could not find chpldoc, skipping test compflags/thomasvandoren/chpldoc/z_copyright_help_license_version.doc]
[Warning: Could not find chpldoc, skipping test compflags/thomasvandoren/chpldoc/z_help_license.doc]
[Warning: Could not find chpldoc, skipping test compflags/thomasvandoren/chpldoc/z_help_version.doc]
[Warning: Could not find chpldoc, skipping test compflags/thomasvandoren/chpldoc/z_license_version.doc]
[Warning: Could not find chpldoc, skipping test release/examples/primers/chpldoc.doc]
[Warning: Could not find chpldoc, skipping test variables/bradc/pragmaMultipleVars.doc]
[Summary: #Successes = 12068 | #Failures = 60 | #Futures = 0 | #Warnings = 146 ]
[Summary: #Passing Suppressions = 0 | #Passing Futures = 0 ]
[END]

make: *** [Makefile.devel:62: test] Error 2
```
### Information on your system
[root@localhost spack-src]# spack debug report
* **Spack:** 0.16.1-1624-a0b5dcca3c
* **Python:** 3.6.8
* **Platform:** linux-centos8-aarch64
* **Concretizer:** original

**Comment by bradcray** [comment] 2021-07-14 02:29
Hi @Tom-python0121 — This is going to be a quick response, but maybe not the most helpful one (though I hope more helpful ones will follow it).

Any Spack-based support for Chapel was not developed by the Chapel team / this organization, and I've heard it said that the original Spack formula (is that even the right term?) for Chapel didn't really "get" how to best build and install Chapel like our team intends, and wasn't very useful as a result.  Perhaps things have improved since then, but I'm not sure, and I'm not sure anyone else on my team would know either without investigating further.

That's not to say that we wouldn't be willing to work through this issue with you and try to improve the status quo (we've definitely discussed expending effort to get Chapel better integrated into Spack, but haven't started on it yet).  Just that installing Chapel via Spack is not something we're particularly expert in nor have much ownership over—or investment in—at present.  So it's not completely surprising to me that this doesn't work as you'd hoped / expected.

**Comment by bradcray** [comment] 2021-07-14 03:09
(I don't think there's any need to close this per se; I do think it'd be good for us to understand the state of Chapel with Spack, so that other users don't step into a pit trap that's laying in wait for them; at best, we could fix or improve the Spack package; at worst, we could ask Spack to remove the Chapel formula).

I also should've said in the original mail:  This is the official source of information for ways to install Chapel that are supported by our team:  https://chapel-lang.org/download.html

**Comment by Tom-python0121** [comment] 2021-07-14 03:12
@bradcray You're right, let me reflect: these tests took me a day and a night to complete, too long, but the results surprised me and were not ideal. Then I'll reopen it.

**Comment by mppf** [comment] 2021-07-14 11:49
Yes, ideally `make test` in such a configuration doesn't take that long. We have `make check` for a quick check and this is intended for end-user testing. Also the next release is already adjusted to run a subset of tests on `make test` (but it will still probably take longer than most projects). https://github.com/chapel-lang/chapel/commit/355a1beed20348d4f7906cadd13c34907726f3cd#diff-67cdd459db044e746e6ec9bac9505db86ffe2de7199ff30874e0c7ef52431ab5R61 is the change that did that. Note that `make test` isn't even included in our normal release tarballs (the expectation is that users of the release will run `make check` instead). If that's confusing, we'd probably be open to make `make test` just do the same thing as `make check` if that's something you'd like to advocate for.

Additionally, while I agree that the spack package isn't necessarily ideal, many of those test failures you would see in other settings using `make install`. The 12,000 or so tests you ran are intended to work in our nightly testing configurations and from source code checkouts but they aren't really intended for end user testing. It is possible to get them passing with something that is already `./configure`'d but it would take some adjustments.

**Comment by mingodad** [comment] 2021-07-14 15:39
For me and a fresh repository clone on ubuntu 18.04 (I can build chapel-1.24.1):
```
make: /home/mingo/dev/c/A_programming-languages/chapel/util/config/find-python.sh: Command not found
make: /home/mingo/dev/c/A_programming-languages/chapel/util/config/find-python.sh: Command not found
make[1]: /home/mingo/dev/c/A_programming-languages/chapel/util/config/find-python.sh: Command not found
make[1]: /home/mingo/dev/c/A_programming-languages/chapel/util/config/find-python.sh: Command not found
Making the compiler...
Traceback (most recent call last):
  File "/home/mingo/dev/c/A_programming-languages/chapel/util/chplenv/printchplenv.py", line 48, in <module>
    from chplenv import *
  File "/home/mingo/dev/c/A_programming-languages/chapel/util/chplenv/chplenv.py", line 11, in <module>
    import chpl_gmp
  File "/home/mingo/dev/c/A_programming-languages/chapel/util/chplenv/chpl_gmp.py", line 5, in <module>
    import chpl_3p_gmp_configs, chpl_compiler, chpl_platform, overrides
ImportError: No module named chpl_3p_gmp_configs
/home/mingo/dev/c/A_programming-languages/chapel/make/Makefile.base:102: *** error running util/printchplenv -- please see error above.  Stop.
Makefile:78: recipe for target 'compiler' failed
make[1]: *** [compiler] Error 2
Makefile:59: recipe for target 'comprt' failed
make: *** [comprt] Error 2
```

**Comment by mppf** [comment] 2021-07-14 15:57
@mingodad - that's surely a different problem from this issue. Additionally we'll need more information to help you with it. (For one thing I am able to build Chapel on Ubuntu 18.04). You'll probably need to show the exact commands you are running, starting from the `git clone`. I recommend you bring it up in our Gitter, Discourse, or in a different issue. Thanks.

**Comment by mingodad** [comment] 2021-07-14 16:47
The problem is that a fresh git clone has the chckout of `early-shasta-modules` this will make more than one ask the same question again and again:
```
git clone https://github.com/chapel-lang/chapel.git
git branch
  1.23-for-EX
* early-shasta-modules
  main
```

**Comment by mppf** [comment] 2021-07-14 16:53
@mingodad - I don't see that behavior on Ubuntu 18.04. Like I said, better to move this to another issue/topic/etc.

**Comment by mppf** [comment] 2022-02-17 13:52
I'm going to close this issue since 1.24 is no longer the current release and the new release adjusts `make test` to run a more reasonable number of tests.

**Closed by mppf** 2022-02-17 13:52 UTC
