### ISSUE TITLE
Provide line number and / or file name for config var errors

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8600] opened 2018-02-26 19:02 UTC
Getting this guy and I can't track it down.  It would be good to provide line numbers and file names for something like this

```
internal error: unknown config var case not handled appropriately
```

**Comment by ben-albrecht** [comment] 2018-02-26 19:17
Is this any different than #8471 ?

**Comment by buddha314** [comment] 2018-02-26 19:19
Good question, it happened in a completely different code base, but I don't know what threw either.  Still trying to fix this one.

**Comment by bradcray** [comment] 2018-02-26 19:24
I agree that one or the other is a duplicate.  Like #8471, I'm willing to take this issue (it's probably my bug), but without some code or a reproducer, I don't know how to make progress with it.

**Comment by bradcray** [comment] 2018-02-26 19:32
(implementing the edit to the runtime proposed on #8471 and seeing what the new output would be would be a great starting point).

**Comment by buddha314** [comment] 2018-02-26 19:32
It's really hard to reproduce, I'm dealing with a bunch of libraries and internal code, so trying to strip everything down is a lot of time.

I think I have a clue, however.  It seems to happen if I am running a compiled program that expects a `const config` but doesn't get it.  I'm not certain because in my rather complicated build system I am going from error to error.  Sorry to not have better insights!

**Comment by bradcray** [comment] 2018-02-26 19:35
There's no need to strip it down if you can share the code and tell me how to reproduce it.  If you can't do that, making the proposed runtime change, re-building, re-running, and seeing which module/variable name it's complaining about may help us determine what's going wrong and what's unique about this case.

**Comment by buddha314** [comment] 2018-02-26 19:43
This is the test I'm running when the error occurs:

```chapel
use Ayatollah, Chrest, ChrestClient, Spawn, Time;

const API_VERSION = "v1",
      API_HOST: string = "127.0.0.1",
      API_PORT: int = 8080;

var msg = """
   Running Tests on the Ayatollah API against the binary currently in bin/ayatollah.
   From the top of the repository (where you see the Makefile)
   - Refresh the binary with
     make
  """;
writeln(msg);

writeln("*** Starting APIyatollah on host:port ", API_HOST, ":", API_PORT);
var sub = spawn(["exec", "--listen=true", "-f", "../macbuddha.cfg"], executable= "../bin/ayatollah");
sleep(2);
writeln("*** Building clientollah");
try {
  var clientollah = new ChrestClient(API_HOST, API_PORT);
  var res = clientollah.Get("/api/" + API_VERSION);
  var content:string = res();
  writeln("\tContent Get: ",content);
}  catch e:ChrestConnectionError{
  writeln("Connection Error: ", e);
} catch e {
  writeln(e);
}
sub.kill();
sub.close();
```

Note that it runs our server in a thread and then creates a client to connect.  This means the server has to be pre-compiled.  In the `macbuddha.cfg` file I set several variable, including `API_VERSION`.  That's about all i can tell you at the moment.

**Comment by buddha314** [comment] 2018-02-26 19:50
Okay, appears to be another clue (but my errors are inconsistent, so not sure).  I use the config constant `API_VERSION` and pass it into a proc called `listen(API_VERSION)`.  My guess now is that when the const isn't set, it barfs at the point of calling `listen`.  See what I man? Nobody listens to me...

**Comment by bradcray** [comment] 2018-02-26 19:55
API_VERSION doesn't appear to be a `config const` but instead merely a `const`.  Could that be the issue?  Trying to set a `const` as though it was a `config` when it's not?

Aha, yes, that seems to be the issue.  OK, I can reproduce now, thanks!

**Comment by bradcray** [comment] 2018-02-26 20:25
I've got a branch that would now generate the error:

```
error: attempt to set config named 'API_VERSION', but there is no such config
```

Would that have been sufficient to make the issue clear?

**Comment by buddha314** [comment] 2018-02-26 20:32
Man, I love a good hand-tailored solution!! As a customer, I feel heard.  I can wait another 10 minutes if you want to generalize the error with a configurable string....

I *think* it would have surfaced it.  Either way, it seems a reasonable approach, right?

**Comment by bradcray** [comment] 2018-02-26 22:58
Oh yeah, it's definitely a step forward.  I was wondering more whether it was sufficient / if there was anything I should change about it before testing / reviewing / merging.

**Comment by buddha314** [comment] 2018-02-26 23:00
It seems there are a couple of errors working in concert to create the Devil's Symphony here.  My feeling is that I can't discriminate which of the little cuddly bits is the worst.  All that to say "I don't know, but it will help to some degree".

**Comment by bradcray** [comment] 2018-02-27 08:40
I've filed PR #8616 to improve this case as alluded to above.  It still needs testing and review but I expect it will go in on Tuesday (and you're welcome to merge it to try it out in the meantime).  I'm also going to close the original issue as a duplicate of this one.

**Closed** 2018-02-28 18:12 UTC
Labels: area: Runtime, type: Error Message, user issue

**Comment by bradcray** [comment] 2018-02-28 18:39
@buddha314 : This should now be fixed on master.  Thanks for helping us to track down the cause.
