### ISSUE TITLE
Compiler Error: AST-PRI-IVE-0242 chpl version 1.29.0

### ISSUE THREAD

**Issue by kwaters4** [chapel-lang/chapel#22011] opened 2023-03-30 14:53 UTC
### Summary of Problem

Run into this compiler error working through a problem. Below is a reduced example that reproduces the error. Here is an [ATO link](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3vUqLUxWcQyoLUoutubiKUpPzi1IU0vLzFaq5OMsSixQqrLlq4eJJQAGoeFJpWpqVQnJ8QUmRBlC5JlAZxESowTALAA) as well. If the type of `var x` is defined in `record foo` the error is not present.

I have not yet tried to reproduce this with Chapel 1.30, but I will do that later. If I am unable to reproduce it, I will close this issue.

### Steps to Reproduce

**Source Code:**

```chapel
use CTypes;

record foo {
    var x;
}

record bar {
    var buff: c_ptr(foo);
}
```

**Compile command:**
`chpl foo.chpl`

**Error Message**
```
/ATO/code.chpl:8: In method 'buff':
/ATO/code.chpl:8: internal error: AST-PRI-IVE-0242 chpl version 1.29.0
```
### Configuration Information

Reproduced in [ATO](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3vUqLUxWcQyoLUoutubiKUpPzi1IU0vLzFaq5OMsSixQqrLlq4eJJQAGoeFJpWpqVQnJ8QUmRBlC5JlAZxESowTALAA) (Chapel 1.29.0)

**Comment by DanilaFe** [comment] 2023-03-30 16:19
Still happens on `main`:
```
bug.chpl:1: In module 'kwaters':
bug.chpl:8: warning: partial instantiation without '?' argument
bug.chpl:8: note: opt in to partial instantiation explicitly with a trailing '?' argument
bug.chpl:8: note: or, add arguments to instantiate the following fields in generic type 'c_ptr(foo)':
$CHPL_HOME/modules/standard/CTypes.chpl:124: note:   generic type field 'eltType'
bug.chpl:8: In method 'buff':
bug.chpl:8: internal error: invalid attempt to get reference type [AST/primitive.cpp:238]
```

As the warning hints, this likely has something to do with `buff` being a `c_ptr` to a generic type `foo` (generic because of `var x`). Not sure yet what causes the internal error.

**Comment by bradcray** [comment] 2023-03-30 17:53
Thanks for reporting this Kevin, and for looking into it, Daniel!

Coincidentally, this was one of the things I was preparing release notes slides for yesterday.  The crux of the issue is definitely that `foo` is a generic type by virtue of `x` being an untyped field, and the internal error is almost certainly because the compiler wasn't expecting that along some code path.  My expectation is that there isn't any intention to support `c_ptr` types to generic types in order to be as concrete as C is when it comes to its C pointer type.  If you needed something more generic, `c_void_ptr` is probably your best bet at present.

Besides supplying a type for `x` in its declaration, you could also specify a type signature for `foo` in the `c_ptr` type specifier to make it concrete:  [ATO](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3-0qLUxWcQyoLUoutubiKUpPzi1IU0vLzFaq5OMsSixQqrLlq4eJJQAGoeFJpWpqVQnJ8QUmRBlC5RmZeiaYmWC1INk3BViEvtRxkkIaJEVAcrAUqCDRFA6wxJF8jDaSpvCizJDUnTyNJ0xriKqjjYI4EAA).

I want to caution, though, that there's discussion about whether to remove the automated type constructor that the compiler creates for records like `foo` with untyped/generic fields.  That is, where today, it creates a type constructor that effectively has the signature `proc type init(type x)`(which is what permits me to say `c_ptr(foo(int))` in the ATO example above), we are discussing potentially revoking that because it's generally pretty subtle to map from generic fields to type constructor signatures like we do today (this case is not so bad, but it's not difficult to create much more subtle cases once arrays or generic classes/records are involved.  Nothing's been decided yet, just wanted to make you aware.

For code that isn't just sketching, a better practice is to declare an explicit type field describing foo, like:

```chapel
record foo {
    type t;
    var x: t;
}
```

which will generate a type constructor signature like `proc type init(type t)` (which we don't intend on changing/removing) while still permitting you to write `c_ptr(foo(int))` (or whatever instantiation you want).

**Comment by DanilaFe** [comment] 2023-03-30 18:42
Alternatively, if a generic `bar` is still desired, consider explicitly adding a type parameter to feed to `foo`:

```Chapel
record foo {
    var x;
}

record bar {
    type t;
    var buff: c_ptr(foo(t));
}
```

This seems to work ([ATO](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3V5cWpyo4h1QWpBZbc3EVpSbnF6UopOXnK1RzKQBBWWKRQoU1Vy1cKgkoAJEqAepRKLGGK0sqTUuzUkiOLygp0gAaoFGiqQnWCJYztALp1MjMKwEKlhdllqTm5GkkGeqBNAFFIIqMIIqKUhNzkFUZwVRBnAx1OcwHAA)). From a technical perspective: the issue is that it's not clear to the compiler early enough that `bar` is generic. Making it explicitly generic fixes the problem.

**Comment by bradcray** [comment] 2023-04-01 00:56
Putting myself into the shoes of a semi-naive user receiving the warning:

```bash
bug.chpl:8: warning: partial instantiation without '?' argument
```

My intuition was "of course, I should declare this as `c_ptr(foo(?))` since foo is a generic.  Yet that didn't make the error go away, and `c_ptr(foo, ?)` did even though we think of `c_ptr` as a one-argument generic.  That makes me think that something may be wrong with our partial-instantiations-without-? warning.  At first, I thought this might be specific to `c_ptr`, which is admittedly a fairly special type., though it may be specific to c_ptr, which is a fairly special type.  Yet, replacing it with an equivalent user record, I got the same behavior:

```chapel
use CTypes;

record MyCPtr {
  type t;
}

record foo {
    var x;
}

record bar {
  var buff: MyCPtr(foo);  // MyCPtr(foo(?)) doesn't help, but MyCPtr(foo, ?) does even though MyCPtr is a 1-arg generic
}
```

Tagging @mppf for his thoughts on this when he gets back as the author of #21410

**Comment by bradcray** [comment] 2023-04-01 01:03
Independent of the previous comment, I was curious whether we could turn the 1.29 internal error or 1.30 warning requesting `?`'s into a more specific error for `c_ptr` types, requiring that the argument be concrete rather than generic.  This was fairly easy to do, and I prototyped it in #22034, though for me it's a good instance of the larger question "Do we really want `type` arguments to accept generic types?  (at least, by default?)"

**Comment by mppf** [comment] 2023-04-14 15:16
Replying to the example in https://github.com/chapel-lang/chapel/issues/22011#issuecomment-1492765079 --

> That makes me think that something may be wrong with our partial-instantiations-without-? warning.

I agree -- at the very least I was not aware it would fire in such a case. However, I'd lean towards continuing to have a warning for `MyCPtr(foo)` in this case -- just one with different wording. Since `foo` is generic, `MyCPtr(foo)` is a generic type. It's not a partial instantiation, but I think it could be surprising for similar reasons.

> `MyCPtr(foo(?))` doesn't help, but `MyCPtr(foo, ?)` does even though MyCPtr is a 1-arg generic

I would expect that the way to resolve the potential confusion here would be to write `MyCPtr(foo(?))`. I could look at adjusting the warning implementation to have that case not warn, but at the moment I am leaning towards waiting to see if we can get more clarity on whether or not we will require the `(?)` in more cases (or something along those lines that addresses the issue broadly).

> Independent of the previous comment, I was curious whether we could turn the 1.29 internal error or 1.30 warning requesting `?`'s into a more specific error for `c_ptr` types, requiring that the argument be concrete rather than generic

The main thing that I am aware of that this prevents (when interpreted strictly) is using the generic type in a type argument context:

``` chapel
use CTypes;

record GR {
  type t;
}

proc foo(arg: c_ptr(GR)) {
  writeln(arg.type:string);
}

var x: GR(int);
foo(c_ptrTo(x));
```

Here `arg: c_ptr(GR)` is a generic type. Of course, the current behavior can be written alternatively with a `where` clause.

However, we don't get the "partial instantiation without ?" warning with the above program today. I think that's due to the way that the compiler is normalizing the function arguments into a `where` clause. However I would expect that the dyno resolver will treat it differently.

I'd lean towards waiting on your PR (which I know is a draft for discussion) and continuing to answer the question along the lines of "Do we want to require `GR(?)` generally when referring to the generic type?" since such a change would also address the potential for confusion here (you would write `MyCPtr(foo(?))`). However, I would be fine merging it if we feel that a stopgap is needed to improve warnings/errors, provided we aren't viewing it as a long-term policy choice about `c_ptr`.

**Comment by jabraham17** [comment] 2024-02-03 00:34
I think we can close this. On main today, the original issue looks as follows.

```chapel
use CTypes;
record foo { var x; }
record bar { var buff: c_ptr(foo); }
```

When compiled, this gives a warning and a error.

```
test.chpl:8: warning: partial instantiation without '?' argument
test.chpl:8: note: opt in to partial instantiation explicitly with a trailing '?' argument
test.chpl:8: note: or, add arguments to instantiate the following fields in generic type 'c_ptr(foo)':
$CHPL_HOME/modules/standard/CTypes.chpl:126: note:   generic type field 'eltType'
test.chpl:8: error: could not determine the concrete type for the generic return type 'c_ptr(foo)'
```

If you resolve the warning and add an explicit `?` like follows, the code compiles as expected.

```
use CTypes;
record foo { var x; }
record bar { var buff: c_ptr(foo(?)); }
```

This is also true for the future `test/types/records/generic/issue-22011.chpl`. This compiles with an error and a warning about `(?)`. If I add `(?)` like the warning says to `generic_record` on line 10, this compiles without error.

**Comment by bradcray** [comment] 2024-02-05 17:50
Sounds good to me, thanks @jabraham17!  If you haven't already, would you be up for creating a PR that retires `issue-22011.chpl`, locking the error messages into its .good file, probably also adding a clone of it with the `?`'s to lock in the working behavior?

**Closed** 2024-02-06 22:33 UTC
Labels: type: Bug, area: Compiler, user issue

**Comment by bradcray** [comment] 2024-02-07 00:42
Thanks for reporting this, @kwaters4!
