### ISSUE TITLE
definition of shadowing is inconsistent between variables and functions

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19167] opened 2022-02-03 12:27 UTC
I have been looking at [this code](https://github.com/chapel-lang/chapel/blob/6702b173cfc8fffe10185e7f145c2c2e2ba55b33/compiler/resolution/functionResolution.cpp#L1825-L1826) in function resolution as part of porting it over to the new resolver. I have been scratching my head a bit. I am pretty sure that the current behavior is not reasonable. But, that might be a bug in function resolution or maybe it is a sign that we need to adjust the language design.

One thing to note about the current implementation is that it's pretty complicated and it does a traversal of all scopes visible from the call (including use/import), twice, in order to decide if one candidate is more specific than another candidate. I am worried that this contributes to performance problems. It would be much less worrisome if the consideration only needed to go up through the parent scopes (not counting use/import).

However a larger issue is that the behavior seems unnecessarily inconsistent between variables and functions. More details about that are in the next section.
   
### Program to Explore the Current Behavior

Here is a program to explore the current behavior.

To summarize the current situation:
 * with `UseA_UseUseB` in the program below:
   * variables are resolved according to an idea of distance in terms of use/import statements - e.g. A.x is available with fewer hops through use statements than B.x, so A.x is shadowing B.x
   * for function disambiguation, the fact that A.f is available through fewer hops does not seem to matter, and it is ambiguous

 * with `CUseA_ImportA`
   * for variables, `import A` does not impact what could be defining `x`, so it has no effect on what `x` could refer to
   * for function disambiguation, `import A` is considered the same as `use A` and so is considered creating a path to `A.f` at the same number of hops as the path to `C.f`.
   * I am pretty sure that private uses, uses with renaming, or `use only` with an unrelated name will have the same problem for functions as the import here

``` chapel
module A {
  proc f() { writeln("A.f"); }
  var x = "A";
}
module B {
  proc f() { writeln("B.f"); }
  var x = "B";
}

module CUseA {
  public use A;
  proc f() { writeln("C.f"); }
  var x = "C";
}

module UseA_UseB {
  public use A;
  public use B;
}

module UseB {
  public use B;
}

module UseA_UseUseB {
  public use A;
  public use UseB;
}

module CUseA_UseA {
  public use CUseA;
  public use A;
}

module CUseA_ImportA {
  public use CUseA;
  import A;
}

module Program {
//use UseA_UseB;     // -> ambiguity between A.f and B.f
                     // -> x is multiply defined

//use UseA_UseUseB;  // -> ambiguity between A.f and B.f
                     // -> x refers to A.x

//use CUseA;         // -> f refers to C.f
                     // -> x refers to C.x

//use CUseA_UseA;    // -> ambiguity between A.f and C.f
                     // -> x is multiply defined
  
//use CUseA_ImportA; // -> ambiguity between A.f and C.f
                     // -> x refers to C.x
  proc main() {
    f();
    writeln(x);
  }
}
```

### History and Related Issues

* bde150a476e5c05cd0a8e8038221fd1ac8d6d2aa has some history of the isMoreVisible code for functions and it definitely predates `import` and probably predates `use only` and private uses.
* #14014 brings up a related question about module scoping
* #19160 is related because it asks if symbols brought in by `import` should be subject to shadowing at all
* #19219 asks if `use` statements should have two shadow scopes

### What does the spec say on the matter?

https://chapel-lang.org/docs/language/spec/procedures.html#determining-more-specific-functions

For functions X and Y, we have this rule about which is more specific (which is considered after things like formal argument types):

> * If X shadows Y, then X is more specific.
> * If Y shadows X, then Y is more specific.

However this section does not define *shadows* in any way.

https://chapel-lang.org/docs/language/spec/modules.html#conflicts

Describes shadowing in terms of a distance idea:

> Because symbols brought into scope by a use or import statement are placed at a scope enclosing where the statement appears, such symbols will be shadowed by other symbols with the same name defined in the scope with the statement. The symbols that are shadowed will only be accessible via [Qualified Naming of Module Symbols](https://chapel-lang.org/docs/language/spec/modules.html#explicit-naming).
> 
> Symbols defined by public use or import statements can impact the scope they are inserted into in different ways (see [Public and Private Use Statements](https://chapel-lang.org/docs/language/spec/modules.html#public-use) and [Re-exporting](https://chapel-lang.org/docs/language/spec/modules.html#reexporting) for more information on the public keyword). Symbols that are brought in by a public use for unqualified access are treated as at successive distances relative to how many public use statements were necessary to obtain them. For instance,
> 
> ...
> 
> Symbols brought in directly by a public import are treated as though defined at the scope with the public import for the purpose of determining conflicts (see [Re-exporting](https://chapel-lang.org/docs/language/spec/modules.html#reexporting)). This means that if the public use in module B of the previous example was instead replaced with a public import A.x, A’s x would conflict with C.x when resolving the main function’s body.

### What should we do about it?

I think that at the very least, the language should have one definition of *shadowing* that is used for both resolving variables and for resolving functions.

Here are some ideas:

A. Consider the behavior with variables today to be correct and formalize it by describing a *distance* in number of hops. A symbol shadows another symbol if, in a given scope, it has a smaller distance. Have the new compiler code literally compute this distance and compare distances.
  * the module brought in by `use` and any symbol brought in by `import` adds 1 to the number of hops
  * the contents of a module brought in by a `use` adds 2 to the number of hops
  * an enclosing scope (e.g. going outside of `{ }`) adds 3 to the number of hops

B. Simplify the rules about number of hops:
  * If a symbol is defined at an inner scope, or if it is defined in a module but that module `use` / `import`s something defining that symbol, then we have shadowing within that module. This can continue to consider 3 scopes: things defined directly in the module; modules `use`d; and contents of modules brought in by `use`. This is the situation within `CUseA` in the example program.
  * However, something `use` / `import`ing that module views the symbols defined in it as completely flat. So if you wanted `use CUseA` to find `C.x` and `C.f` (and not find them ambiguous with `A.x` and `A.f`) you would have to adjust `CUseA` to not publicly export `A.x` and `A.f`.
  * This design is simpler to implement (because the `isMoreVisible` operation can reuse other scope resolution ideas) and it's probably easier for users to predict what will happen with their programs.
  
C. Do not consider `use` / `import` to create additional scopes.
  * This means that `CUseA` would become a multiply-defined symbol error. A user would need to use renaming or `import` to address it.
  * This approach is the simplest of all
  * This approach has the advantage that errors that would occur when a library module is used in the above approaches will instead be reported immediately when compiling the library.
  * It would make the example at the top of #14014 be an ambiguity error which was the original request in that issue
  * It would answer #19160 with "no" -- it would not be possible to shadow symbols brought in from an import.
  
C'. Do not consider `public use` or `public import` to create additional scopes, but private use/import can do so
  * Note that `public import` is already documented as not creating an additional scope.

**Comment by lydia-duncan** [comment] 2022-02-03 16:12
> * or function disambiguation, `import A` is considered the same as `use A` and so is considered creating a path to `A.f` at the same number of hops as the path to `C.f`.

That shouldn't be true.  `import A` should mean `A.f` can only be referred to in a qualified way.  Anything else is a bug and should be fixed.

But that's a side issue.  At a high level, the reason variable and function resolution is different is because functions don't necessarily conflict with each other unless they can be called in the same manner.  This means that you can write a function at one scope that takes one set of arguments and a function at a different scope with a different set of arguments, and be able to call both of them from a third scope, no matter their relative distances - where your `UseA_UseUseB` is a problem with the same set of arguments (or in this case lack of arguments), adjust one of them to take an int and the conflict goes away.  I think that's valuable behavior to preserve, but I agree that it's frustrating in the case where two functions have the same set of arguments and one could be considered to shadow the other.  I think it would be reasonable to adjust function resolution to consider it shadowing in that situation, and doing so would be more consistent for users.  But I want us to be careful not to discard overloads simply because we're only considering the function name when determining if shadowing can occur.

**Comment by mppf** [comment] 2022-02-03 16:17
> But I want us to be careful not to discard overloads simply because we're only considering the function name when determining if shadowing can occur.

We're talking about disambiguation, not finding candidates, so we're not discarding any overloads; just choosing among them. But anyway I'm not proposing here that we change where scoping/shadowing matters in function disambiguation -- only what the definition of shadowing is. (It is true one could argue that the definition of shadowing should ignore the argument types, but I'm not arguing for that).

**Comment by lydia-duncan** [comment] 2022-02-03 17:04
Okay, cool.  As long as that's clear in whatever documentation we adjust as a result, I'm okay with A or B, then.

**Comment by bradcray** [comment] 2022-02-04 02:15
In:

```chapel
  import A;
```

should this be a `public import`?  (otherwise it won't affect anything outside of this module I think?).  Should it be a `public import A.{f, x}'`?  Or is the main goal of that example to show that imports, by nature, don't inject symbols?

**Comment by skaller** [comment] 2022-02-04 05:36
So here is what I do in Felix. My solution is not completely good. First principle is that "most specialised" has a single coherent definition. There are no complex rules. The algorithm determines if a polymorphic type A is a subtype of a polymorphic type P, and, the reverse. The algorithm is a stock-standard unification algorithm supporting subtyping in which the two sides of the inequality being tested are kept separated. We are seeking a set of equation which fix the values of all the type variables in P, in terms of type variables in A, such that P, after substitution, is a supertype of A.

**Comment by mppf** [comment] 2022-02-04 12:38
@bradcray 

> In:
> 
> ```chapel
>   import A;
> ```
> 
> should this be a `public import`?  (otherwise it won't affect anything outside of this module I think?).  Should it be a `public import A.{f, x}'`?  Or is the main goal of that example to show that imports, by nature, don't inject symbols?

It does not matter for the example - the behavior is the same (and x vs f differ). The point of the example is to show that the logic in function disambiguation is ignoring the details of what kind of use/import and just traverses everything assuming it is a `public use` including all symbols. And that this is inconsistent with what we are doing in scope resolve for variables.

**Comment by mppf** [comment] 2022-02-04 12:48
@skaller - it is nice to know that at least one other language has the "shadow scope" idea. We do that today but have two shadow scopes for `use`.

>  If you have incoherent implicit conversions in your language, you have to fix them.

Can you say more about what you mean by "incoherent implicit conversions" here? Later you say:

> get rid of implicit conversions that are not subtyping relations.

Is this exactly the implicit conversions you were calling "incoherent"?

I don't think we'll be willing to remove all non-subtyping implicit conversions from the language, and in any case that would be a massive change and is definitely off-topic for this issue.

**Comment by skaller** [comment] 2022-02-04 13:56
Two shadow scopes? Interesting! 

So: removing some implicit conversions is a trivial change. It simply forces the user to write them explicitly. Since the compiler knows when one is used that will be removed it can simply tell the user to write one or their code will soon stop working. In fact, with some work, a tool can be written to automatically fix user code. So actually it is not a massive change although it is a breakage. I would argue breaking something is just fine, if it is needed to repair an even worse breakage.

So, there is a correspondence between implicit coercions and subtyping as explained in discourse post. Subtyping is used to select between candidates in overload resolution, to select the most specific function. I will note there are the usual subtyping rules but also we include a concrete type as a subtype of a type variable. One of these is called subsumption but i can never figure out which.

Subtyping relations are transitive.

Now, if you have say a coercion from real to int and a coercion from int to real and they're subtyping relations as well, then we can prove int is the same type as real. Note: I said *PROVE*.  And then, we have just proven the type system is unsound, which is equivalent to being able to prove every statement in a logic system, including both A and not A for every A. So we simply cannot allow this.

Well, the way it works in Felix and will also work in Chapel I guess, is that if you have an argument of type A and a parameter of type P, and they're not equal types, the *compiler* fixes the discrepancy by magically inserting a conversion. This conversion is implicit by definition: the compiler put it in there, not the user. So ALL subtyping relations imply the existence of an implicit coercion. [In our kinds of languages]

So now, can we have an implicit conversion anywhere else? Remember, implicit conversions are inserted by the compiler. Where else could it insert one?

The answer is NOWHERE. There is ONLY one way for the compiler to insert the coercion implicitly and that is on a function call or any context where you have a target and source type. For example, in assignment: same deal. The RHS has to be a subtype of the LHS. Initialisation: same deal.

You see? You can have an implicit coercion that isn't a subtype but it is certain to be entirely useless. It will never get inserted by the compiler, so you might as well take it out of the documentation.

So now, lets consider real and int are equivalent and show where both conversions can be inserted:
```
proc f (x:int, y:real) ... f (1.0, 2)
```

The problem is, with the specialisation algorithm, unless both int->real and real->int are subtypes, this call will fail. There's no match. And if they are both subtypes, your type system is unsound. You simply cannot allow this, and you really DO have no choice but to overload based on the standard algorithm which depends entirely on a strict subtyping rule which must be transitive.

Otherwise you're polluting your overload resolution with a heap of special cases and that NEVER works, because such special cases almost universally fail to be recursive. Eg if you have nested tuples.

The reason this comes up is that when you import modules you're importing function sets. Even if you put all the imports in a shadow scope, you are still merging function sets from multiple imports. The original issue is how to handle the conflicts which arise here and that is directly related to overload resolution (so it is not really off topic :-)

**Comment by mppf** [comment] 2022-02-04 14:51
@skaller - I will continue the conversation about subtyping and implicit conversions over on https://chapel.discourse.group/t/overload-resolution/10252 .

**Comment by mppf** [comment] 2022-02-07 17:07
I've opened #19198 to describe a related problem with `isMoreVisible`.

**Comment by mppf** [comment] 2022-02-08 17:51
Here is an even simpler program showing the inconsistency between scope resolution and function resolution:

``` chapel
module M {
  var X: int;
  proc f() { writeln("M.f"); }
}

module N {
  var X: real;
  proc f() { writeln("N.f"); }

  proc main() {
    use M;
    writeln(X);
    f();
  }
}
```

**Comment by mppf** [comment] 2022-02-08 17:55
I've created #19219 about whether or not `use` should have two shadow scopes (or one, or none).

**Comment by mppf** [comment] 2022-02-08 18:36
I think some of my previous comments might represent a misunderstanding of the current rules.

     

From https://github.com/chapel-lang/chapel/issues/11262#issuecomment-528644174 :

> The traditional definition has been more like: "use statements make symbols available as though they were in a scope just outside of the current lexical scope but closer in that its parent scope (and the module name that was used is in a scope just above that)."

So if I were to turn this in to a numeric distance, a regular enclosing scope would add 2, so that a use statement can create a distance between the symbols contained and the outer scope.

E.g.

``` chapel
module M {
  var x = ...;
}
module N {
  var y = ...;
  {
    // y is available here at distance 2
    use M; // x is available here at distance 1
    var z = ...; // z is available here at distance 0
  }
}
```

**Comment by lydia-duncan** [comment] 2022-02-08 18:53
I think that's a simplification.  A use can bring in an arbitrary number of scopes, depending on if the module being used itself contains public use statements.  I tend to think of scopes brought in by use and import statements as following a different dimension from the scopes defined with `{}`

**Comment by mppf** [comment] 2022-02-08 18:56
Right but the compiler has this `isMoreVisible` element where it needs to be able to answer the question about visibility in function disambiguation. How can it do that with the scopes and the use statement things being in a different dimension? Maybe I am missing something but it seems it has to linearize it somehow in order to say if one thing is more visible than another thing. I could imagine that `isMoreVisible` could return "Incomparable" in some cases and maybe that would be OK but AFAIK our current scope resolver cannot do such a thing.

**Comment by skaller** [comment] 2022-02-08 21:32
Hang on. If the rules are that complicated the compiler cannot figure it out in a simple way (meaning the algorithm is quite complex) then the rules are bad because the user has no hope of figuring it out. So perhaps the wrong question is being asked.

In my language, the rules for variables and functions are indeed different. It is an error to define the same non-function symbol in a scope. A function, on the other hand is identified by its name and domain type and duplicate definitions are allowed.

I use a single shadow scope, however there are two name maps, one for private use inside a module only, and one for public  use from outside the module. Explicit qualification looks only in the specified module. It does not look in shadow scopes or in parent scopes. Each name map has two kinds of entry, a non-function entry and a function entry (a name map is a hash table). Function entry in the lookup table contains a set of functions. When I import two modules, the functions of the same name are merged into a single set. I had to do an experiment to see what happens to variables. To my dismay its a not exactly what I might have expected:
```
class X { var x = 3; }
class Y { var x = 2; }
class Z { inherit X; inherit Y; }
open Z;
println$ x;
```
Output:
```
~/felix>flx xx
3
```
I don't know if this is random or it just takes the first definition, but it is a design fault either way I think. The problem is, you cannot ban the importation or use of two modules just because they happen to contain duplicate variables. But it should be an error to use one (not silently picking one of them). The problem is, how can the compiler represent this? If it cannot bug out on constructing the scope, it would need to put an entry for the duplicate symbol which if found, would generate a diagnostic .. the only other option is to not put either symbol in the scope. However that is also bad because then, a symbol from the parent scope might be found instead of being hidden.

I would note also you need to think about Interfaces. In Felix, a module and and Interface are the same thing, a module is simply a non-generic Interface (i.e. with no type parameters). I used to have them separate, but it was too hard to figure out the differences and impossible to maintain two sets of complicated lookup rules.

So when you're trying to figure out rules for modules .. don't forget you will have to do it for interfaces as well.

**Comment by mppf** [comment] 2022-02-08 21:56
In an off-issue discussion with @lydia-duncan I learned that one problem with Option B. is that it makes the rules for shadowing different within a module and when the module is `use`d. I think that's a reasonable criticism of it. For what it's worth, Option C. doesn't have that problem. Arguably, Option C. is just making `public use` behave more like `public import` (where we already have `public import` working like Option C per the description in the last paragraph in https://chapel-lang.org/docs/language/spec/modules.html#conflicts ).

Another thing we talked about is that the current rules could lead to "hijacking" in this scenario:

We start with Library which publicly uses Dependency:

``` chapel
// this is Library v1
module Library {
  public use Dependency;
}
```

Let's suppose that when `Library` is developed, `Dependency` looks like this:

``` chapel
// this is Dependency v1
module Dependency {
  // other stuff unrelated to example
}
```

And the next thing that happens is that `Dependency` is improved to look like this:

``` chapel
// this is Dependency v2
module Dependency {
  proc foo();
}
```

Then, somebody makes an `Application` that uses `Library` v1 and `Dependency` v2:

``` chapel
module Application {
  use Library;
  foo(); // intended to call Dependency.foo
}
```

Now, suppose that the author of `Library` doesn't realize that the new version of `Dependency` has a `foo` and they add on of their own:

``` chapel
// this is Library v2
module Library {
  public use Dependency;
  proc foo() { }
}
```

They might test `Library` v2 using `Dependency` v1 and not notice any problem and then publish it. But, a user goes to try to build `Application` with `Library` v2 and `Dependency` v2. Then their call to `foo` starts running `Library.foo` where they expected it to run `Dependency.foo`, and they are surprised and confused.

(Vs in both Option B and Option C there would be a compilation error).

**Comment by skaller** [comment] 2022-02-08 22:00
BTW: if the module rules are complicated (and they usually are in any language) thing the user is going to need a psychiatrist to cope with POI lookup, because that has to look in at least THREE distinct places: the original point of definition, the module in which the instantiated type is defined, and the point of instantiation .. all of which can involve modules and imports and stuff.

**Comment by mppf** [comment] 2022-02-10 13:31
I've edited https://github.com/chapel-lang/chapel/issues/19167#issuecomment-1033100674 a bit with some thoughts about how the "hijacking" scenario relates to semantic versioning and mason.

**Comment by bradcray** [comment] 2022-02-11 18:20
Returning late to this issue and jumping into Michael's simpler example in the middle:

```chapel
module M {
  var X: int;
  proc f() { writeln("M.f"); }
}

module N {
  var X: real;
  proc f() { writeln("N.f"); }

  proc main() {
    use M;
    writeln(X); // prints out 0 so refers to M.X
    f(); // ambiguity error
  }
}
```

I think the behavior of `X` here is appropriate and would be averse to changing it.  If fear of hijacking were to cause us to change it, I think that'd be an argument that the user should've written `import M;` rather than `use M;`.

I also think that `f()` should probably call `M.foo()` rather than reporting the ambiguity, in part to act more symmetrically to `X` above, and also because in this example:

```chapel
proc foo() {
  writeln("In outer foo");
}

{
  proc foo() {
    writeln("In inner foo");
  }

  foo();
}
```

we get a call to inner `foo()` rather than outer `foo()` (and given the shadow scope interpretation of `use`—which still matches my intuition—this seems similar to Michael's example.

I think the trick here is how far that shadowing goes.  For example, if inner foo() had been declared to require arguments as in `proc foo(x: int)`, would the call `foo()` invoke the outer routine, or would the outer routine be shadowed by inner foo()?  And if "shadows" is the right answer, does this make it harder to add new overloads to a given function when you don't have access to the source code of the module that defined the original versions of the routine?

**Comment by mppf** [comment] 2022-02-11 20:23
> I think the trick here is how far that shadowing goes. For example, if inner foo() had been declared to require arguments as in proc foo(x: int), would the call foo() invoke the outer routine, or would the outer routine be shadowed by inner foo()? And if "shadows" is the right answer, does this make it harder to add new overloads to a given function when you don't have access to the source code of the module that defined the original versions of the routine?

A next step for me is to check to see if we have cases in the test system where more aggressive shadowing here would be a problem for non-method non-operator cases.

**Comment by bradcray** [comment] 2022-02-11 20:24
Catching up a bit more, I am generally in favor of something along the lines of approach B.  Specifically, when I think about what a module logically does in Chapel, I think of it as making a set of symbols available to another piece of code via `use` or `import` statements, where those symbols may be defined by the module itself, or they may have the appearance of being defined by the module as a result of `public use` or `public import` statements that it contains.  Generally speaking, once I'm outside the module (and maybe even when I'm within it?), I don't really want to have to worry about where those symbols came from or how they were implemented, simply that they're available or not.  And from a compilation time/complexity standpoint, I'd like the compiler to see something more like a "flat bill of sale" for what a given module provides rather than for the module to expose all of the structure that led to its definition.  Put another way, I think of a module as defining all the stuff that its documentation says it does (noting that chpldoc doesn't help with `public use` or `public import` today, but I think we all agree there should be a better story there) where ideally nobody would be the wiser how those symbols were implemented, and those implementations could change without changing behavior (e.g., pushing symbols into the module into a helper module that's publicly used/imported or vice-versa).

Where I might pause with option B (if I'm understanding it correctly) is with a concern that I think Lydia raised about having the resolution of a call `foo()` happen differently within a module vs. outside of it.  But as I understand it, issue #19219 may propose a solution to that (?).  Going to check that out now.

**Comment by mppf** [comment] 2022-02-11 20:26
Right, if `public use` does not create a shadow scope, the inconsistency goes away for option B.

**Comment by bradcray** [comment] 2022-02-11 20:38
Ah, I'd missed option C' earlier.  Yeah, I think option C' makes the most sense to me:  It keeps `private use` behaving as it does today; it makes the behavior for a call within a module and outside it (assuming all relevant symbols are equally visible in both cases) more consistent; it makes `public use` more interchangeable with defining a symbol directly within a module such that code can be refactored into or out of helper modules without changing the code's meaning; and it seems to support the "bill of sale" model

An example that came up in talking with Michael seems worth capturing here.  Say I had:

```chapel
module M {
  proc foo() { ... }
}
module N {
  public use M;
  proc foo() { ... }
  // foo();  // maybe I call foo here?
}
module O {
  use N;
  // foo();  // and/or maybe I call foo here?
}
```

Because we don't resolve overloads until a call is made—and because we generally can't very easily determine whether or not two functions do have overlapping signatures or not because of type inference, generics, and the like—while the code above effectively defines two `foo()` overloads at the same scope according to the rules of C', this would not be caught until someone tried to call `foo()`.  And that's similar to what would happen today if the two `foo()` procedures were defined at the identical scope (no error until the call was made).  Put another way, the "bill of sale" for N would be "I define two functions named foo() that take no arguments" which makes that routine useless, but consistent with what would happen if they were both defined within module N outright.

We discussed whether the compiler could try to consider certain function signatures to shadow others, but apart from some easy cases like 0-argument routines above, this felt pretty intractable to do in any way that felt like it wasn't a band-aid solution, covering some cases but letting others through.

**Comment by skaller** [comment] 2022-02-12 01:39
@bradcray wrote:

>And if "shadows" is the right answer, does this make it harder to add new overloads to a given function when you don't have access to the source code of the module that defined the original versions of the routine?

Yes it does. When I face this issue in Felix, knowing in C++ if a name shadows an outer name, that's the end: if overload resolution in the inner scope fails there is no recourse to the outer scope. [In C++ you can put a `using` directive to pull extra overloads in, originally designed to pull in overloads from  a base class] 

It is important to understand the *algebraic* reason for this: in C++ a function set is identified by a name. In Felix, I changed the notion of identity: a function is Felix is identified by its name *and* the type of the domain. So if you are looking for a function with a given name, and arguments of some type T, then a function in the inner scope with a type X, where T is not a subtype of X, does *not* hide functions in the outer scope.

I'm not saying Chapel should do it my way or the C++ way or any other way, I'm saying that you have to step back and ask the right question: what identifies a function? Do you identify individual functions, or do you identify sets of functions?

The idea of a shadow scope is that you have *the usual* lookup rules for looking for a symbol by name in the current scope and if you fail, you go to the parent scope, etc all the way to the global scope. So with a shadow scope you would use *the same* rules, but just add an extra scope into the environment. The reason of course is simplicity: you can *decouple* the problem into the already implemented parent lookup rules and construction of the shadow scope.

So in Felix, I first search for an identifier, and find either a non-function or function set. If i'm looking for a function, the lookup routine must also accept the argument type being sought, not just the name. Which means there are two distinct lookup routines one for functions and one for everything else. It gets complicated because sometimes you don't know, and sometimes in Felix, a type can be a function, for example the name of a `struct` is also the name of its constructor, so sometimes, looking for a function, you find a non-function but its OK.

In fact in Felix lookup system, the shadow scope does not contain symbols, it contains the directives (use, import etc), which modify the lookup. So my system actually breaks the principle I cited above, so to re-establish it I have to encode the interpretation of lookup in spaces defined by directives, to work *as if* I had actually eagerly built the environment, instead of lazily waiting until i need to (performance is part of the reason but not the only one).

If you identify a function only by it's identifier name, then, an inner function of that name hides all functions in all enclosing scopes, including shadow scopes. This is the case in C++. It is not in Felix precisely because of the effect @bradcray noted above. The lookup algorithm should be *derived* from your concept of identity and environment.

**Comment by skaller** [comment] 2022-02-12 01:55
@bradcray wrote
> We discussed whether the compiler could try to consider certain function signatures to shadow others, but apart from some easy cases like 0-argument routines above, this felt pretty intractable to do in any way that felt like it wasn't a band-aid solution, covering some cases but letting others through.

I don't follow. The way this is done is absolutely stock standard using a well known algorithm, namely (a modification of) unification. Generics do not cause a problem, nor do implicit conversions provided they're transitive. Furthermore you have to use precisely this algorithm to resolve overloads anyhow right now, and, you will have to use it again in a different way to resolve overloads mediated by `Interfaces`. Unification is a core algorithm used in almost every compiler one way or another. There's nothing band-aid here.

Whether or not a function domain type hides another or not is trivial to compute and is not an issue at all. The actual issue is what to do when you get either an ambiguity, or, no matches at all. Felix continues if there are no matches. C++ will not continue, unless there is no function with the given name, in which case unification is not done in the first place.

**Comment by mppf** [comment] 2022-02-18 13:54
From earlier comments:

> > > I think the trick here is how far that shadowing goes. For example, if inner foo() had been declared to require arguments as in proc foo(x: int), would the call foo() invoke the outer routine, or would the outer routine be shadowed by inner foo()? And if "shadows" is the right answer, does this make it harder to add new overloads to a given function when you don't have access to the source code of the module that defined the original versions of the routine?

> > We discussed whether the compiler could try to consider certain function signatures to shadow others, but apart from some easy cases like 0-argument routines above, this felt pretty intractable to do in any way that felt like it wasn't a band-aid solution, covering some cases but letting others through.

> The lookup algorithm should be derived from your concept of identity and environment.

It is interesting to consider how shadowing is related to overriding for child classes. There, we have the design that, basically, you can think of the combination of method name + argument names + types as the thing that determines what a method is, in terms of overriding. If we were to make the language design have overloads shadow more aggressively, would we would need to also change what we consider to be an override? In particular, if you are overidding something that has multiple overloads, you would have to override all of the overloads. In practice this is easy to do simply by copying the signatures from the parent class(es). But it is not required today.

Current checking is described here: https://chapel-lang.org/docs/language/spec/classes.html#overriding-base-class-methods

Here is an example:

``` chapel
class Parent {
  proc f(arg: int)    { writeln("Parent f(arg: int)"); }
  proc f(arg: string) { writeln("Parent f(arg: string)"); }
}

class Child : Parent {
  override proc f(arg: int)    { writeln("Child f(arg: int)"); }
}

var x: owned Parent = new owned Child();

x.f(1);     // Child f(arg: int)
x.f("hi");  // Parent f(arg: string)
```

In this case I think it would actually improve the clarity of the situation to require that the author of Child also write `override proc f(arg: string)`. Especially since, when implicit conversions are involved, it may not be so obvious as in this example which `f` overload will be called.

**Comment by mppf** [comment] 2022-02-20 14:12
I have been investigating option C': Do not consider public use or public import to create additional scopes, but private use/import can do so.

This design has two implications that were not obvious to me at the start.

One implication is that, if there is both a `public use` and a `private use` defining the same symbol within a module, mentions of that symbol within that module will refer to the `public use`.

E.g.

``` chapel
module M1 { var x: int; }
module M2 { var x: int; }
module Program {
  public use M1;
  private use M2;
  x; // this is M1.x because the public use did not introduce a shadow scope
     // but the private use did
}
```

I think that this is defensible on the argument that it makes the behavior of the code in the module better match what happens when you `use` it, but it is a bit odd.

The second implication is that, without adjustment, it's no longer possible to create a module that one can `use` in order to shadow a symbol defined in the automatically-used modules from the standard library. For example:

``` chapel
module ReplaceE { param e = 10; }
module Program {
  // use StandardLibrary; is effectively here but implicit
  use ReplaceE;
  e; // now ambiguous, because ReplaceE.e and StandardLibrary.e are
     // both in the same shadow scope
}
```

(But this pattern would work if it were `public use ReplaceE`).

I think this pattern is something that we probably want to support (e.g. if we want to have a module you can `use` to change what `+` does on numeric types, we would need it). I think that we could use the simple solution of placing that implicit "use StandardLibrary" in its own shadow scope just outside of the regular shadow scope.

**Comment by bradcray** [comment] 2022-02-21 17:44
> I think that this is defensible on the argument that it makes the behavior of the code in the module better match what happens when you use it, but it is a bit odd.

I agree that this is defensible, but does it generate a new opportunity for hijacking?  Say you wrote your code intending to refer to `M2.x` and at the time `M1.x` didn't exist, but is later added.  Even if so, I'm also still OK with saying "If you want to avoid hijacking, use `import` rather than `use`.  But I'm also wanting to make sure we're not just trading one source of confusion for another.

All that said, I still like the new interpretation of `public use` because of the fact that it supports the ability to refactor code from a scope into a module or vice-versa without changing its visibility, which seems like a major motivation for `public use` (i.e., it was more convenient for me to organize my code in another way, but I'd like it to behave the same).

> The second implication is that, without adjustment, it's no longer possible to create a module that one can use in order to shadow a symbol defined in the automatically-used modules from the standard library.

This seems acceptable to me since there is actually an ambiguity (i.e., why should `ReplaceE` necessarily win?  In this case, the name suggests it's what's desired, but maybe in another case, it's not, and would cause confusion?  Or would be a case of a module hijacking something important without the user realizing?).  Is there reason to believe that the user variable ought to win?

I agree we'll want a way to override such symbols, but I continue to imagine doing that through some way of opting out of auto-used modules/symbols (altogether, or maybe on a case-by-case basis).  I'm also cautiously optimistic that as we continue to reduce the sizes of auto-used modules (like Math, ChapelEnv, etc.) this will be less of an issue, though your point about overriding built-in operators is well-taken—though also something that probably shouldn't be done lightly.

I was going to say something about `import` helping here, but it seems that's probably not the case since the auto-used modules aren't imported...  That said, somehow `import ReplaceE.e;` feels like it ought to "win" over something obtained through a `use` without being named.

Of course, fully qualifying `e` at the use site would be a way to break the ambiguity while also making the code's intent clearer.

Maybe turning the question around:  Can we rationalize why it's a good thing for the user module to "win" today?  (given that the user module may not be a user module but some package module that they know nothing about which could be malicious).  It seems to me that this ambiguity is making things better (?).

**Comment by lydia-duncan** [comment] 2022-02-22 19:48
> In this case I think it would actually improve the clarity of the situation to require that the author of Child also write `override proc f(arg: string)`. Especially since, when implicit conversions are involved, it may not be so obvious as in this example which `f` overload will be called.

Is there precedent for this?  My initial reaction is that sounds like a pain for implementers of Child classes.

> Taking a completely different tack, what if we had two different record types that both wanted to define a method? If we were to consider defining anything named `f` to shadow all other things named `f`, we wouldn't be able to have methods with the same name on different record types.

That seems pretty obviously wrong to me.

> One implication is that, if there is both a `public use` and a `private use` defining the same symbol within a module, mentions of that symbol within that module will refer to the `public use`.
> 
> E.g.
> 
> ```chapel
> module M1 { var x: int; }
> module M2 { var x: int; }
> module Program {
>   public use M1;
>   private use M2;
>   x; // this is M1.x because the public use did not introduce a shadow scope
>      // but the private use did
> }
> ```
> 
> I think that this is defensible on the argument that it makes the behavior of the code in the module better match what happens when you `use` it, but it is a bit odd.

This seems pretty subtle to me.  Suddenly if you decide to make a use public that was private before, you may find you have conflicts that weren't present before.  Which is very relevant because the default use is private - a user could very easily write `use Bar` and interact with it in their code without issue but then realize "oops, I meant for those symbols to be available outside my module as well" and suddenly their program breaks.

**Comment by mppf** [comment] 2022-02-23 22:59
I agree it is subtle but I'm not sure what to do about it. It is something we already have today (at least in the behavior in the spec) for import. Also I think it is less bad than some of the alternative designs.

I suppose we could make this specific case of `public use` symbol shadowing a `private use` one an ambiguity (even though it would not be a general thing) but I'm not sure that makes the system more understandable.

**Comment by mppf** [comment] 2022-02-24 15:40
Continuing a comment from here -- https://github.com/chapel-lang/chapel/issues/19167#issuecomment-1047110744

> I agree we'll want a way to override such symbols, but I continue to imagine doing that through some way of opting out of auto-used modules/symbols (altogether, or maybe on a case-by-case basis). I'm also cautiously optimistic that as we continue to reduce the sizes of auto-used modules (like Math, ChapelEnv, etc.) this will be less of an issue, though your point about overriding built-in operators is well-taken—though also something that probably shouldn't be done lightly.

Well, today we cannot do that at all, because the `use ChapelStandard` is implicit. I suppose though, we could allow people to write `import ChapelStandard` or `use ChapelStandard except e` etc and then have the compiler see that and leave out the implicit one.

**Comment by mppf** [comment] 2022-02-25 15:22
I've made
 * #19312

To spin-off the discussion about shadowing an automatically used symbol (like Math.e) that started here: https://github.com/chapel-lang/chapel/issues/19167#issuecomment-1046246622

**Comment by mppf** [comment] 2022-02-25 15:31
I've made

 * #19313

To spin-off the idea described here https://github.com/chapel-lang/chapel/issues/19167#issuecomment-1049986810

**Comment by bradcray** [comment] 2022-05-11 23:52
@mppf: I'm looking through issues associated with https://github.com/chapel-lang/chapel/pull/19306 to see what is open and what is closed.  What needs to happen in order to resolve this issue currently?

**Closed** 2022-05-12 13:25 UTC
Labels: type: Design, area: Language
