### ISSUE TITLE
BUILD: 1.25.0: make clobber errors

### ISSUE THREAD

**Issue by tonycurtis** [chapel-lang/chapel#18455] opened 2021-09-24 15:56 UTC
### Summary of Problem

```
$ make clobber

...

cd qthread && make clobber
/bin/sh: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/llvm/install/linux64-aarch64-gnu/bin/clang: No such file or directory
/bin/sh: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/llvm/install/linux64-aarch64-gnu/bin/clang++: No such file or directory
/bin/sh: line 0: test: -lt: unary operator expected
/bin/sh: line 0: test: too many arguments
/bin/sh: line 0: test: -lt: unary operator expected
/bin/sh: line 0: test: -lt: unary operator expected

...

cd tools/mason && make clobber

Removing Mason...
rm -f /lustre/home/arcurtis/chapel/chapel-1.25.0/bin/linux64-aarch64/mason
cd tools/protoc-gen-chpl && make clobber
/bin/sh: line 0: cd: tools/protoc-gen-chpl: No such file or directory
make: *** [Makefile:196: clobber] Error 1
```

### Steps to Reproduce

**Compile command:**

`make clobber`

**Execution command:**
N/A

### Configuration Information

- Output of `chpl --version`:

```
chpl version 1.25.0
  built with LLVM version 11.0.1
Copyright 2020-2021 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: aarch64
CHPL_TARGET_CPU: unknown
CHPL_LOCALE_MODEL: numa +
CHPL_COMM: gasnet +
  CHPL_COMM_SUBSTRATE: ibv +
  CHPL_GASNET_SEGMENT: fast +
CHPL_TASKS: qthreads
CHPL_LAUNCHER: gasnetrun_ibv +
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_RE2: none
CHPL_LLVM: bundled +
CHPL_AUX_FILESYS: lustre +
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:

```
$ gcc --version
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by bradcray** [comment] 2021-09-24 18:29
Thanks for filing this @tonycurtis !  (I'm assuming that this is not holding you up in any way, but please give a shout if I'm incorrect in that).

**Comment by tonycurtis** [comment] 2021-09-24 18:30
> On Sep 24, 2021, at 2:29 PM, Brad Chamberlain ***@***.***> wrote:
> 
> 
> Thanks for filing this @tonycurtis <https://github.com/tonycurtis> ! (I'm assuming that this is not holding you up in any way, but please give a shout if I'm incorrect in that).
> 

No, just testing…

**Comment by bradcray** [comment] 2021-09-24 18:37
For the team, `CHPL_LLVM=bundled` seems to be the root of the problem here.  Or, at least, starting from my default environment, setting that, and doing `make clobber` reproduced the issue for me.

**Comment by bradcray** [comment] 2021-09-24 19:22
@mppf: I believe that this behavior is because in these lines:

```
DEF_C_VER := $(shell echo __STDC_VERSION__ | $(CC) -E -x c - | sed -e '/^\#/d' -e 's/L$$//' -e 's/__STDC_VERSION__/0/')
DEF_CXX_VER := $(shell echo __cplusplus | $(CXX) -E -x c++ - | sed -e '/^\#/d' -e 's/L$$//' -e 's/__cplusplus/0/')
```

`CC` and `CXX` are referring to the bundled versions of clang/clang++ which have already been deleted due to the clobber.  Based on other CC/CXX plumbing that you've done, do you have any thoughts about the best way to handle this?  Part of me is tempted to just do something like make these macros no-op if `test -x $(CC)` fails, but maybe there'd be something smarter to do upstream where CC/CXX themselves are defined?  Or to even move this logic out of the Makefiles and into the Python scripts?

**Comment by mppf** [comment] 2021-09-24 19:46
Yes, I think a quick fix would be to adjust these to no-op if the command fails. However in fact I would advocate for moving this logic into the Python scripts.

**Closed** 2021-10-12 15:23 UTC
