### ISSUE TITLE
Erroneous _unknown_chpl type with the LLVM backend

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#24307] opened 2024-02-01 11:18 UTC
### Summary of Problem

LLVM backend fails to compile the code below, throwing a "Could not find C type for _unknown_chpl" error. I think the code is legal, and the C backend does not have this issue.

@bradcray found out that the error is related to `chpl_external_array`.

Note that if you comment out the `var a : chpl_external_array;` line in the code below, the error disappears.

A workaround would be highly appreciated :smile: 

### Steps to Reproduce

**Source Code:**

Bug.chpl:
```chapel
use CTypes;

require "Bug.h";

extern record Foo {
  var a : chpl_external_array;
}

record Bar {
  var b : c_ptr(Foo);
}

proc main() {
  const x = new Bar(nil);
}
```

Bug.h:
```c
#pragma once

#include "chpl-external-array.h"

typedef struct Foo {
    chpl_external_array a;
} Foo;
```

**Compile command:**

`chpl Bug.chpl`

### Configuration Information

- Output of `chpl --version`: chpl version 1.34.0 pre-release
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: none *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none *
CHPL_TIMERS: generic
CHPL_UNWIND: system *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: system *
CHPL_HWLOC: bundled
CHPL_RE2: bundled *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: LLVM 16.0.6 (but the issue also occurs for LLVM 15)

**Comment by twesterhout** [comment] 2024-02-01 11:22
Another note, it seems that the extra indirection is necessary to trigger the error, i.e., this works fine:
```chapel
extern record Foo {
  var a : chpl_external_array;
}

proc main() {
  const x = nil:c_ptr(Foo);
}
```

**Comment by dlongnecke-cray** [comment] 2024-02-01 22:43
When are concrete aggregates actually resolved in the legacy compiler? I'm trying to trigger a breakpoint but to no avail.

FWIW right now my guess is that this has to do with `dtExternalArray` being installed as a "wellknown" type. I think we don't sanitize those with the same level of care that we do user types - we take them verbatim, which is why the fields with type `c_ptr(void)` are slipping through as "unknown". The expression `c_ptr(void)` can't be known a-priori, we actually have to go resolve the `CPtr` module so we can construct it.

Options:

- If we have a builtin, compiler-only we can use to represent `c_void(ptr)` a-priori, then we can continue to assume `chpl_external_array` is a always-resolved type
- If there's a mechanism to force resolve/sanitize wellknown types, I could try that
- I could write some new code to force resolve the fields of `chpl_external_array`

**Comment by dlongnecke-cray** [comment] 2024-02-01 23:01
For right now I'm opting to try and force-resolve the fields of `dtExternalArray` at the start of `resolve()`.

**Comment by bradcray** [comment] 2024-02-01 23:15
Ohhhh... Is the theory that we don't resolve that type if there are only mentions of it in `extern` declarations, not in Chapel code itself?  So my attempt at reproducing got through because I actually declared variables of those types?  (although...  I've gotta think Tom's did too?  Although maybe not in code that was resolved...?)  OK, I think that's a good theory, thanks David!

**Comment by dlongnecke-cray** [comment] 2024-02-01 23:24
Right, I think if a type is "wellknown" we just don't resolve its body, because it's supposed to be "trusted". This was fine for `chpl_external_array` when we used `c_void_ptr` because that type was also a special "wellknown" type. So since we never go beyond scope-resolving the body of `chpl_external_array` the `c_ptr(void)` type just remains typed as `unknown_`.

We'll see if this theory pans out in a few 😄.

**Comment by lydia-duncan** [comment] 2024-02-01 23:35
I can't remember why we made `chpl_external_array` well known.  Was it because we needed to generate referenced to it in exported functions?  If we can get away with not doing that for `c_ptr`, it seems like we could maybe get away with it for `chpl_external_array`

**Comment by dlongnecke-cray** [comment] 2024-02-02 02:41
Yeah, it seems like we made it well known because we use it to adjust intents for wrapper functions. At this point, I'm thinking that it's more to do with the nature of it being marked `extern` and not having any mentions of it (and thus no type constructors for it) in module code, rather than it being well known. This is because `chpl_opaque_array` doesn't have this problem. In my PR I went ahead and noted that as future work.

**Comment by twesterhout** [comment] 2024-02-02 10:33
Thanks for working on this @dlongnecke-cray! The discussion goes a bit beyond my current level of understanding of Chapel's codebase, so I can't contribute here :smile: But if at some point you need me to test something on my side, let me know.

**Comment by dlongnecke-cray** [comment] 2024-02-02 21:39
No worries @twesterhout. I share what I'm thinking just so the team can follow along in case I get stuck, or share ideas. You've already done more than enough just by filing such a helpful reproducer.

**Closed** 2024-02-02 21:57 UTC
Labels: type: Bug, user issue

**Comment by bradcray** [comment] 2024-02-02 22:11
Thanks for the quick fix here David, and for reporting it Tom!
