### ISSUE TITLE
Support assigning lists to iterators

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#14497] opened 2019-11-21 15:50 UTC
Assigning arrays to iterators (similar to list comprehensions in python) is a very useful pattern:

```chpl
var A = for i in 1..10 do i;
var B = [i in 1..5] i**2;
var C = for char in 'abc' do char.toUpper();

writeln(A);
// 1 2 3 4 5 6 7 8 9 10
writeln(B);
// 1 4 9 16 25
writeln(C);
// A B C
```

Unfortunately, lists do not support this pattern:

```chpl
use List;

var l: list(int) = for i in 1..10 do i;
```

```bash
> chpl listArray.chpl
listArray.chpl:3: error: unresolved call 'list(int(64),false).init=(iterator)'
$CHPL_HOME/modules/standard/List.chpl:235: note: this candidate did not match: list.init=(other: list(this.type .eltType, ?p))
listArray.chpl:3: note: because call actual argument #1 with type iterator
$CHPL_HOME/modules/standard/List.chpl:235: note: is passed to formal 'other: list'
$CHPL_HOME/modules/standard/List.chpl:249: note: candidates are: list.init=(other: [?d] this.type .eltType)
$CHPL_HOME/modules/standard/List.chpl:268: note:                 list.init=(other: range(this.type .eltType, ?b, ?d))
note: and 1 other candidates, use --print-all-candidates to see them
```

(this is after the fix in https://github.com/chapel-lang/chapel/issues/14363)

It would be nice for lists to support this pattern as well.

**Comment by ben-albrecht** [comment] 2019-11-21 15:53
https://github.com/chapel-lang/chapel/issues/6330 and https://github.com/chapel-lang/chapel/issues/14364 are related in that they discuss options to making iterator assignment less of a special case in the compiler code, e.g. perhaps some syntax should be required to determine if the LHS will be an iterator object, or unrolled into a list, array, etc.

**Comment by arezaii** [comment] 2021-08-13 19:34
This appears to be implemented as:
```chpl
use List;

var l: list(int) = for i in 1..10 do i;
writeln(l);
```
outputs:
```
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

Can we close it?

**Comment by bradcray** [comment] 2021-08-13 19:49
Looks like @mppf added this in https://github.com/chapel-lang/chapel/pull/16708 .  And since @ben-albrecht is on leave, I think "yes."  I'm also noticing that https://github.com/chapel-lang/chapel/issues/16166 was a duplicate of this issue (whoops).

**Closed by bradcray** 2021-08-13 19:49 UTC
Labels: area: Compiler, area: Libraries / Modules, type: Feature Request, area: Language
