### ISSUE TITLE
Overriding methods with variadic arguments

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#6928] opened 2017-08-03 14:48 UTC
### Summary of Problem
Overrides of methods with variadic arguments are never called. Parent's method is invoked, instead.

### Steps to Reproduce

**Source Code:**

```chapel
class Parent {
  proc foo(elts: int ... ?nElts) {
    writeln("Parent");
    for e in elts do writeln(e);
  }
}

class Child: Parent {
  proc foo(elts: int ... ?nElts) {
    writeln("Child");
    for e in elts do writeln(e);
  }
}

var p: Parent;
p = new Child();
p.foo(1); // prints out "Parent"

```

**Compile command:**
```
chpl foo.chpl
```

**Execution command:**
```
./foo
```

**Associated Future Test(s):**
Not yet.

### Configuration Information

- Output of `chpl --version`:
```
chpl Version 1.15.0.5260a416af
```

**Comment by e-kayrakli** [comment] 2017-08-03 14:48
ping @lydia-duncan

**Comment by lydia-duncan** [comment] 2017-08-03 15:18
Thanks for reporting!

**Comment by ben-albrecht** [comment] 2018-02-23 16:08
@mppf and I agree this is a gating issue due to blocking #7768 and #8488, with no great work-arounds available.

**Comment by marcoscleison** [comment] 2018-02-23 16:19
Thanks, everybody.

In fact, I realized that the problem is really the overriding variadic methods. It is making things difficult to abstract.
 If possible, add this in to do list. I really appreciate.

**Comment by daviditen** [comment] 2018-04-03 19:31
This issue should now be fixed in master as of https://github.com/chapel-lang/chapel/pull/9018.  Thanks for reporting it!

**Closed by daviditen** 2018-04-03 19:31 UTC
Labels: area: Compiler, gating issue, type: Bug, user issue
