### ISSUE TITLE
How to write a class method which returns a generic domain where the shape of the domain is unknown at compile time?

### ISSUE THREAD

**Issue by abhishekingit** [chapel-lang/chapel#19571] opened 2022-03-30 10:50 UTC
I was trying to write an overriding class method that returns a domain of any shape but I cannot figure out a way to do so.
I want a way to perform a dynamic dispatch to fetch a generic domain from `DerivedChild` as I am fetching values from a `Map`.
I wrote some code like this that fails because it needs a specific domain type at compile time.
```
class AbstractParent {
	// less generic fields
	const rank: int;

    proc init(rank: int) {
        this.rank = rank;
    }

	proc getDomain(): domain {
		halt("Pure virutal method");
	}	
}

class DerivedChild: AbstractParent {	
	param rank: int;
	param stridable: bool;
	var dom: domain(rank, stridable = stridable);	
	
    proc init(size: domain) {
        super.init(size.rank);
        this.rank = size.rank;
        this.stridable = size.stridable;
        this.dom = size;
    }
	//generic fields
	
	override proc getDomain(): domain {
		return this.dom;
	}
}

var dataMap: map(string, shared AbstractParent);
var d1: domain(2) = {1..2, 1..3};
var dervChild1 = new shared DerivedChild(d1);
dataMap.add("quantity1", dervChild1);
writeln(dataMap.getValue("quantity1`").getDomain());
```
With reference to [#19570](https://github.com/chapel-lang/chapel/issues/19570) I was also wondering if there is some workaround that allows us to like downcast `AbstractParent` to `DerivedChild` and call `getDomain()` from there. 

Thanks,
Abhishek

**Comment by mppf** [comment] 2022-03-30 12:59
So, the error message definitely needs improving, but I don't see how the compiler could make this program work.

The problem is that on this line `writeln(dataMap.getValue("quantity1").getDomain());`, the compiler needs to figure out the type of the subexpression `dataMap.getValue("quantity1").getDomain()` which is just the return type of `AbstractParent.getDomain`. `AbstractParent.getDomain` is declared to return a generic type, but a generic type *just won't do* here because we need to be able to do things like store the result into a variable in the generated code. (Maybe one day we will have the ability to say "any implementation of this generic interface, known at runtime" but we don't have interfaces fully implemented yet).

Now, I don't know the reason for the class hierarchy here but I can imagine two strategies to work around the issue.
 1. Adjust `AbstractParent` to itself be generic with a `type domainType`, say. Then you can arrange for `getDomain` to return that type.
 2. Use a cast
 
 
Here is a version with the cast

``` chapel
use Map;

class AbstractParent {
  // less generic fields
  const rank: int;

  proc init(rank: int) {
    this.rank = rank;
  }
}

class DerivedChild: AbstractParent {	
  param rank: int;
  param stridable: bool;
  var dom: domain(rank, stridable = stridable);	

  proc init(size: domain) {
    super.init(size.rank);
    this.rank = size.rank;
    this.stridable = size.stridable;
    this.dom = size;
  }
  //generic fields
    
  proc getDomain() {
    return this.dom;
  }
}

var dataMap: map(string, shared AbstractParent);
var d1: domain(2) = {1..2, 1..3};
var dervChild1 = new shared DerivedChild(d1);
dataMap.add("quantity1", dervChild1);
var val = dataMap.getValue("quantity1");
var asD = val: dervChild1.type;
// notes:
//  * above cast must cast to a concrete type
//  * above cast throws the class type can't be converted
writeln(asD.getDomain());
```

**Comment by abhishekingit** [comment] 2022-03-31 12:45
Hi @mppf,  Thanks for the reply. The constraint here is that casting to a static subtype is something I don't know how to do. 
To briefly explain it, I am trying to make a function that returns dimension lengths of the different quantities in the `dataMap` which is the argument for the function. I don't know how to downcast it to static subtype without knowing DerivedChild's type.

**Comment by bradcray** [comment] 2022-03-31 16:02
> I don't know how to downcast it to static subtype without knowing DerivedChild's type.

@abhishekingit : For this example, rather than trying to convert an abstract superclass into the appropriately concrete subclass, could you make the thing you're trying to do with the subclass into another dynamically dispatched method?  For example, rather than `writeln(dataMap.getValue("quantity1`").getDomain());`, imagine defining a `writeDomain()` method and then saying:  `dataMap.getValue("quantity").writeDomain();`?

The other way I could imagine doing it would be to store sufficient information in the parent class to define what cast is necessary, which is what I believe Arkouda does with its `entryType` field.  For instance, you're already storing the rank in the parent class, so I could imagine you writing code like:

```chapel
if (rank == 1) then
  writeln(dataMap.getValue("quantity1`").getDomain():domain(1));
else if (rank == 2) then
  writeln(dataMap.getValue("quantity1`").getDomain():domain(2));
else
  halt("I can't handle rank " + rank:string + " yet");
```

You'd obviously need to store the stridable property in the parent class as well in order to decode that properly.  The main downsides to this approach apart from a bit of tedium in writing out the cases is that you'll necessarily be enumerating a fixed number of choices (e.g., here I'm only handling 1D and 2D, so 3D would break), and generating code proportional to those choices.

Others who are more savvy about OO patterns than I am may see other paths forward here...

**Comment by bradcray** [comment] 2022-03-31 17:26
@abhishekingit: One other different approach that occurs to me belatedly:  Since Chapel supports dynamic casts of classes that will throw if the cast is not correct, and will generate the requested class if it is, another approach would be to attempt to cast the object returned by `dataMap.getValue()` to each of the possible results.

Like the "if (rank == 1) ... if (rank == 2)" approach, this still requires enumerating all possibilities.  However, it doesn't require storing additional meta information in the abstract class.  Essentially it could be viewed as a tradeoff between "store less information and try each possible answer to see which one firts" vs. "store more information so that we know exactly which cast will be legal".

Here's a toy example:

```chapel
class C {
}

class D: C {
  param rank: int;
}

var myC: C = new D(rank=1);
var myC2: C = new D(rank=2);

foo(myC);
foo(myC2);

proc foo(ref c: C) {
  writeln("In foo(",c,")");
  try {
    var c1 = c: D(1);
    writeln("c is a ", c1.type:string);
  } catch {
    writeln("c is not a D(1)");
  }

  try {
    var c1 = c: D(2);
    writeln("c is a ", c1.type:string);
  } catch {
    writeln("c is not a D(2)");
  }
}
```

**Comment by abhishekingit** [comment] 2022-04-05 09:46
@bradcray I am trying to get domain.shape which is a tuple and after looking at some of the approaches that you have mentioned above, I tried this but it gives me an error saying "ambiguous call".

```
use Map;

class AbstractParent {
	// less generic fields
	const rank: int;

    proc init(rank: int) {
        this.rank = rank;
    }

	proc getDomainShape(): int {
		halt("Pure virtual method");
	}

	proc getDomainShape(): 2*int {
		halt("Pure virtual method");
	}

	proc getDomainShape(): 3*int {
		halt("Pure virutal method");
	}	
}

class DerivedChild: AbstractParent {	
	param rank: int;
	param stridable: bool;
	var dom: domain(rank, stridable = stridable);	
    //generic fields
	
    proc init(size: domain) {
        super.init(size.rank);
        this.rank = size.rank;
        this.stridable = size.stridable;
        this.dom = size;
    }
	
	override proc getDomainShape(): rank*int {
		return this.dom.shape;
	}
}

var dataMap: map(string, shared AbstractParent);
var d1: domain(3) = {1..2, 1..3, 1..2};
var d2: domain(2) = {1..2, 1..3};
var dervChild1 = new shared DerivedChild(d1);
var dervChild2 = new shared DerivedChild(d2);

dataMap.add("quantity1", dervChild1);
dataMap.add("quantity2", dervChild2);

var val1 = dataMap.getValue("quantity1");
var val2 = dataMap.getValue("quantity2");

writeln(val1.getDomainShape(), " ", val2.getDomainShape());
```
I am also looking into dynamic casts of classes that you also described above.

Thanks,
Abhishek

**Comment by mppf** [comment] 2022-04-05 12:48
@abhishekingit - indeed the above is an ambiguous call because you have 3 `getDomainShape` methods on `AbstractParent` that all take the same arguments.

You could give each a different name (`getDomainShape1D` `getDomainShape2D`  `getDomainShape3D` ). You could have them always return `3*int` and just leave the later dimensions zeros. Or you could return a type that isn't a tuple (because tuples have a length fixed at runtime).

Here is a version of your program using the last approach - returning an array instead of a tuple.

``` chapel
use Map;

class AbstractParent {
	// less generic fields
	const rank: int;

    proc init(rank: int) {
        this.rank = rank;
    }

	proc getDomainShape(): [] int {
          halt("Pure virtual method");
          var dummy:[1..0] int;
          return dummy;
	}
}

class DerivedChild: AbstractParent {	
	param rank: int;
	param stridable: bool;
	var dom: domain(rank, stridable = stridable);	
    //generic fields
	
    proc init(size: domain) {
        super.init(size.rank);
        this.rank = size.rank;
        this.stridable = size.stridable;
        this.dom = size;
    }
	
	override proc getDomainShape(): [] int {
                var A:[0..#rank] int = this.dom.shape;
		return A;
	}
}

var dataMap: map(string, shared AbstractParent);
var d1: domain(3) = {1..2, 1..3, 1..2};
var d2: domain(2) = {1..2, 1..3};
var dervChild1 = new shared DerivedChild(d1);
var dervChild2 = new shared DerivedChild(d2);

dataMap.add("quantity1", dervChild1);
dataMap.add("quantity2", dervChild2);

var val1 = dataMap.getValue("quantity1");
var val2 = dataMap.getValue("quantity2");

writeln("val1 shape: ", val1.getDomainShape());
writeln("val2 shape: ", val2.getDomainShape());
```

Note that the Chapel array type is a bit too much for this use case and it's probably possible to write something else that performs better. You could create your own class for the domain shape, as an example.

> To briefly explain it, I am trying to make a function that returns dimension lengths of the different quantities in the dataMap which is the argument for the function. 

It is challenging to have a map combining values of types that you want to be different compile-time types. You might be able to avoid making such a map at all. If you really must do it, you are going to face the problem of compile-time types vs runtime types over and over again, so you will need a strategy that fits well in to the larger effort.

**Comment by bradcray** [comment] 2022-04-15 21:40
Hi @abhishekingit — I wanted to check in and see whether you were able to work through this dynamically vs. statically typed language challenge, and whether it would be OK to close this issue.  Or if not, what you think needs to happen in order to close it.  Thanks.

**Comment by abhishekingit** [comment] 2022-04-18 08:17
Hi @bradcray 
Yeah we decided to make the rank non generic by creating three versions of DerivedChild corresponding to different ranks (1D, 2D, 3D). This helps in returning the domain Shape as a 3 element tuple.

```
use Map;

class AbstractParent {
	// less generic fields
	const rank: int;

    proc init(rank: int) {
        this.rank = rank;
    }	

	proc getDomShape(): 3*int {
		halt("Pure virtual method");
	}
}

class DerivedChild1: AbstractParent {	
	var dom: domain(1, stridable=false);
	var dimensions: domain(string);
    //generic fields
	
    proc init(size: domain, labels: domain(string)) {
        super.init(size.rank);        
        this.dom = size;        
		this.dimensions = labels;
    }
		
	override proc getDomShape(): 3*int {
		return (dom.shape(0), 0, 0);
	}
}

class DerivedChild2: AbstractParent {	
	var dom: domain(2, stridable=false);
	var dimensions: domain(string);
    //generic fields
	
    proc init(size: domain, labels: domain(string)) {
        super.init(size.rank);        
        this.dom = size;        
		this.dimensions = labels;
    }

	override proc getDomShape(): 3*int {
		return (dom.shape(0), dom.shape(1), 0);
	}
}

class DerivedChild3: AbstractParent {	
	var dom: domain(3, stridable=false);
	var dimensions: domain(string);
    //generic fields
	
    proc init(size: domain, labels: domain(string)) {
        super.init(size.rank);        
        this.dom = size;        
		this.dimensions = labels;
    }

	override proc getDomShape(): 3*int {
		return (dom.shape(0), dom.shape(1), dom.shape(2));
	}
}

var d1: domain(1) = {1..4};
var d2: domain(2) = {1..2, 1..3};
var d3: domain(3) = {1..4, 1..2, 1..3};
var labels: domain(string) = {"X", "Y"};

var dataArr1 = new shared DerivedChild1(d1, labels);
var dataArr2 = new shared DerivedChild2(d2, labels);
var dataArr3 = new shared DerivedChild3(d3, labels);

var dataMap: map(string, shared AbstractParent);
dataMap.add("prop1", dataArr1);
dataMap.add("prop2", dataArr2);
dataMap.add("prop3", dataArr3);

writeln(dataMap.getValue("prop1").getDomShape(), "\n", dataMap.getValue("prop2").getDomShape(), "\n", dataMap.getValue("prop3").getDomShape());

```
I guess this is the way to go forward for now. Sorry for the late reply, I was busy with some other things lately. I guess this issue can be closed.
Thanks,
Abhishek

**Closed** 2022-04-18 16:45 UTC

**Comment by bradcray** [comment] 2022-04-19 05:33
Hi @abhishekingit —

Earlier I closed this without really looking at the code at all.  Closing tabs tonight, it caught my eye.  Here's a way to write the same code as the above, yet with one derived class rather than three:

```chapel
use Map;

class AbstractParent {
	// less generic fields
	const rank: int;

    proc init(rank: int) {
        this.rank = rank;
    }	

	proc getDomShape(): 3*int {
		halt("Pure virtual method");
	}
}

class DerivedChild: AbstractParent {
  param rank: int;
	var dom: domain(rank, stridable=false);
	var dimensions: domain(string);
    //generic fields
	
    proc init(size: domain, labels: domain(string)) {
      super.init(size.rank);
      this.rank = size.rank;
      this.dom = size;        
		  this.dimensions = labels;
    }
		
	override proc getDomShape(): 3*int {
    const shape = dom.shape;
    var retval: 3*int;
    for i in 0..<dom.rank do
      retval(i) = shape(i);
    for i in dom.rank..<3 do
      retval(i) = 0;
    return retval;
	}
}

var d1: domain(1) = {1..4};
var d2: domain(2) = {1..2, 1..3};
var d3: domain(3) = {1..4, 1..2, 1..3};
var labels: domain(string) = {"X", "Y"};

var dataArr1 = new shared DerivedChild(d1, labels);
var dataArr2 = new shared DerivedChild(d2, labels);
var dataArr3 = new shared DerivedChild(d3, labels);

var dataMap: map(string, shared AbstractParent);
dataMap.add("prop1", dataArr1);
dataMap.add("prop2", dataArr2);
dataMap.add("prop3", dataArr3);

writeln(dataMap.getValue("prop1").getDomShape(), "\n", dataMap.getValue("prop2").getDomShape(), "\n", dataMap.getValue("prop3").getDomShape());
```

Please let me know if you have any questions.

**Comment by abhishekingit** [comment] 2022-04-20 10:33
@bradcray Ohh yeah that does work. Thanks for all the help :+1:
