### ISSUE TITLE
Ubuntu build giving conftest errors during qthreads build

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17440] opened 2021-03-19 23:29 UTC
When upgrading the Computer Language Benchmarks Game website to use Chapel 1.24.0, [Isaac reported](https://salsa.debian.org/benchmarksgame-team/benchmarksgame/-/issues/426#note_232709) that he received errors of the form:

```
Sorry, the application conftest has stopped unexpectedly.

This problem report applies to a program which is not installed any more. (/opt/src/chapel-1.24.0/third-party/qthread/build/linux64-x86_64-native-gnu-none-flat-jemalloc-bundled/conftest)
```

when building.  This did not seem to affect the result (in that he was still able to compile and run Chapel programs), but is a bit disconcerting all the same.

**Comment by gbtitus** [comment] 2021-03-20 15:59
`conftest` is the name the GNU `configure` script (of the `autoconf` toolset) uses for the teensy programs it builds to determine whether a given feature or capability exists and/or works on the system. Those programs are always deleted after the decision they contributed to is made, so that's not surprising. We could probably learn a lot more from the `config.log` file that should have been left in that same directory.

**Comment by bradcray** [comment] 2021-03-22 21:58
I've been mailed a copy of the `config.log` file, and am guessing that this might be the problematic portion:

```bash
configure:20165: checking for qsort_r argument style
configure:20206: gcc -o conftest -O3   -DCHPL_JEMALLOC_PREFIX=chpl_je_ -DCHPL_HAS_GMP -I/opt/src/chapel-1.24.0/runtime//include/localeModels/flat -I/opt/src/chapel-1.24.0/runtime//include/localeModels -I/opt/src/chapel-1.24.0/runtime//include/comm/none -I/opt/src/chapel-1.24.0/runtime//include/comm -I/opt/src/chapel-1.24.0/runtime//include/tasks/qthreads -I/opt/src/chapel-1.24.0/runtime//include/threads/none -I/opt/src/chapel-1.24.0/runtime//include -I/opt/src/chapel-1.24.0/runtime//include/qio -I/opt/src/chapel-1.24.0/runtime//include/atomics/cstdlib -I/opt/src/chapel-1.24.0/runtime//include/mem/jemalloc -I/opt/src/chapel-1.24.0/third-party/jemalloc/install/linux64-x86_64-ivybridge-gnu-none/include -I/opt/src/chapel-1.24.0/third-party/gmp/install/linux64-x86_64-ivybridge-gnu-none/include -I/opt/src/chapel-1.24.0/third-party/hwloc/install/linux64-x86_64-ivybridge-gnu-none-flat/include   conftest.c -lm -lpthread  >&5
conftest.c: In function 'main':
conftest.c:113:5: warning: null argument where non-null required (argument 4) [\
-Wnonnull]
  113 |     qsort_r(array,5,sizeof(int),NULL,cmp);
      |     ^~~~~~~
configure:20206: $? = 0
configure:20206: ./conftest
/opt/src/chapel-1.24.0/third-party/qthread/qthread-src/configure: line 2023: 19\
4228 Segmentation fault      (core dumped) ./conftest$ac_exeext
configure:20206: $? = 139
configure: program exited with status 139
```

seems like the core dump could result in the reported pop-up in ubuntu, and meanwhile the script had gone on to the next conftest step, erasing the binary for the current one resulting in the "not installed anymore" message?

**Comment by gbtitus** [comment] 2021-03-22 22:22
Interesting. The point of that `configure` check is apparently to determine whether the system has a FreeBSD-like or Linux-like definition of `qsort_r()`. The gcc warning and the segfault are certainly what you'd expect for the one quoted in the code (which matches the FreeBSD decl) on a Linux system. Personally I think I would have written that test to catch the `SIGSEGV` and exit synchronously but hey, to each their own!

I think you're right, though, both about the cause of the pop-up and that its occurrence doesn't indicate an actual problem.

**Comment by janciesko** [comment] 2021-03-23 15:58
Thanks for reporting this. Is this behavior a showstopper in your opinion and worth to change?

**Comment by bradcray** [comment] 2021-03-23 16:51
@janciesko : I think it's awkward for users to get a pop-up dialog* reporting that something has failed during their build process, so yeah, I think it's worth changing/improving to avoid the segfault.  Since it doesn't seem to break the build in any way, I don't know that I'd call it a showstopper, though.  Just regrettable and preferable to avoid if there's an easy fix.

`*` = I didn't say so in this issue's summary, but the original comment that spawned this issue (linked in the OP) made it sound as though the error showed up as a pop-up dialog box, which is what caught my attention.  If it was just a segfault or error in a long build log output, I'd definitely be far less concerned about it.

**Comment by janciesko** [comment] 2021-04-07 04:13
I see. [This](https://github.com/janciesko/qthreads/commit/6ee758a6dddd82930bd5dbbccc7ee885b98630e1 ) could fix the problem by catching signals. It resolves segfault / sigabrt pop-ups which I see on MacOS.

**Comment by bradcray** [comment] 2021-04-07 04:55
Cool, thanks!

**Comment by janciesko** [comment] 2021-04-08 16:49
@gbtitus - we're catching SIGSEGV now as shown [here](https://github.com/janciesko/qthreads/commit/6ee758a6dddd82930bd5dbbccc7ee885b98630e1). Please, can you comment if such signal handling looks portable to you? It seems to work on Linux and MacOS. On MacOS I have been seeing the pop-up message when not catching the segfault. Thanks!

**Comment by gbtitus** [comment] 2021-04-08 18:14
Strictly speaking if `sa_flags` has `SA_SIGINFO` set then the handler should be defined as an `sa_sigaction` style (3-argument) function. Since the handler in this case is an `sa_handler` style (1-argument) function it should be assigned to the `sa_handler` member instead, and `SA_SIGINFO` should not be set in `sa_flags`. As it stands, the handler will be called with 3 arguments even though it's only defined to take 1 (which it ignores). Having said that, though, I don't know of any architectures on which this will actually cause a problem.

Another potential issue is that `exit()` is not safe to call in a signal handler, so for best portability the handler should call `_exit()` instead. (The POSIX signal-safe functions can be seen in a list in the `signal(7)` man page on a Linux system.) In practice this probably won't cause a problem either -- where I've seen issues it's in multithreaded programs in which two threads call `exit()` at the same time and then the `atexit()` processing gets messed up.

Otherwise and in general, it looks good -- catching the signal and exiting is definitely the right way to address this!

**Comment by janciesko** [comment] 2021-04-09 02:49
Ok, thanks a lot for the info. Code fixed in the branch. Will issue PR to QThread master.

**Comment by leekillough** [comment] 2021-05-13 16:08
Closing this because it is fixed in https://github.com/Qthreads/qthreads/pull/84

**Comment by bradcray** [comment] 2021-05-13 16:57
@leekillough : But we haven't updated our version of Qthreads in Chapel to get the fix yet, have we?

**Comment by bradcray** [comment] 2021-05-14 20:02
I'm reopening this because I'm fairly certain it's not fixed for our source base yet, and don't want to lose sight of it.

[As a general practice to review churn, it's typically good to check with the developer who filed the issue (if they're still active on the team) before closing to make sure they agree].

**Comment by bradcray** [comment] 2021-08-19 15:50
@ronawho: I forgot to bring this up in the priorities meeting this week, but is it still on your radar to see if we can bring this patch in (if not an overall qthreads update) to silence this issue?

**Comment by ronawho** [comment] 2021-08-19 15:58
Yeah, I opened https://github.com/Cray/chapel-private/issues/2351 to track bringing that in -- I'm planning on doing that next sprint.

**Comment by ronawho** [comment] 2021-08-23 16:33
Brought in with https://github.com/chapel-lang/chapel/pull/18272

**Closed by ronawho** 2021-08-23 16:33 UTC
Labels: area: BTR, user issue, type: Portability

**Comment by mppf** [comment] 2021-09-13 19:46
If this kind of error comes up again it might be useful to know that one can use `sudo tail -f /var/log/apport.log` to watch for core dumps.
