### ISSUE TITLE
internal error with generic nilable class return type in override method

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14148] opened 2019-09-21 23:19 UTC
Bug. This code generates an internal error.

The `Cursor` class is overriding a method that has a return type of generic nilable class `Row?`.

Making it non-generic `owned Row?` (at [[2]]) fixes the issue.

Notably, making [[1]] non-generic doesn't alter the behavior.

```chapel
class Row {
    var curRow: int;
}

class CursorBase {
    proc fetchone(): Row? { // [[1]]
        use HaltWrappers only;
        HaltWrappers.pureVirtualMethodHalt();
    }
}

class Cursor: CursorBase {
    var curRow: int;
    var numRows: int;

    proc init() {
        this.curRow = 0;
        this.numRows = 10;
    }

    override proc fetchone(): Row? { // [[2]]
        if (this.curRow == this.numRows) {
            return nil;
        }

        var row = new Row(curRow);
        return row;
    }
}


proc main() {
    var cursor = new owned Cursor();
    var res: owned Row? = cursor.fetchone();
    writeln(res);
}
```
```terminal
app.chpl:34: internal error: UTI-MIS-0672 chpl version 1.21.0 pre-release (b2b1b701)
```

**Comment by BryantLam** [comment] 2019-09-22 18:46
Another program that exhibits the same erroneous behaviors.
```chapel
class Row {
    var valid: bool;
    var curRow: int;

    proc isValid(): bool {
        return valid;
    }
}

class CursorBase {
    iter these() ref {
        use HaltWrappers only;
        HaltWrappers.pureVirtualMethodHalt();
    }

    iter fetchAll(): Row { // [[3]]
        use HaltWrappers only;
        HaltWrappers.pureVirtualMethodHalt();
    }

    proc fetchOne(): Row {
        use HaltWrappers only;
        HaltWrappers.pureVirtualMethodHalt();
    }
}

class MysqlCursor: CursorBase {
    var curRow: int;
    var numRows: int;

    proc init() {
        this.curRow = 0;
        this.numRows = 4;
    }

    override iter these() ref {
        for row in this.fetchAll() {
            yield row;
        }
    }

    override iter fetchAll(): Row { // [[4]]
        var row: Row = this.fetchOne();
        while row.isValid() {
            yield row;
            row = this.fetchOne();
        }
    }

    override proc fetchOne(): Row {
        if this.curRow == this.numRows {
            return new Row(valid=false);
        }

        var row = new Row(valid=true, curRow=curRow);
        curRow += 1;
        return row;
    }
}

proc main() {
    var cursor = new MysqlCursor();
    for row in cursor {
        writeln((row.type :string, row));
    }
}
```
```terminal
# This program
app.chpl:38: internal error: AST-PRI-IVE-0233

# This program with [[3]] as `owned Row`
app.chpl:38: internal error: AST-PRI-IVE-0233

# This program with [[4]] as `owned Row`
app.chpl:16: internal error: AST-CHE-AST-0327
```
`chpl version 1.21.0 pre-release (b2b1b701)`

**Comment by vasslitvinov** [comment] 2022-04-29 21:28
This is a summary of my plan going forward.

#19709 fixed the issue raised in the OP here. The next step is to fix several related issues brought up in the first comment above: https://github.com/chapel-lang/chapel/issues/14148#issuecomment-533907322

* Observe that if the return type of a procedure or iterator, as concluded by the compiler, is generic, it causes trouble for the caller.

* Handle the case where a recursive procedure declares a generic return type. Currently this may crash the compiler. The easiest solution is to handle this analogously to a recursive procedure without a declared return type. It would be a different check (is fn->retType a recursive type?) and a different error text ("please make your declared return type concrete"). A small reproducer:


```chpl
proc p(): Row {
  return p();   // for simplicity
}

compilerWarning((p()).type:string); // needs to print a concrete type

var q = p();
compilerWarning(q.type:string);     // ditto
```

* If an iterator declares a generic return type, it needs to be instantiated. This is done for a procedure, needs to be done for an iterator. In `resolveFunction.cpp`:

  - `resolveSpecifiedReturnType()` -- iteratorInfo is set up with the generic return type:
```
    if (fn->isIterator() == true && fn->iteratorInfo == NULL) {
      // Note: protoIteratorClass changes fn->retType to the iterator record.
      // The original return type is stored here in retType.
      protoIteratorClass(fn, retType);
    }
```

  - `resolveFunction()` -- iteratorInfo should be updated with the instantiated return type, however it is not because iteratorInfo has already been setup -- beware there are several places in iteratorInfo that need to be updated:
```
      if (fn->isIterator() == true && fn->iteratorInfo == NULL) {
        protoIteratorClass(fn, yieldedType);
      }
```

* Handle a combination of the previous two bullets, i.e., a recursive iterator declaring a generic return type.

Other notes:

* Verify that the above works for a variety of generic types:

  - `Row` is a concrete class, so the type `Row` is generic over memory management
  - switch `Row` to a generic class and consider the generic types `Row` and `borrowed Row`
  - switch `Row` to a generic record
  - use another predefined generic type such as `integral`

* The code examples throughout this issue declare a parent class and a child class, then invoke methods only on the child class. There are probably issues with the parent class that we are not observing because the compiler does not resolve its methods. It would be good to check that the parent methods are handled properly, i.e., either they work or generate nice error messagse.

**Comment by DanilaFe** [comment] 2024-07-09 20:48
Today on `main`, the function's return type is computed instantiating the generic (so the actual return type is `owned Row` in the example, `shared Row` if you fix the ownership issues caused by `owned`). As a result, I think this issue is resolved. The original program contains the nil-in-generic-return issue (https://github.com/chapel-lang/chapel/issues/25468), but otherwise works fine. I will add a regression test to https://github.com/chapel-lang/chapel/pull/25469 and close this.

**Closed** 2024-07-10 03:00 UTC
Labels: type: Bug, area: Compiler, user issue
