### ISSUE TITLE
Nil dereference for maps of domains

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#20167] opened 2022-07-06 20:23 UTC
Related to https://github.com/chapel-lang/chapel/issues/20164, I'm trying to cache distributed domains in Arkouda. However, I'm seeing issues when storing domains in a map. Here's a simplified reproducer using local domains.

```chpl
use Map;

type domType = {0..0}.type;
var tab: map(int, domType);

proc cachedDom(size: int) const ref {
  if !tab.contains(size) {
    tab.add(size, {0..<size});
  }
  return tab.getReference(size);
}

proc main() {
  var d = cachedDom(10);
}
```

```sh
chpl cache-dom.chpl
./cache-dom
cache-dom.chpl:8: error: attempt to dereference nil # tab.add(size, {0..<size});

CHPL_UNWIND=system chpl cache-dom.chpl --devel
./cache-dom

$CHPL_HOME/modules/internal/ChapelArray.chpl:760: error: attempt to dereference nil
Stacktrace

newRectangularDom() at $CHPL_HOME/modules/internal/ChapelArray.chpl:757
newRectangularDom() at $CHPL_HOME/modules/internal/ChapelArray.chpl:770
init() at $CHPL_HOME/modules/internal/ChapelDomain.chpl:959
cachedDom() at cache-dom.chpl:6
main() at cache-dom.chpl:13
```

Where the nil seems to be at at https://github.com/chapel-lang/chapel/blob/3ffc1fff4a2329753f5addb752beb85c1d5416c7/modules/internal/ChapelArray.chpl#L760

Note that in my real use case the domain type is either default rectangular or block depending on `CHPL_COMM`

**Comment by bradcray** [comment] 2022-07-06 21:10
This seems akin to https://github.com/chapel-lang/chapel/issues/19118

**Comment by ronawho** [comment] 2022-07-06 21:36
Sure seems to be, thanks. Close as duplicate?

**Comment by bradcray** [comment] 2022-07-06 21:52
Either way's fine with me since they're different data structures.  If you were to close it, it might be good to edit the other to extend it to include Maps.

**Comment by vasslitvinov** [comment] 2022-07-07 18:29
As a hack/workaround, we could have the map store the domain classes instead of actual domains.

**Comment by ronawho** [comment] 2022-07-11 23:57
> As a hack/workaround, we could have the map store the domain classes instead of actual domains.

@vasslitvinov how would you implement this. I'd like to try to see the potential performance impact, but it's not obvious to me what this would look like.

The following seems to work, but is a complete guess:

```chpl
use Map;

type domType = {0..0}._value.type;
var tab: map(int, domType);

proc cachedDom(size: int) {
  if !tab.contains(size) {
    var _dom = {0..<size}._value;
    _dom._arrs_containing_dom += 1;
    tab.add(size, _dom);
  }
  return _getDomain(tab.getReference(size));
}

proc main() {
  var d = cachedDom(10);
}
```

**Comment by vasslitvinov** [comment] 2022-07-12 02:20
@ronawho -- you are right, the details need to be worked out, which I did not do.

Your implementation looks spot on. I like your trick `_arrs_containing_dom += 1`. Would your code work without it?

I assume that this is a prototype and you will switch it to Block-distributed domains for Arkouda.

`proc cachedDom` needs `pragma "no copy return"` and perhaps(?) `pragma "return not owned"`.

@mppf do you have any insights here?

**Comment by ronawho** [comment] 2022-07-12 12:15
> Your implementation looks spot on. I like your trick `_arrs_containing_dom += 1`. Would your code work without it?

No, the domain/distribution get destroyed at the end of `cachedDom` without that, so the unmanaged `_value` class is referring to deleted memory without that.

> I assume that this is a prototype and you will switch it to Block-distributed domains for Arkouda.

Yes, and this seemed to work for the arkouda case too, just keeping things simple in this issue.

**Comment by vasslitvinov** [comment] 2022-08-05 00:42
Aside: for SymEntries over small arrays that can comfortably fit on the current locale, we could have makeDistDom(size) distribute the domain over just the current locale. Would kind of speedup would that offer?
```chpl
// omitting the select statement
proc makeDistDom(size:int) {
   if size < singleLocaleSizeThreshold {
      return {0..#size} dmapped Block(boundingBox={0..#max(size,1)}, targetLocales = [here]);
   } else {
      return {0..#size} dmapped Block(boundingBox={0..#size});
   }
}
```

**Comment by ronawho** [comment] 2022-08-08 19:27
That's possible (and had been discussed in a few perf meetings), but has potential to lead to load/comm imbalance (especially in cases where a small distributed array is used as a helper data structure in a larger computation) , and is not something I'm ready to explore at this time (and definitely not as part of this issue)

**Closed** 2022-08-22 18:25 UTC

**Comment by ronawho** [comment] 2022-08-25 15:30
@dlongnecke-cray this still fails for me when trying to use it in Arkouda. I think I have a small reproducer by just switching to OP to use block dist arrays:

```chpl
use Map, BlockDist;

type domType = newBlockDom({0..1}).type;
var tab: map(int, domType);

proc cachedDom(size: int) const ref {
  if !tab.contains(size) {
    tab.add(size, newBlockDom({0..<size}));
  }
  return tab.getReference(size);
}

proc main() {
  var d = cachedDom(10);
}
```

**Comment by dlongnecke-cray** [comment] 2022-08-25 16:05
I'll take a look.

**Comment by jabraham17** [comment] 2025-01-15 00:50
This still fails on main today (with `CHPL_COMM!=none`), but the reproducer has changed slightly with 2.0. Here is the updated reproducer

```chapel
use Map, BlockDist;

type domType = blockDist.createDomain({0..1}).type;
var tab: map(int, domType);

proc cachedDom(size: int) const ref {
  if !tab.contains(size) {
    tab.add(size, blockDist.createDomain({0..<size}));
  }
  return tab(size);
}

proc main() {
  var d = cachedDom(10);
  writeln(d);
}

```
