### ISSUE TITLE
Some types are hard to read and confusing in chpldoc

### ISSUE THREAD

**Issue by Rapiz1** [chapel-lang/chapel#15229] opened 2020-03-16 10:19 UTC
# Summary of Problem
For
```chapel
  var envs: map(string, string);
```
`chpldoc` will produce this:
![image](https://user-images.githubusercontent.com/20105061/76746209-186f2c00-67b2-11ea-950d-d2e4f3258cd9.png)

`stringmapstring` is hard to read  and very confusing. I think simply printing the type `map(string, string)` is acceptable.
Are there some design reasons why `chpldoc` not simply copying the types to the docs? And what the line like `map(string,string)` should look like?

**Comment by lydia-duncan** [comment] 2020-03-16 15:24
This is a duplicate of #13626

**Closed by lydia-duncan** 2020-03-16 15:24 UTC
