### ISSUE TITLE
split init failure when const with explicit type is split init in a standard module

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#15649] opened 2020-05-08 06:55 UTC
### Summary of Problem

When this module is in `modules/standard/TheseIters.chpl`:

```chapel
module TheseIters {

  proc foo() {
    const n: int;

    n = 8;

    return n;
  }
}
```

This program fails to compile:

```chapel
use TheseIters;

writeln(foo());
```

```
fortytwo@magrathea:~/src/chapel (dynamic-chunkidx)$ chpl split-init.chpl 
$CHPL_HOME/modules/standard/TheseIters.chpl:3: In function 'foo':
$CHPL_HOME/modules/standard/TheseIters.chpl:6: error: illegal lvalue in assignment
```

But it does compile if the module is located in a user dir:

```
fortytwo@magrathea:~/src/chapel (dynamic-chunkidx)$ cp modules/standard/TheseIters.chpl yonder/
fortytwo@magrathea:~/src/chapel (dynamic-chunkidx)$ chpl -M yonder split-init.chpl 
warning: Ambiguous module source file -- using yonder/TheseIters.chpl over $CHPL_HOME/modules/standard/TheseIters.chpl
fortytwo@magrathea:~/src/chapel (dynamic-chunkidx)$ 
```

Also, it compiles if the `: int` is removed from the declaration of `n`!  (Even with the module still in `modules/standard`.)  This seems really weird.

**Associated Future Test(s):**

None yet.  I don't know how to write a future that requires certain code in `modules/standard`.

### Configuration Information

```
chpl version 1.23.0 pre-release (0fbea6869d)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

**Comment by cassella** [comment] 2020-05-08 06:58
@mppf  I presume?

This is responsible for the lack of an explicit `: int` and a comment in #14628 .

**Comment by cassella** [comment] 2020-05-08 07:32
Ah,

```
chpl --prepend-standard-module-dir yonder split-init.chpl 
```

hits the error, and gives me a clue how to write a future.

**Comment by mppf** [comment] 2020-05-08 12:05
@cassella - split init isn't enabled for internal/standard modules yet. https://github.com/Cray/chapel-private/issues/641 is tracking the TODO to add it. That is the cause of this issue.

**Comment by bradcray** [comment] 2020-05-18 21:30
@cassella: This will be fixed in PR #15699.

**Comment by cassella** [comment] 2020-05-18 22:21
Thanks!

And the `const n;` version must have been taking advantage of the "unless there is no alternative" case?

**Comment by bradcray** [comment] 2020-05-18 22:42
> And the const n; version must have been taking advantage of the "unless there is no alternative" case?

Yes, I believe so.

**Closed** 2020-05-29 23:42 UTC
