### ISSUE TITLE
when should a value returned by a function be mutable?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#22330] opened 2023-05-17 16:03 UTC
See also #17195.

Today it's the case that a function that returns by value produces something that cannot be modified, unless it is an array.

For example:

``` chapel
proc foo() {
  return 42;
}

foo() = 43; // error: illegal lvalue in assignment
```

But, when returning an array, such things are valid and sometimes useful. Here is an example that mutates the value returned by `makeInputArray` in-place to avoid needing more space:

``` chapel
proc makeInputArray(n: int) {
  var A:[1..n] int = 1..n;
  return A;
}

proc mutateAndSum(ref A) {
  for x in A {
    x *= 2;
  }
  return + reduce A;
}

var sum = mutateAndSum(makeInputArray(1000)); // compiles today!
writeln(sum);
```

What should we do about this?

### Option 1: Allow returned values to be mutated

Make both of the above programs legal with the default intent. Not because the first program is useful, but because it simplifies the rules about whether returned values can be modified without breaking patterns using the array exception today.

### Option 2: Make both programs result in compilation error

Keep the 1st program a compilation error but extend that checking to array-returning functions. To write such patterns, you would need an intermediate variable. For example

``` chapel
var array = makeInputArray(1000);
var sum = mutateAndSum(array);
```

### What about explicit return intents?

Separately, we can consider having an explicit way to opt in to or out of this checking. For example, it has been proposed that we could write `proc f() out` to return a mutable value and `proc f() const out` to produce a non-mutable value.

One concern with this approach is that it's not so clear that a function knows whether or not it's reasonable to modify the value returned. That seems more of a style issue at the call site. So how can a function author (say, writing a library) make a good choice between these options? Perhaps instead of a return intent, the call site could use an attribute on the block making the call to indicate that modifying the returned value is OK. Or, perhaps it's good enough to ask people to add a temporary variable.

**Comment by bradcray** [comment] 2023-05-17 16:10
The asymmetry strikes me as being odd, so I wouldn't stick with the status quo.  Offhand, I'd be inclined to do option 2, at least unless we have compelling / motivating cases for not doing so (where I'd still probably be more inclined to rely on a return intent than having arrays be different/special here).  I'm also open to option 1, though it seems somewhat more weird to me in the case of returning `int`.

**Comment by mppf** [comment] 2023-05-17 17:40
FWIW I also like Option 2.

**Comment by bradcray** [comment] 2023-05-18 21:24
I took a little bit of time trying to see if I could determine why arrays are different in this respect in hopes of trying to stop them from being different, but failed to find the logic where it happens.  If anyone has pointers or ideas, I'm all ears.

**Comment by mppf** [comment] 2023-05-19 01:39
There might be more than one place but the place I know of is in `isLegalLvalueActualArg` -- you can see `bool actualExprTmp = sym->hasFlag(FLAG_EXPR_TEMP) && !sym->type->symbol->hasFlag(FLAG_ARRAY);` ruling out arrays for the expr-temp lvalue check.

**Comment by vasslitvinov** [comment] 2023-05-19 02:29
@mppf - that change, along with another one in checkResolved, comes from https://github.com/chapel-lang/chapel/commit/c63d8e55cac . What was the reason for making that change? I suspect it is because otherwise some tests would be failing. Or maybe there was more to it?

**Comment by bradcray** [comment] 2023-05-19 02:55
I got about ~350+ failures with the first of the two changes, where most of the ones I inspected were caused by assigning to a slice, like `A[2..n-1] = 1.0;`  That was right as I was hitting my stopping point.

**Comment by mppf** [comment] 2023-05-23 16:36
> @mppf - that change, along with another one in checkResolved, comes from [c63d8e55cac](https://github.com/chapel-lang/chapel/commit/c63d8e55cac) . What was the reason for making that change? I suspect it is because otherwise some tests would be failing. Or maybe there was more to it?

Yes it was to keep tests passing, IIRC.



> I got about ~350+ failures with the first of the two changes, where most of the ones I inspected were caused by assigning to a slice, like `A[2..n-1] = 1.0;` That was right as I was hitting my stopping point.

This slice case feels like something that "should work". But ever writing something like `ref S = A[2..n-1]; S = 1.0;` doesn't help because the result of the function call producing the slice is still returned by value and then "modified" (stored in a mutable `ref`).

Does this sink Option 2?

One way out of it is to view array slices not as values but as special references. (This idea comes from #21233). So the thing constructing the slice returns a "reference" for this purpose. But, this "reference" needs to have action taken when it goes out of scope etc to potentially free some memory.

**Closed** 2023-07-31 13:58 UTC
Labels: type: Design, area: Language, type: Chapel 2.0
