### ISSUE TITLE
Building chpl compiler fails if the OS locale is not English

### ISSUE THREAD

**Issue by intractabilis** [chapel-lang/chapel#15155] opened 2020-03-10 08:28 UTC
### Summary of Problem
If you are building chapel from the source code (release/1.20 branch git snapshot) in Linux with different from English locale, the compilation fails with the following errors:

```
cd standard/gen/linux64-x86_64-gnu && /home/me/chapel/util/config/make_sys_basic_types.py SysCTypes.chpl
Traceback (most recent call last):
  File "/home/me/chapel/util/config/compileline", line 234, in <module>
    main()
  File "/home/me/chapel/util/config/compileline", line 194, in main
    mysystem(make_helper, "printcompileline")
  File "/home/me/chapel/util/config/compileline", line 35, in mysystem
    s = myrun(cmd, arg)
  File "/home/me/chapel/util/config/compileline", line 26, in myrun
    output = utils.run_command(use_cmd)
  File "/home/me/chapel/util/chplenv/utils.py", line 55, in run_command
    output = (output[0].decode(), output[1].decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 9: ordinal not in range(128)
sh: 1: -E: not found
ERROR: Found 0 max values, but 16 types were expected.
```

Obviously some of the code generators added some symbols not from English locale to one of the files. Setting `LANGUAGE=en:en` and `LANG=en_US.UTF-8` and rebuilding fixes the problem.

### Steps to Reproduce
```
./configure
make
```

**Comment by bradcray** [comment] 2020-03-11 00:33
Hi — For a bit more information, what were LANGUAGE/LANG set to / defaulted to when you ran this?  And does it use a UTF-8 character locale?

[for developers, this issue seems potentially related: https://github.com/Cray/chapel-private/issues/407]

**Comment by bradcray** [comment] 2020-03-26 00:27
(I've received these settings offline)

**Comment by bradcray** [comment] 2020-03-26 00:31
(That said, I was unable to reproduce the error with the given settings)

**Comment by e-kayrakli** [comment] 2020-03-26 00:55
I am wondering if explicitly setting encoding in that script helps. There maybe other instances where this change needs to be made, but if the error mode changes at least, then we may be on the right track.

Here is how that change should look like:

```
diff --git a/util/chplenv/utils.py b/util/chplenv/utils.py
index c8e20f4cd3..f313c5711f 100644
--- a/util/chplenv/utils.py
+++ b/util/chplenv/utils.py
@@ -46,13 +46,13 @@ def run_command(command, stdout=True, stderr=False, cmd_input=None):
     except OSError:
         error("command not found: {0}".format(command[0]), OSError)

-    byte_cmd_input = str.encode(cmd_input) if cmd_input else None
+    byte_cmd_input = str.encode(cmd_input, encoding="utf-8") if cmd_input else None
     output = process.communicate(input=byte_cmd_input)
     if process.returncode != 0:
         error("command failed: {0}\noutput was:\n{1}".format(
             command, output[1]), CommandError)
     else:
-        output = (output[0].decode(), output[1].decode())
+        output = (output[0].decode(encoding="utf-8"), output[1].decode(encoding="utf-8"))
         if stdout and stderr:
             return output
         elif stdout:
@@ -72,8 +72,8 @@ def run_live_command(command):
     except OSError:
         error("command not found: {0}".format(command[0]), OSError)

-    for stdout_char in iter(lambda: process.stdout.read(1), str.encode("")):
-        yield stdout_char.decode()
+    for stdout_char in iter(lambda: process.stdout.read(1), str.encode("", encoding="utf-8")):
+        yield stdout_char.decode(encoding="utf-8")
     process.stdout.close()
     returncode = process.wait()
```

Alternatively you can check this branch: https://github.com/e-kayrakli/chapel/tree/explicit-encoding-utils-py

@intractabilis -- if you can test it in your system please let us know. Thanks!

**Comment by e-kayrakli** [comment] 2020-04-14 20:52
Found one more decode that might need explicit encoding:

```
diff --git a/util/config/make_sys_basic_types.py b/util/config/make_sys_basic_types.py
index 64ab520467..e1f3a164e2 100755
--- a/util/config/make_sys_basic_types.py
+++ b/util/config/make_sys_basic_types.py
@@ -102,7 +102,7 @@ def get_sys_c_types(docs=False):
     compileline_env.pop('CHPL_MAKE_CHPLENV_CACHE', None)
     compileline_proc = subprocess.Popen([compileline_cmd, '--compile'],
         stdout=subprocess.PIPE, env=compileline_env)
-    compileline = compileline_proc.communicate()[0].decode().strip();
+    compileline = compileline_proc.communicate()[0].decode(encoding="utf-8").strip();
     logging.debug('Compile line: {0}'.format(compileline))

     # Create temp header file with *_MAX macros, then run it through the C
```

There are some more calls to `bytes.decode` in our scripts but I believe this (and the one above) should cover all things that we run during build. (If we know this is the right direction I can add the necessary argument to all of them)

**Comment by intractabilis** [comment] 2020-04-14 21:43
In my opinion it solves the symptom, not the root cause.

The real problem is that you start an instance of `make` without passing the file descriptors responsible for communication between different instances of `make`. That's why you receive a warning that triggered this issue. It's probably not a big problem for getting a compile string for gcc, but do you really want to hide the issue that later can lead to a bug that will be very difficult to discover later?

**Comment by e-kayrakli** [comment] 2020-04-14 22:00
Am I interpreting right that you are now able to build without the issue in your original post? If so, I think there are potentially two issues that you were encountering (1) is this missing encoding argument issue that's solved by the above patches, (2) is the make problem that you mention above. I think (2) should be discussed/solved under a separate issue.

I personally am not that well-versed about our build system to make comments on your assessment on the problem there.

**Comment by intractabilis** [comment] 2020-04-14 22:13
Sorry, I thought Brad passed my notes.

I haven't tried your last patch. The problem that triggered this particular issue is that `make` outputs a fair warning: “jobserver unavailable: using -j1. Add '+' to parent make rule”. On my machine it was in different locale, so your Python script failed.

This being said, I would strongly discourage to solve this issue by making the warning message being ignored (this is what you are doing by juggling with encoders) by your Python script. Instead you should address the _warning_, not its _encoding_.

My assumption is that the reason for this warning is here:
```
$(SYS_CTYPES_MODULE): $(MAKE_SYS_BASIC_TYPES)
    mkdir -p   $(@D)
    cd $(@D)  && $(MAKE_SYS_BASIC_TYPES) $(@F)
```

The second line starts a new shell, which probably doesn't inherit the file descriptors. Maybe I am wrong, but this where I would start.

**Comment by e-kayrakli** [comment] 2020-04-14 22:45
No I am aware of this issue, but my point is different.

Our scripts seem to be not able to non-ascii characters returned by commands either in stdout or stderr. That's why they were giving the errors that you encounter and the patches above should fix that issue and you should be able to build whatever your locale is (barring another issue that we haven't encountered yet) as long as you use a UTF-8 locale. If you can test the patch above, it might tell us whether I am right or wrong here.

You are also right in principle that the scripts can check for warnings and errors better, but I am not sure how feasible it is to check for every possible warning and error. For clarity, we capture both stderr and stdout [here](https://github.com/chapel-lang/chapel/blob/master/util/chplenv/utils.py#L55-L61), ignore stderr in your case but still decode it.

Another way to look at it is, the patches above should bring us to a point where non-English locales behave the same way as the English locale. But that same behavior might be problematic because of ignoring warnings from the make commands as you point out. But I'd argue that it is less severe given that we are probably able to build Chapel in English locales, and it is a separate issue. I'd also argue that the warning is not a fatal one and that it strengthens my point that is not that severe and shouldn't block you.

**Comment by intractabilis** [comment] 2020-04-14 23:15
> the patches above should fix that

They will hide the real problem. By applying these patches you are fixing a problem by implanting an explosive charge that nobody knows when and how it will go off.

> barring another issue that we haven't encountered yet

How do you know?

> You are also right in principle that the scripts can check for warnings and errors better

I've never said this. I said that you should pass file descriptors to the new instance of `make`. What you do with other warnings is up to you.

> I'd also argue that the warning is not a fatal one and that it strengthens my point that is not that severe and shouldn't block you.

It's not fatal in this particular case. But it can lead to hidden bugs in the future that would be very hard to discover.

I just gave you my opinion based on experience. It's your code and your responsibility. Feel free to ignore my opinion and submit the patches.

**Comment by bradcray** [comment] 2020-04-14 23:28
@intractabilis: The issue you filed was about having `make` fail when run from non-English locales, something that we have not been able to reproduce locally, so have been relying on you to help us debug via the patches we're providing.  If you're not willing to test the patches for us to see whether they address the core issue by permitting you to build and run, that's fine, but please let us know that so we can icebox this issue until someone else can reproduce it.

As I understand it, in looking into the source of the issue, you came across a `make -j` warning that we may very well be getting and ignoring in our builds as well, and that may be an issue worth looking into, but it seems to us like a separate issue (so deserving of a separate GitHub issue if it matters to you rather than holding this one up).

**Comment by intractabilis** [comment] 2020-04-14 23:30
Sure, I'll test your patch and will file another issue.

**Comment by bradcray** [comment] 2020-05-06 20:22
@e-kayrakli: Assuming we believe your patches do no harm (and some good), I propose that we put together a PR to merge them and then close this issue as "cannot reproduce."

**Comment by e-kayrakli** [comment] 2020-05-06 20:29
Sounds good. I'll put a branch together and test. Will also need to check with others who are more knowledgeable with our build system.

**Comment by e-kayrakli** [comment] 2020-05-11 17:50
https://github.com/chapel-lang/chapel/pull/15652 added the patches I put above on master. We can't reproduce the exact error but I believe that build wouldn't get stuck after that PR. There might be something we can do for those warning messages, but it is unclear what to do or how important that is

**Closed by e-kayrakli** 2020-05-11 17:50 UTC
