### ISSUE TITLE
internal compiler error, maybe related to lambda functions?

### ISSUE THREAD

**Issue by lucaferranti** [chapel-lang/chapel#20046] opened 2022-06-19 13:28 UTC
### Summary of Problem

While playing with [ForwardModeAD](https://github.com/lucaferranti/ForwardModeAD), a package I'm writing, I hit the following internal compiler error

```
Skipping registry update since no dependency found in manifest file.
/home/lferrant/ForwardModeAD/example/example1d.chpl:12: internal error: RES-PRE-OLD-2900 chpl version 1.26.0
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

compilation failed for example1d.chpl
```

My lucky guess would be that it has to do with lambda functions, but I'm not sure. Please feel free to change this issue name to be more informative/accurate.

### Steps to Reproduce

**Source Code:**

The code is also available in the `example` folder of the package [here](https://github.com/lucaferranti/ForwardModeAD/blob/main/example/example1d.chpl)

```chapel
use ForwardModeAD;

proc f(x) {
    return x ** 2 + 2 * x + 1;
}


var y = derivative(lambda(x : DualNumber) {return f(x);}, 1.0);
writeln(y);

proc df(x) {
    return derivative(lambda(t : DualNumber) {return f(t);}, x); // this is line 12
}

var z = df(1.0);
```

**Compile command:**

`mason build --example` (also `chpl example/example1d.chpl -M src/` gives the same outcome) 

**Execution command:**

N/A

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.26.0
  built with LLVM version 12.0.0
Copyright 2020-2022 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system
CHPL_AUX_FILESYS: none`
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

- (For Cray systems only) Output of `module list`:

**Comment by bradcray** [comment] 2022-07-07 08:12
@lucaferranti : While cleaning up my inbox, I'm realizing that this issue never got a comment or (as far as I know) even a quick look to see what was going wrong.

@dlongnecke-cray : Could I ask you to take a look at it sometime, given the potential relationship to lambdas?

**Comment by dlongnecke-cray** [comment] 2022-07-07 18:02
I'll take a look.

**Comment by bradcray** [comment] 2022-07-08 03:32
[Irrelevant but:  Yesterday I was surprised to find that we'd never replied to this.  Tonight, while closing up tabs en route to vacation, I found a tab from a few weeks ago in which I'd started replying to this, but never finished.  So our intentions were good even though my follow-through was poor.  Here's what I was writing:]

Hi @lucaferranti : Thanks very much for reporting this, as our preference is never to generate internal errors.  I haven't had the chance to look into this case yet, but wanted to make sure you were aware (if we haven't already discussed it) that Chapel's current support for first-class functions and lambdas is known to be incomplete and problematic in some cases.  It is an area that we are hoping to address in the coming months, where a sketch of our thoughts and plans can be found in the first section of: https://chapel-lang.org/releaseNotes/1.26/06-ongoing.pdf]

**Comment by dlongnecke-cray** [comment] 2022-07-22 00:57
Instantiation is occurring for `df` and the visible functions are not being propagated from the uninstantiated block to the instantiated one. This results in an assertion firing because 0 candidates are found for the second lambda. I don't know if this is a general problem or just due to quirks of lambdas yet.

**Comment by dlongnecke-cray** [comment] 2022-07-22 03:25
I opened: https://github.com/chapel-lang/chapel/pull/20287

**Comment by dlongnecke-cray** [comment] 2022-07-22 17:08
And for posterity, here is a simple reproducer that doesn't even rely on a lambda:

```chapel
proc foo(x) {
  proc bar(n : int) { return n; }
  return bar;
}
foo(8);
```

**Closed** 2022-07-26 17:21 UTC
Labels: type: Bug, area: Compiler, user issue

**Comment by bradcray** [comment] 2022-08-08 18:39
Thanks for picking this up, David, and for reporting it Luca!
