### ISSUE TITLE
errors with --library-fortran and file with dash in name

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#15897] opened 2020-06-19 19:29 UTC
I'm seeing compilation errors with `--library-fortran` where a module name with a `-` in it causes invalid C to be generated: 

```
chpl -o unhandledType-tuple --cc-warnings --library-fortran unhandledType-tuple.chpl 
unhandledType-tuple.chpl:1: In function 'returnsTuple':
unhandledType-tuple.chpl:1: warning: Unknown Fortran KIND generating interface for C type: _ref__tuple_2_star_int64_t_chpl
unhandledType-tuple.chpl:1: warning: Unknown Fortran type generating interface for C type: _ref__tuple_2_star_int64_t_chpl
In file included from /tmp/chpl-mppf-454355.deleteme/_main.c:2:
/tmp/chpl-mppf-454355.deleteme/chpl__header.h:3756:30: error: expected ~~~=~~~, ~~~,~~~, ~~~;~~~, ~~~asm~~~ or ~~~__attribute__~~~ before ~~~-~~~ token
3756 | void chpl__init_unhandledType-tuple(int64_t _ln,
      |                              ^
In file included from /tmp/chpl-mppf-454355.deleteme/_main.c:49:
/tmp/chpl-mppf-454355.deleteme/unhandledType-tuple.c:1:30: error: expected ~~~=~~~, ~~~,~~~, ~~~;~~~, ~~~asm~~~ or ~~~__attribute__~~~ before ~~~-~~~ token
    1 | void chpl__init_unhandledType-tuple(int64_t _l
```

**Comment by lydia-duncan** [comment] 2020-06-19 19:56
Is this a duplicate of #9594?

**Comment by mppf** [comment] 2020-06-19 21:03
Looks like it, thanks for noticing.

**Closed** 2020-06-19 21:04 UTC
Labels: stat: Duplicate
