### ISSUE TITLE
Performance mystery using --no-ieee-float

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#15822] opened 2020-06-12 00:50 UTC
### Summary of Problem
Compiling with `-no-ieee-float` produces *slower* code.

### Steps to Reproduce

**Source Code:**

```chapel
use Random;
import Time.{Timer};

config const Ng=100_000_000;
const Dom = {0.. #Ng};

var x,y : [Dom] real;

fillRandom(x);
fillRandom(y);

var tt : Timer;
tt.clear(); tt.start();
var dot : real = 0.0;
forall ii in Dom with (+ reduce dot) {
  dot += x[ii] * y[ii];
}
tt.stop();

writeln("Time elapsed : ",tt.elapsed());
```
**Compiling and run time**

Compiling this on my laptop as 
```
$ chpl --fast dot1.chpl -o dot1
$ ./dot1 --Ng=300_000_000
Time elapsed : 0.168408
```

Using `--no-ieee-float`, I get 
```
$ chpl --fast --no-ieee-float dot1.chpl -o dot1 
$ ./dot1 --Ng=300_000_000
Time elapsed : 0.361886
```
While `--no-ieee-float` not improving things would not have been surprising, I am a little surprised to see a significant slowdown here.

### Configuration Information
Chapel version 1.22
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu *
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none

**Comment by npadmana** [comment] 2020-06-12 00:51
@bradcray -- as requested.

**Comment by damianmoz** [comment] 2020-06-12 06:04
I must be missing something. Why not write this as just:
```chapel
use Random;
use Time;

config const N = 100000;
const Dom = {0..N};

var x,y : [Dom] real;

fillRandom(x);
fillRandom(y);

{
	const dot = + reduce (x * y);

	writeln("Dot: ", dot);
}
```

Admittedly I am using 1.20 and have simplified it somewhat.

$ chpl --fast t.chpl ; time ./t --N=800000000
Dot: 1.99994e+08
./t --N=800000000  32.84s user 6.92s system 531% cpu 7.480 total
$ chpl --fast --no-ieee-float t.chpl ; time ./t --N=800000000
Dot: 1.99998e+08
./t --N=800000000  32.04s user 6.05s system 570% cpu 6.674 total

Here you do see an improvement.

**Comment by npadmana** [comment] 2020-06-12 10:38
@damianmoz -- the code evolved from a different piece of code, therefore it got written up that way. However, I actually see the same slowdown running the `reduce` form as well.

I'll add that I see an improvement when I run a serial version of the for loop.

**Comment by damianmoz** [comment] 2020-06-12 11:45
I rewrote it as
```chapel
use Random;
use Time;

config const N = 100000;
const Dom = {0..N};

proc main
{
        var x,y : [Dom] real;

        fillRandom(x);
        fillRandom(y);

        writeln(Locales.numPUs());

        Locales.maxTaskPar = 1;

        serial
        {
                const dot = + reduce (x * y);

                writeln("Dot: ", dot);
        }
}
```
When I run this, which thouight would force it to run the reduction as serial, it still uses all 6 cores opn my machine and refuses to run serially.  Very weird.

Note that running, my executable t-ieee, compiled wit --ieee-float,. or my executable t-noieee, compiled with --no-ieee-float, the performance is much the same. Which I would expect.

$ time ./t-ieee --N=800000000
6
Dot: 1.99992e+08
./t-ieee --N=800000000  31.41s user 2.65s system 524% cpu 6.499 total
$ time ./t-noieee --N=800000000
6
Dot: 2.00009e+08
./t-noieee --N=800000000  31.03s user 2.61s system 526% cpu 6.384 total

Why cannot get it to run serially?

**Comment by npadmana** [comment] 2020-06-12 15:57
Hm. I don't know why it isn't running serially.

A few more observations -- 
1. The slow down I'm seeing is machine dependent. I see the slow down on my laptop, but not on a cluster node. The timings appear to be pretty reproducible on a given machine.
2. I see similar slowdowns (on my laptop) when I run either explicitly SIMD vectorized code or what I believe is implicitly vectorized code (calling into MKL BLAS).

So my guess is that this is something particular about running on a laptop. 

I'll leave this open in case anyone has some better ideas/tests, but otherwise fine to close.

**Comment by bradcray** [comment] 2020-06-12 16:23
Depending on the configuration and execution characteristics of the program, the threads Chapel spins up during start-up may busy-wait for more work, so generally reports like top or % cpu shouldn't be trusted as an indicator of whether or not a Chapel program is running serially.  This "Why is my CPU %age so high when my Chapel code is serial?" is such a FAQ'd question that it would be great to have someone post a version of it as a StackOverflow question to get the answer out in a definitive form for general reference.

I would expect the serial block in Damian's code to be doing exactly as expected, though a better (if more verbose) way to write a serial reduction might be `const dot = + reduce (for (xx,yy) in zip(x,y) do (xx * yy));`  Specifically, the `serial` keyword is a bit of a big hammer and has the effect of still creating numCores tasks, but then running them one at a time.  By contrast, a serial for loop will run using one task and be simpler as a result.

**Comment by bradcray** [comment] 2020-06-12 16:25
@npadmana: Given the apparent sensitivity in your results to machine, it might be useful to know the version of gcc and the processor that you're using on each system.

**Comment by npadmana** [comment] 2020-06-12 16:58
> @npadmana: Given the apparent sensitivity in your results to machine, it might be useful to know the version of gcc and the processor that you're using on each system.

@bradcray -- updated my comment above

**Comment by damianmoz** [comment] 2020-06-13 00:20
As regards my code, my serial block did not include the two calls to fillRandom. And hence, that is what consumed the multi-core CPU time. Apologies for my lack of thoroughness and rigour.

Once I fixed this, it all worked as I expected, even with the heavy handed **serial** block. Compiling with **--no-ieee-float** ran slightly faster than **--ieee-float**. There were no inconsistencies across multiple desktop and server systems. I think it points to your laptop.

**Comment by damianmoz** [comment] 2020-06-13 03:09
As regards my code, my serial block did not include the two calls to fillRandom. And hence, that is what consumed the multi-core CPU time. Apologies for my lack of thoroughness and rigour.

Once I fixed this, it all worked as I expected, even with the heavy handed **serial** block. Compiling with **--no-ieee-float** ran slightly faster than **--ieee-float**. There were no inconsistencies across multiple desktop and server systems. I think your performance issues points to your laptop.

With the ability to be able to test ones code in either serial or parallel mode being an invaluable way to diagnose and debug code, I think the intricacies of serial or otherwise should be explained in the reference manual. Also, on my wish list is the ability to be able to take fully parallel code and then recompile it as a purely serial executable directly at the command line. That makes debugging a parallel algorithm sooooo much easier.

**Comment by damianmoz** [comment] 2020-06-13 11:01
My serial block did not include the two calls to fillRandom. And hence, that is what consumed the multi-core CPU time. Apologies for my lack of thoroughness and rigour.

Once I merged this into the serial block, it all worked as I expected, even with the heavy handed **serial** block. Compiling with **--no-ieee-float** ran slightly faster than **--ieee-float**. There were no inconsistencies across multiple desktop and server systems. I think your performance issues points to your laptop.

With the ability to be able to test ones code in either serial or parallel mode being an invaluable way to diagnose and debug code, I think the intricacies of **serial** should be explained in the reference manual or the user guide. Also, on my wish list is the ability to be able to take fully parallel code and then recompile it as a purely serial executable directly at the command line. That makes debugging a parallel algorithm sooooo much easier.

**Comment by bradcray** [comment] 2020-06-16 00:44
@npadmana: I'm going to close this issue (as you expressed openness to above) because I'm worried that the effort to reproduce it is going to be too great, and my sense is that things are behaving as you'd expect on the platforms that matter most.

>  I think the intricacies of serial should be explained in the reference manual or the user guide. 
> on my wish list is the ability to be able to take fully parallel code and then recompile it as a purely serial executable directly at the command line.

@damianmoz: I think these are fine things to request, but would suggest filing new issues for them rather than tacking them onto an unrelated one (particularly since I'm about to close it :) ).

**Closed by bradcray** 2020-06-16 00:44 UTC
