### ISSUE TITLE
`import super.x` can't refer to a member `x`, only module `x`.

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15309] opened 2020-03-24 04:12 UTC
### Summary of Problem

At present, it seems that `import super.x` can't be used to refer to a variable `x` in a parent module, only to a module `x` in that parent module.  This seems like a likely oversight in the implementation (?).

### Steps to Reproduce

**Associated Future Test(s):**
[`test/visibility/import/superDotVar.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/visibility/import/superDotVar.chpl
          ) #15307 
[`test/visibility/import/superDotSuperDotVar.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/visibility/import/superDotSuperDotVar.chpl
          ) #15307

### Configuration Information

- Output of `chpl --version`: `1.21.0 pre-release (52b68d036f)`

**Comment by lydia-duncan** [comment] 2020-04-27 17:29
In looking at the tests we checked in with the change, it seems like this is intended behavior and symmetrical to the behavior for `super` in `use` statements (where the last symbol can't be anything except a module) and the behavior of `this` for imports (where it doesn't make sense to follow `this` with anything other than a module, since you can already access every symbol in scope without the qualifier).  However, I think it would be fair to argue that `super` in `import` statements should do as you are expecting.  I think it would also be fair to enable `import super;` as well, unless the `import` statement is already in a top-level module.  I'd like to hear @mppf's thoughts on this before proceeding, though.

**Comment by mppf** [comment] 2020-04-27 17:31
I think it's reasonable to implement the feature requested in this issue. I don't think it adds confusion particularly - it seems clear enough what `import super.x` would do if x is a variable.

**Comment by lydia-duncan** [comment] 2020-04-28 17:40
Michael brought up the following case in the PR to fix this issue:
```chapel
module M {
  module Mod { ... }
  module SubMod {
     var x: int;
  }
  module User {
    import super.Mod.super.SubMod.x;
    proc main() {
      writeln(x);
    }
  }
}
```
It currently raises `error: Cannot find symbol 'super' in module 'Mod'` on both master and my branch.  I'm okay with it either raising that error (meaning that `super` cannot be used after an actual module name), or allowing it (under the argument that it's vaguely similar to `../Foo/../Bar` in file paths, so potentially could be expected to work) and Michael is similarly ambivalent.  Do you have a preference, Brad?

**Comment by lydia-duncan** [comment] 2020-04-28 17:40
Any change to it would be in a separate PR (and so probably tracked in a separate issue going forward)

**Comment by bradcray** [comment] 2020-04-28 17:45
Not a strong preference.  I haven't felt motivated to use `super` or `this` anywhere other than at the start of a module path and have trouble coming up with a case where it would be necessary / attractive rather than arbitrary, so would probably be inclined to stick with the approach we have.  But I also wouldn't be offended if I found that the example above worked.

Does `import super.super.super.Mod;` work?  That seems arguably more attractive/useful.

**Comment by lydia-duncan** [comment] 2020-04-28 20:01
> Does `import super.super.super.Mod;` work?  That seems arguably more attractive/useful.

Yup!

**Closed** 2020-04-28 20:07 UTC
Labels: area: Compiler, type: Unimplemented Feature
