### ISSUE TITLE
Resolution fails with forwarding to Owned (doubly forward)

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10062] opened 2018-06-27 19:40 UTC
### Summary of Problem
Compiler fails to forward a method call if the `forwarding` is to a field of type Owned.
```
In function 'main':
error: unresolved call 'C.print_data()'
note: candidates are: A.print_data()
note:                 B.print_data()
```
For what it's worth, the same error is reported with `--lifetime-checking` and the relevant changes of `Owned` to `owned`.

### Steps to Reproduce

**Source Code:**

```chapel
module CannotForward {
use OwnedObject;

class A {
  var data = [1, 2, 3];
  proc print_data() { writeln(this.data); }
}

// Works.
class B {
  var data: A;
  proc init() { this.data = new A(); }
  proc deinit() { delete this.data; }
  forwarding data;
}

// Does not work.
class C {
  var data: Owned(A);
  proc init() { this.data = new Owned(new A()); }
  forwarding data;
}

proc main() {
  var b = new B();
  b.print_data();
  delete b;

  var c = new C();
  c.print_data();
  delete c;
}
} 
```

### Configuration Information
`chpl version 1.18.0 pre-release (b0251ba45e)`

**Comment by mppf** [comment] 2018-06-27 19:46
I believe this is a duplicate of  #9601

**Comment by bradcray** [comment] 2018-07-04 18:14
Closing based on the assumption that both @mppf and @BryantLam think this is a duplicate.  If I've got this wrong and it was kept open for a reason, I'm not seeing, please feel free to reopen (and explain why).

**Closed by bradcray** 2018-07-04 18:14 UTC
Labels: area: Compiler, stat: Duplicate, type: Bug, user issue
