### ISSUE TITLE
Easier parallel iterator definitions

### ISSUE THREAD

**Issue by Iainmon** [chapel-lang/chapel#23203] opened 2023-09-04 00:42 UTC
There have been many times where I wanted to define an iterator that would be used in a `forall` loop, but decided not to define it correctly because of the hassle with the leader/follower overloads. I usually end up just condensing the serial iterator into an array then using that in the forall loop:
```chapel
const results = mySerialIter();
forall x in results { ... }
```

If possible, it would be nice if this transformation could be done by default whenever there is no explicit parallel version of the iterator defined. So one could write
```chapel
forall x in mySerialIter() {...}
```

Maybe it would be possible to optimize this so that each parallel task would spawn as the results are `yield`ed, so that `results` is not stored all in memory.

**Comment by bradcray** [comment] 2023-11-18 17:29
I definitely agree with the notion of simplifying the definition of parallel iterators in Chapel to avoid the clunky and difficult-to-remember use of standalone/leader/follower tag arguments, and also to potentially get away from the current approach of relying on an overload set to define a family of iterators.  But, I don't think we should go so far as to make `forall` automatically construct an array of results when no parallel iterator was available for a given expression for the following reasons:

* the space requirements could be arbitrarily large (could run you out of memory, even) and Chapel has been designed to avoid silently introducing large temporary arrays without the user being aware of it.
* the `forall` statement was designed to say "invoke the parallel iterator if it exists; fail otherwise" so that `forall` always implies the parallelism (or at least, the extreme likelihood of it; a given parallel iterator may choose to create no new tasks if it decides they're overkill), so having it automatically result in serial execution under the hood would be confusing.
* the implementation in a distributed memory setting seems like it could be naive

With respect to:
> Maybe it would be possible to optimize this so that each parallel task would spawn as the results are yielded, so that results is not stored all in memory.

This sounds the same as what a `coforall` loop would do, so if this was an acceptable/attractive behavior, I think writing the loop as `coforall x in mySerialIter()` should be used instead.

I also want to note that while the leader/follower iterators can be challenging to write, standalone parallel iterators are much easier to write (even though they still rely on the clunky `tag`-based overload) and should essentially be achievable by putting your two lines:

```chapel
const results = mySerialIter();
forall x in results { ... }
```

into the iterator body if that's the desired implementation approach.

My answer to how we should support making a serial iterator be invokable from a forall loop without writing an explicit parallel iterator would be to wrap it in another iterator, like:

```chapel
forall x in autoParallelize(mySerialIter) { ... }
```

This would probably require some form of first-class iterator support, which we don't have today.

I'm going to close this issue due to my sense that the specifics of the proposal don't fit the language philosophy and due to the  lack of discussion it's generated.  We can of course re-open it in the future if those things change.  It would also be very reasonable to spawn off new issues about simplifying the creation of parallel iterators or supporting one of these other approaches.

**Closed** 2023-11-18 17:30 UTC
