### ISSUE TITLE
Weird error and halt upon `export CHPL_REGEXP=none`

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#18021] opened 2021-07-01 19:12 UTC
Setting `export CHPL_REGEXP=none` without setting `CHPL_RE2` when running the compiler gives me:

```
error: CHPL_HOME=XXX CHPL_RUNTIME_INCL=XXX/runtime/include CHPL_RUNTIME_LIB=XXX/lib CHPL_THIRD_PARTY=XXX/third-party XXX/util/printchplenv --all --internal --no-tidy --simple 2> /dev/null did not run successfully
```

which is understandable, yet undesirable.

My environment is:
```
CHPL_COMM=none
CHPL_DEVELOPER=1
CHPL_GMP=none
CHPL_HOME=XXX
CHPL_LLVM=none
CHPL_MEM=cstdlib
CHPL_REGEXP=none
CHPL_TASKS=fifo
CHPL_VERIFY=1
```

**Comment by mppf** [comment] 2021-07-01 20:18
I've set my environment as you show here and run `make clobber; make` and I'm not seeing an error on a `chpl` compiling Hello World. However I did observe the `make` building re2 in this configuration, which is probably not what is supposed to happen.

**Comment by vasslitvinov** [comment] 2021-07-01 21:12
@mppf's note makes me realize that I :
* built Chapel in a correct configuration, i.e. CHPL_RE2=none, CHPL_REGEXP unset, then
* ran the compiler in this tree in a different shell using the obsolete setting of CHPL_REGEXP

Meaning that this scenario is less likely to happen to users, who are more likely to have consistent environment settings.

**Comment by ronawho** [comment] 2021-07-02 20:48
@PHHargrove ran into something similar in his testing. @vasslitvinov can you give more details on how to reproduce, or what error message you're getting? Commenting out the stderr redirection from https://github.com/chapel-lang/chapel/blob/3216fdc5bc56f996765aa1cf32cce6dc94631939/compiler/util/files.cpp#L563 should give us a more helpful error message.

**Comment by bradcray** [comment] 2021-07-06 21:48
I couldn't reproduce either, even with [Vass's addendum](https://github.com/chapel-lang/chapel/issues/18021#issuecomment-872553240).  I did:

a) `export CHPL_RE2=none`
b) `make`
c) `export -n CHPL_RE2`
d) `export CHPL_REGEXP=none`
e) `chpl test/release/examples/hello.chpl`

and didn't see any errors (just deprecation warnings about `CHPL_REGEXP`.

**Comment by vasslitvinov** [comment] 2021-07-07 04:55
I tried reproducing and have not succeeded yet, however I am going to try again.

If I can't reproduce, should I go ahead and close this issue?

**Comment by bradcray** [comment] 2021-07-07 05:21
I think so.

**Comment by ronawho** [comment] 2021-07-12 22:43
https://github.com/chapel-lang/chapel/pull/18057 updates the compiler to print the underlying error instead of hiding it with `... printchplenv did not run successfully`. I think we should close this since any future errors like this should give the user the underlying error message, which should allow them to debug.

**Comment by bradcray** [comment] 2021-07-12 23:11
Sounds good to me, esp. since we were on the verge of closing it due to not knowing how to reproduce it.  I'll do that now.

**Closed by bradcray** 2021-07-12 23:11 UTC
Labels: type: Error Message
