### ISSUE TITLE
Compiler fails to generate default comparison between records with array fields

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7615] opened 2017-10-19 17:07 UTC
### Summary of Problem
The Chapel compiler generates incorrect code for comparison between
records that have fields that are arrays.

### Steps to Reproduce

**Source Code:**
```chpl
record R {
  var A : [1..5] int;
}

var A, B : R;
writeln(A == B);
```

```
In file included from /path/to/gen/_main.c:43:0:
/path/to/gen/foo.c: In function ‘chpl___EQUALS__2’:
/path/to/gen/foo.c:146:5: error: used struct type value where scalar is required
 if (call_tmp_chpl) {
     ^~~~~~~~~~~~~
gmake: *** [/path/to/gen/foo.tmp] Error 1
error: compiling generated source
```

**Compile command:**
`chpl foo.chpl`

**Associated Future Test(s):**
[types/records/bharshbarger/recordArrCmp.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/records/bharshbarger/recordArrCmp.chpl)
[types/records/bharshbarger/recordDomArrCmp.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/records/bharshbarger/recordDomArrCmp.chpl)

### Configuration Information

All configurations, present since version 1.7

**Comment by bradcray** [comment] 2017-10-19 19:15
At a guess, this looks like an offshoot of the classic "Should array equality return a bool or an array of bools?" question...  Not sure if that issue ever made it onto GitHub from the email conversations where it had taken place before.

**Comment by mppf** [comment] 2018-10-29 15:43
The email conversations are here:

 https://sourceforge.net/p/chapel/mailman/message/31854070/

 https://sourceforge.net/p/chapel/mailman/message/30194494/

**Comment by mppf** [comment] 2018-10-29 15:58
#11487 seems to be a very similar issue (possibly a duplicate of this one).
I created #11490 to discuss what `==` on arrays should be doing.

**Comment by mppf** [comment] 2018-10-29 16:06
Potential solutions:
 * change `A == B` on arrays to return just a `bool`
 * provide `x.equals(y)` on all types and call it from default `==`
 * provide a function to "normalize" the result of `A == B` when it is called on fields in records. This function can be internal and just returns a `bool`. If given an array, it would `&& reduce` but if given a bool it would just return it. If we were to make this function user-facing, it could be named `all()`. Note that this strategy would have to be different for other comparison operators - `!=` would need to use `any()` to "normalize" it - and `<` would need a totally different approach if it is to support lexicographic comparison.

**Comment by mppf** [comment] 2018-10-29 16:09
My current viewpoint is that we should:
 1. Use `<==>` or `<=>` for a generalized comparison operator (see #8545)
 2. Implement the generalized comparison operator by default on records (see #11347)
 3. Make the generalized comparison operator return a single `bool` for arrays
 4. As a result, `==` on arrays would return a single bool.

**Comment by bradcray** [comment] 2018-10-31 23:02
For a short-term fix, and because it seems like it's conceptually simple (few code changes, no language changes), I'd be inclined to pursue:

> provide x.equals(y) on all types and call it from default ==

And then continue to discuss the questions of a generalized comparison operator / what == should do for arrays on their respective issues.

**Comment by benharsh** [comment] 2018-11-01 17:37
By "provide x.equals(y) on all types and call it from default ==" are either of you proposing that users now implement the ``==`` operator with an ``equals`` method?

**Comment by mppf** [comment] 2018-11-01 18:57
@benharsh - as long as `==` for their type returns `bool`, I'd expect the default `.equals` that calls `==` to be sufficient. If users were writing `==` for a generic record or class and it could possibly contain array fields, then they would need to call `.equals` on the fields or handle arrays in a separate function/overload.

**Comment by bradcray** [comment] 2018-11-02 16:13
I was imagining a equals on arrays that "did the right thing" and then a completely generic catch-all equals that would call `==` for all other cases.  I'm realizing belatedly, though, that making a completely generic `==` call for all other cases isn't easy if we take the method-based syntax, which makes my "few code changes" statement incorrect.  Would we want to have a standalone `equals(x, y)` function in the standard namespace?  (in which case I think it's back to being easy again).

Alternatively, the compiler could just generate an appropriate "all equal" reduction for array fields in records without going down the equals path, which doesn't seem too bad either.

As I've been thinking more about equality on arrays this week, I've been wondering whether there are users / use cases who would want `==` (or `equals`) to also say things about (a) the arrays' index sets being identical, (b) the arrays' index sets being identical and distributed identically, (c) the arrays' sharing the same domain.  This continues to add to my sense that defining a default `==` on arrays is fraught.

**Comment by bradcray** [comment] 2020-12-07 19:37
I've got the quick fix for this sketched above implemented.  Testing now.

**Closed** 2021-05-21 01:02 UTC
Labels: area: Compiler, type: Bug
