### ISSUE TITLE
Bigint remote assignment remote value forwarding issue

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#21889] opened 2023-03-15 14:02 UTC
## Reproducer 

```chpl
use CTypes;
use BigInteger;

config const alwaysFalse = false;

proc main() {
  var val1: bigint = 2;
  var val2: bigint = 3;

  on Locales[1] {
    val1 = val2;
  }

  if alwaysFalse {
    var other: bigint;
    var tmp = c_ptrTo(other);
    tmp.deref() = val1; // comment out and code no longer crashes
  }
}
```

Running with checks enabled results in `error: references to remote data cannot be passed to external routines like 'mpz_set'`

In this code, the assignment is done `on Locales[1]`, while the data for the bigints lives on locale 0. In the bigint assignment, another on statement is run to return to locale 0 to do the actual assignment https://github.com/chapel-lang/chapel/blob/fd6086eff89ae5888577a7a529c0ef8a9d4bee25/modules/standard/BigInteger.chpl#L653-L676.

Without the `deref()` call, remote value forwarding will trigger on both `on` statements, so the record is copied to locale 1 first, then copied back to locale 0, so the locality of the data is still kept in tact.

When the `.deref()` call is added, the record is only remote value forwarded in the first `on` statement, and then a wide pointer is created for the second on statement, meaning that the pointer for that record is stored on locale 1, while the data is stored on locale 0 and accessing that field, expecting it to be on locale 0, as it should be, results in a remote access and a crash.

## Notes

Adding `pragma "always RVF"` causes this particular crash to go away, but I am not sure that we want to be forwarding the bigint record in all cases.

I believe this could happen with any record that has a non-trivial-copyable extern field and is not exclusive to the bigint record.

The `deref()` call adds a `PRIM_ARRAY_GET` to the token during codegen that I believe is what is affecting the behavior of widening vs RVFing.

**Comment by ronawho** [comment] 2023-03-16 13:49
Might be a duplicate of https://github.com/Cray/chapel-private/issues/2651

**Comment by bradcray** [comment] 2023-03-20 18:32
@bmcdonald3 : Should this be a user issue since https://github.com/Cray/chapel-private/issues/4521 was?

**Closed** 2023-03-30 18:08 UTC

**Comment by bradcray** [comment] 2023-04-22 01:06
@bmcdonald3 : Please feel encouraged to apply the user issue label in such cases when opening them in the future (i.e., I don't need (or want) to be the person to do so).
