### ISSUE TITLE
Internal Error when using nested procedures that both make queries of their arguments

### ISSUE THREAD

**Issue by damianmoz** [chapel-lang/chapel#23079] opened 2023-08-24 23:35 UTC
Nested procedures with argument type queries result in an internal error:

```chapel
proc foo(x: int(?w)) {  // changing to 'int' works  OR
  proc bar(x: ?T) {   	// removing '?T' works  OR
    return x;           // moving this procedure to the module scope works
  }

  bar(x);
}

foo(42);
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.32.0 pre-release (68cbd398e2)`

**Comment by bradcray** [comment] 2023-08-25 00:35
Just in case you're online, @damianmoz : As I build a version of 1.29.0, is the above all that's required to reproduce the error, or does it require a call of some form to the routine as well?

**Comment by damianmoz** [comment] 2023-08-25 00:48
Thanks for the reply. There must be some interest. Don't waste you time with 1.29. If my problem has gone away with the latest release, you can close this.

Why do I always have problems with attachment. The attachment operation not show any of the files in my directory that have a .chpl extension.  Change to .txt. That works.

Let me know my comments about how to reproduce the problem make sense.

I did
```
 chpl --ieee-float --fast cproj.chpl
cproj.chpl:92: internal error: AST-EXP-0312 chpl version 1.29.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```
Same happens without any options.

Here is the file but with a `.txt` extension (hope it is useful):
[cproj.txt](https://github.com/chapel-lang/chapel/files/12434432/cproj.txt)

**Comment by bradcray** [comment] 2023-08-25 01:05
OK, thanks.  With that complete example, I can reproduce on 1.29.0 and `main`, so it's a problem that still exists.  Looking at the source, it's not obvious to me what the problem is—this looks like a pattern we rely on everywhere ourselves.  Taking a quick look to see if the fix is easy.

**Comment by bradcray** [comment] 2023-08-25 01:22
Aha, it's a combination of:
* the formal argument type query
* the procedure being a nested procedure that also uses a formal argument type query

So, another workaround is to move the nested procedure to the module-scope (optionally marking it private if it's not intended for use outside the module; of course, in your code, this would also require threading the `propagate_NaNs` through the argument list since you couldn't rely on scoping to resolve it).

But I think the workaround you found is better.

Thanks for reporting this.  I'm going to update the OP and title to reflect what I've found.

**Comment by bradcray** [comment] 2023-08-25 01:25
(BTW, I assume that since you found a workaround, this is not blocking you, but let me know if that's not the case)

**Comment by damianmoz** [comment] 2023-08-25 01:45
One of the huge programming advantages of Chapel is that it properly supports true nested functions that can use variables in the scope of the function within which those nested functions are defined. This is a concept that sadly too many languages never had for lots of reasons. 

I am happy for you to change the title. As I did not really know what the problem was, it was a bit hard to provide the optimal name. OK, so a type query in an argument list is a **formal** query. What do you call the way I did it my workaround?  An **informal** query or an **explicit** query?

It did not stop me at the time (which was ages ago). I was just documenting the loose ends of that old work and realized I had forgotten to post this.

I did not have that _propagate_NaNs variable in my original code because I always do the propagation unlike some C library routines. So, if someone else was reading and testing it, I inserted that extra logic to ensure that I made my routine almost compatible with what is in the C library (and currently in Chapel).

If you want to close this now that I know what the cause is and that somebody might fix it, go for it.

My guess is that the problem is one of those really fundamental, easy to fix but difficult to find, animals.

**Comment by bradcray** [comment] 2023-08-25 04:01
Oh, sorry, not "formal" in that sense, but in the sense that it's a query of the formal argument.  "formal argument with a type query" is how I'd describe `t: ?T`.  I think "explicit type query" or "type alias created from a type query" is how I'd describe your workaround.

I'd like for us to keep this open until we close it.  It may not be too difficult to find given how small the reproducer ended up being.  It looks to me as though someone is failing to insert something into the right scope, or something like that.

**Comment by damianmoz** [comment] 2023-08-25 04:29
I can do the workaround even more simply and reduce the lines of code by one line if I move the definition of `zero` into the routine `proj` which is outside the scope of where it is needed but still visible to it which means I never need to query the type of the argument and that `zero` is still available to the internal **proc** signedzero. But that is bad form which I try and avoid.

**Comment by jabraham17** [comment] 2024-02-06 21:34
This issue was resolved by https://github.com/chapel-lang/chapel/pull/23798. That PR added a similar test to this, but I also opened #24349 to add this specific case to our tests. Merging that PR will close this issue

**Closed** 2024-02-06 22:00 UTC
Labels: type: Bug, area: Compiler, user issue
