### ISSUE TITLE
man pages not building with Python 2.7.13 on Ubuntu

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8750] opened 2018-03-08 23:34 UTC
No surprise, but it's another victim of python dependencies, like the `make test-venv` issue.

```
> make chpldoc
...
cd compiler && make chpldoc
rm -f /home/buddha314/chapel/bin/linux64/chpldoc
ln -s chpl /home/buddha314/chapel/bin/linux64/chpldoc
cd man && make chpldoc
mkdir -p man1
sed "/confchpldoc.rst/r confchpldoc.rst" chpldoc.rst > chpldoc.rst.tmp
/home/buddha314/chapel/third-party/chpl-venv/install/linux64/py2.7/chpl-virtualenv/bin/rst2man.py chpldoc.rst.tmp > man1/chpldoc.1
Traceback (most recent call last):
  File "/home/buddha314/chapel/third-party/chpl-venv/install/linux64/py2.7/chpl-virtualenv/bin/rst2man.py", line 24, in <module>
    from docutils.core import publish_cmdline, default_description
ImportError: No module named 'docutils'
Makefile:31: recipe for target 'man1/chpldoc.1' failed
make[2]: *** [man1/chpldoc.1] Error 1
Makefile.devel:34: recipe for target 'man-chpldoc' failed
make[1]: *** [man-chpldoc] Error 2

buddha314@notes:~/chapel$ python --version
Python 2.7.13
```

**Comment by buddha314** [comment] 2018-03-08 23:58
Looks like an issue for Python 2.7 as well.  This surprised me

```
> make chpldoc
...
cd compiler && make chpldoc
rm -f /home/buddha314/chapel/bin/linux64/chpldoc
ln -s chpl /home/buddha314/chapel/bin/linux64/chpldoc
cd man && make chpldoc
mkdir -p man1
sed "/confchpldoc.rst/r confchpldoc.rst" chpldoc.rst > chpldoc.rst.tmp
/home/buddha314/chapel/third-party/chpl-venv/install/linux64/py2.7/chpl-virtualenv/bin/rst2man.py chpldoc.rst.tmp > man1/chpldoc.1
Traceback (most recent call last):
  File "/home/buddha314/chapel/third-party/chpl-venv/install/linux64/py2.7/chpl-virtualenv/bin/rst2man.py", line 24, in <module>
    from docutils.core import publish_cmdline, default_description
ImportError: No module named 'docutils'
Makefile:31: recipe for target 'man1/chpldoc.1' failed
make[2]: *** [man1/chpldoc.1] Error 1
Makefile.devel:34: recipe for target 'man-chpldoc' failed
make[1]: *** [man-chpldoc] Error 2

buddha314@notes:~/chapel$ python --version
Python 2.7.13
```

**Comment by ben-albrecht** [comment] 2018-03-09 16:09
We test `python3` nightly, but only for `make && make check`. Perhaps that should be extended to include `make chpldoc`. Note, `make test-venv` is *not* currently expected to work with `python3` since it is a developer feature.

The `python 2.7.13` failure on building the man pages is surprising. We testing on `python 2.7` nightly. I suspect something else about your build environment is impacting this failure. Did you try to `make clobber` and rebuild?

If that does not work, can you provide some more information so that we may try to reproduce the failure? e.g.

- OS & version
- `python --version` for the python 3 case
- error output for the python 3 case
- `chpl --version`

Thanks for reporting!

**Comment by buddha314** [comment] 2018-03-09 16:55
Yes, this was after `make clobber; make all` on an Ubuntu machine.

Here is the Python 3 example on OS X

```
macbuddha:chapel buddha$ python --version
Python 3.6.4
macbuddha:chapel buddha$ printchplenv 
machine info: Darwin macbuddha.lan 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
CHPL_HOME: /Users/buddha/github/chapel *
script location: /Users/buddha/github/chapel/util
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
macbuddha:chapel buddha$ chpl --version
chpl version 1.17.0 pre-release (8cbb52db9c)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)
macbuddha:chapel buddha$ make chpldoc
cd compiler && /Applications/Xcode.app/Contents/Developer/usr/bin/make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/buddha/github/chapel/third-party/llvm none
make[2]: Nothing to be done for `none'.
***** adt/ *****
***** AST/ *****
***** backend/ *****
***** codegen/ *****
***** ifa/ *****
***** ipe/ *****
***** main/ *****
***** optimizations/ *****
***** parser/ *****
***** passes/ *****
***** resolution/ *****
***** util/ *****
***** ./ *****
cd chpl-venv && /Applications/Xcode.app/Contents/Developer/usr/bin/make chpldoc-venv
export PYTHONPATH=/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6:$PYTHONPATH && \
	/usr/local/bin/easy_install --install-dir=/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6 virtualenv==12.0.5
Searching for virtualenv==12.0.5
Best match: virtualenv 12.0.5
Processing virtualenv-12.0.5-py3.6.egg
virtualenv 12.0.5 is already the active version in easy-install.pth
Installing virtualenv script to /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6
Installing virtualenv-3.4 script to /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6

Using /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg
Processing dependencies for virtualenv==12.0.5
Finished processing dependencies for virtualenv==12.0.5
install/darwin/py3.6/virtualenv --python=/usr/local/bin/python /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv
Running virtualenv with interpreter /usr/local/bin/python
Using base prefix '/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv/bin/python3.6
Not overwriting existing python script /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv/bin/python (you must use /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv/bin/python3.6)
Installing setuptools, pip...
  Complete output from command /Users/buddha/github...ualenv/bin/python3.6 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/utils/__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 1649, in <module>
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv.py", line 2352, in <module>
    main()
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/buddha/github...ualenv/bin/python3.6 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
make[2]: *** [/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv] Error 1
make[1]: *** [/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv/bin/sphinx-build] Error 2
make: [third-party-chpldoc-venv] Error 2 (ignored)
cd compiler && /Applications/Xcode.app/Contents/Developer/usr/bin/make chpldoc
make[1]: Nothing to be done for `chpldoc'.
cd man && /Applications/Xcode.app/Contents/Developer/usr/bin/make chpldoc
make[2]: Nothing to be done for `chpldoc'.
macbuddha:chapel buddha$ 
```

I'm sorry I couldn't make this longer.

**Comment by ben-albrecht** [comment] 2018-03-09 20:28
I think this is now a duplicate with #8756, which subsumes the python 3 component of this issue. I'll keep this open until the python 2.7.13 issue is resolved, however.

**Comment by ben-albrecht** [comment] 2018-03-09 23:10
Only interested in the Python 2.7 failure for this issue now:

> I'm sorry I couldn't make this longer.

Here's your chance:

- What version of Ubuntu are you using?
- What is the `chpl --version` output on the Ubuntu machine?
- Can you try just: `make clobber && make chpldoc` on the Ubuntu (Python 2.7) machine?

**Comment by ben-albrecht** [comment] 2018-03-09 23:22
> The make chpldoc built on the Ubuntu machine

Wait, so is the Python 2.7.13 error resolved? The original error was `make chpldoc` failing on the man page build (I pasted that output into the issue description).

**Comment by buddha314** [comment] 2018-03-09 23:24
It's chaos, I know.  But it failed twice yesterday.  I'm wondering if this isn't being hidden by an incomplete `make clobber` where the build can fail but the old binary is around.  THat's what happened with mason on my local machine.  I will test that

**Comment by ben-albrecht** [comment] 2018-03-09 23:28
An outdated virtualenv would be the most plausible explanation. If you can confirm that it's now building consistently, let's close this issue. We can reopen if you hit this in the future, and maybe try to carefully document the cause to help others who might stumble upon it in the future.

**Comment by buddha314** [comment] 2018-03-09 23:42
Well, I guess it can be closed.  I'm trying to build chapel things on multiple environments with shifting python versions and dependencies...

**Comment by ben-albrecht** [comment] 2018-03-09 23:44
> I'm trying to build chapel things on multiple environments with shifting python versions and dependencies...

Ah, then the cause of the issue has been identified.

**Closed by ben-albrecht** 2018-03-09 23:44 UTC
Labels: area: Tools, type: Portability, user issue
