### ISSUE TITLE
Resolution failure for function with if-expr as default value for an argument

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#8189] opened 2018-01-12 22:51 UTC
### Summary of Problem
The compiler fails to resolve a function that uses an if-expr for a default-value of an argument. The if-expr in this case depends on a param bool argument.

The example below is of an initializer that encounters this problem, but normal methods and functions are also impacted.

### Steps to Reproduce

**Source Code:**

```chapel
record Foo {
  param stridable:bool;
  var _stride;

  proc init(param stridable:bool = false,
            _stride = if stridable then 1 else _void) {
    this.stridable = stridable;
    this._stride = _stride;
    super.init();
  }
}

proc main() {
  var f = new Foo();
}
```

**Compile command:**
```
> chpl foo.chpl
foo.chpl:5: In initializer:
foo.chpl:6: error: unresolved call '_if_fn126()'
```

**Associated Future Test(s):**
[`test/classes/lydia/defaultArgumentIsConditional.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/lydia/defaultArgumentIsConditional.chpl) #8206
[`test/classes/lydia/defaultArgumentIsConditional-field.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/lydia/defaultArgumentIsConditional-global.chpl) #8222
[`test/classes/lydia/defaultArgumentIsConditional-global.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/lydia/defaultArgumentIsConditional-field.chpl) #8222
[`test/functions/lydia/defaultArgumentIsConditional.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/functions/lydia/defaultArgumentIsConditional.chpl) #8206
[`test/functions/lydia/defaultArgumentIsConditional-global.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/functions/lydia/defaultArgumentIsConditional-field.chpl) #8222

### Configuration Information
chpl Version 1.17.0 pre-release (fe20d15)

Programs failing under ``--force-initializers``:
- classes/deitz/class/conditional_init_expr
- classes/marybeth/test-init
- parallel/taskPar/sungeun/private
- release/examples/primers/voidVariables
- studies/ssca2/rachels/SSCA2_test (x5)

**Comment by lydia-duncan** [comment] 2018-01-16 17:04
Never mind, not specific to classes and records.  Just impacts every function.

**Comment by lydia-duncan** [comment] 2018-01-17 18:38
Interesting thing to note - the following program does not encounter this error:
```chapel
proc foo(x: int, y: int = if x < 0 then -1 else 1) {
  writeln(x, y);
}

foo(2);
foo(-2);
```
But removing the type of the `y` argument causes it to encounter the error:
```chapel
proc foo(x: int, y = if x < 0 then -1 else 1) {
  writeln(x, y);
}

foo(2);
foo(-2);
```
This implies that the issue is with the resolution of the argument's type, which is inferred from the default expression when one is not specifically declared.

**Comment by lydia-duncan** [comment] 2018-01-17 18:40
I had opened a PR to generate a warning for using conditional expressions as the default value for an argument (#8222) since it seemed like the fix for this would be different than that for default initializers, but now I'm uncertain if that is the right choice considering it works in some places.  I'll probably bring this up to the rest of the team as well, but what are your thoughts, @benharsh?

**Comment by benharsh** [comment] 2018-01-17 18:53
Yeah, I think it's worth mentioning to the rest of the team.

**Closed** 2018-05-31 19:54 UTC
Labels: area: Compiler, type: Bug
