### ISSUE TITLE
Errors thrown in parallel loop occasionally result in `SIGSEGV(11)/SIGBUS(10)`

### ISSUE THREAD

**Issue by pierce314159** [chapel-lang/chapel#23648] opened 2023-10-13 19:23 UTC
There is a very high probability that I'm doing something wrong here, but @bmcdonald3 asked me to put up an issue for this to avoid it falling off his radar after the weekend

### Summary of Problem

While working https://github.com/Bears-R-Us/arkouda/issues/2804 (reading a csv file with missing values into arkouda), I was seeing issues of errors being thrown inside a parallel loop losing error class/message information and occasionally resulting in server crashes

When running the reproducer from the Bears-R-Us issue with `CHPL_COMM=None`, I saw the following error message:
```python
RuntimeError: 2 errors: IllegalArgumentError: bad cast from empty string to int(64) ... IllegalArgumentError: bad cast from empty string to int(64)
```
Which makes sense because missing values in an int column are interpreted as the empty string which results in a bad cast when `"":int` gets called. 

However when running in multi-locale, I see the following error message:
```python
RuntimeError: 0 errors:
```
And this would sometimes result in a server crash with one of the following signals: `SIGSEGV(11)/SIGBUS(10)`. This seems to be due to the error being thrown inside of a parallel loop. This sometimes results in a fatal signal even with the `CHPL_DEVELOPER`, `ARKOUDA_DEVELOPER`, and `ARKOUDA_RUNTIME_CHECKS` env variable all set

This is not a blocking issue, I was able to use a boolean variable `hadError` and add a `with ( | reduce hadError)` to throw the error after the parallel completed. I just need to clean up my feature branch but expect to have a PR fixing this for us up by the end of today

### Steps to Reproduce

**Source Code:**
I'll be using arkouda code for the reproducer but the relevant chunk of chapel code can be found [here](https://github.com/Bears-R-Us/arkouda/blob/f3f1de8930a536fbb8b40d1538a14a16aab0856b/src/CSVMsg.chpl#L326-L373). If necessary, I can try to put together an easier reproducer only using chpl code. And obviously feel free to ping me for more information :)
```python
>>> import arkouda as ak
    _         _                   _
   / \   _ __| | _____  _   _  __| | __ _
  / _ \ | '__| |/ / _ \| | | |/ _` |/ _` |
 / ___ \| |  |   < (_) | |_| | (_| | (_| |
/_/   \_\_|  |_|\_\___/ \__,_|\__,_|\__,_|


Client Version: v2023.10.06
>>> ak.connect()
connected to arkouda server tcp://*:5555

# this line might need to be run multiple times to see one of program error signals
>>> ak.read_csv("empty_test.csv")
```

**Execution command:**

```
./arkouda_server -nl 2
...
*** Caught a fatal signal (proc 0): SIGSEGV(11)
*** NOTICE (proc 0): Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace.
*** NOTICE (proc 0): We recommend linking the debug version of GASNet to assist you in resolving this application issue.
```

`empty_test.csv` looks like this:
```
**HEADER**
int64,int64,int64,int64,int64
*/HEADER/*
vertex,name,born,brand,model
34,0,1990,,
69,1,1975,,
89,,,2,4
89,,,3,5
```

### Configuration Information

- my chapel arkouda related env variables: 
```
env | grep -E 'CHPL|ARK'

CHPL_HOME=/Users/pierce/opt/chapel-1.32.0
CHPL_LLVM=system
CHPL_GMP=system
CHPL_TARGET_CPU=native
CHPL_COMM=gasnet
CHPL_HOST_MEM=jemalloc
ARKOUDA_SKIP_CHECK_DEPS=True
CHPL_RE2=bundled
CHPL_GASNET_CFG_OPTIONS=--disable-ibv
CHPL_TEST_TIMEOUT=500
CHPL_RT_OVERSUBSCRIBED=yes
CHPL_DEVELOPER=true
ARKOUDA_DEVELOPER=true
ARKOUDA_RUNTIME_CHECKS=true
```
- Output of `chpl --version`:
```
chpl version 1.32.0
  built with LLVM version 15.0.7
  available LLVM targets: xcore, x86-64, x86, wasm64, wasm32, ve, systemz, sparcel, sparcv9, sparc, riscv64, riscv32, ppc64le, ppc64, ppc32le, ppc32, nvptx64, nvptx, msp430, mips64el, mips64, mipsel, mips, lanai, hexagon, bpfeb, bpfel, bpf, avr, thumbeb, thumb, armeb, arm, amdgcn, r600, aarch64_32, aarch64_be, aarch64, arm64_32, arm64
Copyright 2020-2023 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: system *
CHPL_HWLOC: bundled
CHPL_RE2: bundled *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
$ gcc --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin23.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin23.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by bradcray** [comment] 2023-11-18 16:37
@pierce314159 : I need to apologize, this issue arrived at a busy time and simply slipped between the cracks.  Can you let me know if it's a blocking issue for you?

@bmcdonald3 : Have you happened to have a chance to look into this issue at all?

**Comment by pierce314159** [comment] 2023-11-18 20:13
@bradcray no worries! Nope this issue is non-blocking

I was able to workaround it by identifying the condition causing the error (an illegal cast from string to int when values are missing) and setting a boolean variable `hadError` to true in the loop iterations that would result in the bad cast. So after adding a `with ( | reduce hadError)` to the parallel loop, I can throw the error after the parallel loop completed

**Comment by bmcdonald3** [comment] 2023-11-20 16:01
@bradcray no, I haven't looked into this yet, can give it a shot today.

**Comment by bradcray** [comment] 2023-11-20 16:04
Maybe not necessary since Pierce described it as non-blocking... I was just curious.

**Comment by bmcdonald3** [comment] 2023-11-20 17:11
This crash is coming from this block of code in CSVmsg:
```chpl
                            forall x in intersection {
                                var row = lines[x-offsets[file_idx]+data_offset].split(col_delim);
                                A[x] = row[colidx]: t;
                            }
```
Where the cast is calling Chapel's string casting with `row[colidx]: t`, which appears to be causing the issue.

When switching to a `for` instead of a `forall`, I am unable to reproduce the crash (but can consistently when it's a `forall`).

In the casting code, we are doing something like this:
```chpl
...
var localX = x.localize();
...
retVal = c_string_to_int64_t(localX.c_str(), isErr);
...
```

So, I believe we are passing something we shouldn't be to these extern functions and that is causing the issue, but still speculation at this point.

**Comment by bmcdonald3** [comment] 2023-11-22 18:53
The issue here seems to be unrelated to the string casting problem, I think it is actually throwing a `TaskErrors` from within a `coforall`. I've opened up https://github.com/chapel-lang/chapel/issues/23905 to capture that.

**Comment by bradcray** [comment] 2023-11-27 17:58
Potentially related issues (both using throws within foralls, I believe):  

* https://github.com/chapel-lang/chapel/issues/21058
* https://github.com/chapel-lang/chapel/issues/18742

**Comment by bradcray** [comment] 2023-12-11 18:29
@vasslitvinov / @bmcdonald3 : Was this issue resolved by https://github.com/chapel-lang/chapel/pull/23992 or does more remain here?

**Comment by bmcdonald3** [comment] 2023-12-11 19:17
I confirmed that this was resolved, closing now.

**Closed by bmcdonald3** 2023-12-11 19:17 UTC
Labels: user issue
