### ISSUE TITLE
Compile error using `dot` on slices of 3D arrays

### ISSUE THREAD

**Issue by redhatturtle** [chapel-lang/chapel#23634] opened 2023-10-12 08:12 UTC
### Summary of Problem
Calling the `dot` proc from the **LinearAlgebra module** to multiply slices of matrices of dimension higher than 2  will cause a compile error when not using the BLAS version of the proc.
Can't find any workaround other than manually coding the matrix multiplication. Which for me is fine since these are small enough matrices, and this is sometimes also faster.

I took a short look at the module and couldn't figure out why `hasNonStridedIndices(Adom: domain(2))` matched the call.

Should be easy to reproduce but he's my trace
```
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:1067: In function '_matmatMult':
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:1079: error: unresolved call 'hasNonStridedIndices(ArrayViewRankChangeDom(2,int(64),one,3*bool,3*int(64),int(64),unmanaged ArrayViewRankChangeDist(unmanaged DefaultDist,3*bool,3*int(64))))'
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:1154: note: this candidate did not match: private hasNonStridedIndices(Adom: domain(2))
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:1079: note: because actual argument #1 with type 'ArrayViewRankChangeDom(2,int(64),one,3*bool,3*int(64),int(64),unmanaged ArrayViewRankChangeDist(unmanaged DefaultDist,3*bool,3*int(64)))'
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:1154: note: is passed to formal 'Adom: domain(2,int(64),one)'
  $CHPL_HOME/modules/packages/LinearAlgebra.chpl:894: called as _matmatMult(A: [ArrayViewRankChangeDom(2,int(64),one,3*bool,3*int(64),int(64),unmanaged ArrayViewRankChangeDist(unmanaged DefaultDist,3*bool,3*int(64)))] real(64), B: [ArrayViewRankChangeDom(2,int(64),one,3*bool,3*int(64),int(64),unmanaged ArrayViewRankChangeDist(unmanaged DefaultDist,3*bool,3*int(64)))] real(64)) from function 'matMult'
  $CHPL_HOME/modules/packages/LinearAlgebra.chpl:850: called as matMult(A: [ArrayViewRankChangeDom(2,int(64),one,3*bool,3*int(64),int(64),unmanaged ArrayViewRankChangeDist(unmanaged DefaultDist,3*bool,3*int(64)))] real(64), B: [ArrayViewRankChangeDom(2,int(64),one,3*bool,3*int(64),int(64),unmanaged ArrayViewRankChangeDist(unmanaged DefaultDist,3*bool,3*int(64)))] real(64)) from function 'dot'
  test.chpl:9: called as dot(A: [ArrayViewRankChangeDom(2,int(64),one,3*bool,3*int(64),int(64),unmanaged ArrayViewRankChangeDist(unmanaged DefaultDist,3*bool,3*int(64)))] real(64), B: [ArrayViewRankChangeDom(2,int(64),one,3*bool,3*int(64),int(64),unmanaged ArrayViewRankChangeDist(unmanaged DefaultDist,3*bool,3*int(64)))] real(64))
note: generic instantiations are underlined in the above callstack
```

### Steps to Reproduce

**Source Code:**

```chapel
use LinearAlgebra;

var matA : [1..3, 1..3, 1..3] real;
var matB : [1..3, 1..3, 1..3] real;

writeln(dot(matA[1, .., ..], matB[1, .., ..]));
```

Using temporary variables/constants wont work either, it produces the same compile error.
```chapel
use LinearAlgebra;

var matA : [1..3, 1..3, 1..3] real;
var matB : [1..3, 1..3, 1..3] real;

const matC = matA[1, .., ..];
const matD = matB[1, .., ..];

writeln(dot(matC, matD));
```

**Compile command:**
`chpl  --set blasImpl=off --set lapackImpl=off test.chpl`

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.32.0
  built with LLVM version 15.0.7
  available LLVM targets: amdgcn, r600, nvptx64, nvptx, aarch64_32, aarch64_be, aarch64, arm64_32, arm64, x86-64, x86
Copyright 2020-2023 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native +
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none +
CHPL_TASKS: qthreads
CHPL_LAUNCHER: smp +
CHPL_TIMERS: generic +
CHPL_UNWIND: bundled +
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib +
CHPL_GMP: bundled +
CHPL_HWLOC: bundled +
CHPL_RE2: bundled +
CHPL_LLVM: bundled +
CHPL_AUX_FILESYS: none +
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (SUSE Linux) 13.2.1 20230912 [revision b96e66fd4ef3e36983969fb8cdd1956f551a074b]
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Guillaume-Helbecque** [comment] 2023-10-17 09:32
Hello, I'm not a Chapel expert but I think I could help you to workaround this issue.

In my understanding, `dot` calls the private `_matmatMult` method, itself calling `hasNonStridedIndices(Adom)`. The compiler error you get is due to a mismatch in `hasNonStridedIndices` argument (`Adom`). It must be a `domain(2)`, but `matA[1, .., ..].domain.type` is an `ArrayViewRankChangeDom` (due to an internal conversion I guess).

One workaround that could help you is to use temporary variables/constants and explicitly specify their domain (otherwise it is assigned to `ArrayViewRankChangeDom` also):
```chapel 
use LinearAlgebra;

var matA : [1..3, 1..3, 1..3] real;
var matB : [1..3, 1..3, 1..3] real;

const matC : [1..3, 1..3] real = matA[1, .., ..];
const matD : [1..3, 1..3] real = matB[1, .., ..];

writeln(dot(matC, matD));
```
**Note for potential fix:** One solution could be to check the type of `Adom` in `hasNonStridedIndices`, and if not `domain(2)`, perform the explicit cast `ArrayViewRankChangeDom:domain(2)`.

**Closed** 2023-10-31 21:49 UTC
Labels: type: Bug, area: Libraries / Modules, user issue

**Comment by bradcray** [comment] 2023-11-01 16:52
@redhatturtle : Just noting that this has now been merged.  Thanks again for reporting it, and please let me know if it does not resolve the original problem in your own code (rather than just this reproducer).
