### ISSUE TITLE
`make clean` doesn't clean the GMP build

### ISSUE THREAD

**Issue by russel** [chapel-lang/chapel#8144] opened 2018-01-06 10:23 UTC
After a `make clean` then with a `make -j 4` I see in the build output:

make -C /home/users/russel/BuildArea/Chapel/third-party gmp
make[3]: Nothing to be done for 'gmp'.

which seems to indicate the GMP build is not cleaned.

### Configuration Information

- Output of `chpl --version`:
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
- (For Cray systems only) Output of `module list`:

Debian Sid using Chapel b5f488253dc2e0c3176680116daca22b4ab2faff

|> chpl --version
chpl Version 1.17.0 pre-release (b5f488253d)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

|> $CHPL_HOME/util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp *
CHPL_HWLOC: none
CHPL_REGEXP: none *
CHPL_AUX_FILESYS: none

|> gcc --version
gcc (Debian 7.2.0-18) 7.2.0

**Comment by bradcray** [comment] 2018-01-06 16:46
Hi @russel --

Try a `make clobber` rather than `make clean`.  In Chapel-land, `make clean` simply cleans up things that may have been used to build Chapel but are not required to run it.  So, for example, it might delete intermediate `.o` files, but not the libraries and binaries that they resulted in.  In contrast, `make clobber` returns things to as close to a pristine state as possible and is the way to "try again from scratch" without literally checking out a completely pristine copy of the repository.  Targets supported by our Makefiles are detailed in the "[building chapel](https://chapel-lang.org/docs/latest/usingchapel/building.html#makefile-targets)" documentation.

All that said, I'm a bit surprised that a clobber would be needed.  I work from master and almost never invoke it because our dependencies have gotten much better over time (thanks to a recent effort by @ronawho).  And, I wouldn't expect GMP to not work on any recent copies of GitHub master, as there's been no sign of instability in our testing or local development efforts.  But that's the nature of bugs I suppose.

Let us know if a `make clobber` and re-build fixes things for you or not.  Thanks!

**Comment by ronawho** [comment] 2018-07-06 16:11
Closing since it's expected behavior that `make clean` doesn't get rid of the install, just temporary build files. Feel free to reopen if you're still running into any issues though.

**Closed by ronawho** 2018-07-06 16:11 UTC
Labels: area: Makefiles, area: Third-Party, type: Bug, user issue
