### ISSUE TITLE
segfault in calling generic record initializer

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6058] opened 2017-04-19 20:09 UTC
### Summary of Problem

I'm seeing a segfault when trying to call a generic record initializer.  I'm not confident that the initializer is something that we intend to support, but we shouldn't segfault.

### Steps to Reproduce

**Associated Future Test(s):**

``test/studies/shootout/chameneos-redux/bradc/chameneosredux-blc-ideal.chpl``

**Compile command:**
``chpl chameneosredux-blc-ideal.chpl``

### Configuration Information

- Output of `chpl --version`: ``1.16.0 pre-release (5d73d1c)``

**Comment by daviditen** [comment] 2017-10-26 18:45
This is a duplicate of the more general #7341.  The error can be seen with the simplified code:

```
class C { }

record R {
  var c;

  proc init() {
    c = new C();
    super.init();
  }
}

var r = new R();
```

**Closed by daviditen** 2017-10-26 18:45 UTC
Labels: area: Compiler, type: Bug
