### ISSUE TITLE
ARM LLVM configuration forgets state of re2 build

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#11910] opened 2018-12-18 22:17 UTC
### Summary of Problem
On a Cray XC ARM system,  compiling a Chapel program using the LLVM back end results in an error because the re2 portion of the path says "none" when it should say "re2".

This is a fairly recently-introduced bug.  However, I have verified that it is not due to #11905 .

### Steps to Reproduce

**Source Code:**

Any Chapel program will do, for example hello.chpl.

**Compile command:**
```
$ chpl --llvm hello.chpl
error: Could not open file /cray/css/users/dkeaton/ranger-aarch-llvm/chapel/lib/cray-xc/clang-included/aarch64/arch-arm-thunderx2/loc-flat/comm-ugni/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-intrinsics/hwloc/none/fs-none/lib_pic-none/list-includes-and-defines
$
```
The part of the path that says `hwloc/none/fs-none` should say `hwloc/re2/fs-none`, which is why the file is not found.

If I make a symbolic link from `none` to `re2` at that part of the filesystem, the program compiles and runs correctly.

**Execution command:**
N/A -- can't get that far

**Associated Future Test(s):**
All tests fail.

### Configuration Information

- Output of `chpl --version`:
chpl version 1.19.0 pre-release (bb08dcc564)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: cray-xc
CHPL_TARGET_COMPILER: cray-prgenv-gnu
CHPL_TARGET_MACHINE: aarch64
CHPL_TARGET_ARCH: arm-thunderx2
CHPL_LOCALE_MODEL: flat
CHPL_COMM: ugni
CHPL_TASKS: qthreads
CHPL_LAUNCHER: slurm-srun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: ugni
CHPL_GMP: system *
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc (GCC) 8.2.0 20180726 (Cray Inc.)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

- (For Cray systems only) Output of `module list`:
Currently Loaded Modulefiles:
  1) modules/3.2.11.1
  2) nodestat/2.3.85-6.0.7.0_32.1__gc6218bb.ari
  3) sdb/3.3.775-6.0.7.0_32.2__gb339c00.ari
  4) udreg/2.3.2-6.0.7.0_33.11__g5196236.ari
  5) ugni/6.0.14.0-6.0.7.0_23.1__gea11d3d.ari
  6) gni-headers/5.0.12.0-6.0.7.0_24.1__g3b1768f.ari
  7) dmapp/7.1.1-6.0.7.0_34.3__g5a674e0.ari
  8) xpmem/2.2.15-6.0.7.1_5.10__g7549d06.ari
  9) llm/21.3.530-6.0.7.0_39.1__g3b4230e.ari
 10) nodehealth/5.6.14-6.0.7.1_8.3__gd6a82f3.ari
 11) system-config/3.5.2786-6.0.7.0_43.1__gc54785a.ari
 12) slurm/18.08.3-1
 13) Base-opts/2.4.135-6.0.7.0_38.1__g718f891.ari
 14) craype-arm-thunderx2
 15) craype-network-aries
 16) craype/2.5.15.3
 17) cray-libsci/18.12.1.1
 18) pmi/5.0.14
 19) atp/2.1.3
 20) perftools-base/7.0.5
 21) PrgEnv-gnu/6.0.5
 22) rca/2.2.18-6.0.7.0_33.2__g2aa4f39.ari
 23) gcc/8.2.0
 24) craype-hugepages16M

**Comment by ronawho** [comment] 2022-02-08 11:39
llvm has been our default for a little while now and we haven't seen this so I believe it was resolved. I also can't reproduce the failure trying manually just now, closing.

**Closed by ronawho** 2022-02-08 11:39 UTC
Labels: type: Bug, area: BTR
