### ISSUE TITLE
Memory corruption on access to C struct in remote task

### ISSUE THREAD

**Issue by elliottslaughter** [chapel-lang/chapel#11288] opened 2018-10-02 23:16 UTC
### Summary of Problem

In certain cases, attempts to access C structs (even ones which are POD) in remote tasks appears to result in non-deterministic memory-corruption when run on multiple nodes. E.g. in the trace below, the second-to-last line shows all `0`'s for struct fields that had just shown correct values when printed from Chapel immediately prior:

```
running graph 0 on locale 0
  in chapel: graph_index 0 timesteps 1000 max_width 64 dtype 2 (on locale 0)
  chapel is about to call C
    TaskGraph::max_dependence_sets() graph_index 0 timesteps 1000 max_width 64 dtype 2 (on nid00032)
  chapel returned from call to C
running graph 0 on locale 1
  in chapel: graph_index 0 timesteps 1000 max_width 64 dtype 2 (on locale 1)
  chapel is about to call C
    TaskGraph::max_dependence_sets() graph_index 0 timesteps 0 max_width 0 dtype 0 (on nid00033)
  chapel returned from call to C
```

This is non-deterministic; sometimes I get the correct result, sometimes I get `0`, and sometimes I get `-1`.

### Steps to Reproduce

Note this is assuming the use of the **Cori supercomputer**.

**Source Code:**
https://github.com/StanfordLegion/task-bench/blob/chapel-multinode-crash/chapel/task_benchmark.chpl

Strictly speaking, it should be possible to simplify the build below (`make -C core && make -C chapel` would probably do it), but for full reproducibility I'm including my original build commands below.

**Compile command:**
```
git clone -b chapel-multinode-crash https://github.com/StanfordLegion/task-bench.git
cd task-bench
DEFAULT_FEATURES=0 USE_CHAPEL=1 CHPL_COMM=ugni ./get_deps.sh
DEBUG=1 ./build_all.sh
```

**Execution command:**
```
salloc -N 2 -C haswell -q interactive -t 01:00:00
srun --nodes=2 --ntasks=2 --ntasks-per-node=1 --cpus-per-task=64 --kill-on-bad-exit ./chapel/task_benchmark_real -nl 2 -- -kernel compute_bound -iter 1 -type stencil_1d -steps 1000 -width 64
```

### Configuration Information

- Output of `chpl --version`: 1.18.0
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

    ```
    CHPL_TARGET_PLATFORM: cray-xc
    CHPL_TARGET_COMPILER: cray-prgenv-gnu
    CHPL_TARGET_ARCH: haswell
    CHPL_LOCALE_MODEL: flat
    CHPL_COMM: ugni
    CHPL_TASKS: qthreads
    CHPL_LAUNCHER: slurm-srun
    CHPL_TIMERS: generic
    CHPL_UNWIND: none
    CHPL_MEM: jemalloc
    CHPL_ATOMICS: intrinsics
      CHPL_NETWORK_ATOMICS: ugni
    CHPL_GMP: gmp
    CHPL_HWLOC: hwloc
    CHPL_REGEXP: re2
    CHPL_AUX_FILESYS: none
    ```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: gcc (GCC) 7.3.0 20180125 (Cray Inc.)
- (For Cray systems only) Output of `module list`:

    ```
    $ module list
    Currently Loaded Modulefiles:
      1) modules/3.2.10.6                               10) ugni/6.0.14-6.0.5.0_16.9__g19583bb.ari         19) atp/2.1.1
      2) nsg/1.2.0                                      11) pmi/5.0.13                                     20) PrgEnv-gnu/6.0.4
      3) cray-mpich/7.7.0                               12) dmapp/7.1.1-6.0.5.0_49.8__g1125556.ari         21) python/3.6-anaconda-4.4
      4) gcc/7.3.0                                      13) gni-headers/5.0.12-6.0.5.0_2.15__g2ef1ebc.ari  22) tmux/2.2
      5) craype-haswell                                 14) xpmem/2.2.4-6.0.5.1_8.18__g35d5e73.ari         23) htop/1.0.2
      6) craype-network-aries                           15) job/2.2.2-6.0.5.0_8.47__g3c644b5.ari           24) altd/2.0
      7) craype/2.5.14                                  16) dvs/2.7_2.2.65-6.0.5.2_16.2__gbec2cb0          25) darshan/3.1.4
      8) cray-libsci/18.03.1                            17) alps/6.5.28-6.0.5.0_18.6__g13a91b6.ari
      9) udreg/2.3.2-6.0.5.0_13.12__ga14955a.ari        18) rca/2.2.16-6.0.5.0_15.34__g5e09e6d.ari
    ```

**Comment by bradcray** [comment] 2018-10-02 23:33
On chat, @elliottslaughter pointed out [this line](https://github.com/StanfordLegion/task-bench/blob/chapel-multinode-crash/chapel/task_benchmark.chpl#L63) as the one where the call to C is passing `graph` and apparently seeing different values than the ones printed from within Chapel.

**Comment by bradcray** [comment] 2018-10-03 00:11
I think that the problem is as follows:  The code effectively has the following pattern:

```chapel
extern record task_graph_t { ... };             // an extern record (struct) exists
var graphs: [0..#n] task_graph_t;               // create an array of such structs (on locale 0)
coforall graph in graphs {                      // create a task per graph
  coforall loc in Locales do on loc {           // create a task per locale
    writeln(graph);                             // print the extern graph struct
    call_extern_C_routine(graph);               // call C routine which gets garbage value on locales other than 0
  }
}
```

I believe what's happening is that since records have a default task intent of `const ref`, each `graph` value is never copied to the remote locale but all references to `graph` from non-0 locales are referring back to the original object.  For a Chapel statement like `writeln(graph)`, everything works because Chapel knows how to refer to the original object despite the fact that it's remote (through the global namespace).  However, for something like the C routine, which doesn't know about distributed memory, we pass a bogus pointer to the routine.

At times, I believe we've discussed putting in safety checks for such cases to make sure that the user doesn't fall into this pit ("If passing a Chapel record to an extern C routine, make sure that the record is located on the calling locale before passing it along."), but can't recall offhand whether we never implemented that idea, or whether we did and the use of the ``--fast`` flag disabled the checks (checking on that next).

In the meantime, I believe that manually localizing the record within the on-clause should cause the program to work as expected:

```chapel
  on loc {
    const loc_graph = graph;
    writeln(loc_graph);
    call_extern_C_routine(loc_graph);
  }  
```

**Comment by bradcray** [comment] 2018-10-03 00:36
Though I still feel reasonably confident in my diagnosis above, my attempt to create a standalone example showing the same behavior (but not relying on LLVM extern blocks) failed (which is to say it "worked" rather than printing out garbage on locale 1).  Maybe I'm just fried at the end of the day, though, and missing something obvious:

**testit.h:**
```c
typedef struct _R {
  int x;
} R;

static inline void printR(R myR) {
  printf("%d\n", myR.x);
}
```

**testit.chpl:**
```chapel
require "testit.h";

extern record R {
  var x: c_int;
}

extern proc printR(myR: R);

var A: [1..10] R;

forall i in 1..10 do
  A[i].x = i: c_int;

coforall a in A do
  coforall loc in Locales do on loc {
    printR(a);
  }
```

[Or maybe the LLVM-based extern blocks effectively prototype the external C routine differently than I have here, resulting in different behavior?]

Meanwhile, I'm waiting for an LLVM + GASNet build to complete so that I can try creating a reproducer using an extern block.

**Comment by elliottslaughter** [comment] 2018-10-03 04:02
I can confirm that the `const loc_graph = graph;` pattern is sufficient to fix the real application from which this reproducer was derived. Thanks!

**Comment by mppf** [comment] 2018-10-03 16:19
Interestingly, in the context of `--llvm` compilation, we could claim that we also control the C compiler (namely that it's our included clang). In which case we can have the C compiler work with 128-bit wide pointers and still function (generating GETs and PUTs as Chapel does). This would avoid this issue being a correctness problem (although it might continue to be a performance issue) and would address my common complaint that `c_ptr` is always only the node-local part of the pointer, and there isn't any equivalent for wide `c_ptr`s.

I think if we went down that path, we'd have to somehow handle (ideally at compile time) the case where Chapel code is passing a wide pointer to code not compiled by Chapel or our version of clang.

**Comment by bradcray** [comment] 2018-10-03 16:38
I don't think we should change the semantics of whether or not records are copied across locales based on whether or not they're passed to a C function...  Is that what you're suggesting?

**Comment by mppf** [comment] 2018-10-03 16:38
@bradcray - no, just that we could allow C code to accept wide pointers and do GETs/PUTs with them.

**Comment by bradcray** [comment] 2018-10-03 16:46
Oh... you're saying that as the author of a C library, I could write an interface that would accept a wide pointer and then I could do the communication myself?

**Comment by mppf** [comment] 2018-10-03 17:08
@bradcray - it's even crazier than that but I think I need an example to explain. Think more along the lines of "PGAS C":

``` chapel
extern {
  static inline int getValue( int* ptr) {
    return *ptr;
   }
}

var x: c_int;
on Locales[numLocales - 1] {
  var z = getValue(c_ptrTo(x));
}
```

Here I'm proposing that we could compile the C code for `getValue` to create a version of the function accepting a wide `int*` argument (since the Chapel compiler can know that is necessary). This could happen transparently to the C code; our existing --llvm-wide-opt techniques can apply to the C code and convert the `*ptr` from a load to a GET.

**Comment by bradcray** [comment] 2018-10-29 23:03
@mppf: Thanks for clarifying.

I want to jump back several steps.  For C code that we don't control (say, a precompiled library), I think that we should either be generating an error when someone tries to pass a pointer to remote data to that external routine, or (if legal/possible) we should be doing the copy automatically for them.  My interpretation of Elliott's original issue is that we were doing neither.  However, I've been having a difficult time creating a simple reproducer of what I was observing, potentially because I'm using explicit externs rather than the extern block (or maybe just because what the extern block does is a black box to me).

@mppf, is it clear to you why Elliott's code seemed to result in accessing a remote pointer within C whereas a case like the following does not:


***testit.chpl***
```chapel
extern record R {
  var x: c_int;
}

require "externRecord.h";

proc main() {
  var myR: R;
  myR.x = 42;

  extern proc foo(x: R);

  on Locales[numLocales-1] {
    foo(myR);
  }
}
```

***externRecord.h:***
```c
typedef struct _R {
  int x;
} R;

static void foo(R r) {
  printf("foo got: %d\n", r.x);
}
```

**Comment by mppf** [comment] 2018-10-30 13:07
@bradcray - our `extern proc` with record arguments makes a by-value call (since C is call by value I think the thinking is that's less surprising, but it doesn't match Chapel rules... I seem to remember another issue bringing this up recently maybe in the context of arrays).

With that in mind, here is a modification of your program:
testit.chpl:
``` chapel
extern record R {
  var x: c_int;
}

require "externRecord.h";

proc main() {
  var myR: R;
  myR.x = 42;

  extern proc foo(ref x: R);

  on Locales[numLocales-1] {
    foo(myR);
  }
}
```

externRecord.h:
``` c
typedef struct _R {
  int x;
} R;

static void foo(R* r) {
  printf("foo got: %d\n", r->x);
  printf("turning it up to 11\n");
  r->x = 11;
}
```

This seg-faults for me on 2 locales.

>  For C code that we don't control (say, a precompiled library), I think that we should either be generating an error when someone tries to pass a pointer to remote data to that external routine, or (if legal/possible) we should be doing the copy automatically for them.

I think a runtime error when `--checks` is on would be achievable and reasonable. I still think it'd be cool to have PGAS C though :)

**Comment by bradcray** [comment] 2018-10-30 23:15
OK, thanks for fixing my example.  The reason I went down the "by value" rather than "by reference" path is that the original code that Elliott posted used by-value semantics (e.g., when calling from https://github.com/StanfordLegion/task-bench/blob/chapel-multinode-crash/chapel/task_benchmark.chpl#L63 to https://github.com/StanfordLegion/task-bench/blob/chapel-multinode-crash/core/core_c.h#L88).  Looking again today, though, I'm seeing that a difference is that it's passing the record through a local argument first, which seems to make all the difference.

Thanks again!

**Comment by mppf** [comment] 2018-10-31 12:49
@bradcray - I think it'd be nice if you could summarize what you see as the next steps from this issue.

Next steps I can imagine:
 * investigate PGAS C for extern blocks
 * `--checks` adds runtime checking that refs passed to extern routines are local

**Comment by bradcray** [comment] 2018-10-31 15:13
Sorry, I'd hoped to make this clear yesterday, but got interrupted by a late afternoon meeting.  I've got a PR almost done that adds three new futures for bullet 2 and was planning to close this issue in favor of a new more precise one referencing those futures once I had.  For bullet 1, I think you should fire off a new feature request issue if you want to promote it.

**Comment by bradcray** [comment] 2018-10-31 20:54
I've distilled this issue down to some future tests filed in PR #11538 and a feature request in issue #11539.  I'm closing this one in favor of those two.  Thanks for bringing this to our attention @elliottslaughter!

**Closed by bradcray** 2018-10-31 20:54 UTC

**Comment by bradcray** [comment] 2018-11-01 00:12
Just a quick note to point out that I think I've got a fix for this in PR #11543.

**Comment by mppf** [comment] 2018-11-01 14:55
I created #11545 for the "PGAS C" proposal.

**Comment by bradcray** [comment] 2018-11-06 00:39
Hi @elliottslaughter — Thanks again for filing this.  As of this afternoon, we generate an execution-time error for cases like this rather than having your external routine poke off into random addresses.  Hopefully this'll help other users who would've tripped over this, so thanks again for reporting it.
