### ISSUE TITLE
Lists of domains and arrays don't work ("attempt to dereference nil")

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19118] opened 2022-01-26 01:45 UTC
### Summary of Problem

Something about our current `list` implementation doesn't seem to work for domain or array elements, where the behavior is an "attempt to dereference nil" error.

[edit: below, DavidL and Michael point out that #15929 is the root cause]

### Steps to Reproduce

**Associated Future Test(s):**
[`test/studies/adventOfCode/2021/bradc/futures/day22a-listOfDomain.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/studies/adventOfCode/2021/bradc/futures/day22a-listOfDomain.chpl
          ) #19028 

### Configuration Information

- Output of `chpl --version`: `chpl version 1.26.0 pre-release (b94e1c4598)`

**Comment by bradcray** [comment] 2022-01-26 01:46
Pinging list-master @dlongnecke-cray to see if the cause here is obvious to you.

**Comment by dlongnecke-cray** [comment] 2022-01-26 03:31
The problem is runtime types bugging out when default-initializing a record.

This code also works as a reproducer:

```chapel
record foo {
  type T;
  proc doSomething(in val: T) {
    writeln(val);
  }
}

proc test() {
  var obj: foo(domain(3));
  obj.doSomething({0..1, 2..3, 4..5});
}
test();
```

Before resolution, the compiler calls `chpl__buildDomainRuntimeType` for the `domain(3)` and passes that into the default-init for the record (which is great, and exactly what we want it to do).

During resolution, the compiler decides to pass in a `default_runtime_temp` instead (leaving the old pattern in the tree to be garbage collected). The `default_runtime_temp` is uninitialized, and the empty `dist` field is what causes the halt.

This bug does not occur if I change the initialization pattern to `var l = new list(domain(3));` instead.

I'm timing out right now, but can look into it a bit more tomorrow.

**Comment by bradcray** [comment] 2022-01-26 18:16
Oh bummer, I'm seeing that `var l: list([1..3] int);` has the same problem.  For some reason, I was thinking that was a case we'd covered on our big "collections of types" matrix in https://chapel-lang.org/releaseNotes/1.24/01-lang-lib.pdf, but now I'm seeing that's not the case.  :'(

If we weren't able to fix this easily, it'd be nice to at least have it generate a compile-time "not supported yet; try this workaround" style message if that were easy.  But ultimately, I think it's important for us to support these cases for the sake of orthogonality.

**Comment by dlongnecke-cray** [comment] 2022-01-26 18:55
I agree this pattern should be supported. Seeing the right thing happen and then get garbled is a good indicator (plus the right thing happening for `new list(domain(3))` is a good sign as well).

**Comment by dlongnecke-cray** [comment] 2022-01-26 22:32
Michael pointed out that this is the exact same as #15929.

**Comment by bradcray** [comment] 2022-01-26 22:52
> Michael pointed out that this is the exact same as #15929.

You're saying that #15929 is the root cause of this behavior, not that a user running into this in this specific instance would necessarily find their way to that issue, is that right?

**Comment by dlongnecke-cray** [comment] 2022-01-26 22:53
Yep, #15929 is the root cause.

**Comment by dlongnecke-cray** [comment] 2022-02-07 21:28
I have a fix for this sitting around that I can PR. Last I tested it there were 60 failures to attend to first.

**Comment by dlongnecke-cray** [comment] 2022-02-08 18:21
Drafted here: https://github.com/chapel-lang/chapel/pull/19220

**Comment by bradcray** [comment] 2022-07-07 07:11
@dlongnecke-cray : If you need some encouragement to return to this PR, @ronawho ran into a related case today in https://github.com/chapel-lang/chapel/issues/20167  (also, whenever this comes up, it makes me shudder to think that we have such a non-orthogonality in some of our major types—and I don't mean that as a criticism, just a sinking feeling.  I also realize that runtime types make things challenging...)

**Comment by dlongnecke-cray** [comment] 2022-07-07 18:28
Yeah, when last I left off the draft PR had about 60 test failures. Essentially what it's doing is some simple pattern matching to try and see - "when this type was initialized, did it construct a runtime type for its type expression? If so try and find that and use it instead of default constructing a RTT". I don't know if that's a sound approach but that's what I was going for. I can try to resurrect that effort, but I wasn't entirely sure about the soundness (maybe because it's touching RTTs).

**Comment by dlongnecke-cray** [comment] 2022-08-10 17:21
I am revisiting this effort right now and I am wondering if there is a better approach that can be used.

Specifically, the current approach I have uses pattern matching to try and recover the runtime types used in a type constructor call (if a type was constructed with subs that are runtime types, the compiler keeps those calls around for long enough to recover them).

However I am afraid that the approach is fragile and will fall apart in ways that I cannot predict.

I could proceed with current patch as a short-term fix, but for the future I am wondering if the correct thing to do is to carry around runtime types in the substitutions map of the aggregate type. I am not sure if this new idea is completely sound, though, but it seems more holistic to me.

**Comment by dlongnecke-cray** [comment] 2022-08-11 02:02
We've decided to proceed with my current effort for now. Followup work can be discussed in #15929.

**Closed** 2022-08-22 18:25 UTC
Labels: type: Bug, area: Libraries / Modules
