### ISSUE TITLE
Should `set.remove()` return the removed element?

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#15819] opened 2020-06-11 19:48 UTC
Currently `set.remove()` does not return the removed element at all, instead choosing to drop it on the floor. This choice was inspired by Python, where `set.remove` also returns `None` instead of the removed value.

Some of my reasoning for why Python's `set.remove` might return `None` instead of the removed element:

- In Python, all types have reference semantics
- Because of this, all set values are required to be immutable to ensure correctness

Chapel has value types (records) and reference types (classes) while Python only has reference types. In Chapel values added to a set are not required to be immutable. To achieve immutability without this requirement we make a copy of any element added to a set and only allow access to the set element by `const ref`.

In addition to copying added elements, because users can overload the `==` operator for their types, this can create a scenario where two instances of a type (such as a record) evaluate as equal but contain significant differences.

While one might argue that this is not overloading the `==` operator in good faith, that this can happen in practice suggests that `set.remove()` should return the removed value, -OR- at the very least we should add another method that returns the removed value such as `removeAndReturn`.

**Comment by mppf** [comment] 2020-06-11 20:31
@dlongnecke-cray - I'm not sure if you expressed an opinion for the answer to "Should `set.remove()` return the removed element?" but my opinion is that the answer is "yes, it should".

**Comment by dlongnecke-cray** [comment] 2020-06-11 20:36
Oh, good point.

I think `set.remove()` should return the removed element as well.

Do you know what happens to returned values that are not assigned in a multilocale context? Are they still potentially communicated across locales? This might be a separate issue at heart, but it might be reason enough to justify adding a method to `set` such as `.drop()` that returns the value without removing it.

**Comment by mppf** [comment] 2020-06-11 20:41
Well, if `set.remove` contains an `on` statement, then yes, removing it on a different locale from the set would introduce communication. But most likely if somebody cares about performance the don't want the `on` statement either...

**Comment by dlongnecke-cray** [comment] 2020-06-11 21:44
I wrote the last part of my sentence wrong, edited for clarity ><.

**Comment by bradcray** [comment] 2020-06-12 16:12
What will `set.remove()` return if it doesn't find the element?

**Comment by dlongnecke-cray** [comment] 2020-06-12 17:19
Well historically, (based on what we've done for other such methods), we'd have it `halt`. An alternative is to make it `throw`, though I think we've generally disapproved of such an approach. If we want to break precedent we use an `out` parameter and return a `bool`...

**Comment by bradcray** [comment] 2020-06-12 17:29
That makes me think I might prefer to stick with the current interface (which, as I understand it, returns `true` or `false` depending on whether or not it was found?).

On my first quick read of this issue, it seemed odd to me that in saying `mySet.remove(10)` I'd care to have 10 returned back to me.  I think I understand your OP's point to be that since (1) sets look for the element using `==` and (2) a given `==` may permit some sort of approximate match, (3) the value that's remove()d might be different in an interesting way than the thing I passed in.  And while I can see that's the case, I'm pretty sure I'd rather get `true` or `false` back instead of taking a `halt`.

If we either used the `out` argument you propose (or maybe cleaner, returned a tuple), we'd need to have some way of creating a dummy value of `eltType` for any type used to create sets which seems iffy to me (and potentially expensive depending on the type).

If we had option types, we could have it return an option type value of course.

We could also consider having `remove()` remain as it is today and have a `fetchRemove()` or somesuch that would return the value in one of these forms if/when we wanted to add it.

**Comment by dlongnecke-cray** [comment] 2020-06-12 17:34
I would prefer to introduce a method like `.drop`, which will retain the current semantics of `.remove()`, and then update `.remove()` to halt if the element is not contained in the `set`.

Though I like the above names better, your idea would avoid breaking existing code, so it's probably better.

**Comment by bradcray** [comment] 2020-06-12 17:39
I worry about having something as fundamental as `set.remove()` halting in a parallel language.  It seems like there'd be no way to safely remove elements in a parallel context because you'd never know whether someone else would slightly beat you to removing them.

Is there a precedent for `.remove()` returning the value in other value-based languages like C++?

**Comment by dlongnecke-cray** [comment] 2020-06-12 18:01
> It seems like there'd be no way to safely remove elements in a parallel context because you'd never know whether someone else would slightly beat you to removing them.

I view it as a problem also shared by `list.pop` and `map.remove`. It seems like `parSafe=true` should handle a data race nicely?

> Is there a precedent for .remove() returning the value in other value-based languages like C++?

It looks like the C++ `unordered_set` type has `erase`, which returns `1` if the element was removed, so basically the exact same semantics as `set.remove` has today.

**Comment by bradcray** [comment] 2020-06-12 18:37
> It seems like parSafe=true should handle a data race nicely?

What does "nicely" mean if the routine halts, though, when the value you thought was there isn't because someone else just removed it?

I agree map.remove seems like it should share a similar design.  list.pop() feels a little different because multiple things could pop simultaneously and both succeed... until the list becomes empty, I suppose.

**Comment by dlongnecke-cray** [comment] 2020-06-12 18:49
Part of me wants to say that I feel like a more general locking mechanism for containers in the spirit of https://github.com/chapel-lang/chapel/issues/12306 could help solve this problem and others.

We could also revisit the idea of having `set.remove` throw an exception instead of halting once again (it seems like exceptions were designed to solve this sort of problem).

**Comment by mppf** [comment] 2020-06-12 19:06
> We could also revisit the idea of having set.remove throw an exception instead of halting once again (it seems like exceptions were designed to solve this sort of problem).

Halting for this seems untenable to me. Throwing would be fine, in my opinion.

> If we had option types, we could have it return an option type value of course.

I'm pretty sure we could get an option type together in short order, if we really wanted to.

> I agree map.remove seems like it should share a similar design.

I think the problem is worse for map.remove because with a map you'll remove based on the key but might want to get the value back.

**Comment by bradcray** [comment] 2020-06-12 19:12
I'd still be inclined to leave `remove()` as-is on the basis of (a) not breaking existing code, (b) C++'s precedence and then adding a `removeFetch()` or `remove(val, returnVal=true)` or something overload if/when someone really wants this feature.

**Comment by dlongnecke-cray** [comment] 2020-06-12 19:27
If we want to throw then there are a whole lot of other cases where we currently halt that we might want to revisit.

I'm fine with leaving things as is for now but I do think for `set` to be feature complete we should offer some variant of `removeFetch`, `remove...` (as Brad suggests) in the future.

**Comment by lydia-duncan** [comment] 2023-08-18 15:53
Given the decision on #18649 to keep remove as is and support a different method for removing and returning, I'm closing this issue

**Closed by lydia-duncan** 2023-08-18 15:53 UTC
Labels: type: Design, area: Libraries / Modules, type: Chapel 2.0
