### ISSUE TITLE
Why did this code cause us to discover PCGRandom's writeThis needed a use of the IO module?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#16846] opened 2020-12-10 17:06 UTC
### Summary of Problem
The resolution of an unrelated function in another module exposed a resolution error with PCGRandom's writeThis method.  Why was PCGRandom's writeThis even looked at in this scope?  Why was its body resolved to the point where we saw a resolution error, when no instances of the type were supposed to be written?  Does it have something to do with first class functions, since replacing the argument with a string avoids the problem?

### Steps to Reproduce

Comment out the `use IO;` statements in the Random module, then compile the following:

**Source Code:**

```chapel
module Foo {
  use Random;
  use Random.PCGRandom only PCGRandomStream;

  proc generateToken(len: int=32) : string {
    var alphanum = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
                    "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M",
                    "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
                    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j","k", "l", "m",
                    "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"
                    ];
    var upper_bound = alphanum.size;
    var indices : [0..upper_bound-1] int;
    for i in 0..upper_bound-1 do
      indices[i] = i;

    var ret : [0..len-1] string;
    var r = new owned PCGRandomStream(int);
    var rindices = try! r.choice(indices, len);

    for i in 1..len-1 do
      ret[i] = alphanum[rindices[i]];
    return ''.join(ret);
  }
}

module Two {
  use IO;
  proc otherGenFunc(x) throws {
    writeln("%s".format(x));
  }
}
module Three {
  use Two;

  proc callGenFunc() {
    try! otherGenFunc(otherFunc); // Note missing parentheses here
  }

  proc otherFunc() {
    writeln("eh");
  }
}
module User {
  use Foo, Three;
  proc main() {
    callGenFunc();
    var token = generateToken(32);
    writeln(token);
  }
}
```

**Compile command:**
`chpl foo.chpl`

**Associated Test(s):**
[`test/library/standard/Random/checkWriteThis.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/library/standard/Random/checkWriteThis.chpl) #16838

### Configuration Information

- Output of `chpl --version`: 1.24.0 pre-release

**Comment by cassella** [comment] 2020-12-10 19:04
The interaction with an FCF and anyClass.writeThis is reminiscent of #14467.  As there, replacing the call to `callGenFunc()` with

```chapel
    var o: object = new object();
    writeln(o);
```

still reproduces the error (with the uses of `IO` in Random removed).

**Comment by vasslitvinov** [comment] 2020-12-11 13:15
The error in `checkWriteThis.chpl` upon commenting out `use IO` in Random is generated when resolving `PCGRandomStream.writeThis(f)` located around Random.chpl:1290. At which time, `<~>` is indeed not visible.

How does it happen? Here is compiler thinking.

* There is a call to `writeThis(a FCF)`, due to the call `"%s".format(a FCF)` in the test code in `otherGenFunc()`.

  <details>
  <summary>call stack</summary>

    main     // test code
  callGenFunc
  otherGenFunc
  "%s".format(a FCF)   // calls into IO.chpl
  chpl_do_format
  writef
  _writefOne
  _writeOne
  _write_one_internal
  notNilX.writeThis(writer)
  </details>

* This call resolves to `object.writeThis(f)`, which is generated by the compiler.

* In virtualDispatch.cpp _buildVirtualMaps()_, the compiler resolves all the overrides of `object.writeThis(f)`. This is because at run time a call `(some object).writeThis(f)` can potentially dynamically-dispatch to any of those overrides, conservatively speaking.

* `PCGRandomStream.writeThis(f)` is one of those overrides and so gets resolved as well.

* When resolving it, its POI is in `generateToken()` in the test code.

  <details>
  <summary>why so?</summary>

  * This override is instantiated in virtualDispatch.cpp in _buildVirtualMaps()_ --> _addAllToVirtualMaps()_ --> _addToVirtualMaps()_ --> _getInstantiatedFunction()_

  * So, it inherits the POI from the POI of the receiver class for which it is instantiated, see _getInstantiatedFunction()_

  * That receiver class is `PCGRandomStream(int(64),true)`, most likely instantiated at `var r = new owned PCGRandomStream(int);`, which is in `generateToken()` in the test code. Voilà.

  </details>

* `<~>` is not visible from the lexical scope of `PCGRandomStream.writeThis(f)` or from the scope of its POI, `generateToken()`. The latter is a concrete function, so does not have a POI that could be consulted next.

**Comment by lydia-duncan** [comment] 2020-12-11 15:59
That makes sense, thanks Vass!  Calling back to #16837, this still seems like an error that would confuse users.  That doesn't necessarily mean the compiler is wrong for discovering the error, though.  Is there more that we could/should do to clarify that this is happening?  Say, outputting that we're instantiating the function for all child types and listing the child types?

**Comment by bradcray** [comment] 2020-12-11 17:44
Given the role of dynamic dispatch in Vass's explanation, I wonder whether this can be resolved as we move forward by making I/O only rely on operators and not on methods (particularly once operators are associated with types).  This seems as though it would have the benefit of removing a huge virtual dispatch table for `writeThis()` (which has caused us problems in other cases like objects containing sync variables, I think) and reducing the chances of weird entanglements between unrelated types like this?

**Comment by lydia-duncan** [comment] 2020-12-11 21:13
That would certainly remove the most likely places where we'd see issues, though I would argue it addresses symptoms rather than the cause.  A general solution that indicates the instantiations would help if the user has gotten themselves into a similar position by failing to fully test a type hierarchy they've written.

**Comment by bradcray** [comment] 2020-12-11 21:42
I suppose, though I feel disinclined to invest much effort now to help users avoid that kind of confusion until we actually have cases in hand where users are getting confused.  Or at least, I'd need to see a standalone example that made me think "Yeah, we're not doing as much there as we should."  This I/O-oriented case seemed particularly bad since it's due to things that we wrote and that most non-expert users would consider to simply be "built-in".

**Comment by lydia-duncan** [comment] 2020-12-11 22:59
It sounds like the course of action then is:
- close this issue
- discuss the idea of moving to I/O relying on operators rather than `writeThis` with whomever ends up reviewing the IO modules
- if a user encounters a similar issue related to their code, then start thinking about how to make such errors easier to diagnose
Does that sound right?

**Comment by bradcray** [comment] 2020-12-12 00:06
That's probably what I would do.  Alternatively, we could write a completely user-based code that exhibited the same problem and then weigh whether we think that's something that we should address now, or live with until it becomes more of an issue for real users (i.e., they complain, or we become aware that they're suffering from it), or decide that it's not actually a problem.

In any case, I definitely like wrestling more with the question of "What would it take to have I/O be operator-based only?"  I feel like we've been in an inconsistent, or at least confusing-to-me state, for awhile where I don't have a really clear vision when I'm writing a type whether I should define `writeThis()` or `readWriteThis()` or `<~>` or some combination thereof.  So if making I/O more operator-based helped clarify that while also avoiding the ever-growing dynamic dispatch table for writeThis() on every class, that'd be a win-win.  But getting operators to support a type-method-based form is probably still higher priority.

**Closed** 2020-12-14 18:28 UTC
Labels: area: Compiler, area: Libraries / Modules, type: Bug, user issue
