### ISSUE TITLE
Improve sys_getenv documentation

### ISSUE THREAD

**Issue by tmacd8** [chapel-lang/chapel#16705] opened 2020-11-15 01:14 UTC
# Summary of Problem
The online documentation for function ```sys_getenv``` could be improved.  The prototype is:

  ```procsys_getenv(name: c_string, ref string_out: c_string): c_int```

yet the meaning of the return value is not clear.  Some experimentation shows that if the value ```1``` is returned then the environment variable (i.e., ```name```) is defined and if the value ```0``` is returned then the environment variable is not defined.  The Standard C library defines ```getenv``` to return a pointer if defined and ```NULL``` if not defined.  Making the return values (```0``` and ```1```) and their meaning (undefined and defined) explicit in the documentation would help.  Or, perhaps, just saying that a return value of ```0``` means undefined and all other values mean defined.

**Comment by mppf** [comment] 2020-11-16 15:01
Actually it is documented here:

https://github.com/chapel-lang/chapel/blob/36921709813e2c221505ad518b1014a8ed6a43a9/runtime/src/qio/sys.c#L481-L486

However that does not mean it couldn't/shouldn't be documented in Sys.chpl. But, we are working on doing module reviews to stabilize modules (so that they do not change in the future and break programs). While this routine might continue to exist in the C runtime, we will almost certainly need to make a more Chapel-y way to get an environment variable (say, one that returns a `string`).

In any case I think we would be happy to have a PR more or less the documentation to Sys.chpl for the near term. You're welcome to prepare such a thing and you can check the rendered docs with `make docs`.

**Comment by bradcray** [comment] 2020-11-16 17:27
I disagree with the tone of Michael's previous comment, which seems to suggest that the issue as written is somehow invalid or not our problem.  The [documentation for the `Sys` module](https://chapel-lang.org/docs/master/modules/standard/Sys.html) states that to learn how a routine `sys_foo()` works, one should read `man foo`, but for `sys_getenv()` the signature described in `man getenv` doesn't match the Chapel routine, [with no additional indication of how to translate between them](https://chapel-lang.org/docs/master/modules/standard/Sys.html#Sys.sys_getenv).  I don't think it's reasonable to expect a user to find their way from our online documentation into the runtime source code that implements it to find a comment that's there.  And given that `Sys` is a standard module, I think this is definitely a reasonable request that's on us by default.

That said, I completely agree with him that with the library review and stabilization effort we're undertaking (see slide 20 of [these release notes](https://chapel-lang.org/releaseNotes/1.23/05-ongoing.pdf)), it is likely that these routines will be replaced with ones with a more Chapeltastic interface, so whether or not it's worth the immediate effort to fix this routine (given that there are probably other routines within the `Sys` module that would need similar documentation improvements) given that it's likely to change is a reasonable question.

**Comment by tmacd8** [comment] 2020-11-16 19:32
Making functions like getenv be more chapel-y seems like a good idea to
me.  I don't believe it's a high priority.  I had to write a little
testcase and discover for myself what the return values meant and it just
felt like I should have been able to figure it out by reading the docs.
Anyway, I defer to all of your collective best judgements on the best way
to handle this.  If you want me to mark this issue as 'resolved' then I'm
happy to do so.

--
TMacD

**Comment by bradcray** [comment] 2020-11-20 20:37
> If you want me to mark this issue as 'resolved' then I'm
happy to do so.

Hi @tmacd8 — Thanks, I don't think there's any need to do so.  I suspect we'll probably address the root issue by creating Chapel-y versions of these routines with their own documentation rather than putting effort into documenting the existing routines better, but it doesn't hurt to keep this open until then since it may help others understand what's going on here.

**Comment by tmacd8** [comment] 2020-11-20 22:31
Sounds good.

--
TMacD

**Comment by Rupeshkoushik** [comment] 2020-11-21 12:41
Hi, I'm Rupesh and I'm interested in this issue can you please suggest me ways to get started

**Comment by bradcray** [comment] 2020-11-23 17:46
Hi Rupesh.  This issue is a case of needing to improve documentation for the sys_getenv routine.  To get started with it, you should:

* make sure you're familiar with how to contribute to Chapel (where the three mail places to look are https://github.com/chapel-lang/chapel/blob/master/.github/CONTRIBUTING.md, https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/ContributorInfo.rst, and https://chapel-lang.org/contributing.html)

* build and get familiar with `chpldoc` — our tool used for generating online documentation from Chapel sources:  https://chapel-lang.org/docs/tools/chpldoc/man.html

* add documentation to chpl_getsys() describing what its arguments and return value are, potentially using the information supplied by @tmacd8 in this issue's OP (original post).

* run chpldoc to make sure it turns out correctly

* open a PR with your changes

**Comment by Rupeshkoushik** [comment] 2020-11-29 16:35
HI,i am a beginner and I am interested to contribute to this issue, can you help me how to get started

**Comment by tushargoyl123** [comment] 2020-12-20 12:02
Hi, I'm Tushar and I wanna cope with this issue can you guide me through the process...

**Comment by bradcray** [comment] 2020-12-21 16:34
Hi @tushargoyl123 — We're on winter break through January 4th, so won't be able to be very responsive until then.  Please see the guidance I gave @Rupeshkoushik just above and insure that they are not currently running with the issue so that neither of your time is wasted.

**Comment by Yudhishthira1406** [comment] 2021-01-25 14:35
Hi @bradcray I just wanted to know if the issue is still active and if I can work on it.

> * add documentation to chpl_getsys() 

Also I didn't understand what you meant by the term `chpl_getsys()`

**Comment by mppf** [comment] 2021-01-25 15:24
This issue is talking about the missing documentation here: https://chapel-lang.org/docs/master/modules/standard/Sys.html#Sys.sys_getenv

**Comment by Yudhishthira1406** [comment] 2021-01-25 16:16
@mppf @bradcray please review my PR #16996

**Comment by bradcray** [comment] 2021-01-29 01:34
This was fixed in #16996.  Thanks @tmacd8 for pointing out the lack of clarity, and @Yudhishthira1406 for adding the documentation.

**Closed by bradcray** 2021-01-29 01:34 UTC
Labels: area: Docs, easy / straightforward, good first issue, type: Unimplemented Feature, user issue

**Comment by tmacd8** [comment] 2021-01-29 01:43
Great - glad that documentation is improved.

TMacD
