### ISSUE TITLE
Parallel Iterators

### ISSUE THREAD

**Issue by DanielFeshbach** [chapel-lang/chapel#6337] opened 2017-05-26 22:26 UTC
I am new to chapel and to github, so please excuse me if this issue has been addressed elsewhere already. In an effort to learn more about chapel, I am attempting to use iterators to implement and compare row major and column major orders in a parallel function to find the maximum value in a two-dimensional array of reals. Based on the [Parallel Iterators](http://chapel.cray.com/docs/1.14/primers/primers/parIters.html) page in the documentation, I tried to implement them as standalone parallel iterators:

```
iter rowmajor(param tag: iterKind, rowrange: range, colrange: range) where tag == iterKind.standalone {
	for r in rowrange do
		for c in colrange do
			yield (r, c);
}
proc max2D_rowmajor(rowrange: range, colrange: range, a: [rowrange, colrange]){
	var max: real = a[(rowrange.first, colrange.first)];
	forall (r,c) in rowmajor(iterKind.standalone, rowrange, colrange) with (ref max) do
		if a[(r,c)] > max then max = a[(r,c)];
	return max;
}
//equivalents of the iter and the proc exist for colmajor but I've omitted them here for brevity
```

When I run it, I get the following error message (hence my posting here):

```
$CHPL_HOME/modules/internal/ChapelIteratorSupport.chpl:160: internal error: FUN3918 chpl Version 1.13.1
 
Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see http://chapel.cray.com/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```
I'm writing this mainly because it says you'd appreciate me reporting the bug, but any guidance you can give me about how to proceed from here would be greatly appreciated.

In case it's relevant, here's the function I'm calling it in and the call I'm making to it:
```
proc timeTest(min, max, interval){
	var t: Timer;
	writeln("#n time");
	for i in min..max by interval{
		var A = gen2D(1..i, 1..i);
		t.start();
		var m = max2D_rowmajor(1..i, 1..i, A);
		t.stop();
		writeln(i, " ", t.elapsed());
		t.clear();
	}
}

timeTest(500,5000,500);
```

**Compile command:**
<chpl -o test iters.chpl>

### Configuration Information

- Output of `chpl --version`:
```
chpl Version 1.13.1
Copyright (c) 2004-2016, Cray Inc.  (See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
`Usage: printchplenv [--list|--make|--simple|--compiler|--runtime|--launcher|--sh|--csh|--debug]`

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (Ubuntu 4.8.5-4ubuntu2) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by bradcray** [comment] 2017-05-26 23:04
Hi @DanielFeshbach : Thanks for reporting this and asking the question.  This turns out to be a fairly simple issue (albeit one that we should handle better than via an "internal error" -- I'll file an issue against that behavior).  While your implementation of rowmajor() is defined correctly in its inclusion of the ``iterKind`` tag and making sure it's set to ``standalone``, this argument is filled in automatically by the compiler.  That is, you should not be providing it explicitly in your forall loop:

```chapel
	forall (r,c) in rowmajor(iterKind.standalone, rowrange, colrange) with (ref max) do
```

Rather, you should invoke the loop like this:

```chapel
	forall (r,c) in rowmajor(rowrange, colrange) with (ref max) do
```

and then the compiler will add in the standalone tag given that it's being invoked in a forall loop, but in a non-zippered context.  (If it were being zippered with something else in a forall loop, the leader and/or follower version would be called; if it were called in a serial loop, a version with no tag would be called).

Making that change (and providing my own gen2D() function), I had to make one more change to get it to work:  Our compiler currently requires a serial overload of any parallel iterator in order to resolve the parallel versions of it (like your standalone iterator).  Thus, I also had to add code like this:

```chapel
iter rowmajor(rowrange: range, colrange: range) {
  for r in rowrange do
    for c in colrange do
      yield (r, c);
}
```

This requirement is somewhat artificial and a byproduct of how our compiler works at present -- it's something we'd like to relax in the future.  (Perhaps your code already had the serial overload and you just didn't include it in your issue... but if not, you'd get an unresolved call error, which might have caused you to try adding the tag in manually, unsurprisingly).  I'll try to take a look at the parIters primer and see if this can be clarified.

Hope this gets your code compiling.  And note that once it does, you can redefine your parallel iterator to actually use parallelism (e.g., by changing one or both of the loops into foralls).

Also, a parting note and common issue:  Once your program's correct and you're ready to start measuring timings, don't forget to compile with the --fast flag!

**Comment by bradcray** [comment] 2017-05-26 23:11
I filed issue #6339 to note the lame requirement to have to provide a serial overload to invoke a parallel iterator.  There was a pre-existing "future" test filed against this, so I linked to that.

**Comment by bradcray** [comment] 2017-05-26 23:50
I filed issue #6342 against the internal error itself.

**Comment by bradcray** [comment] 2017-05-26 23:56
I filed #6343 against the fact that the primer could be clarified to make the requirement for a serial iterator overload clearer.

**Comment by DanielFeshbach** [comment] 2017-05-30 15:21
Thanks for the help, it seems to be working now! And yeah I did have an issue with an unresolved call error from that iter earlier, which returned once I corrected my call to rowmajor (whichever version of rowmajor I had in the file, until I had both).

**Comment by DanielFeshbach** [comment] 2017-05-30 15:32
Actually it compiles and runs now, but I don't think it is running in parallel. The timing data for running it is essentially identical to data from a version that used a regular for loop and no iterators, and much slower than a version that used a forall loop without iterators. Is there a way to use an iterator in a forall loop and have it still run in parallel?

**Comment by bradcray** [comment] 2017-05-30 16:43
@DanielFeshbach: If you're still using the iterator you showed above, it's not surprising that it's not running in parallel because there's no parallelism within your standalone parallel iterator (it's the parallel iterator author's responsibility to specify _how_ to run the iterator in parallel).  For example, one way to do so would be to change the first for loop to a forall loop, as follows:

```chapel
iter rowmajor(param tag: iterKind, rowrange: range, colrange: range) where tag == iterKind.standalone {
	forall r in rowrange do
		for c in colrange do
			yield (r, c);
}
```

Another would be:

```chapel
iter rowmajor(param tag: iterKind, rowrange: range, colrange: range) where tag == iterKind.standalone {
	forall rc in {rowrange, colrange} do  // create a 2D domain from the two ranges and iterate over it
			yield rc;
}
```

Probably the most dependable way to see if it's running in parallel would be to run it over a large data set, print out the indices yielded, and see whether they come out in a semi-random order or not.  Simply relying on timing is not the best technique because the loop body may have a serial bottleneck which prevents speedup, or some other problem limiting performance...

**Comment by DanielFeshbach** [comment] 2017-05-30 16:43
I got it to run at the speed it should be running at by changing the for loops to forall loops in the standalone iter (it throws an error at me when I do it in the other iter):

```
iter rowmajor(param tag: iterKind, rowrange: range, colrange: range) where tag == iterKind.standalone {
	forall r in rowrange do
		forall c in colrange do
			yield (r, c);
}
iter rowmajor(rowrange: range, colrange: range) {
	for r in rowrange do
		for c in colrange do
			yield (r, c);
}
proc max2D_rowmajor(rowrange: range, colrange: range, a: [rowrange, colrange]){
	var max: real = a[(rowrange.first, colrange.first)];
	forall (r,c) in rowmajor(rowrange, colrange) with (ref max) do
		if a[(r,c)] > max then max = a[(r,c)];
	return max;
}
```

So it is working now! And to get it working at that speed I still need a forall loop in max2D_rowmajor.

**Comment by DanielFeshbach** [comment] 2017-05-30 16:44
Oh you commented while I was typing that!

**Comment by DanielFeshbach** [comment] 2017-05-30 16:45
Thanks for the suggestion about how to figure out whether it's running in parallel. It makes a lot of sense so I'll definitely do that in the future.

**Comment by bradcray** [comment] 2017-05-30 17:04
> it throws an error at me when I do it in the other iter

Yeah, serial iterators, by definition, may not contain yields within parallel code (otherwise, they wouldn't be serial).  Parallel iterators may be serial as your original one was, but in practice they typically aren't (because it defeats the purpose...).

I'm noting that your code has a race condition:

```chapel
	var max: real = a[(rowrange.first, colrange.first)];
	forall (r,c) in rowmajor(rowrange, colrange) with (ref max) do
		if a[(r,c)] > max then max = a[(r,c)];
	return max;
```

Imagine two distinct tasks are executing two different iterations of the forall loop simultaneously, and 'max' is currently '10'.  Imagine that the first task's value of a[r,c] is 12 and the second task's value is 14.  Moreover, imagine that the instructions from these tasks are interleaved by the HW/OS/runtime in the following manner:

* task 1 compares 12 to max (10) and finds it's larger
* task 2 compares 14 to max (10) and finds it's larger
* task 2 stores 14 to max
* task 1 stores 12 to max

This will make it seem that 12 was the maximum value found by the tasks when in fact it should've been 14.  This is a very common RRWW (read-read-write-write) race.

In order to avoid this type of race, you'd either need to do some sort of synchronization around the parallel reads and writes to `max` (like make it atomic or use a lock) or --- likely better for performance --- use a `reduce` intent such that each task has its own local value of `max` and combines it into the original variable using the `max` operation when it exits.  Here's a simple example of using this reduce intent on a forall loop (note that I avoid using the identifier `max` for my variables to avoid any potential confusion with the built-in `max` reduction):

```chapel
var mymax: real;
forall a in A with(max reduce mymax) do
  if a > mymax then mymax = a;

writeln(mymax);
```

Of course, you could also just use a reduce expression for a case like mine:

```chapel
var mymax = max reduce A;
```

and you should be able to do similarly for your iterator as well:

```chapel
var mymax = max reduce [(r,c) in rowmajor(rowrange, colrange)] a[r,c];
``` 

or equivalently:

```chapel
var mymax = max reduce (forall (r,c) in rowmajor(rowrange, colrange) do a[r,c]);
```

Finally, a few stylistic notes:

* there's no need to parenthesize `r` and `c` in ``a[(r,c)]`` --- `a[r,c]` is fine as well
* in all of these iteration contexts, if you're not using `r` and `c` separately, you can also just store them as a tuple and then index into `a` using the tuple:  ``forall rc in rowmajor(rowrange, colrange) do ... a[rc] ...``

**Comment by DanielFeshbach** [comment] 2017-05-30 21:04
I tried rewriting max2D_rowmajor with max reduce as you suggested:
```
proc max2D_rowmajor(rowrange: range, colrange: range, a: [rowrange, colrange]){
	var mymax: real;
	forall rc in rowmajor(rowrange, colrange) with (max reduce mymax) do
		if a[rc] > mymax then mymax = a[rc];
	return mymax;
}
proc max2D_rowmajor_2(rowrange: range, colrange: range, a: [rowrange, colrange]){
	return max reduce (forall rc in rowmajor(rowrange, colrange) do a[rc]);
}
proc max2D_rowmajor_3(rowrange: range, colrange: range, a: [rowrange, colrange]){
	return max reduce [rc in rowmajor(rowrange, colrange)] a[rc];
}
```
But when I run max2D_rowmajor it gives me the following error:
```
$CHPL_HOME/modules/internal/ChapelIteratorSupport.chpl:209: internal error: FUN5786 chpl Version 1.13.1

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see http://chapel.cray.com/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```
Meanwhile max2D_rowmajor_2 and max2D_rowmajor_3 run, but are even slower than the serial version. I also updated the non-iterator-based parallel and serial versions to use max reduce, and they are the same speeds as they were. I'd proceed by checking whether max2D_rowmajor_2 and 3 are running in parallel the way you suggested, but I can't figure out how to embed a write statement in them. So I guess I can't know for sure that this is the problem, but it does not seem as if they are running in parallel.

**Comment by bradcray** [comment] 2017-05-30 21:11
Thanks for reporting the internal error -- Could I get a complete copy of your program in order to try and reproduce the issue?

W.r.t. the apparent slowdowns, would you let me know how to reproduce once I have your code?  e.g., what problem size you're running?  And can you also confirm that you're compiling with the --fast flag?  Thanks.

And you're correct that it's a bit harder to put a debug write() into the forall expressions being reduced in your new versions.  One trick would be to replace the array accesses that you're reducing with a function call that takes the array element in, prints something out, then returns the array element (of course, this will be even slower, but it's a way to print from within an expression).

**Comment by DanielFeshbach** [comment] 2017-05-30 21:34
I have actually not been running with the --fast flag, because I did not know it existed. Now that I do, I tried it and it made the max functions too fast to measure and compare values. So I increased the size of the arrays I'm using, but quickly got to the point where the max functions were still too fast but something else in my program (probably filling the arrays with random numbers to test) was unconscionably slow.

My file should be attached. To test it, make sure the max2D function in timeTest is the one you want to be testing (currently set to max2D_rowmajor) and a call to timeTest is in the last line. To change the test sizes, adjust the parameters of timeTest: the first parameter is the test size to start with, the second parameter is the maximum test size, the third parameter is the interval between test sizes.

It's a .txt file because github doesn't support .chpl files.
[arraymax (copy).txt](https://github.com/chapel-lang/chapel/files/1039754/arraymax.copy.txt)

**Comment by DanielFeshbach** [comment] 2017-05-30 22:15
I tried you suggestion about making a separate function to put a debug write in:
```
proc testproc(a, rc: (int, int)){
	writeln(rc);
	return a[rc];
}

proc max2D_rowmajor_test(rowrange: range, colrange: range, a: [rowrange, colrange]){
	return max reduce (forall rc in rowmajor(rowrange, colrange) do testproc(a, rc));
}

var A = gen2D(1..3, 1..3);
writeln(max2D_rowmajor_test(1..3, 1..3, A));
```
The result of running this was:
```
(1, 1)
(1, 2)
(1, 3)
(2, 1)
(2, 2)
(2, 3)
(3, 1)
(3, 2)
(3, 3)
0.953636
```
Which appears to confirm that this is not running in parallel.

**Comment by bradcray** [comment] 2017-05-30 22:26
Thanks for providing the source.  What do I need to do to reproduce the internal error you ask about [above](https://github.com/chapel-lang/chapel/issues/6337#issuecomment-305007695)?  It seems like max2D_rowmajor() is still written as you quoted in that response, yet I'm not getting an internal error when compiling with either Chapel 1.15 or the master branch on github.  Are you still seeing the internal error?

> I have actually not been running with the --fast flag, because I did not know it existed.

I tried to give you a heads-up about it in my [first response](https://github.com/chapel-lang/chapel/issues/6337#issuecomment-304405466) (see the last paragraph).

> To change the test sizes, adjust the parameters of timeTest: the first parameter is the test size to start with, the second parameter is the maximum test size, the third parameter is the interval between test sizes.

As a style note, if you make these constants into config consts, you can change them from run to run rather than from compile-to-compile:

```chapel
config const lo = 500, hi = 5000, step=500;

timeTest(lo,hi,step);
```

Then you can run with, say:

```
./a.out --step=1000 --hi=4500
```

to override the defaults.

> It's a .txt file because github doesn't support .chpl files.

GitHub is so behind the times...

**Comment by bradcray** [comment] 2017-05-30 22:34
> The result of running this was:
> ...
> Which appears to confirm that this is not running in parallel.

Huh... when I run your same test code, I'm getting the output in arbitrary orders, so it does seem to be running in parallel.  Are you definitely running on a system with multiple processor cores?  What's the output of the following program for you?

```chapel
writeln(here.maxTaskPar);
```

**Comment by DanielFeshbach** [comment] 2017-05-30 22:35
I guess I missed where you originally mentioned the --fast flag. But actually, while I am happy to know that it exists now, I don't think it actually helps me here because what I'm doing is ultimately about comparing the speeds of different implementations, not actually putting it into something which needs to run quickly. The --fast flag works so well that it makes what I'm actually testing run too fast to make effective comparisons at the sizes I've been testing, but doesn't improve the speed of other things enough to be able to generate larger tests effectively.

Also thanks for the style suggestion about config consts, that could save me some time.

**Comment by DanielFeshbach** [comment] 2017-05-30 22:38
I am definitely running on a system with four cores. As such, the output of running that program is 4.

**Comment by bradcray** [comment] 2017-05-30 22:39
The danger of not using the --fast flag is that your program may spend all of its time doing unnecessary operations like NULL pointer checks or array bounds checks rather than the computation about which you're trying to draw conclusions, which would water down the results.  Not using the --fast flag is like not using -O when compiling a C benchmark that you're trying to compare.  A common trick to avoid having to create larger tests if some other bottleneck gets in the way is to run multiple trials of the computation of interest (potentially hundreds or thousands) and then divide the result by the number of trials.  In any case, I wouldn't trust any Chapel timings that were not gathered with the --fast flag.

**Comment by bradcray** [comment] 2017-05-30 22:42
Oh, with respect to both the serialization you mention and the internal error that I couldn't produce, I'd forgotten between Friday and today that you're using Chapel 1.13.1.  Upgrading to Chapel 1.15.0 should solve both of these issues (i.e., I was able to reproduce both of them once I switched to Chapel 1.13.1).  This should also provide you with several other nice improvements, bug fixes, and features going forward.

**Comment by DanielFeshbach** [comment] 2017-05-30 22:43
To reproduce my error, rename the file "arraymax_copy.chpl" and type in the terminal:
`chpl -o atest arraymax_copy.chpl`

As for the --fast flag, thank you for telling me this, I will now try generating some larger random arrays to output to a file on which to run tests so I don't have to generate them every run.

**Comment by DanielFeshbach** [comment] 2017-05-30 22:44
Oh okay, I'll definitely switch then!

**Comment by DanielFeshbach** [comment] 2017-05-30 22:47
Thanks so much for all the help, I'll post here if related issues remain after switching.

**Comment by bradcray** [comment] 2017-05-30 22:53
You're welcome.  I'm going to close this issue for a sense of resolution and so that any new issues you run into may help others by being top-level issues that they'll have a better chance of finding in a search.

**Closed by bradcray** 2017-05-30 22:53 UTC
Labels: area: Compiler, type: Bug, user issue
