### ISSUE TITLE
LinearAlgebra Solve() changes input array, gives wrong answer

### ISSUE THREAD

**Issue by sdbachman** [chapel-lang/chapel#24095] opened 2023-12-15 05:31 UTC
The issue is demonstrated by the following test code (the numbers in M and b are arbitrary):

------------------------------------------------

use LinearAlgebra;

var M : [0..5, 0..5] real;

M[0,..] = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0];
M[1,..] = [1410.47, 2246.66, 836.194, 0.0, 0.0, 0.0];
M[2,..] = [0.0, 758.597, 1463.83, 705.234, 0.0, 0.0];
M[3,..] = [0.0, 0.0, 363.457, 742.756, 379.298, 0.0];
M[4,..] = [0.0, 0.0, 0.0, 171.054, 352.782, 181.729];
M[5,..] = [0.0, 0.0, 0.0, 0.0, 0.0, 1.0];

var B : [0..5] real = [0.0, -1.61637e+08, -2.22976e+08, -1.56702e+08, -8.82075e+07, 0.0];

writeln("B before:\n", B);

var tmp = solve(M, B);

writeln("B after:\n", B);

writeln("tmp:\n", tmp);

-------------------------------------------

B before:
0.0 -1.61637e+08 -2.22976e+08 -1.56702e+08 -8.82075e+07 0.0
B after:
-1.61637e+08 -2.22976e+08 -1.56702e+08 -8.82075e+07 0.0 0.0
tmp:
-8.83858e-11 -25433.6 -1.24967e+05 -29426.0 -2.35766e+05 0.0

We also know this is incorrect because, based on the inputs, the first and last elements of "tmp" should be zero.

**Comment by bradcray** [comment] 2023-12-15 06:08
@sdbachman : Apart from the answer, the fact that B changed definitely seems suspect, right?  I'm noticing that it seems to have shifted by an element, which is odd, and suggests some sort of 0/1 indexing issue.  What version of Chapel are you using?  (I seem to be able to reproduce it with `chpl version 1.34.0 pre-release (8371b2af80)`, so am curious whether you're using a similar recent version or whether this has been the behavior for some time).

I'm tagging @Guillaume-Helbecque on this, knowing that he touched this routine recently, on the offchance that he has any insights.

**Comment by Guillaume-Helbecque** [comment] 2023-12-15 10:31
As far as I know, the changes of the input vector `B` is the expected behaviour of the `solve` procedure. More precisely, `solve` computes an LU factorization of `M` using partial pivoting, and for some reasons, the permutation is then applied to `B`. I don't know what motivates this behaviour, but I agree that it is strange and would not be expected in practice.

For the wrong answer, I suspect an issue with the precision of floating-point numbers. Indeed, you expected 0.0 as first element of `tmp`, but you get -8.83858e-11, which is essentially zero.

**Comment by damianmoz** [comment] 2023-12-15 17:22
As Guillaume correctly notes, _solve_ does in fact alter its original `B` argument due to the pivoting strategy. Why this is exposed to the user, I do not know.  
I see a slightly worse answer in the first element of the solution vector, -2.53552e-10 with the latest compiler. But, yes, that is the result of the underlying algorithm..  If you normalize the solution vector, the first element is just slightly more than 4 times the machine precision. So you have only lost 2 binary digits in accuracy which is extremely close to zero, again as correctly noted by Guillaume. A single pass of an enhanced precision iterative improvement might reduce that discrepancy

**Comment by sdbachman** [comment] 2023-12-15 18:26
Thanks everyone!   In my real code I was writing out `B` as a sanity check, so you can imagine my stress when I was `B` was changing after the Solve.   It is good to confirm that this is expected behavior.

**Comment by damianmoz** [comment] 2023-12-15 21:58
One could argue that the behavior be changed to not alter that input vector.

**Comment by damianmoz** [comment] 2023-12-15 23:30
Try
```chapel
proc solve(A: [?Adom] ?eltType, ref b: [?bdom] eltType) {
  var (LU, ipiv) = lu(A);
  var y = permute (ipiv, b, true);
  var z = solve_tril(LU, y);
  var x = solve_triu(LU, z);
  return x;
}
```
in LinearAlgebra. That will not affect the original parameter `b`.

**Comment by bradcray** [comment] 2023-12-16 16:07
Echoing Scott, thanks for the assists here, Guiillaume and Damian!  It sounds as though all here agree that it would be better for the routine not to modify the `b` input argument, is that right?  (or, if not, to at least document that it will be changed).  

I think the way I'd achieve the "don't modify `b`" would be to change its argument into to `in`, which would give the routine a local copy of `b` to play with if need be (or to steal the actual argument if it is dead after this), while documenting the potential for a copy.  So:

```chapel
proc solve(A: [?Adom] ?eltType, in b: [?bdom] eltType) {
  var (LU, ipiv) = lu(A);
  b = permute(ipiv, b, true);
  var z = solve_tril(LU, b);
  var x = solve_triu(LU, z);
  return x;
}
```

**Comment by damianmoz** [comment] 2023-12-17 03:45
As an aside, the approach taken by LinearAlgebra generally follows the style  of MATLAB and does not overwrite the space used by matrix and vector parameters. This gobbles up memory, sometimes inordinately so if used without care.

The other approach is to overwrite space, i.e. the LU decomposition of A replaces A, the solution of `Ax=b` is overwritten in `b`, etc. If there  is a need to keep a copy of the original data, that must be copied explicitly and saved elsewhere. This is a more fine grained approach. It avoids memory blowouts but requires slightly more work. This is the approach taken by tools such as LAPACK.

**Comment by damianmoz** [comment] 2023-12-17 05:16
Scott, what error did you expect in your solution vector?

**Comment by vasslitvinov** [comment] 2024-01-31 03:11
@sdbachman How do the following address this issue?

* With #24294, `solve()` no longer modifies its actual arguments.

* The the last element of `tmp` in your test code is `0`; the first element of `tmp` is close to zero.

Can this issue be closed now?

**Comment by bradcray** [comment] 2024-02-02 05:37
@vasslitvinov : Thanks for the fix here!  I'm going to assert that we're in better shape now w.r.t. this issue and close this, but Scott, please let us know if you find or think otherwise.  Thanks for reporting the issue!

**Closed by bradcray** 2024-02-02 05:37 UTC
Labels: type: Bug, area: Libraries / Modules, user issue
