### ISSUE TITLE
Support C++ headers in compileline

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7666] opened 2017-10-26 22:58 UTC
`compileline` barfs on C++ headers

hello.cpp
```cpp
/* Hello World program */

//#include<stdio.h>   // just fine
#include<iostream>  // gastro-intestinal distress...

int main()
{
    printf("Hello World\n");
}
```

And the `Makefile`
```make
default: hello.cpp
	`/Users/buddha/github/chapel/util/config/compileline --compile` $<
```

If you watch closely, you can see it:

```bash
make default
`/Users/buddha/github/chapel/util/config/compileline --compile` hello.cpp
In file included from hello.cpp:4:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/iostream:38:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/ios:216:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__locale:18:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/mutex:189:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__mutex_base:17:
/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support:156:1: error: unknown type name 'mach_port_t'
mach_port_t __libcpp_thread_get_port();
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support:300:1: error: unknown type name 'mach_port_t'
mach_port_t __libcpp_thread_get_port() {
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support:301:12: error: use of undeclared identifier 'pthread_mach_thread_np'
    return pthread_mach_thread_np(pthread_self());
           ^
3 errors generated.
make: *** [default] Error 1
```

```bash
chpl --version
chpl Version 1.17.0 pre-release (8e8a423107)
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```

```bash
 printchplenv 
machine info: Darwin macbuddha.lan 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
CHPL_HOME: /Users/buddha/github/chapel *
script location: /Users/buddha/github/chapel/util
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```

**Comment by bradcray** [comment] 2017-10-30 23:46
I'm not able to reproduce this.  Are you able to compile the file manually with your copy of clang++ or do you get the same errors?  (in which case your C++ installation may be the issue, not `compileline`).

```
$ make -f Makefile.test
`$CHPL_HOME/util/config/compileline --compile` hello.cpp
$ 
```

**Comment by buddha314** [comment] 2017-10-31 15:38
I'm not sure I understood your note completely, so I tried this.

```c
/* Hello World program
 * `/Users/buddha/github/chapel/util/config/compileline --compile` hello.cpp
 * */

//#include<stdio.h>   // just fine
#include<iostream>  // gastro-intestinal distress...

int main()
{
    printf("Hello World\n");
}
```

Then ran w/o a make file

```
> clang++ hello.cpp; ./a.out 
Hello World
> clang hello.cpp; ./a.out 
Hello World
```

Then using `compileline` straight from the command line

```bash
#include<stdio.h>
> `/Users/buddha/github/chapel/util/config/compileline --compile` hello.cpp; ./a.out
Hello World

#include<iostream>
>  `/Users/buddha/github/chapel/util/config/compileline --compile` hello.cpp; ./a.out
In file included from hello.cpp:6:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/iostream:38:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/ios:216:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__locale:18:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/mutex:189:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__mutex_base:17:
/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support:156:1: error: unknown type name 'mach_port_t'
mach_port_t __libcpp_thread_get_port();
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support:300:1: error: unknown type name 'mach_port_t'
mach_port_t __libcpp_thread_get_port() {
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support:301:12: error: use of undeclared identifier 'pthread_mach_thread_np'
    return pthread_mach_thread_np(pthread_self());
           ^
3 errors generated.
```

**Comment by bradcray** [comment] 2017-10-31 16:10
I think I'm missing something.  What's the difference between the two "straight from the command line" cases where the first seemed to work and the second didn't?  Or is the point that it works the first time but not in subsequent invocations?

**Comment by buddha314** [comment] 2017-10-31 16:30
One is `clang++` and the other is `clang`, just being thorough. I know it's an alias.

**Comment by buddha314** [comment] 2017-10-31 16:35
Sorry, wrong answer. The first `compileline` uses `#include <stdio.h>` and the second uses `#include<iostream>`

**Comment by bradcray** [comment] 2017-11-01 00:03
I'm still not able to reproduce this, with either #include enabled.  I assume that the manual invocations of clang++ that you showed were also with the `#Include <iostream>` enabled?

I think the next step here is to hand-modify the `compileline` script to have it print out the commands that it's executing and then see how they differ from what you've done by hand.  There's some "uncomment this code to do that" code within the script, but when I tried to get it running yesterday I failed.  Will try again tomorrow unless you / someone else beats me to it.

**Comment by nspark** [comment] 2017-11-01 12:06
When I run `$CHPL_HOME/util/config/compileline --compile`, the output makes it clear that the underlying compiler being invoked is `gcc` or `clang`, depending on how `CHPL_TARGET_COMPILER` is set. (To be clear, I'm on Linux, not macOS.) Both compilers will automatically select C or C++ for the language front-end based on the extension type (i.e., `*.c` vs. `*.cpp`), but compiling C++ code with `clang` or `gcc` (vs. `clang++` or `g++`) gives me undefined reference linker errors that are resolved by linking the appropriate C++ standard library (i.e., adding the `-lstdc++` or `-lc++` flags). The point is that even though `clang++` may be an alias to `clang`, the name of `argv[0]` actually does affect the compilation and linking behavior for sources of different languages.

For my tests, I updated `hello.cpp` to the following:
```c++
#if defined(__cplusplus)
#include <iostream>
#else
#include <stdio.h>
#endif

int main(void)
{
#if defined(__cplusplus)
  std::cout << "Hello, world! (C++)\n";
#else
  printf("Hello, world! (C)\n");
#endif
  return 0;
}
```

I compiled `hello.cpp` with both `gcc` and `clang` using C or C++ as the language by setting the `-x <language>` flag explicitly and got the results that I expected:
```bash
export CHPL_TARGET_COMPILER=gnu
$($CHPL_HOME/util/config/compileline --compile) -x c   hello.cpp          && ./a.out
# Output: Hello, world! (C)
$($CHPL_HOME/util/config/compileline --compile) -x c++ hello.cpp -lstdc++ && ./a.out
# Output: Hello, world! (C++)

export CHPL_TARGET_COMPILER=clang
$($CHPL_HOME/util/config/compileline --compile) -x c   hello.cpp          && ./a.out
# Output: Hello, world! (C)
$($CHPL_HOME/util/config/compileline --compile) -x c++ hello.cpp -lc++    && ./a.out
# Output: Hello, world! (C++)
```

I'm not sure whether this helps (since I can't test on macOS), but I think there's more to compiling as C++ vs. C than just the file extension.

**Comment by buddha314** [comment] 2017-11-01 15:36
What should I do next?  I'm not sure re-writing `compileline` is within my skill set.

**Comment by nspark** [comment] 2017-11-02 00:40
@buddha314 I'm not sure what you mean. You seem to be invoking `compileline` from within a Makefile. Does invoking `compileline` with the extra flags in my earlier comment resolve your issue? If so, can you add those arguments to your Makefile?

**Comment by mppf** [comment] 2017-11-16 16:07
@buddha314 - I too am confused by this issue. My question is this - why are you using compileline --compile at all? Did you need includes, defines, C compiler flags, or the name of the configured C compiler? Many of these can be gotten separately from --compile.

**Comment by buddha314** [comment] 2017-11-16 16:54
Sorry, I let this slip.  @nspark no, it did not compile even with your flags.  I was using `compileline`  to be able to call a chapel program from within C++.  I was getting the error on the compilation of the `.cpp` file, so I removed the Chapel call entirely to see what would happen.

**Comment by mppf** [comment] 2017-11-16 17:30
@buddha314 - are you able to try the version for this PR: #7814 ? It adds a --compile-c++ option which would presumably solve your problem.

**Comment by mppf** [comment] 2017-11-28 14:13
@buddha314 - I just merged PR  #7814 which adds --compile-c++ option. Do you feel that addresses your concern? If so, let's close this issue.

**Comment by buddha314** [comment] 2017-11-29 17:49
Let me try this today and get back.

**Comment by buddha314** [comment] 2017-11-29 18:15
YES!  This worked!

```
`/Users/buddha/github/chapel/util/config/compileline --compile-c++` hello.cpp 
```

against 

```
/* Hello World program
 * `/Users/buddha/github/chapel/util/config/compileline --compile` hello.cpp
 * */

//#include<stdio.h>   // just fine
#include<iostream>  // gastro-intestinal distress...

int main()
{
    printf("Hello World\n");
}
```

let's close this baby!

**Closed** 2017-11-29 18:23 UTC
Labels: type: Feature Request, user issue

**Comment by bradcray** [comment] 2017-11-29 21:32
I'm trying to catch up on this thread and understand its relationship to the [StackOverflow question](https://stackoverflow.com/questions/47559380/compiling-c-with-chapels-compilelinei/47560938#47560938) Brian posted today.  Thanks for helping with this Michael—I've had this issue open in my browser for weeks hoping to find time to look into it more.

Interpretations of Brian's SO question include:

* he accidentally switched from '--compile-c++` to `--compile`
* he's suggesting in a roundabout way that the documentation should be updated (which looks like it might be correct to me)
* something else is wrong that I'm not understanding

I still can't reproduce either the original issue or Brian's version of it, suggesting to me that we're using different versions of clang/clang++ or something underlying.

**Comment by buddha314** [comment] 2017-11-29 21:37
Briefly, when I was doing it and following the docs, I was using just "--compile" and that was before the commit yesterday. Now, with "--compile=c++" it works.  So the SO (I think) is answerable by simply saying "pull the new version and do --compile=c++".

As to reproducing it.  I am, as they say, often imitated by but never duplicated.  You're wasting your time buying blue glasses trying to be me.

**Comment by bradcray** [comment] 2017-11-29 22:55
@mppf: Would you agree that the documentation should be updated to reflect the changes in PR #7814?  I'd be more comfortable posting the answer Brian suggests on SO if the master version of the documents reflected the change that had been implemented in some manner.
