### ISSUE TITLE
Having error message during 1.27.0 install compile.

### ISSUE THREAD

**Issue by kurtnordlander** [chapel-lang/chapel#20363] opened 2022-08-03 15:24 UTC
After downloading, and checking prerequisites, I began the 'make' to begin 
the chapel code compiling process. After several minutes of watching compiling
process, it quit with the following error message:

topo-hwloc.c:43:10: fatal error: hwloc.h: No such file or directory
   43 | #include "hwloc.h"
      |          ^~~~~~~~~
compilation terminated.

I also went through the compiling info and came across this warning: 

n file included from /home/kurt/chapel-1.27.0/third-party/hwloc/hwloc-src/src/topology.c:45:
/usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: warning: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Wcpp]
   21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
      |  ^~~~~~~

Here is the output from printchplenv:

Warning: $~/.chplconfig:line 21: "CHPL_REGEXP" is not an acceptable variable
Warning: $~/.chplconfig:line 22: "CHPL_WIDE_POINTERS" is not an acceptable variable

machine info: Linux Triton 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64
CHPL_HOME: /home/kurt/chapel-1.27.0 *
script location: /home/kurt/chapel-1.27.0/util/chplenv
CHPL_TARGET_PLATFORM: linux64 +
CHPL_TARGET_COMPILER: gnu +
CHPL_TARGET_ARCH: native +
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat +
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none +
CHPL_TIMERS: generic +
CHPL_UNWIND: none +
CHPL_MEM: cstdlib *
CHPL_ATOMICS: intrinsics +
CHPL_GMP: none *
CHPL_HWLOC: hwloc +
CHPL_RE2: none *
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none +

Honestly, I have no clue.
Thank you for checking this out.

**Comment by e-kayrakli** [comment] 2022-08-03 15:50
> Honestly, I have no clue.

Me, too! :)

Hi @kurtnordlander -- please check out the issue template (that you've deleted while creating this) on how to report a bug. At a minimum, we'd need to see the error message and the output from `printchplenv`. Ideally, some system information, too.

**Comment by bradcray** [comment] 2022-08-03 17:36
@kurtnordlander : Thanks for reporting this.  Since hwloc is a third-party package we bundle, I did a google search on the warning message and hwloc and found my way to [this issue](https://github.com/open-mpi/hwloc/issues/384) which suggests to me that its cause relates to glibc versions and that it may have long since been resolved by newer releases of hwloc (?).

We have some internal issues about updating the hwloc 2.x (https://github.com/Cray/chapel-private/issues/795 and https://github.com/Cray/chapel-private/issues/3585 for Chapel developers), and I believe @jhh67 is currently working this and may (?) have a branch that would be interesting to have you try.  @ronawho will also likely be interested when he's back from vacation.

In the meantime, I wonder whether setting `CHPL_HWLOC=none` to disable the use of hwloc will help you make some forward progress?  I'm seeing that we also have an `#include` of `sys/sysctl.h` in our runtime, so there's a chance you'll just hit the same issue later in compilation, but maybe not depending on which flags we throw relative to hwloc (?).

**Comment by ronawho** [comment] 2022-08-08 19:11
Can you provide more information so we can try to reproduce the issue (in particular OS flavor/version and gcc version would be helpful)

I'd also like to better understand how you ended up with your chplenv settings. In particular why you selected `CHPL_TASKS=fifo`, `CHPL_ATOMICS=intrinsics`, and  `CHPL_MEM=cstdlib`

**Comment by bradcray** [comment] 2022-08-09 17:20
@kurtnordlander : Backing away from my previous comment a bit:  I'm accustomed to warnings being errors as a developer and am only realizing now that that warning shouldn't have broken the hwloc build.  In addition to Elliot's question above, I'd be curious what the C compiler invocation line for `topo-hwloc.c` looks like and also what you see for `cd $CHPL_HOME/third-party/hwloc/install && ls`.

Beyond that, if you're willing to share your full build log, that could be particularly helpful.

**Comment by jabraham17** [comment] 2024-07-09 23:26
Closing this, as I would expect the upgrade to hwloc 2.x to resolve this issue. @kurtnordlander, feel free to reopen this issue if it is still causing problems on main

**Closed by jabraham17** 2024-07-09 23:26 UTC
Labels: type: Bug, area: Makefiles / Scripts, user issue
