### ISSUE TITLE
PCGRandomStream does not default the seed to the current time

### ISSUE THREAD

**Issue by nspark** [chapel-lang/chapel#5281] opened 2017-01-30 18:52 UTC
### Summary of Problem
The `RandomStream` class in the `PCGRandom` module does not appear to set the default seed to the current time, as documented. The output of pseudo-random values is identical from run-to-run, even across different systems. I expected the pseudo-random values to vary from run-to-run, as one would see with `srandom(time(NULL))` and `random()` in C.

### Steps to Reproduce

**Source Code:**

```chapel
use Random.PCGRandom;

var R = new RandomStream(uint);
for i in 1..10 do
  writeln(R.getNext() % 100);
```

**Compile command:**
`chpl test-pcg-random.chpl -o test-pcg-random`

**Execution command:**
`./test-pcg-random`

**Output:**
```
0
0
94
62
28
10
41
53
39
79
```

### Configuration Information

- Output of `chpl --version`: 1.14.0
- Environments:
  - Cray chapel/1.14.0 module
  - Source build with `CHPL_UNWIND=libunwind`, `CHPL_GMP=gmp`, and `CHPL_REGEXP=re2` set

**Comment by nspark** [comment] 2017-01-30 18:54
I noticed that `PCGRandom.RandomStream` behaves as expected with the following change:

```chapel
use Random.PCGRandom;

var R = new RandomStream(eltType=uint); // Added "eltType="
for i in 1..10 do
  writeln(R.getNext() % 100);
```

This is a bit surprising, and I think the case identified in the bug report should be supported as valid behavior.

**Comment by bradcray** [comment] 2017-01-30 19:58
@mppf: Can you take a look at this one?

**Comment by mppf** [comment] 2017-02-02 22:35
Another work-around is to use makeRandomStream(eltType=uint). The problem is that the compiler-generated constructor is being called in your first version:
```chapel
var R = new RandomStream(uint);
```

Really there are two problems in the implementation:
 1) The constructor in RandomStream does not prevent the compiler-generated constructor from being made
 2) Function resolution doesn't match actual arguments to formal arguments based upon type/param-ness. For example:
    ```chapel
    proc f(x:int = 1, type t = real) {
      writeln("in f(", x, ", ", t:string);
    }

    f(uint);
    ```

    does not compile.

I intend to look and the second issue but would prefer to wait for generic new-style initializers to be complete to solve the first issue.

**Comment by bradcray** [comment] 2017-02-02 23:00
I don't think that the example in item 2 above should compile.  By analogy, the following is not intended to compile:

    proc f(x: int = 1, y: string = "hello") {
      writeln("in f(", x, ", ", y);
    }

    f("hi");

In the absence of keyword-based argument passing, the language only matches things positionally; it doesn't try to find a "best match" for arguments based on type or kind (e.g., type or param).  I'm not inclined to change the language in this regard because I think it will result in more confusion and ambiguity in resolving function calls than benefit.

**Comment by bradcray** [comment] 2017-02-02 23:10
@mppf: A couple of other questions/thoughts:

* I think in the new initializers world, the current proposal is that the presence of a user-defined initializer will prevent the compiler-defined initializer from being created.  If that was the case, would that change be sufficient?  (i.e., you seem to be saying that issue 1 and 2 need to be fixed, but why would fixing issue 1 by itself not be sufficient?)

* Is there any reason not to reorder either the fields in RandomStream or the arguments in its user-defined constructor to match the other so that the compiler-generated constructor would not win in @nspark's case?  (I'm guessing that the former would be less impactful on existing user code, while the latter would give Nick the call he wants.  I did a quick check and it seems to work).

**Comment by mppf** [comment] 2017-02-03 14:23
@bradcray - good point about positional vs. named argument matching. I was mis-remembering the rules for normal functions.

I'm not sure what (if any) solution beyond waiting for better initializers is called for. The solutions I can see are these:

Changing it into a error:
 1. add a run-time check, in an initialize() method, that seed != 0
 2. re-order the fields to match the constructor argument order
 3. use new-style generic initializers (once they are ready / longer term)

Making the example work correctly as written:
 4. add a constructor to RandomStream and NPBRandomStream with a type first argument (but note, it might lead to ambiguity with calls with by-name if it has the same defaults)
 5. re-order the constructor arguments in RandomStream and NPBRandomStream to put the type argument first

Can we justify changing the order of the constructor arguments? It will impact existing code... would we need a deprecation warning? I think I agree with @nspark that a default seed (based on time) is probably more useful than a default element type (real), but I'd personally prefer to see people use named-argument-passing in such cases.

**Comment by bradcray** [comment] 2017-02-03 17:36
I share the hesitation of reordering arguments in a constructor and its impact on user codes, though I also share Nick's intuition that the current order is strange (doesn't put the arguably most important arguments first).  With a quick check, it appears to me that we could support two user-defined constructors with both argument orders, either for one release (where the old order gives a deprecation warning) or forever.  The former is my preference.  It seems to make Nick's test work unless I did something wrong (it really was  a quick check).

In the reordered constructor, I'd also be inclined to not give 'eltType' a default type...  Seems a little arbitrary (and probably was done more as a nod to the floating-point-only random streams of the past than the present?).

**Comment by mppf** [comment] 2017-02-03 18:06
I don't see how we can support two orders. E.g.:
``` chapel
proc f(a = 1, b = 2) {
  writeln("f (", a, ",", b, ")");
}
proc f(b = 2, a = 1) {
  writeln("f'(", a, ",", b, ")");
}


f(a = 1);
```

```
ab.chpl:10: error: ambiguous call 'f(a=1)'
ab.chpl:2: note: candidates are: f(a = 1, b = 2) [185621]
ab.chpl:5: note:                 f(b = 2, a = 1) [185673]
```

but `f(a=1)` would have worked before we added the 2nd order. Isn't the RandomStream constructor in the same situation?

I think all 3 of us think the type should go first in the argument list; that's probably worth changing. I just don't think we can get a deprecation / backward compatible solution. (Maybe if we re-named the eltType argument? but I'm not sure that is worrth it just for deprecation.....)

**Comment by bradcray** [comment] 2017-02-03 18:29
Good point.  I wasn't using a keyword-based call which is why my simple example was working.  As you point out, we could use different argument names for one of the two constructors -- but of course, we'd want to use the ideal argument names for the new constructor.  And we have to use the field names for the param/type arguments for now in constructors (if generic initializers were on-board, we could rename everything).  

So now I'm trying to think what would break if the old constructor renamed 'seed' to 'initSeed' and kept the generic arguments the same.  If the user used a keyword-based call involving the seed, they'd get the new constructor and be none the wiser; if they used positional arguments, they'd get the old one and the deprecation warning; if they used a mix... they might get into trouble?; oh, but if they only said eltType=uint, they'd get an ambiguity again...  Hmm...

I think that given we're in early days yet in terms of long-term users and codes, getting the argument order "right" from this point onward is more important than having bulletproof deprecation warnings, so would advocate for reordering the arguments and apologizing for users whose codes break.  Or, we could wait until generic initializers are online, at which point we can rewrite the old constructor argument order to use different names and avoid the ambiguity.

**Comment by mppf** [comment] 2017-02-03 21:48
I have a new idea for how we can get a deprecation warning - use pragma "compiler generated" which gets resolution to only use that function if there's no non-compiler-generated option.
``` chapel
proc f(a = 1, b = 2) {
  writeln("f (", a, ",", b, ")");
}
pragma "compiler generated"
proc f(b = 2, a = 1) {
  writeln("f'(", a, ",", b, ")");
}


f(a = 1);
```

works as expected.

**Closed** 2017-02-08 11:34 UTC
Labels: area: Modules, type: Bug, user issue
