### ISSUE TITLE
Passing Shared(Derived) to formal expecting Shared(Parent)

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#8179] opened 2018-01-11 18:50 UTC
It would be useful to support passing a derived Shared object to a formal argument accepting a Shared parent object.

```
class Parent { // Abstract Base Class
  proc method() { halt("Called ABC method"); }
}

class Derived: Parent {
  proc method() { writeln("Derived.method()"); }
}

proc f(x: Shared(Parent)) {
  x.method();
}

f(new Shared(new Derived()));
```

This would be useful for example in the `DateTime.time` type, where the `tzinfo` field is of the abstract type `Shared(TZInfo)`, but to use it you need pass in a concrete type.  Currently it requires a cast back to the base type: `new time(tzinfo = new Shared(new ConcreteTZ(): TZInfo))`.

**Comment by cassella** [comment] 2019-03-09 17:00
This works now, with warnings about `Shared` being obsolete, and `override` being recommended.

Modified per the warnings, it still works.

**Comment by lydia-duncan** [comment] 2019-09-18 16:08
I just tried what I think Paul tried:

```chapel
class Parent { // Abstract Base Class
  proc method() { halt("Called ABC method"); }
}

class Derived: Parent {
  override proc method() { writeln("Derived.method()"); }
}

proc f(x: shared Parent) {
  x.method();
}

f(new shared Derived());
```

Unfortunately, this no longer works the way it did when he checked.  I'm currently getting the following error message:
```
dynamic-dispatch.chpl:13: error: value from coercion passed to const ref formal 'x'
dynamic-dispatch.chpl:9: error: to function 'f' defined here
dynamic-dispatch.chpl:9: note: default intent for shared Parent has changed from `in` to `const ref`
```
which is distinct from the original issue David reported.  It looks like the `time` initializer in the DateTime module has an explicit `in` intent and so avoid this error message - adding an `in` intent to the toy program allows it to compile and run as intended.  I don't feel I know enough about `shared` to say for certain, but I think this means there is something wrong for coercions and `shared`.  @mppf - do you agree?  If so, I will commit this as a test, open a separate issue to track and close this one.

**Comment by mppf** [comment] 2019-09-18 16:44
> but I think this means there is something wrong for coercions and shared. @mppf - do you agree?

no, there is nothing wrong with this example. It should only work with the `in` intent (which used to be the default and is no longer). Otherwise it is running into the known issue #8489. I believe this issue can be closed.

**Closed** 2019-09-18 16:47 UTC
Labels: area: Compiler, area: Language, type: Feature Request
