### ISSUE TITLE
COMPILE: 1.25.0: make clean error in primers

### ISSUE THREAD

**Issue by tonycurtis** [chapel-lang/chapel#18464] opened 2021-09-25 22:57 UTC
The GNU_PROPERTY_TYPE thing is already known as a binutils issue (#18454).

### Summary of Problem

```
login1[2](~) cd  chapel/chapel-1.25.0/
login1[2](~/chapel/chapel-1.25.0) source util/setchplenv.bash
Setting CHPL_HOME to /lustre/home/arcurtis/chapel/chapel-1.25.0
Updating PATH to include /lustre/home/arcurtis/chapel/chapel-1.25.0/bin/linux64-aarch64
                     and /lustre/home/arcurtis/chapel/chapel-1.25.0/util
Updating MANPATH to include /lustre/home/arcurtis/chapel/chapel-1.25.0/man
login1[2](~/chapel/chapel-1.25.0) cd examples/primers/
login1[2](~/chapel/chapel-1.25.0/examples/primers) chpl locales.chpl
/usr/bin/ld: warning: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/gmp/install/linux64-aarch64-unknown-llvm-none/lib/libgmp.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/ld: warning: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/gmp/install/linux64-aarch64-unknown-llvm-none/lib/libgmp.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/ld: warning: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/gmp/install/linux64-aarch64-unknown-llvm-none/lib/libgmp.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/ld: warning: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/gmp/install/linux64-aarch64-unknown-llvm-none/lib/libgmp.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/ld: warning: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/gmp/install/linux64-aarch64-unknown-llvm-none/lib/libgmp.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/ld: warning: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/gmp/install/linux64-aarch64-unknown-llvm-none/lib/libgmp.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/ld: warning: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/gmp/install/linux64-aarch64-unknown-llvm-none/lib/libgmp.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/ld: warning: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/gmp/install/linux64-aarch64-unknown-llvm-none/lib/libgmp.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/ld: warning: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/gmp/install/linux64-aarch64-unknown-llvm-none/lib/libgmp.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/usr/bin/ld: warning: /lustre/home/arcurtis/chapel/chapel-1.25.0/third-party/gmp/install/linux64-aarch64-unknown-llvm-none/lib/libgmp.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
login1[2](~/chapel/chapel-1.25.0/examples/primers) make clean
chpl interopWithC.chpl cHelper.h cHelper.c fact.h fact.c --library --library-makefile --savec ccode
In file included from <built-in>:8:
In file included from ccode/chpl_mli_server.c:2:
In file included from /lustre/home/arcurtis/chapel/chapel-1.25.0/runtime/etc/src/mli/chpl-mli-server-runtime.c:24:
/lustre/home/arcurtis/chapel/chapel-1.25.0/runtime/etc/src/mli/chpl-mli-common-runtime.c:49:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
         ^~~~~~~
1 error generated.
error: error running clang during code generation
rm -f arrays associative atomics chpldoc.doc classes distributions domains errorHandling fileIO forallLoops genericClasses iterators learnChapelInYMinutes listOps locales modules nothingVariables parIters procedures randomNumbers ranges records reductions replicated slices sparse specialMethods syncsingle taskParallel timers tuples varargs variables  cClient interopWithC arrays_real associative_real atomics_real chpldoc.doc_real classes_real distributions_real domains_real errorHandling_real fileIO_real forallLoops_real genericClasses_real iterators_real learnChapelInYMinutes_real listOps_real locales_real modules_real nothingVariables_real parIters_real procedures_real randomNumbers_real ranges_real records_real reductions_real replicated_real slices_real sparse_real specialMethods_real syncsingle_real taskParallel_real timers_real tuples_real varargs_real variables_real cClient_real interopWithC_real
login1[2](~/chapel/chapel-1.25.0/examples/primers)
```

### Configuration Information

- Output of `chpl --version`:
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
- (For Cray systems only) Output of `module list`:

**Comment by bradcray** [comment] 2021-09-27 16:16
@lydia-duncan / @stonea : Would one of you be able to take this as a follow-up to reviewing #18030?

**Comment by tonycurtis** [comment] 2021-09-27 18:12
The GNU_PROPERTY_TYPE appears to be because the binutils is slightly older.   This will be rectified after some maintenance window in a week or so, let's call it a non-issue.

**Comment by bradcray** [comment] 2021-09-30 19:30
@stonea: Any further progress here?  Anything I/we can help out with?

**Comment by stonea** [comment] 2021-10-01 00:34
Hi @bradcray , it's kind of interesting\confusing question of what we should do here.  I definitely want someone more familiar with how Makefiles work to chime in.

There's actually two problems I see:

1. Not finding zmq.h on Tony's system
2. Trying to generate the "Makefile helper" when doing "make clean"

For (1): I haven't been able to reproduce this.  It looks like `chpl-mli-common-runtime` wants this. Do you know what this runtime is and under what conditions `chpl` would need it?  I think we might want to fork that out onto a separate issue.

I've spent more time thinking about this second bullet. The interoperability primer wants to illustrate that you can have a Makefile for your Chapel project that include a "makefile helper" (see: https://chapel-lang.org/docs/technotes/libraries.html#makefile-helper)

We have a single Makefile for all the primers (see here: https://github.com/chapel-lang/chapel/blob/main/test/release/examples/primers/Makefile). So, for the interoperability primer we have the Makefile illustrating:

* how to generate the Makefile helper
  * Specifically with this rule:  
     ```makefile
     lib/Makefile.interopWithC:
       $(CHPL) $(INTEROP_DEPS) $(INTEROP_LIB_OPTS)
     ```
* and how to use the Makefile helper
  * specifically with this line: `-include lib/Makefile.interopWithC`

The problem is really you would only want to do this if you're making cClient, but the `-include` directive gets included indiscriminately and as a side effect forces its generation even when your Make target is something unrelated like "clean".

As a hack solution I think we could do something like this, which will only include the Makefile helper if its invoked in one of the following ways:

* 'make'
* 'make all'
* 'make cClient'

```makefile
ifeq ($(MAKECMDGOALS),)
  ifneq ($(filter cClient, $(TARGETS)),)
    BUILD_CLIENT = true
  endif
endif
ifeq ($(MAKECMDGOALS),all)
  ifneq ($(filter cClient, $(TARGETS)),)
    BUILD_CLIENT = true
  endif
endif
ifneq ($(filter cClient, $(MAKECMDGOALS)),)
  BUILD_CLIENT = true
endif

ifeq ($(BUILD_CLIENT),true)
  -include lib/Makefile.interopWithC
endif

cClient: cClient.test.c interopWithC.chpl
  +$(CHPL_COMPILER) $(CHPL_CFLAGS) -o $@ $< $(CHPL_LDFLAGS)
```

I think an alternate plan would be to have the cClient target call a script that checks for the presence of lib/Makefile.interopWithC (and if its not there generates it) then calls another Makefile.

Anyway, that seems kind of clunky too. I want a second opinion on this in case I'm missing something better\obvious.

**Comment by lydia-duncan** [comment] 2021-10-05 18:11
Sorry not to respond to this sooner, with the conference last week I've been pretty swamped.



> There's two problems I see:
> 
> 1. Not finding zmq.h on Tony's system
> [...]
> 
> For (1): I haven't been able to reproduce this. It looks like `chpl-mli-common-runtime` wants this. Do you know what this runtime is and under what conditions `chpl` would need it? I think we might want to fork that out onto a separate issue.

This is used for multilocale interoperability support.  This issue seems slightly related to the issue Tom has been running into on Gitter this week.  It sounds like @dlongnecke-cray is taking some points to look into it this sprint.

For the second issue, I don't have a better solution than the ones you've proposed.  I agree that it's a bit unfortunate, and that the pure Makefile modification is better than the script that checks for the presense.

**Comment by stonea** [comment] 2021-11-17 23:55
I'm closing this issue since we've fixed the "make clean" problem in this PR: https://github.com/chapel-lang/chapel/pull/18695

**Closed by stonea** 2021-11-17 23:55 UTC
Labels: type: Bug, area: Makefiles, user issue
