### ISSUE TITLE
internal error: UTI-MIS-0602 chpl version 1.19.0

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#12582] opened 2019-03-12 17:37 UTC
I know today is *really* not the day you want a new bug report, but the following showed up in our nightly CI runs this morning, and was **not** present for the same configuration 24-hours earlier:

```
chpl -o fft --ieee-float fft.chpl
internal error: UTI-MIS-0602 chpl version 1.19.0
Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

This is occurring for several of the tests we compile (fft, hpl, isx-weakISO, ptrans, sscas2_rmat) but not for several others.  This is master at 7e39e187

NOTE: this platform is a Windows Subsystem for Linux (WSL) instance.  
Since this is not the most stable platform, it is possible this is an "external issue".  
If so, I apologize for the timing of this report.

More details at (or available by following links in):
http://upc-bugs.lbl.gov/upc_tests/detail.php?testname=external-chapel%2Ffft&date=2019-03-12&branch=ALL&config=EX-wsl_ubuntu-smp-gcc-pshm  
For instance the `chapel.log` link on that page will take you to the build log for the Chapel compiler/runtime.  

The failures (and 1 week history) for this platform are here:
http://upc-bugs.lbl.gov/upc_tests/chistory.php?date=2019-03-12&start_date=2019-03-05&cr=compile&config=EX-wsl_ubuntu-smp-gcc-pshm&optdbg=opt&shortform=on&reload=1

I am sorry I've not given more detail, but we are working toward UPC++ and GASNet-EX releases on Friday.  I will do my best to respond promptly to specific questions.

CC: @bonachea

**Comment by bradcray** [comment] 2019-03-12 18:10
Thanks for the quick report, Paul.  This looks consistent with some other errors that seem to have turned up in our testing last night.

**Comment by mppf** [comment] 2019-03-12 18:48
@PHHargrove - thanks for reporting it. While it's not the day we'd want to have a new bug, it *is* the day we'd want to know about it and resolve it. I have a fix in the works (it was a type-o adding an out-of-bounds array access within the compiler).

**Comment by mppf** [comment] 2019-03-12 21:20
@PHHargrove - I've merged a fix for the valgrind failures and I believe it's highly likely that the same issue was causing these WSL failures. Please let us know if the issue is resolved you you. Thanks.

**Comment by PHHargrove** [comment] 2019-03-12 23:16
@mppf Retesting on WSL at 2cd38c47 shows the issue has been resolved.

**Comment by bradcray** [comment] 2019-03-12 23:19
Great, thanks for confirming Paul, and thanks for reporting this!

**Closed by bradcray** 2019-03-12 23:19 UTC
