### ISSUE TITLE
Improve flexibility of string.join

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7648] opened 2017-10-25 18:31 UTC
The ``string.join`` method can currently take three kinds of arguments:
- varargs
- a tuple
- an array

While this covers some common cases, I think what we really want is to have ``string.join`` accept something that can be iterated over and that yields strings. Today we have no standard methodology for checking if something is iterable and checking the yield type.

An additional feature could be to accept things that can be cast to a string.

**Comment by buddha314** [comment] 2017-10-30 16:04
Here is an example of unexpected behavior

```
use Sort;
var l: [1..0] string;
l.push_back("bananas");
l.push_back("rice");
l.push_back("apple sauce");
l.push_back("toast");


writeln(l);
writeln(",".join(l));
writeln(l.sorted());
writeln(",".join(l.sorted()));
```

Output it
```
bananas rice apple sauce toast
bananas,rice,apple sauce,toast
apple sauce bananas rice toast
apple sauce bananas rice toast  // expect apple sauce, bananas, rice, toast
```

**Comment by buddha314** [comment] 2017-10-30 16:13
+1 for anyone who gets the reference...

**Comment by cassella** [comment] 2019-10-12 02:46
#9372  added a `join(ir: _iteratorRecord)`.  Though none of the new tests mentioned apple sauce, @buddha314 's sorted shopping list includes commas now.

**Comment by bradcray** [comment] 2019-10-19 00:10
@cassella: Just to make sure: are you suggesting you think this can be closed now?

I tried updating @buddha314's example to use lists since push_back is now deprecated but it didn't seem to work (maybe due to user error on my part?  I haven't used lists much...):  https://tio.run/##bY5BDsIwDATveUWUUyJVeQD5AjdeYFoLgqwkil14fuoeEBShPXh31oed79CQxlgZ7aV2mew5syTzhG7pZEmDZ@m53EIyFKE1LIt3VygqdgfY84xHopfQMqy/hVRg2ZExr54FqXjS9PZucvFR8w6/KEXWhbj48Pf104Y0xgY

**Comment by cassella** [comment] 2019-10-19 01:12
> @cassella: Just to make sure: are you suggesting you think this can be closed now?

I don't remember now what my intention was, probably somewhere between noting an improvement since the opening of the issue, and an "is this close enough?" ping.  I had just run the apple sauce example as written (and ignored the deprecation warning, since I took the point to be the `join` of the `l.sorted()` result).  (BTW, once you get past the `join(l)`, there is no `list.sorted()`.)

BTW, I think when you edit-in a mention like @dlongnecke-cray above it doesn't generate an email to the mentionee.

**Comment by mppf** [comment] 2021-02-24 19:24
This works for me now
``` chapel
use Sort;
var l = ["bananas", "rice", "apple sauce", "toast"];

writeln(l);
writeln(",".join(l));
writeln(l.sorted());
writeln(",".join(l.sorted()));
```

and as a result I'm closing this issue.

However, the earlier example using `push_back` should arguably now correspond to code using `list`. And that doesn't work directly - see issue TODO.

**Closed** 2021-02-24 19:26 UTC
Labels: area: Libraries / Modules, type: Feature Request
