### ISSUE TITLE
Need Access to Transposes *and* Slicing of Sparse Arrays

### ISSUE THREAD

**Issue by Tshimanga** [chapel-lang/chapel#8819] opened 2018-03-14 17:40 UTC
As in [On the Subtleties of Sparseness in Chapel](https://stackoverflow.com/questions/49283425/on-the-subtleties-of-sparseness-in-chapel), among my desiderata are access to both slicing and transposition  of sparse arrays simultaneously. Hoping this is an issue of ignorance rather than something that will need to be introduced.

**Comment by ben-albrecht** [comment] 2018-03-16 14:50
>  access to both slicing and transposition of sparse arrays simultaneously

This could be solved by supporting proper slicing on `CS` arrays, which have a supported transpose function in the `LinearAlgebra` module. Would that be an acceptable solution to you? 

If so, this may be considered a duplicate of #8023

**Comment by ben-albrecht** [comment] 2018-09-07 21:55
With sparse transpose supported and #8023 covering sparse slicing, I'm going to close this issue as duplicate.

**Closed by ben-albrecht** 2018-09-07 21:55 UTC
Labels: area: Modules, stat: Duplicate, type: Feature Request, user issue
