### ISSUE TITLE
Mac OS X: gasnet w segment=fast segfaults. Segment=everything works. 

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#7624] opened 2017-10-20 01:51 UTC
### Summary of Problem

On a macbook pro running Sierra, Chapel w CHPL_COMM=gasnet and CHPL_GASNET_SEGMENT=fast, segfaults when you run the hellos, e.g. "make check"

```
== Actual Test Output (raw, with verbose) ==
/Users/bogus/workspace/correctness-test-gasnet.fast.darwin/third-party/gasnet/install/darwin-clang-none/seg-fast/nodbg/bin/amudprun  -np 4 ./hello6-taskpar-dist_real -nl4 --printLocaleName=false -v
QTHREADS: Using 4 Shepherds
QTHREADS: Using 4 Shepherds
QTHREADS: Using 4 Shepherds
QTHREADS: Using 1 Workers per Shepherd
QTHREADS: Using 4 Shepherds
QTHREADS: Using 1 Workers per Shepherd
QTHREADS: Using 1 Workers per Shepherd
QTHREADS: Using 1 Workers per Shepherd
QTHREADS: Guard Pages Enabled
QTHREADS: Guard Pages Enabled
QTHREADS: Guard Pages Enabled
QTHREADS: Using 8388608 byte stack size.
QTHREADS: Guard Pages Enabled
QTHREADS: Using 8388608 byte stack size.
QTHREADS: Using 8388608 byte stack size.
QTHREADS: Using 8388608 byte stack size.
executing on node 2 of 4 node(s): mbp-awallace.local
executing on node 1 of 4 node(s): mbp-awallace.local
executing on node 3 of 4 node(s): mbp-awallace.local
executing on node 0 of 4 node(s): mbp-awallace.local
*** Caught a fatal signal: SIGSEGV(11) on node 0/4
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace. 
*** Caught a fatal signal: SIGSEGV(11) on node 3/4
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace. 
*** Caught a fatal signal: SIGSEGV(11) on node 2/4
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace. 
*** Caught a fatal signal: SIGSEGV(11) on node 1/4
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace. 
make: *** [check] Error 20
```

Change CHPL_GASNET_SEGMENT=everything (or just unset the variable), holding everything else the same, rebuild Chapel from "git clean", and the "hellos" work.

### Steps to Reproduce

**Source Code:**

Chapel master branch, Git rev 4bd4e822f
Chapel release/1.16 branch, Git rev f0bd20812 (not shown)

**Compile command:**
`make`

**Execution command:**
`make check`

### Configuration Information

- Output of `chpl --version`:

`chpl Version 1.17.0 pre-release (4bd4e822f1)`

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: none *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: fast *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```

- environment

```bash
CHPL_COMM=gasnet
CHPL_GASNET_CFG_OPTIONS=--disable-ibv
CHPL_GASNET_SEGMENT=fast
CHPL_HOME=/Users/bogus/workspace/correctness-test-gasnet.fast.darwin
CHPL_HOST_PLATFORM=darwin
CHPL_QTHREAD_ENABLE_OVERSUBSCRIPTION=1
CHPL_TARGET_ARCH=none
GASNET_ROUTE_OUTPUT=0
GASNET_SPAWNFN=L
MANPATH=/Users/bogus/workspace/correctness-test-gasnet.fast.darwin/man:
PATH=/Users/bogus/workspace/correctness-test-gasnet.fast.darwin/bin/darwin:/Users/bogus/workspace/correctness-test-gasnet.fast.darwin/util:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
QT_AFFINITY=no
```

- Back-end compiler and version, `clang --version`:

```
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
```

## Mac Firewall: DISABLED

Otherwise, you get pop-ups asking to allow "amudprun" to accept incoming connections

## VPN: DISCONNECTED

Otherwise, you get errors like this:

```
*** FATAL ERROR(Node 0): An active message was returned to sender,
    and trapped by the default returned message handler (handler 0):
Message type: AM_REQUEST_IM
Error Code: ECONGESTION: Congestion at destination endpoint   

...

*** Caught a fatal signal: SIGABRT(6) on node 0/4
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace. 
```

**Comment by awallace-cray** [comment] 2017-10-20 17:36
## VPN:DISCONNECTED
The following variables "fix" the VPN/gasnet issue. ie, you can get these results with or without the VPN. 

```
export GASNET_MASTERIP=127.0.0.1
export GASNET_WORKERIP=127.0.0.0
```

**Comment by awallace-cray** [comment] 2017-10-20 17:39
I re-tested with Chapel release 1.16.0 and got essentially the same result: 
segment=fast: all four hello6's peg their CPUs, instead of immediately getting SIGSEGV(11)

**Comment by ronawho** [comment] 2017-10-20 23:18
Neither me nor @benharsh can repro this. I'm running with `sierra 10.12.6 (16G29)` and clang `9.0.0 (clang-900.0.38)`. environment and chplenv look similar to me. Can you think of anything that's changed recently on your machine?

@gbtitus can you see if you can repro?

**Comment by noakesmichael** [comment] 2017-10-21 00:40
I think I am seeing the same issue with my Cray laptop.  It’s running Sierra.


I get fatals both on and off VPN with GASNET fast.  I followed up with
GASNET_BACKTRACE=1

When on VPN I simply see

> ./hello -nl 2
*** Caught a fatal signal: SIGSEGV(11) on node 1/2
*** Caught a fatal signal: SIGSEGV(11) on node 0/2


but off VPN I get the same fatals plus a lot of backtrace data.  Happy to help to
try to explore.




Separately I am seeing a different failure mode on my personal mac.

Mike



On Oct 20, 2017, at 4:18 PM, Elliot Ronaghan <notifications@github.com<mailto:notifications@github.com>> wrote:


Neither me nor @benharsh<https://github.com/benharsh> can repro this. I'm running with sierra 10.12.6 (16G29) and clang 9.0.0 (clang-900.0.38). environment and chplenv look similar to me. Can you think of anything that's changed recently on your machine?

@gbtitus<https://github.com/gbtitus> can you see if you can repro?

**Comment by dmk42** [comment] 2017-10-21 16:48
I didn't have to do anything special to reproduce this on my personal Mac (haven't tried on my Cray Mac).

I use Elliot's setGasnetFast function to set things up.  The environment ends up looking like Tony described.

A window pops up each time asking if I want to allow the launcher to access the network, then the window disappears because the program has crashed.  Turning off the firewall prevents the pop-up windows but the hellos still crash the same way.

**Comment by noakesmichael** [comment] 2017-10-23 18:44
I have confirmed that the problem does not occur when
I am at work and my Cray laptop is on the corporate
network.




Incidentally I see that I failed to mention that my
personal mac, which has yet a different failure mode,
is running High Sierra.


On Oct 20, 2017, at 5:40 PM, Mike Noakes <mnoakes@cray.com<mailto:mnoakes@cray.com>> wrote:

I think I am seeing the same issue with my Cray laptop.  It’s running Sierra.


I get fatals both on and off VPN with GASNET fast.  I followed up with
GASNET_BACKTRACE=1

When on VPN I simply see

> ./hello -nl 2
*** Caught a fatal signal: SIGSEGV(11) on node 1/2
*** Caught a fatal signal: SIGSEGV(11) on node 0/2


but off VPN I get the same fatals plus a lot of backtrace data.  Happy to help to
try to explore.




Separately I am seeing a different failure mode on my personal mac.

Mike



On Oct 20, 2017, at 4:18 PM, Elliot Ronaghan <notifications@github.com<mailto:notifications@github.com>> wrote:


Neither me nor @benharsh<https://github.com/benharsh> can repro this. I'm running with sierra 10.12.6 (16G29) and clang 9.0.0 (clang-900.0.38). environment and chplenv look similar to me. Can you think of anything that's changed recently on your machine?

@gbtitus<https://github.com/gbtitus> can you see if you can repro?

**Comment by mppf** [comment] 2017-10-27 20:12
I've tried to reproduce this as well and observed a few things:
 * it doesn't happen with fifo
 * it happens sometimes with 1 locale but more reliably with 2
 * it gets EXEC_BAD_ACCESS in qthreads.c:365 `rdata->tasklocal_size = 0;`
 * the stack trace is 'alloc_rdata' called by 'qthread_master'

**Comment by gbtitus** [comment] 2017-10-31 18:43
Works for me.

I'm running Sierra 10.12.6.

Output of `chpl --version`:

> chpl Version 1.17.0 pre-release (52a0f71)

Output of `printchplenv --anon`:

> CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: none *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: fast *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

Output of `clang --version`:

> Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin16.7.0
Thread model: posix

Environment (output of `env | grep -E 'CHPL|GAS|QT' | sort`:

> CHPL_COMM=gasnet
CHPL_GASNET_CFG_OPTIONS=--disable-ibv
CHPL_GASNET_SEGMENT=fast
CHPL_HOME=/Users/gbt/dev/chapel
CHPL_HOST_PLATFORM=darwin
CHPL_QTHREAD_ENABLE_OVERSUBSCRIPTION=1
CHPL_TARGET_ARCH=none
GASNET_MASTERIP=127.0.0.1
GASNET_ROUTE_OUTPUT=0
GASNET_SPAWNFN=L
GASNET_WORKERIP=127.0.0.0
QT_AFFINITY=no

Output of `make check`:

> [Info] Running minimal test script: $CHPL_HOME/util/test/checkChplInstall
[Info] Found executable chpl in /Users/gbt/dev/chapel/bin/darwin/chpl.
[Info] Found $CHPL_HOME directory: /Users/gbt/dev/chapel
[Info] /Users/gbt/.chpl does not exist. Creating it.
[Info] Temporary test job directory: /Users/gbt/.chpl/chapel-test-Gu6uU
[Info] Compiling $CHPL_HOME/test/release/examples/hello6-taskpar-dist.chpl
[Info] Test job compiled into /Users/gbt/.chpl/chapel-test-Gu6uU/hello6-taskpar-dist
[Info] $CHPL_LAUNCHER=amudprun is compatible with test script.
[Info] Running test job.
[Info] Test job complete.
SUCCESS: 'make check' passed!

**Comment by awallace-cray** [comment] 2017-11-03 22:40
2017-11-02 : 
chapelmac (Jenkins build slave) came back online today.

2017-11-03 : 
Nightly darwin tests on chapelmac did not run this morning - I forgot Jenkins doesn't notice when JJB takes away <disabled>true.  This afternoon, I was manually rerunning gasnet.darwin variants (Jenkins jobs).  For the first time ever, it looks like the hello's will not work in EITHER gasnet configuration on chapelmac ("everything" (default), or "fast"), without putting
```
export GASNET_MASTERIP=127.0.0.1
export GASNET_WORKERIP=127.0.0.0
```

Jenkins gets the same error I first saw on my laptop, connected to the VPN, two weeks ago.  https://github.com/chapel-lang/chapel/issues/7624
I have no explanation. But it is repeatable.

**Comment by awallace-cray** [comment] 2017-11-03 23:50
2017-11-03 : The original problem reported above (SEGV in gasnet.fast.darwin) could not be repro'd on chapelmac build slave today.

**Comment by awallace-cray** [comment] 2017-11-27 22:57
2017-11-27 : chapelmac was upgraded to Sierra on 11/17. Still no SEGV in gasnet.fast.darwin.

**Comment by ronawho** [comment] 2018-07-06 06:34
@dmk42, @mppf, or anybody else -- can you still reproduce this?

**Comment by mppf** [comment] 2018-07-06 14:33
I'm not reproducing it anymore.

**Comment by dmk42** [comment] 2018-07-06 16:07
On the same machine where I reproduced the problem last year, it no longer fails.

**Comment by ronawho** [comment] 2018-07-06 16:13
Closing since this seems to be resolved (or at the very least we can't reproduce)

**Closed by ronawho** 2018-07-06 16:13 UTC
Labels: area: Compiler, type: Portability
