### ISSUE TITLE
what should int - range do?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#20751] opened 2022-09-30 15:08 UTC
### Summary of Problem
I noticed that `1 - 1..10` has a strange result as compared to `1..10 - 1`.

### Steps to Reproduce

**Source Code:**

```chapel
var r = 1..10;

writeln(r + 1); // ok: 2..11
writeln(1 + r); // ok: 2..11
writeln(r - 1); // ok: 0..9
writeln(1 - r); // huh?  0 -1 -2 -3 -4 -5 -6 -7 -8 -9
```

**Associated Future Test(s):**
TODO

**Comment by mppf** [comment] 2022-09-30 15:09
@vasslitvinov - fyi

**Comment by vasslitvinov** [comment] 2022-09-30 15:14
We have been discussing this on #17101.

**Comment by DanilaFe** [comment] 2024-07-09 00:45
Marked as duplicate of https://github.com/chapel-lang/chapel/issues/17101, so closing now.

**Closed by DanilaFe** 2024-07-09 00:45 UTC
Labels: stat: Duplicate
