### ISSUE TITLE
`util/chplenv/chpl_libfabric.py` not found during installation

### ISSUE THREAD

**Issue by rj-jesus** [chapel-lang/chapel#18758] opened 2021-11-22 12:23 UTC
### Summary of Problem

When compiling Chapel on an HPE Cray EX system I got a bunch of errors like:
```
.../chapel-1.25.0/util/config/gather-pe-chapel-pkgconfig-libs.bash: line 31: /util/chplenv/chpl_libfabric.py: No such file or directory
```

As suggested by the error message, the problem seems to lie at line 31 of `util/config/gather-pe-chapel-pkgconfig-libs.bash`
```bash
if [[ "$chpl_comm" == ofi && $($CHPL_HOME/util/chplenv/chpl_libfabric.py) == system ]]; then
```
due to `$CHPL_HOME` (seemingly) not being set at this stage of the compilation.

These errors didn't prevent the compilation from proceeding, but in any case I got it to work by changing `$CHPL_HOME` to `$CHPL_MAKE_HOME` in my installation script with
```bash
sed -i 's#\$CHPL_HOME/util/chplenv/chpl_libfabric.py#\$CHPL_MAKE_HOME/util/chplenv/chpl_libfabric.py#' util/config/gather-pe-chapel-pkgconfig-libs.bash
```
and revert it after installing (if this seems wrong please let me know).

### Configuration Information

```
$ chpl --version
chpl version 1.25.0
Copyright 2020-2021 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

$ $CHPL_HOME/util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: hpe-cray-ex
CHPL_TARGET_COMPILER: cray-prgenv-cray
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: x86-rome
CHPL_LOCALE_MODEL: flat
CHPL_COMM: ofi
  CHPL_LIBFABRIC: system
CHPL_TASKS: qthreads
CHPL_LAUNCHER: slurm-srun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: ofi
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: none +
CHPL_AUX_FILESYS: none
```

**Comment by mppf** [comment] 2021-11-22 15:46
@rt-jesus - I think this will be resolved in 1.25.1 because `util/config/gather-pe-chapel-pkgconfig-libs.bash` no longer exists and is replaced by logic in Python code. If you are able to confirm that the current `main` branch does not have the issue, that would be helpful.

**Comment by rj-jesus** [comment] 2021-11-22 16:58
@mppf Hi, indeed the current main (ae9ebcd28d) does not exhibit the error I described. However, it shows a new error when compiling Chapel programs:
```
$ chpl hello.chpl 
.../chapel/make/Makefile.base:193: .../chapel/third-party/jemalloc/Makefile.target.include: No such file or directory
gmake: *** No rule to make target '.../chapel/third-party/jemalloc/Makefile.target.include'.  Stop.
error: compiling generated source

$ chpl --version
chpl version 1.26.0 pre-release (ae9ebcd28d)
Copyright 2020-2021 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

$ $CHPL_HOME/util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: hpe-cray-ex
CHPL_TARGET_COMPILER: cray-prgenv-cray
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: x86-rome
CHPL_LOCALE_MODEL: flat
CHPL_COMM: ofi
  CHPL_LIBFABRIC: system
CHPL_TASKS: qthreads
CHPL_LAUNCHER: slurm-srun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: ofi
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: none +
CHPL_AUX_FILESYS: none
```

Is it worth opening a new issue for this?

**Comment by aconsroe-hpe** [comment] 2021-11-22 17:18
@rj-jesus I'm looking into this now. The most recent error about Makefile.target.include is likely not related to your original issue. Can hold off creating a new issue for the time being

**Comment by aconsroe-hpe** [comment] 2021-11-22 19:40
I haven't been able to reproduce the exact error 
```
.../chapel/make/Makefile.base:193: .../chapel/third-party/jemalloc/Makefile.target.include: No such file or directory
gmake: *** No rule to make target '.../chapel/third-party/jemalloc/Makefile.target.include'.  Stop.
```
But I'm also not able to build on an XC with cray-prgenv-gnu and CHPL_LLVM=none with main or a checkout before merging changes related to using jemalloc in the compiler.
Will want to check in with @ronawho about this (should be tomorrow) to take another look and we should be able to determine whether to split this issue out into a new one

**Comment by aconsroe-hpe** [comment] 2021-11-23 00:10
@rj-jesus the issues I was having seemed to be a one-off and with a clean copy of `main`, I can build on an XC with cray-prgenv-cray, llvm=none, and comm=ofi without issue.

I'm a bit curious if your `CHPL_HOME` is set? I see an explicit call to `$CHPL_HOME/util/printchplenv` which makes me think it maybe isn't? Another debugging aid would be to do something like:
```bash
echo $CHPL_HOME
chpl --savec /tmp/helloc examples/hello.chpl
grep '^CHPL' /tmp/helloc/Makefile
```

Let's take this into a new issue if the above doesn't lead to a solution. And would be good to include `printchplenv --anonymize --all` and `module list`. Thanks

**Comment by rj-jesus** [comment] 2021-11-23 10:35
Hi @aconsroe-hpe , yes my `CHPL_HOME` is set (I called `printchplenv` explicitly because I don't add the `util` directory to my path).

```
$ echo $CHPL_HOME
<prefix>/opt/chapel

$ chpl --savec build hello.chpl
<prefix>/opt/chapel/make/Makefile.base:193: <prefix>/opt/chapel/third-party/jemalloc/Makefile.target.include: No such file or directory
gmake: *** No rule to make target '<prefix>/opt/chapel/third-party/jemalloc/Makefile.target.include'.  Stop.
error: compiling generated source

$ grep '^CHPL' build/Makefile
CHPL_MAKE_HOME = <prefix>/opt/chapel
CHPL_MAKE_RUNTIME_LIB = <prefix>/opt/chapel/lib
CHPL_MAKE_RUNTIME_INCL = <prefix>/opt/chapel/runtime/include
CHPL_MAKE_THIRD_PARTY = <prefix>/opt/chapel/third-party
CHPLSRC = \
CHPLUSEROBJ = \

$ $CHPL_HOME/util/printchplenv --anonymize --all
CHPL_HOST_PLATFORM: hpe-cray-ex
CHPL_HOST_COMPILER: gnu
  CHPL_HOST_CC: gcc
  CHPL_HOST_CXX: g++
CHPL_HOST_ARCH: x86_64
CHPL_TARGET_PLATFORM: hpe-cray-ex
CHPL_TARGET_COMPILER: cray-prgenv-cray
  CHPL_TARGET_CC: cc
  CHPL_TARGET_CXX: CC
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: x86-rome
CHPL_LOCALE_MODEL: flat
CHPL_COMM: ofi
  CHPL_LIBFABRIC: system
CHPL_TASKS: qthreads
CHPL_LAUNCHER: slurm-srun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_HOST_MEM: cstdlib
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: ofi
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: none +
CHPL_AUX_FILESYS: none
CHPL_LIB_PIC: none
CHPL_SANITIZE: none
CHPL_SANITIZE_EXE: none

$ module list

Currently Loaded Modules:
  1) cce/11.0.4     3) craype-x86-rome         5) craype-network-ofi       7) xpmem/2.2.40-7.0.1.0_2.7__g1d7a24d.shasta   9) cray-libsci/21.04.1.1  11) bolt/0.7        13) load-epcc-module  15) cray-pmi-lib/6.0.10
  2) craype/2.7.6   4) libfabric/1.11.0.4.71   6) perftools-base/21.02.0   8) cray-mpich/8.1.4                           10) PrgEnv-cray/8.0.0      12) epcc-setup-env  14) cray-pmi/6.0.10
```

^ This was after installing Chapel from a clean clone of main (c073e96a4a).

P.S. I doubt this makes a difference, but here's the hello program I was trying to compile:
```chapel
$ cat hello.chpl 
use Memory.Diagnostics;


serial do coforall loc in Locales do on loc {
  writeln("locale #", here.id, "...");
  writeln("  ...is named: ", here.name);
  writeln("  ...has hostname: ", here.hostname);
  writeln("  ...has ", here.numPUs(), " processor cores");
  writeln("  ...has ", here.physicalMemory(unit=MemUnits.GB, retType=real),
          " GB of memory");
  writeln("  ...has ", here.maxTaskPar, " maximum parallelism");
}

writeln("Total number of cores: ", + reduce Locales.numPUs());
writeln("Total memory: ", + reduce Locales.physicalMemory(unit=MemUnits.GB, retType=real), " GB");
writeln("Total maximum parallelism: ", + reduce Locales.maxTaskPar);
```

**Comment by bradcray** [comment] 2021-12-02 04:36
I've only skimmed this issue quickly, but my sense is that we're good to close it.  @mppf and @aconsroe-hpe , do you agree?  Thanks.

**Closed** 2021-12-02 16:43 UTC
