### ISSUE TITLE
some operators formatted differently in html docs

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#17057] opened 2021-01-30 04:32 UTC
### Summary of Problem

In the docs for Map, for example,

https://chapel-lang.org/docs/modules/standard/Map.html

![Screenshot from 2021-01-29 20-20-35](https://user-images.githubusercontent.com/590808/106347009-fec2c000-626f-11eb-8ac4-c58c6df06f0e.png)

The `+` and `+=` operators don't get the code-style formatting that most of the other operators (and all the non-operator functions) get.

Also affected are `=`, `==`, `!=`, `-`, and `-=`.

They get the same treatment in the rst:

```rst
.. function:: proc +(a: map(?keyType, ?valueType, ?parSafe), b: map(keyType, valueType, parSafe))

   Returns a new map containing the keys and values in either a or b. 

.. function:: proc +=(ref a: map(?keyType, ?valueType, ?parSafe), b: map(keyType, valueType, parSafe))

   
   Sets the left-hand side map to contain the keys and values in either
   a or b.
   

.. function:: proc |(a: map(?keyType, ?valueType, ?parSafe), b: map(keyType, valueType, parSafe))

   Returns a new map containing the keys and values in either a or b. 

.. function:: proc |=(ref a: map(?keyType, ?valueType, ?parSafe), b: map(keyType, valueType, parSafe))

   Sets the left-hand side map to contain the keys and values in either
   a or b.
```   

But they pick up different formatting in the html:

```html
<dl class="chpl function">
<dt id="Map.+">
<em class="property">proc </em><code class="sig-name descname">+</code><span class="sig-paren">(</span><em class="sig-param">a: map(?keyType</em>,
 <em class="sig-param">?valueType</em>, <em class="sig-param">?parSafe)</em>, <em class="sig-param">b: map(keyType</em>, <em class="sig-param">val
ueType</em>, <em class="sig-param">parSafe)</em><span class="sig-paren">)</span><a class="headerlink" href="#Map.+" title="Permalink to this defin
ition">¶</a></dt>
<dd><p>Returns a new map containing the keys and values in either a or b.</p>
</dd></dl>

<dl class="chpl function">
<dt id="Map.+=">
<em class="property">proc </em><code class="sig-name descname">+=</code><span class="sig-paren">(</span><em class="sig-param">ref a: map(?keyType</em>, <em class="sig-param">?valueType</em>, <em class="sig-param">?parSafe)</em>, <em class="sig-param">b: map(keyType</em>, <em class="sig-param">valueType</em>, <em class="sig-param">parSafe)</em><span class="sig-paren">)</span><a class="headerlink" href="#Map.+=" title="Permalink to this definition">¶</a></dt>
<dd><p>Sets the left-hand side map to contain the keys and values in either
a or b.</p>
</dd></dl>
```
vs

```html
<dl class="chpl function">
<dt>
<code class="sig-name descname">proc |(a: map(?keyType, ?valueType, ?parSafe), b: map(keyType, valueType, parSafe))</code></dt>
<dd><p>Returns a new map containing the keys and values in either a or b.</p>
</dd></dl>

<dl class="chpl function">
<dt>
<code class="sig-name descname">proc |=(ref a: map(?keyType, ?valueType, ?parSafe), b: map(keyType, valueType, parSafe))</code></dt>
<dd><p>Sets the left-hand side map to contain the keys and values in either
a or b.</p>
</dd></dl>
```

**Comment by lydia-duncan** [comment] 2021-02-01 16:25
Thanks for noticing!  I believe we had to do something special to the Chapel sphinx domain in order to allow the cases that do work.  Probably just an oversight that the other operators weren't handled

**Comment by lydia-duncan** [comment] 2021-02-01 23:23
Looks like this is a duplicate of #13984, but I think this provides more details so I'll close that

**Comment by rajpratyush** [comment] 2021-03-18 12:32
@lydia-duncan hi can I take up this issue

**Comment by lydia-duncan** [comment] 2021-03-18 16:32
Sure!  I don't expect it to be easy to resolve, so definitely feel free to ask questions!

**Comment by cassella** [comment] 2021-11-19 09:07
The link to the sphinx file in the other issue is stale.  The new link is

https://github.com/chapel-lang/sphinxcontrib-chapeldomain/blob/master/sphinxcontrib/chapeldomain/chapel.py

I believe the relevant part is

```python
        'procname': [
            (r'([a-zA-Z_][.\w$]*|'    # regular function name, including 2ndary
             r'\~[a-zA-Z_][.\w$]*|'   # support for legacy destructors?
             r'[+*/!~%<>=&^|\-:]{1,2})',  # operators
             Name.Function, '#pop'),
```

Though that operators regex does include `+` and `-` and `=`.  I don't know how to modify that file and have it used by `make docs` to test.  (And I think the `{1,2}` will exclude `**=`, `&&=`, `||=` `<=>`, and `<~>`.)

**Comment by lydia-duncan** [comment] 2022-04-28 22:12
I've worked on this a little bit (note: under the assumption that `+` and `+=` are right and `|` and `|=` are wrong, because the former will generate a link and match the behavior of other methods otherwise, while the latter are unlinkable and don't adjust the `proc` keyword formatting).

Neither modifying chapel.py as Paul called out nor `chpl_sig_pattern` in `sphinxcontrib/chapeldomain/__init__.py` seem to have made a difference in the HTML rendering (though some of the modifications do allow us to match against those symbols in test function declarations, so may be worth doing anyways).  I'm wondering if the problem is instead in something Sphinx is using to make the HTML, perhaps in Pygments or ReadTheDocs

**Comment by lydia-duncan** [comment] 2022-04-29 21:34
Or it might be specific to `map` in some way?  I wrote some operator chpldoc doc tests and `|` behaves fine there, even as a secondary operator method.  This is very odd.

**Comment by cassella** [comment] 2022-05-02 05:46
Hmm.  The current version of Map.html in the link in the OP looks different now.  All the operators now have mostly bolded black text.  All the non-operator methods too.  Vs. an older version e.g.

https://chapel-lang.org/docs/1.22/modules/standard/Map.html

There's still something different between `+` and `|` -- the line for `+` has blue parentheses and the arguments are printed in variable-width fonts.  For `|` the parentheses are black and the whole line is fixed-width.  At least in my browser,

![Screenshot from 2022-05-01 22-20-20](https://user-images.githubusercontent.com/590808/166187916-0a38b1f6-75ea-4335-831d-67bf751ee210.png)

https://chapel-lang.org/docs/modules/standard/BigInteger.html also has different behavior for operators with `|`, `^`, `&`, and `%` than for its other operators.



Also in the current docs, all the operators are listed as e.g.  `proc type map.+` instead of `operator +` or `operator map.+` how they're defined.

**Comment by bradcray** [comment] 2022-06-01 23:52
> Also in the current docs, all the operators are listed as e.g. proc type map.+ instead of operator + or operator map.+ how they're defined.

I think this is known, and I thought we had an issue for it, but I'm not finding it with a quick search.  @lydia-duncan: This seems like a potentially good intern task if the unsafe effort doesn't take too long?

**Comment by lydia-duncan** [comment] 2022-06-02 15:03
> I think this is known, and I thought we had an issue for it, but I'm not finding it with a quick search.

That's because I foolishly made it a private issue because I thought I'd get back to it faster.  It's in Cray/chapel-private#1643

> This seems like a potentially good intern task if the unsafe effort doesn't take too long?

Yeah, that and documenting interfaces would be pretty quick :)

**Comment by jabraham17** [comment] 2023-08-16 16:12
I ran into this yesterday and have a pretty simple fix. The problem was with `chpl_sig_pattern` in `sphinxcontrib/chapeldomain/__init__.py`, it was missing some operator definitions like `~` and `|`. This fix will also fix a commented out test for documenting casts.

**Closed** 2023-08-16 22:28 UTC
Labels: type: Bug, area: Docs, area: Tools
