### ISSUE TITLE
[Internal Error] RES-CLE-UPS-0730 chpl version 1.29.0

### ISSUE THREAD

**Issue by kwaters4** [chapel-lang/chapel#21299] opened 2022-12-28 19:16 UTC
### Summary of Problem
This occurred when updating code that was stable on 1.28.0 to the newly released version 1.29.0.The deprecation warnings are shown up compilation, however a internal compiler error is triggered soon after. Below is a sample of the output. The easy and reasonable work around is updating ```IO.channel```to ```IO.fileWriter```. There may be something more sinister going on here though.

#### Output
```
foo.chpl:4: warning: channel type is deprecated - use fileReader or fileWriter instead
foo.chpl:6: In initializer:
foo.chpl:6: warning: channel type is deprecated - use fileReader or fileWriter instead
internal error: RES-CLE-UPS-0730 chpl version 1.29.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.
```

### Steps to Reproduce

**Source Code:**

```chapel
module foo {
    import IO;
    class foo {
        const stream: IO.channel;

        proc init(stream: IO.channel= IO.stdout) {
        this.stream  = stream;
        }
    }
    var bar = new foo();
}
```

**Compile command:**
```chpl foo.chpl```

**Execution command:**
Does not compile

### Configuration Information

- Output of `chpl --version`:
``` 
chpl version 1.29.0
  built with LLVM version 14.0.0
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled
CHPL_AUX_FILESYS: none
```

**Comment by dlongnecke-cray** [comment] 2024-02-15 20:29
I can't seem to reproduce this today, so I'm going back in time to 1.29 to see what error we're running into. I'll close if I'm convinced it's fixed today.

**Comment by dlongnecke-cray** [comment] 2024-02-20 19:02
I went back in time to 1.29 and debugged what was going on. Next steps are to try and reproduce it on `main`. If I can't get a simple reproducer working, I'm going to close this for now.

- In the code above `foo` is considered to be marked `generic` because of `IO.channel`.
- Not sure how the line `var bar = new foo();` is working, then? Maybe `channel` has defaults?
- During cleanup we recursively propagate symbols that need to be removed into the "delete" set.
- The type `foo` is marked.
- The `ArgSymbol*` in `foo.deinit()` is marked.
- Thus `deinit()` is marked and deleted.
- Which causes a segfault later on when we consider all the methods of `foo` (why are we considering it if it was deleted?!).

**Comment by dlongnecke-cray** [comment] 2024-02-27 21:27
Closing as I can't seem to reproduce this. Here's the test program I ended up with before I gave up:

```chapel
module Issue21299 {
  module Inner {
    enum kind { foo, bar, baz }

    pragma "ignore noinit"
    record r {
      param writing: bool;
      param k: kind;
      param locking: bool;
      var x: int;
      var _home: locale = here;
    }
    var r1 = new r(false, kind.foo, false);
  }

  // This is the reproducer.
  import this.Inner;

  class foo {
    const x: Inner.r;
    proc init(x: Inner.r=Inner.r1) {
      this.x = x;
    }
  }

  var f = new foo();
}
```

Basically just trying to mimic the state of `channel` at the time of 1.29.

Feel free to reopen if this pops up again on `main`.

**Closed by dlongnecke-cray** 2024-02-27 21:27 UTC
Labels: type: Bug, area: Compiler, user issue
