### ISSUE TITLE
Possible missed type check involving an array of integers

### ISSUE THREAD

**Issue by mstrout** [chapel-lang/chapel#23602] opened 2023-10-07 23:05 UTC
The below assignment of an integer into `histogramCopy` does not result in a compile-time error, but then later code ends up with a runtime error due to `histogramCopy` not being an array.
```
var histogram: [1..numBuckets] atomic int;

var histogramCopy: [histogram.domain] int;
writeln("histogram.domain =", histogram.domain);
forall i in histogram.domain do
  histogramCopy = histogram[i].read();
outputHistogram(histogramCopy);
```

Using homebrew, chapel version 1.32 and on Intel Mac.

**Comment by mppf** [comment] 2023-10-09 14:51
@mstrout - I've tried to fill in some details to get a reproducer, but my reproducer is not reproducing it:

``` chapel
config const numBuckets = 12;

var histogram: [1..numBuckets] atomic int;

var histogramCopy: [histogram.domain] int;
writeln("histogram.domain =", histogram.domain);
forall i in histogram.domain do
  histogramCopy = histogram[i].read();
outputHistogram(histogramCopy);

proc outputHistogram(arg: []) { 
  for x in arg {
    writeln(x);
  }
}
```

Any idea what is missing? Perhaps it depends upon how `outputHistogram` is declared?

**Comment by mstrout** [comment] 2023-10-09 17:15
I have attached the file that doesn't have a compiler error, but does end up with a runtime divide by zero.  I attempted to trim it down by for example commenting out the code after line 70 in outputHistogram, but then the runtime error didn't happen.  Weird, so I am going to just copy the whole file here.
<details> <summary> missing-compiler-error-reproducer.chpl</summary>

```
//
// Histogram: parallel atomic version
//
// Computes the histogram of an array of random numbers.
//
// Oct 7, 2023: copied from chapel/test/exercises/histogram1.chpl and made slight changes
    
// import standard modules to generate random number and use timers
use Random, Time, Math;

// configuration constants
config const printRandomNumbers: bool = true, // print random numbers to screen
             printHistogram: bool = true,     // print histogram to screen
             numNumbers: int = 8,             // number of random numbers
             numBuckets: int = 10;            // number of histogram buckets

// seed the random stream with something reproducible?
config const useRandomSeed = true,
             seed = if useRandomSeed then SeedGenerator.oddCurrentTime else 314159265;

// global variables
var X: [1..numNumbers] real,                    // array of random numbers
    histogram: [1..numBuckets] atomic int,      // histogram
    timer: stopwatch;                           // computation timer

// output startup message
writeln("Running Histogram Example");
writef(" Number of Random Numbers = %{########}\n", numNumbers);
writef(" Number of Buckets        = %{########}\n", numBuckets);
writeln();

// fill array with random numbers (using standard Random module)
fillRandom(X, seed, algorithm=RNG.NPB);
  
// output array of random numbers
if printRandomNumbers then
  writeln("Random Numbers\n\n", X, "\n");
      
// compute histogram
timer.start();
computeHistogram(X, histogram);
timer.stop();

// FIXME: is there an easier way to copy out of an array of atomics?
var histogramCopy: [histogram.domain] int;
writeln("histogram.domain =", histogram.domain);
forall i in histogram.domain do
  histogramCopy = histogram[i].read();
outputHistogram(histogramCopy);

// verify number of items in histogram is equal to number of random
// numbers and output timing results
if + reduce histogramCopy != numNumbers then
  halt("Number of items in histogram does not match number of random numbers");
writeln("Histogram computed in ", timer.elapsed(), " seconds\n");

// output histogram
if printHistogram then
  outputHistogram(histogramCopy);

proc computeHistogram(X: [] real, ref histogram: [] atomic int) {
  for x in X do
    histogram[1 + (x / (1.0 / numBuckets)): int].add(1);
}

// outputHistogram: output histogram array
proc outputHistogram(histogram: [] int) {
  var bucketMax = max reduce histogram;
  var rowSize = divCeil(bucketMax,10);
  var numRows = divCeil(bucketMax, rowSize);
  for i in 1..numRows by -1 {
    write(" ");
    for j in 1..numBuckets do
      write(if histogram[j]/rowSize >= i then "X" else " ");
    writeln();
  }
  write("+");
  for j in 1..numBuckets do
    write("-");
  writeln("+");
  if rowSize > 1 then
    writeln(" Each 'X' can represent up to ", rowSize, " numbers.");
  writeln(" Raw Data");
  for j in 1..numBuckets {
    writef("  %0.2dr - %0.2dr: %n\n", (j-1)*(1.0/numBuckets), j*(1.0/numBuckets), histogram[j]);
  }
}


```
</details>

**Comment by bradcray** [comment] 2023-10-09 17:30
On some of my runs of the code just above, I'm getting:

```
testit.chpl:54: error: halt reached - Number of items in histogram does not match number of random numbers: (10, 8)
```

```
testit.chpl:54: error: halt reached - Number of items in histogram does not match number of random numbers: (20, 8)
```

(where I've changed the halt to print out the two values).  On those runs, the histogram output looked like this:

```
 XXXXXXXXXX
+----------+
 Raw Data
  0.00 - 0.10: 1
  0.10 - 0.20: 1
  0.20 - 0.30: 1
  0.30 - 0.40: 1
  0.40 - 0.50: 1
  0.50 - 0.60: 1
  0.60 - 0.70: 1
  0.70 - 0.80: 1
  0.80 - 0.90: 1
  0.90 - 1.00: 1
```

and

```
 XXXXXXXXXX
 XXXXXXXXXX
+----------+
 Raw Data
  0.00 - 0.10: 2
  0.10 - 0.20: 2
  0.20 - 0.30: 2
  0.30 - 0.40: 2
  0.40 - 0.50: 2
  0.50 - 0.60: 2
  0.60 - 0.70: 2
  0.70 - 0.80: 2
  0.80 - 0.90: 2
  0.90 - 1.00: 2
```

**Comment by bradcray** [comment] 2023-10-09 17:32
Oh, I think the problem is this line:

```
forall i in histogram.domain do
  histogramCopy = histogram[i].read();
```

which is doing a whole-array assignment to `histogramCopy` from a single element of `histogram` (?).  I.e., seems like the LHS should be `histogramCopy[i]`?  (or this could be written outside a loop as `histogramCopy = histogram.read();`)

**Comment by mstrout** [comment] 2023-10-09 17:35
I didn't know how to do the read on the whole histogram array so that is cool to know.

Yep, I know how to fix the code.  This github issue is to point out that there is no compiler error for `histogramCopy = histogram[i].read();`, and it seems like there should be a type error.

**Comment by bradcray** [comment] 2023-10-09 17:46
> This github issue is to point out that there is no compiler error for histogramCopy = histogram[i].read();, and it seems like there should be a type error.

Oh I see, thanks for clarifying.  I'd missed that and was focusing on the source of the divide-by-zero and what sounded like a mystery around `histogramCopy` not being an array.

This isn't intended to be a type error for the same reason that these statements aren't:

```chapel
var A: [1..1000] real = 1.0;  // OK to initialize an array with a scalar (of compatible type)
A = 2.0;  // OK to assign a scalar (of compatible type) to an array
```

which is that we support promoted assignments from scalars to arrays for convenience.

Because this is an error that can (and has) bitten people, we've occasionally discussed having a warning to flag such cases, like "Note that this statement is re-assigning this whole array within every iteration of this parallel loop, which is likely a race condition—is that what you meant?"  (where this would presumably fire only when the array was passed in with an (explicit or implicit) `ref` intent and when the array assignment was a top-level statement within the parallel loop).

> I didn't know how to do the read on the whole histogram array so that is cool to know.

Note that this isn't anything special, but just another instance of promotion.  That is, in

```chapel
histogramCopy = histogram.read();
```

`.read()` wants to take a single atomic, but here is given an array of atomics, so the RHS gets promoted to:

```chapel
histogramCopy = [h in histogram] h.read();
```

which effectively becomes the following in the array assignment code:

```chapel
forall (hc, h) in zip(histogramCopy, histogram) do
  hc = h.read();
```

**Comment by mstrout** [comment] 2023-10-09 18:00
> we support promoted assignments from scalars to arrays for convenience

Right.  Ok now I better understand this in my gut.  :) 

> we've occasionally discussed having a warning to flag such cases

Maybe there should be a `--wtf` flag that prints more warnings than we would normally want the compiler to show?  We would of course want to workshop the name of the flag.

**Comment by bradcray** [comment] 2023-10-09 18:07
It seems like this is a case we could get right and have on by default without creating a lot of noise—in that it's hard to imagine a correct program written as:

```chapel
var A: [...] ...;
forall ... [with (ref A)] {
  ...
  A = ...;
  ...
}
```

unless the forall loop only had a single trip count (in which case, I think the user arguably deserves a bit of noise).

But more generally I like your notion of "I want *all* the warnings!" that would tell you about a bunch of stuff that may or may not be useful ("Hey, did you know you're doing a promotion here?").  Of course, whether the user could tease the useful warning(s) out of a cloud of ones that would make them say "I know, I meant to do that" is another question.

**Comment by bradcray** [comment] 2023-10-09 22:02
I spun up https://github.com/chapel-lang/chapel/issues/23609 as a capture of the concept of warning about such cases, so am going to close this issue in favor of that one.  Though we've discussed a warning like this in the past, I couldn't find an issue capturing the notion with a quick search of some key terms.

**Closed by bradcray** 2023-10-09 22:02 UTC
Labels: type: Bug, area: Compiler
