### ISSUE TITLE
Explain why --fast isn't the default?

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7197] opened 2017-09-05 20:37 UTC
I don't get this, why not enable `--fast` as the  default and let people set `--show-and-crappy` when they want it slow and...

**Comment by mppf** [comment] 2017-09-05 20:57
My understanding of the design here is that people are expected to develop their program without `--fast` and test it too. Once they are happy it's written reasonably well, they turn on `--fast` before doing a big/production run.

For one thing, `--fast` turns off array bounds checks. If you would like to see somewhat friendly errors for that sort of failure, say if you have an off-by-one array indexing bug in your program, you need to run without `--fast`. Out of bounds array accesses are *undefined behavior* that can produce core dumps and memory corruption with `--fast`.

Like most `chpl` flags, `--fast` can be set with an environment variable. So you could set `CHPL_FAST=1` and then turn on bounds checking with `--bounds-checks`. However I wouldn't recommend doing it that way since the debugging messages can be really useful. But maybe you like core dumps better than I do :P.

**Comment by buddha314** [comment] 2017-09-05 20:59
Can you have a message before a core dump that says "Okay, buddy, you should probably turn on `--debug` now"?  That way they get to see the whiz-banginess of Chapel right from the start.  Not a strong opinion, but a suggestion.

**Comment by mppf** [comment] 2017-09-05 21:00
The problem is that *undefined behavior* doesn't necessarily produce a core dump. It might, for example, simply add 1 to all the results. Or cause the program to fail to print out anything. Or loop forever. Or ...

**Comment by ronawho** [comment] 2017-09-05 21:46
https://github.com/chapel-lang/chapel/issues/5476#issuecomment-284016367 has some more explanation of why checks are on by default.

**Comment by buddha314** [comment] 2017-09-05 21:50
These all make sense, but it seems like there should be a way for people to get the speed immediately, in one example, things have sped up from 5 hours to 101 seconds (thanks BenA).  That's the kind of performance that sells! I've been reluctant to put in `--fast` because I'm not sure how things will break, it kinda make sense to me to have `--debug` in my Makefile while testing, then remove it.  Close this ticket if you like.

**Comment by buddha314** [comment] 2017-09-05 21:52
And just a reply to Brad's opinion in the other ticket.  I completely see his point, but I feel that audience is the converts, they will take the time to work through completeness.  The other audience is new adopters who want to see the thing fly.

**Comment by e-kayrakli** [comment] 2017-09-05 23:04
As a long time Chapel user, I wanted to chime in.. I appreciate the current behavior of the compiler in this context. When I run bare `chpl`, I am either running a small snippet to check if some feature works as I expect, or during the development of a larger piece of code. By the time I am ready to run performance tests, I already have at least a basic Makefile, that generally throws in some `config param` adjustments and module paths etc etc.

So, I am in agreement with the no-fast-by-default camp because of ease of debugging. Another thing that I think worth mention is the compile time. A basic hello world compiles in ~5seconds without `--fast` and in ~7seconds with `--fast` (where most of the difference comes from the backend compilation) on my laptop. In LULESH the difference is 50sec vs 75sec. I think during development process (during which I postpone writing a Makefile), this compilation time difference can be annoying.

That being said, I am sympathetic with needing `--fast` on-by-default as I have also seen people (mostly junior grad students) frustrated by Chapel performance only to be shocked by orders of magnitude performance improvement they can get with `--fast`. That makes me wonder if compiler should throw a performance warning when `--fast` is omitted.. Note that there is a similar behavior when you throw in `--fast` but leave `CHPL_TARGET_ARCH` unset.

**Comment by mppf** [comment] 2017-09-06 13:20
@buddha314 said:
> things have sped up from 5 hours to 101 seconds

If throwing `--fast` had that big of a difference, I think we're asking the wrong question here. What I think you *should* be asking for is for performance improvements to the bounds checking, so that it's not O(n). My understanding is that the bounds checking - especially for sparse/associative array accesses - is inefficient. You can check if my hypothesis is correct by compiling with `--fast` and `--bounds-checks` and observing the performance.

I would guess that performance of code compiled without `--fast` has not received much attention and it wouldn't surprise me if there's a "Doh!" style performance issue in the bound checking itself.

**Comment by tmacd9** [comment] 2017-09-07 19:39
I can understand that improving the performance of unoptimized code is appealing.  I suspect the resources are not there right now.  Maybe they  will magically appear after I retire :-)

**Comment by buddha314** [comment] 2017-09-07 19:45
...ominous...

**Comment by ian-bertolacci** [comment] 2017-09-07 20:23
I agree that `--fast` should not be the default, and other compiler groups agree with this. For example, [GCC (and maybe the whole GNU compiler toolchain?) uses `-O0`](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html).

I think this is more of a marketing/advertising problem than anything.
When I first started writing chapel I did not know about the `--fast` flag, but now I do, and I know when to use it and tell other users about it as much as possible.
We could probably do a better job of telling people about this.

**Comment by dmk42** [comment] 2017-10-25 23:27
It looks like the conversation here has converged.  I sympathize with the OP (as you can see from the other issue) but we do have a decision to not make `--fast` the default.

Noting that on September 5, the OP stated it was OK to close the issue, I will do so.

**Closed by dmk42** 2017-10-25 23:27 UTC
Labels: area: Compiler, type: Design, user issue

**Comment by buddha314** [comment] 2017-10-25 23:29
I prefer to go by OPP. Yeah, you know me.
