### ISSUE TITLE
STDOUT iterates the message along with expanding the array

### ISSUE THREAD

**Issue by saru95** [chapel-lang/chapel#7082] opened 2017-08-23 16:01 UTC
## Summary of the problem / Steps to reproduce

The output of the following snippet:

```chpl
var a = [1, 2, 3, 4, 5];
writeln(a);
writeln("A is: " + a);
```

gives

```chpl
1 2 3 4 5
A is: 1 A is: 2 A is: 3 A is: 4 A is: 5
```

Try out @ https://tio.run/##S85ILEjN@f@/LLFIIVHBViHaUEfBSEfBWEfBREfBNNaaq7wosyQ1J08jURPBVnJUyCy2UlBS0FYACv//DwA

IMO, shouldn't the `writeln` try to not iterate over the message that is supplied with the array?

Expected output:

```chpl
1 2 3 4 5
A is: 1 2 3 4 5
```

**Comment by daviditen** [comment] 2017-08-23 16:35
What is happening here is that the `+` function is being [promoted](http://chapel.cray.com/docs/latest/users-guide/datapar/promotion.html) for the array.  The promoted `+` function creates an array of strings with the repeated "A is: " prefix: `["A is: 1", "A is: 2", "A is: 3", "A is: 4", "A is 5"]` that `writeln` goes on to print out.  To write the array directly use a comma instead of plus:

`writeln("A is: ", a);`

**Comment by saru95** [comment] 2017-08-23 17:03
@daviditen Does it happen on purpose? or is it still unexpected behavior inside of a `writeln`?

**Comment by daviditen** [comment] 2017-08-23 17:16
Yes, it is the intended behavior.  `writeln` is not the thing that is doing the promotion, the `+` function is.

The original example is more or less equivalent to the following:
```
var a = [1, 2, 3, 4, 5];
writeln(a);
var b = "A is: " + a;  // the promotion happens here, b is an array of strings
writeln(b);            // write out the array of strings
```

**Comment by ben-albrecht** [comment] 2017-08-23 17:33
@saru95 -- for more info on promotion, see the [users guide](http://chapel.cray.com/docs/master/users-guide/datapar/promotion.html).

**Comment by daviditen** [comment] 2017-08-23 17:36
This is behaving as intended, so I'm going to close the issue.

**Closed by daviditen** 2017-08-23 17:36 UTC
Labels: user issue
