### ISSUE TITLE
start_test: combine tests for faster compilation?

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#7568] opened 2017-10-10 06:35 UTC
I've noticed that in a start_test run, the compilation time for simple
tests is usually much greater than the execution time.  So I was
wondering if there'd be any interest in speeding up start_test runs by
combining multiple simple tests into one test.

First a motivating example, followed by more detailed thoughts.

I had been poking around at ``test/types/string/psahabu`` the other
day, so I picked it as an example.  The 6 straightforward tests in
this directory take 105 seconds to compile and run via ``start_test``:

``cd test/types/string/psahabu``

```
time start_test join-tuples.chpl join-varargs.chpl single-*.chpl split-whitespace.chpl

real    1m45.493s
user    1m39.632s
sys     0m2.980s
```

But only 18 seconds when they're all in a single file -- less than 1/5
as long.  (After renaming ``split-whitespace.chpl``'s "var empty" to
"empty2" to be unique.):

```
cat join-tuples.chpl join-varargs.chpl single-*.chpl split-whitespace.chpl > all.chpl
cat join-tuples.good join-varargs.good single-*.good split-whitespace.good > all.good

time start_test all.chpl

real    0m17.729s
user    0m16.968s
sys     0m0.336s
```

My impression is that a large portion of the Chapel tests are
similarly simple little standalone tests.  It seems like a full
start_test run could be substantially sped up by doing something like
this throughout the suite.  I imagine that it could help a paratest as
well.

Are these results representative of other people's, or is there just
something wrong with my setup?  (This is with CHPL_COMM=gasnet.)

If this is interesting,

There are a lot of classes of tests where this couldn't be done.
(Some of these apply more obviously to the more fleshed-out version
below):

* Tests where a compilation or runtime failure / halt is desired.
* Tests that are specifically about being in a top-level module.
* Tests that are specifically about the visibility of things in other modules.
* Tests that have a main() or module-level main().
* Tests with different compopts or execopts.
* Tests with prediffs
* Performance tests
* Test of compile speed.  :)

So I'm imagining this behavior would be driven by a file in the
directory manually specifying which tests should be consolidated.

Since this would be orchestrated by the ``start_test`` framework, it
could retry the constituent tests on failure.  That is, if the
combined test failed, it could run the individual tests separately, as
it does today, to be able to report which one(s) failed.

There's sometimes overhead required to make tests compatible with this
mode (e.g., renaming ``empty`` in the example above) when the files
are combined simply with ``cat``.  I think it would be simple to put
the contents of each .chpl file into its own module within the
``all.chpl``.  So e.g. tests ``a.chpl b.chpl c.chpl`` might be
"concatenated" to produce all.chpl:

```chapel
module A {
  writeln("Begin A");
  contents of a.chpl;
  writeln("End A");
}

module B {
  writeln("Begin B");
  contents of b.chpl;
  writeln("End B");
}

module C {
  writeln("Begin C");
  contents of c.chpl;
  writeln("End C");
}

use A; // If these are necessary to get the module init code to run?
use B;
use C;
```  

The generated module names could be more uniquified.

The ``writeln``s are to help distinguish what's going on when some of
the tests by design produce no output.

I assume that most tests, after this sort of transformation, will
provide the same coverage.  And that enough of such test could be
identified with little enough effort that it'd be worthwile.

I don't know how hard it would be to integrate with the paratest
machinery, as I've never used it.

**Comment by mppf** [comment] 2017-10-10 14:24
I've thought about this before and the idea is appealing. Where I think it becomes really challenging is in deciding which test directories are OK to have this behavior and which aren't. It'd be a lot of work to manually mark all of them - but I also think it'd be hard / confusing to come up with a heuristic.

I personally think that we should focus our effort towards separate compilation and faster compilation in the near term.

**Comment by lydia-duncan** [comment] 2017-10-10 14:46
I'd rather we spend effort on improving our compilation speed, as it is something that users have complained about (and it is slow in general).  This seems like a lot of work to avoid fixing that issue.

**Comment by cassella** [comment] 2017-10-11 08:58
I agree that faster compilation will be a more impactful improvement.

This test-combining scheme has the advantage that it feels like
something I could make progress on myself.  :)  And some
back-of-the-email calculations below suggest to me that even with a
faster compiler, consolidated compilation of the tests would still
make a significant difference.

I'm more worried about wrangling ``sub_test`` into doing this
transformation for me than about selecting which tests to combine.
The latter can be done on a piecemeal basis.  One directory at a time,
if need be.

Since the benefit of this approach scales with the number of
cooperating tests in a directory, the first place to look for
low-hanging fruit are the directories with the most tests:

```
fortytwo@magrathea:~/src/chapel (master)$ find test -name \*.chpl | xargs dirname | uniq -c | sort -n | tail -10
     33 test/modules/standard/math/promotion
     34 test/parallel/forall/vass
     36 test/classes/ferguson/forwarding
     39 test/functions/jturner
     44 test/functions/deitz/iterators
     45 test/classes/initializers/generics/phase1
     45 test/optimizations/cache-remote/ferguson/correctness
     50 test/classes/diten
     61 test/extern/ferguson/externblock
     81 test/classes/initializers/phase1
```

Those 10 directories contain 387 tests.

If (waves hands) a third of the tests are testing error cases or are
otherwise unsuitable for combining, that leaves 260 that are suitable.

At 15 seconds each, that's 55 minutes of compilation (on my machine).
Versus 3 minutes for 10 18-second compilations.  (Assuming the
compilation time doesn't actually increase much even for 60 tests.)

If the compiler were 10x faster, that'd be 18 seconds vs. 5.5 minutes.
I think that's still a transformative difference.


(I'm assuming the time to execute all these tests is negligible, so
that the time to run the tests is about the same as the time to
compile them.)


It seems to me that having quicker-running tests would make the
development of a faster compiler easier.  :)



On the other hand another con to this approach is the maintenance of
keeping the lists of combinable tests up to date as new tests are
added.

On the other other hand, another way of looking at it might be that
the tests that are combinable should just be combined to start with.

**Comment by mppf** [comment] 2017-10-11 13:43
@cassella - I'm more open to this if it's a project you want to pursue.

> On the other other hand, another way of looking at it might be that the tests that are combinable should just be combined to start with.

What if we wrote a script that combined them, and adjusted the test runner to have some idea of sub-tests within a given .chpl file?

**Comment by mppf** [comment] 2017-10-11 13:45
I should say, the main reason I (personally) end up writing a lot of tiny tests is that I end up debugging each separately. In debugging the compiler, it helps to limit the code involved. So whatever framework for combining tests would need to allow running just 1 sub-test at a time and possibly extracting just 1 sub-test for compilation.

**Comment by ronawho** [comment] 2017-10-11 18:18
This seems really tricky to get right to me and I worry that it would introduce a lot of potential problems if tests are inappropriately combined. I also don't think it's worthwhile to clutter the test directory even more than it already is. I also worry about things like if there's a sporadic regression, you've just made your test case much larger. There just seems like so many things to think about: what if output needs to be sorted for some tests and not for others, what about tests with prediff, preexecs, etc? I can't imagine having to think about the mergability of tests any time I modify a test.

While faster testing times are tantalizing, I don't think this is the right approach. A current (though not perfect) workaround it to use paratest. Paratest effectively runs multiple start_test clients concurrently so compilations can run concurrently. To test release/examples you could do something like:

```sh
source util/cron/common-oversubscribed.bash
source util/cron/common-localnode-paratest.bash
cd $CHPL_HOME/test
$CHPL_HOME/util/test/paratest.server -nodepara 4 -dirs release/examples
```

Personally, I'm pretty against this idea. If you're interested in contributing, I'm sure we can find something else :)

**Comment by buddha314** [comment] 2017-10-11 19:25
I know that @ben-albrecht has thought about building a Test Suite. Python's `unittest` framework and [Spring Test] allow you to bundle tests together that make sense.  This approach is widespread and I think would make a lot of sense to the community.  I mention some of this in #7495

**Comment by bradcray** [comment] 2018-03-20 23:28
I'm not seeing much support for this proposal and agree with the opinions expressed above that we should follow the K.I.S.S. principle for the testing system for sanity's sake and put our efforts into reducing compilation time itself, since this is also a pain point for users.  Closing this issue on that basis.

**Closed by bradcray** 2018-03-20 23:28 UTC
Labels: area: BTR, area: Tests, type: Design

**Comment by buddha314** [comment] 2018-03-20 23:32
FWIW we take the bundling approach for tests in [Charcoal](https://github.com/buddha314/Charcoal) like `unittest`.  I do agree with @bradcray that compilation is the more aggravating bit.
