### ISSUE TITLE
function visibility and default arguments

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7868] opened 2017-11-27 18:58 UTC
In PR #7858, I'm exploring how adjustments to the implementation of default arguments might resolve some current issues (and that effort is part of an effort to clean up iterator memory management).

I've encountered one issue, which I simply worked around in the PR. The issue is that before that PR, default arguments are resolved in the scope of the function in which they are declared, but after the PR, they are resolved in the scope of the call. That matters when the default argument is a function call that is marked private, as in the following example:.

``` chapel
module Library {
  private proc myZero(param rank : int, type idxType) {
    var ret : rank*idxType;
    return ret;
  }

  proc foo(param rank=1,
           type idxType=int,
           tup:rank*idxType = myZero(rank, idxType)) {
    writeln("In foo ", tup);
  }

}

module Test {
  use Library;

  proc main() {
    foo(1, real);
  }
}
```

I think we could support such code patterns with the work of the PR, but they would require some special treatment. One strategy would be for the compiler to create a function for each default argument at the scope of the function that they apply to. However I'm uncertain how valuable this pattern is from a language design point of view.

Such private default arguments seem questionable to me since I'd like users to be able to implement themselves whatever the compiler is doing with the default arguments. In other words, since `myZero` above is private, somebody wanting to explicitly pass it in to the `tup` argument of `foo` cannot do so.

Do we need to support this pattern?

**Comment by mppf** [comment] 2017-11-27 19:07
I don't believe such generalized function-call default arguments are possible in C#. C++ *does* allow this pattern, as with the example below:
``` c++
#include <cstdio>

class A {

  private:
    static int foo() {
      return 1;
    }

  public:
    void bar(int x=foo()) {
      printf("IN bar %i\n", x);
    }
};

int main() {
  A* a = new A();

  a->bar();
  return 0;
}
```

**Comment by benharsh** [comment] 2017-11-27 19:22
I don't think we should support this pattern because:
- It seems like users should be able to write the equivalent of the default argument themselves
- I can't think of a valuable use-case for default arguments initialized with private functions
- We can relax this constraint later if needed

**Comment by lydia-duncan** [comment] 2017-11-27 20:52
I think the answer should be no - in addition to the arguments you have put forward, the generated documentation for this interaction would be confusing to the reader trying to figure out how to use the function.

**Comment by daviditen** [comment] 2017-11-27 21:11
Would this also apply to `private` variables?  What about variables, types, and functions that aren't `private`, but just weren't `use`d?

```
module M1 {
  record R {}

  proc foo(x = new R()) {
    writeln(x);
  }
}

module M2 {
  proc main {
    use M1 only foo;
    foo();
  }
}
```

I think it would be pretty confusing for the apparent scopes for the function formals and the function body one line below to be so different.  I think the documentation can be made less confusing by just saying the default value is a call to a private function within the text of the doc.

**Comment by lydia-duncan** [comment] 2017-11-27 21:23
I think this should also apply to private variables.  I don't feel strongly about symbols that weren't used in the calling context, but that's a good case to consider

**Comment by noakesmichael** [comment] 2017-11-28 01:29
I am extremely confused by this thread and unsure how to move it forward.  I've had a few
off-thread discussions that have helped but I think there's still a lot that I don't understand.

However I now believe there might be considerations that are more primitive than the role
of the private keyword in all of this.  In particular I was concerned about one of the original
sentences i.e.



"The issue is that before that PR, default arguments are resolved in the scope of the
function in which they are declared, but after the PR, they are resolved in the scope
of the call."




This struck me as problematic if I have interpreted this correctly.

Consider the following program

```chapel
use A;

module A {
  proc foo() : int {
    return 10;
  }

  proc defaultFunc(x = foo()) {
    writeln('x = ', x);
  }
}

proc main() {
  defaultFunc();
}
```

It is clear that this program should print "x = 10".    I compiled
it on master and confirmed that it does.

How about this minor variation?

```chapel
use A;

module A {
  proc foo() : int {
    return 10;
  }

  proc defaultFunc(x = foo()) {
    writeln('x = ', x);
  }
}

proc foo() : int {
  return 20;
}

proc main() {
  defaultFunc();
}
```

I believe this should continue to print "x = 10" but that the proposed PR
would cause it to begin to print "x = 20".  I tested this

**Comment by noakesmichael** [comment] 2017-11-28 01:42
Here's the variation of this program that fails to compile

```chapel
module A {
  proc foo() : int {
    return 10;
  }

  proc defaultFunc(x = foo()) {
    writeln('x = ', x);
  }
}

module B {
  proc foo() : int {
    return 20;
  }

  proc main() {
    A.defaultFunc();
  }
}
```

The errors are

> chpl -o lexical-check lexical-check.chpl
lexical-check.chpl:16: In function 'main':
lexical-check.chpl:17: error: ambiguous call 'foo()'
lexical-check.chpl:2: note: candidates are: foo()
lexical-check.chpl:12: note:                 foo()


I believe this program should compile and print "x = 10".

**Comment by noakesmichael** [comment] 2017-11-28 02:06
Returning to a simple variation of the first simple program

```chpl
module A {
  proc foo() : int {
    return 10;
  }

  proc defaultFunc(x = foo()) {
    writeln('x = ', x);
  }
}

proc main() {
  A.defaultFunc();
}
```

Note that the main module does not use 'A'.  This program
compiles and behaves in the way I would expect.  It does
not bother me in the slightest that the following program
does not compile

```chpl
module A {
  proc foo() : int {
    return 10;
  }

  proc defaultFunc(x = foo()) {
    writeln('x = ', x);
  }
}

proc main() {
  A.defaultFunc();
  writeln('foo = ', foo());
}
```


Continuing in this vein the following program
compiles and generates the expected output

```chpl
use A;

module A {
  proc foo() : int {
    return 10;
  }

  proc defaultFunc(x = foo()) {
    writeln('x = ', x);
  }
}

proc main() {
  defaultFunc();
  writeln('foo = ', foo());
}
```


I think it is entirely correct and reasonable that this
variation does not compile

```chpl
use A;

module A {
  private proc foo() : int {
    return 10;
  }

  proc defaultFunc(x = foo()) {
    writeln('x = ', x);
  }
}

proc main() {
  defaultFunc();
  writeln('foo = ', foo());
}
```

while this one 

```chpl
use A;

module A {
  private proc foo() : int {
    return 10;
  }

  proc defaultFunc(x = foo()) {
    writeln('x = ', x);
  }
}

proc main() {
  defaultFunc();
}
````

compiles and produces the expected output.  It is clear to me that
the definition of the procedure foo() is defined in the same lexical
scope as the definition of defaultFunc() and so the symbol 'foo' is
visible even if it is defined not to be visible at the call site in main().

These follow the rules for lexical scoping and visibility in the
expected way and I do not believe these examples should raise any
concern.


I recognize that some people are concerned about the consequences
of 'private' in certain more complex use cases but I am not convinced
that the cited problems are actually a problem and even if they were
I don't think they should influence our understanding of this relatively
benign use case

**Comment by cassella** [comment] 2017-11-28 06:02
Besides visibility, scoping, and promotion, what about virtual functions with different default values for an argument?  For example,

```chapel
class C {
  proc foo(x = 10) { writeln("C.foo:", x); }
}

class D : C {
  proc foo(x = 20) { writeln("D.foo:", x); }
}

var d = new D();
d.foo();

var c: C = new D();
c.foo();
```

master currently prints

```
D.foo:20
D.foo:10
```

It's surprising me that the second call is being dynamically dispatched to ``D.foo()`` but picking up ``C.foo()``'s default value.

I think this is the behavior that the proposed change would require, since it'd have to evaluate the default value where the call is made, so the base class's method is the only one it knows about there.  But I'm wondering if that's really what should happen.


FWIW, the spec (16.2.5) says methods can be overridden and virtually dispatched if they have identical signatures.  But then it lists what's required to be considered identical: "names, types, and order".  It doesn't include default values.  (Or intents, for that matter.)  If the default value should be part of the identicalness, I'd think it either shouldn't compile, or shouldn't virtually dispatch in this case.

**Comment by mppf** [comment] 2017-11-28 15:36
Thanks @noakesmichael, @daviditen, and @cassella for the good examples! I've also verified that the example @daviditen showed doesn't work on master - for reasons similar to the examples @noakesmichael showed. I believe the issue on master is that the default wrapper function is being generated with fn->instantiationPoint set to the block containing the call. This is happening in buildEmptyWrapper. This behavior came from commit fc9c15575431e251cb3bdc1bb95c464fea6ef987 and I think we can do better now. We do have other questions to resolve (haha) about function visibility and generic functions, but at least I think we can make progress on this issue separately.

I'm fairly convinced by the arguments of @noakesmichael and @daviditen  that the default argument expression needs to resolve with a scope similar to the function body. I'll look in to adjusting my PR to do that.

**Closed** 2017-12-01 16:07 UTC
Labels: area: Language, type: Design
