### ISSUE TITLE
chpldoc support for module-level deinit

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#5791] opened 2017-03-22 22:02 UTC
### Summary of Problem
`chpldoc` crashes when a module has a documented module-level `deinit` function, introduced in #5744.

This resulted in the following PR breaking the docs:  #5769 

### Steps to Reproduce

**Source Code:**

```chapel
// deinit.chpl

module Foo {
  /* deinit function */
  proc deinit() {}
}
```
**Compile command:**
`chpldoc deinit.chpl`

**Associated Future Test(s):**
[`test/chpldoc/module/modDeinit.doc.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/chpldoc/module/modDeinit.doc.chpl
          ) #6238 

### Configuration Information

- Output of `chpl --version`: (master as of writing)

**Comment by lydia-duncan** [comment] 2017-03-22 22:06
Would you or @vasslitvinov add a future to the chpldoc/module test directory to track this?  Assuming the problem isn't specific to having a deinit function in a standard/package module

**Comment by ben-albrecht** [comment] 2017-03-22 22:40
It looks like the cause of error is that the code-path for `chpldoc` calls `appendClassName` on the function symbol, because it has a destructor flag, resulting in an assertion error in `AST/AstToText.cpp`:

```c

  else if (fn->hasFlag(FLAG_DESTRUCTOR) == true)
  {
    appendClassName(fn);
    mText += ".~";
    appendClassName(fn);
  }
```

**Comment by bradcray** [comment] 2017-03-22 22:46
@vasslitvinov : Should the module-level deinit() have a destructor?  I'd guess not, but am not sure what the consequences are...

**Comment by lydia-duncan** [comment] 2017-03-22 22:59
(Note also that new style initializers do not rely on FLAG_CONSTRUCTOR at the moment)

**Comment by lydia-duncan** [comment] 2017-05-15 16:55
I looked into what would happen if I limited when FLAG_DESTRUCTOR was applied.  Unfortunately it gets added at parse time, when we don't know if we're adding the function as a primary method or a module level function (unless it's a secondary method).  I think what I need to do is look into attaching the flag later in compilation and how that impacts the compiler.

**Comment by vasslitvinov** [comment] 2017-05-15 17:20
Module deinit() is in no way a destructor or deinitializer, as far as our init/deinit story is concerned.

FLAG_DESTRUCTOR is an implementation helper. If it causes trouble, I recommend removing it from module deinit() functions after parsing, when such functions are distinguished from actual deinitializers.

**Comment by lydia-duncan** [comment] 2017-05-19 15:37
checkParsed doesn't run before the docs pass, parsing is the only thing that runs before the docs pass.  So we can't remove FLAG_DESTRUCTOR from the functions it was incorrectly applied to before getting to documentation.  And really, if we're adding the flag to functions we shouldn't because we can't distinguish those cases, that implies that we are applying the flag too early in compilation.

Looking at the uses of FLAG_DESTRUCTOR, it seems like it isn't necessary until normalization (which is when FLAG_CONSTRUCTOR gets applied to user-defined constructors, so seems like an appropriate pass for the same action).  It also looks like there are more actions in normalization that don't distinguish between module deinit functions and Aggregate deinit functions, and there may be more later in compilation that I'm not seeing.  @vasslitvinov, can I pass this off to you, since you're more familiar with the deinit implementation and thus would be able to more quickly clean up the cases that should apply to one kind and not the other?  Moving the application of the flag to later in compilation should be all that is necessary to solve the chpldoc error, but I'm happy to take that portion off your hands again if this doesn't prove true.

**Comment by vasslitvinov** [comment] 2017-05-19 23:33
@lydia-duncan I assigned it to myself.

**Comment by vasslitvinov** [comment] 2017-07-25 22:58
@lydia-duncan When `AstToText::appendName()` is invoked on a class/record destructor, the name that it produces is CLASSNAME.~CLASSNAME. This seems obsolete. It should produce either CLASSNAME.deinit() or CLASSNAME.WHATEVER-NAME-THE-USER-WROTE.

If so, `AstToText::appendName()` shouldn't even pay attention to FLAG_DESTRUCTOR. If we remove that check altogether, it will generate the proper function name: "deinit" for module deinit functions, MyClass.~MyClass or MyClass.deinit() for class deinitializers. (or the same without "MyClass." if it's a primary method)

While there, I noticed that `AstToText::appendName()` for FLAG_CONSTRUCTOR does NOT prepend the class name, so the name ends up like "MyClass", rather than "MyClass.MyClass", even for secondary methods. Is that intentional? Does that case even happen?

**Comment by vasslitvinov** [comment] 2017-07-25 22:58
Oops, closed by mistake.

**Comment by vasslitvinov** [comment] 2017-07-25 23:01
P.S.1 The code in question is:

```c++
void AstToText::appendName(FnSymbol* fn)
{
.....
  else if (fn->hasFlag(FLAG_CONSTRUCTOR))
  {
    INT_ASSERT(strncmp(fn->name, "_construct_",      11) == 0);
    INT_ASSERT(false);//vass

    mText += (fn->name + 11);
  }
.....
```

P.S.2 If I remove the above else-if snippet from appendName(), all of the tests in test/chpldoc still pass.

**Comment by lydia-duncan** [comment] 2017-07-25 23:02
@vasslitvinov - the name gets mangled prior to the docs pass.  So instead of CLASSNAME.~CLASSNAME or CLASSNAME.WHATEVER-NAME-THE-USER-WROTE, you would get CLASSNAME._destructor_CLASSNAME, which is gross.  That's why that code is there.

**Comment by lydia-duncan** [comment] 2017-07-25 23:05
It seems likely that there aren't enough chpldoc tests to fully cover destructors, constructors, etc.  You are welcome to write some more :)

I believe the appending of "CLASSNAME." happens prior to entry to that function, but don't quote me on it.

**Comment by vasslitvinov** [comment] 2017-07-26 00:04
Examining the compiler, none of the following names are created prior to the docs pass:

_construct_
_type_construct_
_destruct_

So it would make sense to me to prune the corresponding code from AstToText::appendName.

**Comment by vasslitvinov** [comment] 2017-07-26 00:44
Why `proc this()` in MyClass is printed as `proc MyClass()`, regardless of whether it is a primary method or not? Why not display it more directly as:

```chpl
proc this(); // when primary method
proc MyClass.this();  // when secondary method
```

**Comment by lydia-duncan** [comment] 2017-07-26 15:07
AstToText is used outside of chpldoc.

Not sure about `proc this()` - I definitely didn't write that portion.  If you think it needs to be changed, that seems reasonable to me.  But that won't solve the deinit issue.

**Closed** 2017-07-27 21:53 UTC
Labels: area: Tools, type: Bug
