### ISSUE TITLE
Syntax errors can cause compiler assertion failures for developer builds/runs of the compiler

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#20501] opened 2022-08-24 19:00 UTC
### Summary of Problem
The following class and method declaration causes an assertion failure. Removing the explicit return type for the method or adding a colon (`foo(): CC`) makes it compile.

### Steps to Reproduce

**Source Code:**
```chapel
class CC {
  proc foo() CC {
    return new unmanaged CC();
  }
}
```

**Compile command:**
```
% chpl cc.chpl
Assertion failed: (scopeStack.back().tag == tag), function exitScope, file ./ParserContextImpl.h, line 345.
Abort trap: 6
```
### Configuration Information

- Output of `chpl --version`:
chpl version 1.28.0 pre-release (dc228b96ba)
  built with LLVM version 12.0.1

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: none *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: system *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system
CHPL_AUX_FILESYS: none

**Comment by bradcray** [comment] 2022-08-25 00:06
Wow, nice find!

Interestingly, I get a nicer `syntax error` for this as recently as Chapel 1.27.0 (which was using the dyno parser by default, right?)  So that suggests a potential recent regression and could be worth git bisecting for.

[We should really invest the time to create GitHub groups for each of the subteams so that I could @-tag the dyno team here...]

**Comment by bradcray** [comment] 2022-08-30 01:57
I'm getting a similar, but different error-due-to-a-syntax-error in this code:

```chapel
Assertion failed: (hasAttributeParts), function buildPragmaStmt, file ./ParserContextImpl.h, line 277.
Abort trap: 6
```

Like the previous error, it did not happen this way with 1.27.0.

**Comment by bradcray** [comment] 2022-08-30 02:01
I'm realizing that part of what makes this failure mode cause me to feel panicky when I see it (beyond it feeling like an undetected until last week backslide since 1.27.0) is that the assertions look so raw and developer-oriented.  Have we decided not to continue using INT_ASSERT() and the like in dyno?  And if so, where and when did that discussion take place?

**Comment by dlongnecke-cray** [comment] 2022-08-30 02:12
We tend to face this issue a lot when the Bison parser hits an error and recovers - state managed by our parser context isn't always unwound properly when that happens.

In this case, the parser probably starts parsing the function, pushes a new scope, and upon error recovers to the class-statement level. When it exits the class the tags don't match up.

I don't think the assert is anything to be alarmed at, yes we use `assert` instead of `INT_ASSERT` and the expectation there is that they will be turned off at some point. We might have an ongoing discussion about the role of asserts, (and I recall we did discuss it a bunch recently internally) but I can't remember what it is off the top of my head.

**Comment by bradcray** [comment] 2022-08-30 02:26
> We tend to face this issue a lot when the Bison parser hits an error and recovers - state managed by our parser context isn't always unwound properly when that happens.
> 
> In this case, the parser probably starts parsing the function, pushes a new scope, and upon error recovers to the class-statement level. When it exits the class the tags don't match up.

Is it clear to you what would've made this worse since the last release?  (it's not to me and I haven't had the heart to start git bisecting to try and find out).  E.g., one of the ~6 changes to `chpl.ypp`?  Or something outside of it?

**Comment by dlongnecke-cray** [comment] 2022-08-30 03:25
I just looked through the log for the `chpl.ypp` and it's not entirely clear to me either.

**Comment by bradcray** [comment] 2022-08-30 17:00
It turns out that the reason we're getting assertion failures here rather than syntax errors as we used to with 1.27.0 is that we were running a compiler built with `CHPL_DEVELOPER=true` whereas the 1.27.0 releases I was testing were not.  That makes this feel like an ain't broke / won't fix type of issue to me.

That said, I think it also suggests a design issue about whether a compiler run without `--devel` should trip over developer-oriented assertions based on how it was built (where my preference would be for it not to).  While we do have behavioral differences between `--devel` and `--no-devel` compiles, I can't think of others that are dependent on how the compiler was built (modulo things like performance or whether debugging symbols are available to the developer, but I wouldn't consider those to be user-facing behavioral differences).

**Comment by bradcray** [comment] 2022-09-10 00:56
@daviditen : I probably should've pinged you on this to see whether you agree this can/should be closed given the diagnosis above.

I've filed https://github.com/Cray/chapel-private/issues/3798 as a follow-up on the question about whether building with CHPL_DEVELOPER should lead to assertion failures even if compiling with `--no-devel`.

**Comment by daviditen** [comment] 2022-09-12 14:50
In my opinion an assert failing is an indication that something has gone wrong (or the assertion is incorrect). In this case it sounds like the thing that went wrong is that Bison recovered from an error but the dyno context didn't get updated properly and ended up in an unexpected state. It seems to me that there is a bug here even if we might not notice it in `--no-devel` mode, so I'd be inclined to keep this open.

**Comment by dlongnecke-cray** [comment] 2022-09-12 16:32
Thanks @daviditen, I agree!

**Comment by cassella** [comment] 2022-10-11 01:27
With a similar construction, I hit the `assert()` on the line after the one in the issue description,

```chapel
proc callsomething(fn) throws {
  try fn();
}

proc mainFunc() {
  callsomething(lambda() throws { });
}

mainFunc();
```

```
chpl: ParserContextImpl.h:346: void ParserContext::exitScope(chpl::uast::asttags::AstTag, chpl::UniqueString):
 Assertion `scopeStack.back().name == name' failed.
```

This appeared when I added the `throws` clause to the lambda expression.

It didn't happen if `callsomething` was called at file scope.

**Comment by bradcray** [comment] 2022-10-11 02:08
@cassella: Was your compiler also built with CHPL_DEVELOPER set?  Does re-building without it set cause the error to go away and the code to work?

**Comment by cassella** [comment] 2022-10-11 04:22
> Was your compiler also built with CHPL_DEVELOPER set? Does re-building without it set cause the error to go away and the code to work?

@bradcray: The error went away, but now it's a `syntax error near 'throws'`, which I've found now looks like #16580 (though I didn't provide a return type on my example).

**Comment by bradcray** [comment] 2022-10-11 04:55
Ah yeah, I think that's exactly the problem—that lambdas haven't supported `throws`.  @dlongnecke-cray has been working on beefing up lambdas recently and updating to new syntax proposed in https://chapel-lang.org/releaseNotes/1.26/06-ongoing.pdf.  From what I'm seeing it looks as though it supports `throws` (which is to say, if I change your code to:

```chapel
proc callsomething(fn): void throws {
  try fn();
}

proc mainFunc() {
  callsomething(proc() throws { });
}

mainFunc();
```

it seems to compile and run OK.

**Comment by cassella** [comment] 2022-10-11 05:14
Ah, thanks!  I see the same behaviors.

**Comment by bradcray** [comment] 2022-10-12 17:48
It sure was, thanks David!  I'm going to hide this part of the conversation since it's unrelated to the larger issue here (assertion failures due to syntax errors).

**Comment by milthorpe** [comment] 2022-11-02 23:28
I just hit the same assertion with this piece of (syntactically-invalid) code:
```
record foo {
  var xDom: domain(1) = {0..#100};
  proc createArray(): [] ?t {
    var a: [xDom] t;
    return a;
  }
}
var f: foo;
var x: [f.xDom] real = f.createArray();
```
The compilation result is:
```
$ chpl foo.chpl
chpl: ParserContextImpl.h:345: void ParserContext::exitScope(chpl::uast::asttags::AstTag, chpl::UniqueString): Assertion `scopeStack.back().tag == tag' failed.
Aborted (core dumped)
```
When I wrote it, I was hoping that the Chapel compiler would infer the return type parameter `t` from the variable `x` to which the array is being assigned. I realize that it's possible to achieve the same goal of type parametrization as follows:
```
record foo {
  var xDom: domain(1) = {0..#100};
  proc createArray(type t): [] t {
    var a: [xDom] t;
    return a;
  }
}
var f: foo;
var x: [f.xDom] real = f.createArray(real);
```
-- however, it would be nice if the compiler gave a more friendly error for this type of (wrong) program.

**Comment by dlongnecke-cray** [comment] 2022-11-03 00:03
Thanks for the bump @milthorpe. I think this issue has caused enough friction that it's worth searching for a fix.

**Comment by bradcray** [comment] 2022-11-03 00:34
(as a developer, I'd _really_ like to see this fixed, so @dlongnecke-cray / dyno team, please stop reading here).

Hi @milthorpe : Just to check an assumption (and hope) on my part:  Did you build this version of the compiler with `CHPL_DEVELOPER=true` set?  I ask because, to date, we've only seen this behavior for developer builds of the compiler (which is still annoying / not great, but at least it doesn't affect the typical end-user...).  For example, if I compile your program with a non-developer 1.28.0 version of Chapel, I get the better error:

```
testit.chpl:3: syntax error: near '?t'
```

(Again, though, I'd like to see this error rather than an assertion error as a developer as well).

And then, just for my curiosity, was your hope in the first version of the code that the compiler would look at the calling context, see that the array into which the result was assigned was an array of `real` and infer `t` to be `real` as a result?

**Comment by milthorpe** [comment] 2022-11-07 18:39
You're right, I set `CHPL_DEVELOPER=true` for my compiler build; the non-developer build error looks nicer. 

Yes, I hoped the compiler would unwrap the type of the assigned array to infer `t`. I think that Chapel's ability to pass explicit type parameters (as in my second example) is a good-enough solution for my purposes, and I can't currently think of an example where this wouldn't suffice.

**Comment by bradcray** [comment] 2022-11-18 22:40
I hit this again today due to having a syntax error in my code.  Couldn't figure out where it was without incrementally commenting out things I'd just changed until I happened to see what it was.  My kingdom for a syntax error!

**Comment by arezaii** [comment] 2022-12-01 16:38
https://github.com/chapel-lang/chapel/pull/21109 changes the assert behavior to not fire if `--no-devel` is passed to `chpl` or if `CHPL_DEVELOPER=0` or is unset. 

Tested with this reproducer:
```chapel
pragma "no doc"
proc Matrix(const Arrays: ...?n, type eltType) {
}

var C = Matrix([0,0],[0.0,1.0]);
writeln(C.eltType);
var D = Matrix([0.0,1.0],[1.0, 2.0],[0,0]);
writeln(D.eltType);
```

Built `chpl` with `CHPL_DEVELOPER` set to true:

```
// when compiled without --no-devel
[ParserContextImpl.h:265 in buildPragmaStmt] Assertion failed: hasAttributeParts
Aborted (core dumped)
```

```
// when compiled with --no-devel or after unsetting CHPL_DEVELOPER or setting CHPL_DEVELOPER false
reproducers/assertionOverSyntax.chpl:2: syntax error: near '...'
reproducers/assertionOverSyntax.chpl:2: syntax error: cannot attach 'pragma's to this statement
```

So when built with `CHPL_DEVELOPER` set to true, the behavior will remain if you leave `CHPL_DEVELOPER` untouched and don't pass any flags to `chpl`. 
The change makes it so that now if you want to opt into the "user experience", passing `--no-devel` will allow it. 
Further, if you wanted to allow the compilation to continue but still see the assertion failures, you can run `chpl` with `--ignore-errors`. 
Here is the output from the reproducer case when ran with `--ignore-errors`:
```
[ParserContextImpl.h:265 in buildPragmaStmt] Assertion failed: hasAttributeParts
reproducers/assertionOverSyntax.chpl:2: syntax error: near '...'
reproducers/assertionOverSyntax.chpl:2: syntax error: cannot attach 'pragma's to this statement
reproducers/assertionOverSyntax.chpl:2: internal error: seg fault [util/misc.cpp:970]
Note: This source location is a guess.
Segmentation fault (core dumped)
```

**Comment by bradcray** [comment] 2022-12-07 19:51
Thanks for the update here, @arezaii, and for moving the ball forward on this issue.  The assertions are still disconcerting to me, but we're definitely moving in the right direction.

I don't have time to do it at the moment, but it occurs to me we should file a future against this issue so that we're aware if/when it is fixed (though it may be that different syntax errors would cause very different assertion failures, in which case maybe it would not be as helpful?)

**Comment by bradcray** [comment] 2022-12-07 22:56
@arezaii pointed out a now-obvious mistake in my thinking:  Since his change makes assertions only trigger for developer-enabled builds, and we don't normally test developer builds, we wouldn't see the future start passing.  I was just lazily thinking "it would be nice to have a test that would tell me whether this issue was resolved or not" without thinking it all the way through.

**Comment by cassella** [comment] 2022-12-09 03:33
Here's another instance.  Non-developer mode reports a syntax error on line 2.


```chapel
class C {
  var c: pwned C;
}

var c: C;
```

```
[ParserContextImpl.h:114 in noteVarDeclKind] Assertion failed: !hasNotedVarDeclKind
Aborted (core dumped)
```

**Closed** 2023-12-05 01:20 UTC
Labels: type: Bug, area: Compiler, type: Error Message
