### ISSUE TITLE
init= not called with a isTuple() where clause

### ISSUE THREAD

**Issue by ShreyasKhandekar** [chapel-lang/chapel#18219] opened 2021-08-13 13:34 UTC
Currently we allow `init=` for records where the RHS does not need to be the same type as the Record itself. I was trying to utilize tuples in an `init=` function and was encountering a situation where it seemed like the function was not being called at all.

Here is a small reproducer of the same issue

A trivial record with two values
```chapel
record Foo {
    var x: int;
    var y: string;

    proc init(x: int, y: string){
        this.x = x + 1;
        this.y = y + "!";
    }

    proc init=(tup) where isTuple(tup){
        this.init(tup(0), tup(1));
    }

}
```

I initialized two variables here, one using the `init` function and one using  (in theory) `init=`
```chapel
var bar: Foo = new Foo(10, "Hi"); // Should call init
var baz: Foo = (11, "Bye"); // Should call init=
```

But when I printed these variables and some data associated with them I got the following:
```chapel
writeln(bar);
writeln(baz); // Quietly changed baz's type from Foo to a normal Tuple?

writeln(isTuple(bar)); // false
writeln(isTuple(baz)); // true ??
```
outputs:

```bash
(x = 11, y = Hi!)
(11, Bye)
false
true
```
This behavior seems very buggy since the correct function isn't called and the type of a variable is changed from what it was explicitly typed to be with no indication that it happened.

**Comment by bradcray** [comment] 2021-08-13 16:54
Thanks for filing this.  I'm curious (but haven't had time to check... yet), does declaring `tup` as `tup: _tuple` and removing the where clause work and give the expected behavior?  Do where clauses ever work for `init=` procedures?

**Comment by bradcray** [comment] 2021-08-13 18:03
Since posting that, I've verified that:
* using `tup: _tuple` doesn't change the behavior
* that adding a writeln() into that `init=` overload shows that it's never being called
* that even making `init=` completely generic doesn't cause it to be called

This suggests to me that the problem may relate more to using tuples on the RHS of an initialization expression than on anything specific to `init=` overloads or resolution (?).

**Comment by bradcray** [comment] 2021-08-13 18:12
It does appear that the compiler is rewriting the declaration of `baz` in a way that completely ignores its type.  Here's the ast dump just after resolution passes:

```
    (738334 'move' call_tmp[738331](211776 call _build_tuple[1342082] 11 "Bye"))
    (575049 'move' baz[211778](1342187 call chpl__initCopy[1342190] call_tmp[738331] 0))
```

**Comment by bradcray** [comment] 2021-08-13 18:21
Looks like it may be due to this conditional in functionResolution.cpp : resolveInitVar():

```c
  } else if (isRecord(targetType->getValType()) == false ||
             isParamString ||
             targetType->getValType()->symbol->hasFlag(FLAG_ARRAY) ||
             isDomainWithoutNew ||
             initCopySyncSingle ||
             srcType->getValType()->symbol->hasFlag(FLAG_TUPLE) ||                  /* HERE */                                                            
             initCopyIter) {
    // These cases require an initCopy to implement special initialization      
    // semantics (e.g. reading a sync for variable initialization).             
    //                                                                          
    // For example, even though domains can leverage 'init=' for basic          
    // copy-initialization, the compiler only currently knows about calls to    
    // 'chpl__initCopy' and how to turn them into something else when necessary 

    // Normally e.g. var y = foo() - where foo returns by value - will not add a                                                                               
    // copy and so the result of foo() need not be auto-destroyed.  However, if 
    // foo() is returning an array slice, then it is copied from and the source 
    // of the copy does need to be destroyed.

**Comment by bradcray** [comment] 2021-08-13 19:53
I've got a proposed five-minute fix for this bug that I think moves the ball forward.  Working on running it through testing now to make sure I haven't broken other things.

**Closed** 2021-08-13 22:54 UTC
Labels: type: Bug, area: Compiler
