### ISSUE TITLE
Brian's MEGA-ISSUE!!!

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7884] opened 2017-11-28 23:43 UTC
As to Bruce's suggestion, here is a semi-ordered list of the Github issues I've filed or am watching.

### Bigger Things
* Some arrays deserved to be sliced up: https://github.com/chapel-lang/chapel/issues/8819 
* Sparse matrix inversion's time has come! https://github.com/chapel-lang/chapel/issues/8546
* And how about Stochastic Gradient Descent, eh? https://github.com/chapel-lang/chapel/issues/6847
* More on sparse matrices: Modify: https://github.com/chapel-lang/chapel/issues/8044 and use derived vectors: https://github.com/chapel-lang/chapel/issues/8056
* A test harness, should include integration tests: https://github.com/chapel-lang/chapel/issues/7495
* Get a Jupyter Kernel all up in here: https://github.com/chapel-lang/chapel/issues/7414

### Smaller Things
* We are moving into production with a Chapel service, so JSON support has gotten pretty important https://github.com/chapel-lang/chapel/issues/8278
* I am always asking "what is the best way to do..."  Would be good to have some posted: https://github.com/chapel-lang/chapel/issues/7417 
* Clean up the REPL a bit: https://github.com/chapel-lang/chapel/issues/6760

LAST EDITED: 14 March, 2018

**Comment by saru95** [comment] 2017-12-06 09:09
Let's add a Jupyter notebook kernel to that list of issues.

**Comment by bradcray** [comment] 2018-01-04 23:17
@buddha314, can you clarify what you're using "big" vs. "small" to mean on this issue?  Originally, I was thinking we should use the two categories to mean "something that might take days to a week to months to work on" (big) vs. "something someone might help with if they had a few hours" (small), but I'm not sure you're using the same definition.  For example, adding Jupyter notebook support is expected to be a pretty massive effort due to the need for an interpreter of sorts.  @ben-albrecht thought you were using it to mean "big = important" vs. "small = would be nice, but not crucial", but to me that should just be reflected in the priority ordering (less important things would just always be further down on the list).  Thanks for clarifying for us.

**Comment by buddha314** [comment] 2018-01-04 23:19
I am an enigma...

I have been less that diligent on this.  Okay: Big: Seems like a lot of work.  Smaller Things: seem like less work.  Let me know if I'm wrong about the LOE and I'll move them.  In either case, the things towards the top should be "more important" in general.  I'll check this in a few minutes (by 5pm PT) and make sure it makes sense at least to me.

**Comment by bradcray** [comment] 2018-01-04 23:35
OK, sounds like our definitions agree then.  Maybe it was just the Jupyter support that got mis-filed when it was added in later in the game?  I can see the others potentially counting as "smaller".  Thanks!

**Comment by ben-albrecht** [comment] 2018-01-09 17:27
> Clean up the REPL a bit: #6760

@buddha314 - could you clarify this one a bit? Do you mean to clean up the documentation as to what is/isn't supported or something else?

**Comment by buddha314** [comment] 2018-01-09 17:32
Fair question.  Really, I'd like to be able to use the REPL at all.  Things like this still break:

```
IPE 0.1

 1 > var x = 2;
 2 > x + 3;
(null):2: syntax error: near ';'
   IpeMethod::evaluate(CallExpr*, IpeEnv*)  unsupported
   #<PrimOp error                1606
```
 I suppose I expect that once the above ticket gets started, we'll get other nice features in the REPL.  Also, it would be good to see some examples of what it can/not do at the moment.

**Comment by ben-albrecht** [comment] 2018-01-09 21:10
@noakesmichael can correct me on this, but I believe any improvements to the REPL are considered significant changes, since it currently requires some rearchitecting. I would consider this a *bigger thing* for now.

**Comment by noakesmichael** [comment] 2018-01-09 22:39
This question could be parsed in at least two ways



Q1) What would it take to develop a version of Chapel that
provided a meaningful interactive console aka REPL?


A1) There are a number of people who believe that we
should be applying resources to this but I think everyone
agrees that it would require a substantial level of effort
that we don’t know how to staff vs. other priorities.

There are a number of design decisions that are hardened
in the current implementation of the compiler that would
have to be revisited’/overhauled in order to support an
effective REPL.







Q2) Is it practical to make certain “improvements”
to the existing implementation to address, for example,
issue #6760?


A2) The answer is “yes” but I think this path would not
lead to an effective REPL even when repeated N times
for any practical value of N.


Hope this is helpful.

Mike















On Jan 9, 2018, at 1:10 PM, Ben Albrecht <notifications@github.com<mailto:notifications@github.com>> wrote:


@noakesmichael<https://github.com/noakesmichael> can correct me on this, but I believe any improvements to the REPL are considered significant changes, since it currently requires some rearchitecting. I would consider this a bigger thing for now.

**Comment by bradcray** [comment] 2018-01-10 19:53
One interpretation of issue #6760 is that our current REPL behavior and documentation are
out-of-sync due to changes in strings and c strings that occurred since then and changes to
the tests of the REPL that weren't reflected in the documentation.  It seems obvious to me
that one of the two should be updated, and I think that would be a reasonably low-effort.

But if the REPL item on this mega list is really meant to represent "I want a full-featured Chapel REPL" or "I want Chapel support for Jupyter notebooks) (and many people do want both these things) then I think it should refer to some other issue and be moved into the "bigger things" 
category.

**Comment by bradcray** [comment] 2023-06-20 18:38
I'm closing this issue because it was designed to help prioritize implementation tasks when @buddha314 and co. were actively developing in Chapel and has not been kept up-to-date in recent years.  The underlying issues it refers to will remain open.

**Closed by bradcray** 2023-06-20 18:38 UTC
Labels: user issue
