### ISSUE TITLE
Reproduce existing LAPACK.chpl with gen scripts

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#10976] opened 2018-09-04 21:26 UTC
`LAPACK.chpl` has diverged from the script-generated version. Ideally, additional changes to the module should be done in such a way that we could regenerate them with the script, so that we can automate changes made globally.

It seems like we currently need to update the `LAPACK` header, add `require` statements into function bodies instead of globally, and remove trailing whitespaces.

**Comment by ben-albrecht** [comment] 2018-09-04 21:27
@ian-bertolacci -- FYI

**Comment by riftEmber** [comment] 2024-04-23 17:08
I made a duplicate of this in https://github.com/chapel-lang/chapel/issues/10976 without realizing -- closing this one as the new one contains marginally more info

**Closed by riftEmber** 2024-04-23 17:08 UTC
Labels: area: Libraries / Modules, type: Unimplemented Feature
