### ISSUE TITLE
Need user docs for new CHPL_LLVM build requirement

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#17638] opened 2021-05-04 22:53 UTC
This issue is a continuation of [a thread](https://github.com/chapel-lang/chapel/pull/17615/files#r625515023) of comments in pull request #17615 .  I will repeat the main points here for convenience.

Since the merge of pull request #17615, our CI testing against chapel's master fails with the following when running make to build the runtime (except when CC/CXX are clang/clang++):

```
gmake[1]: Entering directory `/[...]/chapel'
Making the compiler...
rm -rf /[...]/chapel/third-party/llvm/install/none
cd llvm && /usr/bin/gmake
Error: Please set the environment variable CHPL_LLVM to a supported value.
Supported values are:
  1) 'none' to build without LLVM support
  2) 'bundled' to build with the LLVM packaged in the third-party directory
  3) 'system' to use a pre-installed system-wide LLVM
See: https://chapel-lang.org/docs/latest/usingchapel/chplenv.html#chpl-llvm
gmake[4]: *** [none] Error 1
gmake[3]: *** [/[...]/chapel/third-party/llvm/install/none] Error 2
gmake[2]: *** [compiler] Error 2
gmake[1]: *** [comprt] Error 2
gmake[1]: Leaving directory `/[...]/chapel'
```

I have one minor and one major "issue" with the current state of affairs when I do not set `CHPL_LLVM` (which "just worked" for me before).

The minor issue is my confusion at having configure print `CHPL_LLVM: none` and the subsequent `make` command tell me I must set it to one of a list of values which _includes_ the same `none` which was reported by `configure`.

The major issue is that I don't see user-facing documentation describing how to pick one of the three options to resolve the demand to set `CHPL_LLVM`.    At a minimum I'd like to know the PROs and CONs of the three options, and some explanation of the prerequisites for `system`.  I think that, in terms of current docs, at least usingchapel/QUICKSTART.rst, usingchapel/prereqs.rst and technotes/llvm.rst probably need revisions (though there may be others).  Related to this, the prior comment thread mentions that bundled is the default if "bundled is _already_ built" (emphasis mine), implying to me that there may be an additional step needed in the quickstart.

I'd be satisfied with seeing the two items above addressed, but also want to take a moment to enquire about the motivation to switch from something that "just worked" on every system I've attempted to use, to a requirement to explicitly select an option?  Why, for instance, is `bundled` not the default if the prereqs for `system` are not satisfied?

**Comment by bradcray** [comment] 2021-05-05 00:20
Hi Paul —

[Tagging @daviditen on this, who's leading the charge, and @mstrout for her general knowledge]

Thanks for filing this issue, and apologies for breaking your build and catching you off-guard.  I think we still haven't internalized very well that we have teams who are doing automated testing against our main branch, even though I should know it by now.

The rationale behind the current behavior is roughly as follows:

* we're working towards a world in which Chapel uses the LLVM back-end by default in order to get away from having to work so hard to keep Chapel working with all the various C compilers and versions that might be used with our generated code, to have more stable performance (rather than different performance based on the different C back-ends), and to leverage LLVM-based capabilities for vectorization and GPUs, among other reasons.
* the intent is to default to `CHPL_LLVM=system` whenever a version that we can make use of is available on the system
* the "safe option" is to use `CHPL_LLVM=bundled`, which would be a reasonable default to "just do" if the build-time for LLVM weren't so horrendous.  Essentially, we didn't feel like it would be a good thing to have a user unexpectedly step into a multi-hour build-time without either opting into it by setting the environment variable ("Yes, I know that this is going to take time, but I'm willing to pay it") or opting out of it ("OK, I know LLVM is the preferred back-end, but I'll take my chances with the C back-end / or install a compatible system version of LLVM myself.")

FWIW, our own testing is currently in a bit of a shambles as well (something we knew would happen and that we'd need to grit out teeth to get through), so our current focus is on getting through that at which point I hope we can make the documentation improvements you suggest to make the situation clearer for users.

Again, sorry not to have anticipated this or given you a heads-up on it before it happened,
-Brad

**Comment by PHHargrove** [comment] 2021-05-05 01:18
Thanks, @bradcray , for the response regarding the rationale for the changes.  In particular the reasoning behind not defaulting to `bundled` when `system` won't work makes sense to me now.  Given how time-intensive our CI is already, I'll plan to avoid that option.  Given our focus in CI is on exercising `CHPL_COMM=gasnet` (and not Chapel's application code generation), I suspect `none` is my best option except anywhere the prereqs for `system` are already met.  Please let me know if that is not the case.

The apologies for breaking GASNet CI are appreciated, but not strictly necessary.  I fully understand the risk associated with chasing your `master` branch.  I initially chose to pursue my questions in pull request comment instead of a full-blown issue specifically to avoid making too big a deal about it.

-Paul

**Comment by bradcray** [comment] 2021-05-05 01:52
> option. Given our focus in CI is on exercising CHPL_COMM=gasnet (and not Chapel's application code generation), I suspect none is my best option except anywhere the prereqs for system are already met. Please let me know if that is not the case.

I think that's right.  I didn't address your minor issue (because I feel less familiar with it), but I suspect that the default printing as `CHPL_LLVM=none` reflects the prior world and your point suggests to me that we might want to consider other settings like having the default value be `unset` (which might suggest the "Does the system version work?  If not, I'll print this message" behavior that you encountered); or perhaps having a value `system_or_none` that would say "use the system version if it's appropriate but none otherwise"?  (so that you don't have to figure out which to use on a system by system basis, for example).  I'll be curious what others who've worked more with the LLVM back-end think about this.

**Comment by PHHargrove** [comment] 2021-05-05 02:18
Thanks for the confirmation that `none` is a reasonable choice for my circumstances.  However, I have to follow-up by asking if you have an estimate as to how far in the future this may be dropped as an option.  I have no intention to apply pressure, but it helps me to plan work we may want to do at our end to enable `system` where we can.

On the subject of enabling `system`:  
As you have probably gathered from past reports, I try to aggressively chase GCC and LLVM releases and often have them into our nightly regression testing within a week of release.  As a result, I suspect I have LLVM-11 (and 11.1 and 12.0) installed on a large fraction of my CI systems.  However, I am not using the corresponding compilers as CC/CXX in many cases (as my intent is to get coverage of Chapel with GASNet built using various compilers).  So, what is the incantation to specify the LLVM install prefix (such as `/usr/local/pkg/llvm/11.0.0`) to be used as `system`?

**Comment by bradcray** [comment] 2021-05-05 02:55
Personally, I think we'll preserve CHPL_LLVM=none far into the future because being able to get up and running quickly without having to worry about an LLVM dependence will be attractive for quite some time, and it'll provide peace of mind to keep two back-ends going.  I think if/when we moved toward retiring the C back-end, our first step would be to retire support for so many C back-ends while still focusing on some common ones like gcc or clang.

I'm going to have to leave your second question for someone else or until I have more time tomorrow (but probably the former).

**Comment by PHHargrove** [comment] 2021-05-05 03:47
I've additionally discovered that even though setting `CHPL_LLVM=none` in the environment at `configure` time correctly records the setting in `chplconfig`, the subsequent `make` still dies telling me I must set `CHPL_LLVM` to one of the three supported values _unless_ the environment variable is _still_ set.  This seems contrary to the documented behavior/purpose of `configure` as I understand it.  For instance, `CHPL_COMM` and `CHPL_COMM_SUBSTRATE` set in the `configure` environment are effective in influencing the subsequent `make` of the runtime.

**Comment by mppf** [comment] 2021-05-05 13:43
>  So, what is the incantation to specify the LLVM install prefix (such as /usr/local/pkg/llvm/11.0.0) to be used as system?

We recently had this come up on Gitter as well -

https://gitter.im/chapel-lang/chapel?at=6084200b1f84d71853d8d46b

As far as I know the only option currently available is for the first `llvm-config-11` found in your path to be the right one, but even that might not work (since we'll also try to run clang for linking etc). So I think we need to introduce some kind of environment variable / setting on an environment variable to specify the prefix.

**Comment by bradcray** [comment] 2021-05-05 16:39
> I've additionally discovered that even though setting CHPL_LLVM=none in the environment at configure time correctly records the setting in chplconfig, the subsequent make still dies telling me I must set CHPL_LLVM to one of the three supported values unless the environment variable is still set. This seems contrary to the documented behavior/purpose of configure as I understand it. For instance, CHPL_COMM and CHPL_COMM_SUBSTRATE set in the configure environment are effective in influencing the subsequent make of the runtime.

This sounds correct to me.  @daviditen, is the root cause here clear to you?  Are we querying the environment variable directly rather than going through a chplenv script that would know about the configured information?  (which I could imagine being a necessity until we changed the default to something like `unset` as noted above because otherwise we might not be able to distinguish between a "configured" setting of CHPL_LLVM=none and an "inferred" setting of CHPL_LLVM=none?

**Comment by daviditen** [comment] 2021-05-05 17:07
> Are we querying the environment variable directly rather than going through a chplenv script that would know about the configured information? (which I could imagine being a necessity until we changed the default to something like unset as noted above because otherwise we might not be able to distinguish between a "configured" setting of CHPL_LLVM=none and an "inferred" setting of CHPL_LLVM=none?

Yes, that's correct. If the inferred value of `CHPL_LLVM` is `none`  but the `CHPL_LLVM` environment variable is not set we issue the "three options" error. Having the default inferred value instead be `unset` should help clarify things.

**Comment by daviditen** [comment] 2021-05-05 17:18
> Related to this, the prior comment thread mentions that bundled is the default if "bundled is already built" (emphasis mine), implying to me that there may be an additional step needed in the quickstart.

What I meant with that comment is that if you've previously done a build in your current `$CHPL_HOME` where you had `CHPL_LLVM=bundled` set so you've already built the bundled version, then future usage of the same `$CHPL_HOME` will infer that `CHPL_LLVM=bundled` even if the environment variable is no longer set.

**Comment by PHHargrove** [comment] 2021-05-07 23:40
@daviditen Thanks for the explanation of "bundled is already built".

**Comment by PHHargrove** [comment] 2021-05-07 23:48
I am successfully using `CHPL_LLVM=system` on multiple systems where I already have an llvm-11 build, simply by appending the appropriate `$prefix/bin` to `$PATH`.  The only case for which I am confident this is *not* going to work is cases where I am testing a different Clang (such as from LLVM 12.0.0, in particular) which is earlier in `$PATH`.  However, that is not a limiting factor for my usage and such systems (and macOS where I don't feel justified with 1.3GB for Homebrew's llvm@11 in my small VMs) will stay with `none`.

**Comment by bradcray** [comment] 2021-05-20 23:22
Hi @PHHargrove : As an update on one of your issues above:

> The minor issue is my confusion at having configure print CHPL_LLVM: none and the subsequent make command tell me I must set it to one of a list of values which includes the same none which was reported by configure.

I _believe_ that this should be resolved on the main development branch now as a result of @daviditen's PR #17786.  Specifically, we had been using `none` as both the default value for `CHPL_LLVM` and the explicit way to opt out of using LLVM.  This meant that in cases where it wasn't actively set to `none` in the user's environment (as in your configure case), the "hey, you need to make a decision"-style error message was being triggered.  The resolution was to introduce `unset` as the default value in order to better distinguish between these two cases.  If you have a chance to verify that this is the case, that would be great; if you want to wait until we've resolved your other LLVM build problems, that would be completely understandable.  Thanks again for reporting this; we don't use `configure` very often as developers, so would have taken awhile to notice it ourselves.

**Comment by PHHargrove** [comment] 2021-05-21 01:06
@bradcray I can confirm that the behavior is now self-consistent rather than self-contradicting.  
I think this is as good as this particular "pointy corner" is going to get, since you 'vemade a good case that when `system` doesn't work there is no "right" default between `none` and `bundled`.

**Comment by bradcray** [comment] 2021-05-21 01:10
Thanks for confirming, Paul.  We'll be continuing to look for ways to take the pain of this corner down a notch over time.  I'm not closing this issue because of the documentation issues you cite above, and also as a personal mental reminder of the other failure modes that you've encountered that we've discussed off-issue.

**Comment by ronawho** [comment] 2021-11-17 17:36
@daviditen Do we have this documentation now?

**Comment by daviditen** [comment] 2021-11-17 22:23
> @daviditen Do we have this documentation now?

Yes, I think the documentation for CHPL_LLVM is in pretty reasonable shape now.

**Closed by daviditen** 2021-11-17 22:23 UTC
Labels: type: Feature Request, area: Docs, user issue
