### ISSUE TITLE
internal error when using lambda inside a function

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14274] opened 2019-10-12 01:57 UTC
### Summary of Problem
Bug. Internal error when using lambda inside ~~`init`~~ a function.

### Steps to Reproduce

**Source Code:**

```chapel
class MyClass {
    var x: int;

    proc init() {
        var set = lambda(x: int) {
            this.x = x;
        };
        set(42);
        this.complete();
    }
}

proc main() {
    var myc = new owned MyClass();
    writeln(myc);
}
```
```terminal
internal error: RES-NIL-ING-0583 chpl version 1.21.0 pre-release (cba06531)
```

**Comment by cassella** [comment] 2019-10-12 02:56
This looks like the error in #6538.  I don't think it's related to initializers -- if I put the body of that `init()` into a new function (without the `this.complete()`), I get the same error.

**Comment by BryantLam** [comment] 2019-10-12 16:21
Thanks @cassella! You're right. I think part of what I'm looking for is a way to initialize an object during phase 1 (or something like `noinit` the object in phase 1 and then initialize in phase 2) without the overhead of default initialization if I need to initialize it in a specific way, such as a graph with directed edges or a large array.

Right now, it doesn't look like I can do that for a number of reasons: (this issue?), https://github.com/chapel-lang/chapel/issues/6976#issuecomment-407249369, #11195, 8792.

**Comment by cassella** [comment] 2019-10-12 16:53
I think you can use nested functions, so long as they don't try to initialize (or otherwise store to) fields of `this`,

```chapel
    proc init() {
        proc helper(x) {
	  return x;
        }

        this.x = helper(42);

        proc arrhelper(i) { return something_complicated(this.x, i); }

	this.a = for i in 1..n do arrhelper(i);

	this.complete();
	}
    }
```

Though I feel like I don't understand your requirements for the graph or large array cases.

**Comment by cassella** [comment] 2019-10-16 02:09
I think I need to walk back part of that claim.  There's some discussion in #6976 about what functions nested in an initializer may and may not do, though that was opened in the old initializers world.  I don't know if the `arrhelper()` I defined above is intended to be allowed to reference `this.x` in the new initializers world, whether or not it is so allowed today.

**Comment by cassella** [comment] 2023-04-25 05:32
@jabraham17 Now that you mention it (in https://github.com/chapel-lang/chapel/issues/6538) the code here no longer hits an internal error, but instead reports the same sort of error as in the .good file there,

```
foo.chpl:4: In initializer:
foo.chpl:5: error: cannot capture lambda because it refers to outer variables
foo.chpl:6: note: such as 'this', here
```

**Comment by jabraham17** [comment] 2023-04-28 15:03
Since PR #20991 resolved this, I agree I think this can be closed

**Comment by bradcray** [comment] 2023-05-01 17:47
@jabraham17 : What do you think needs to happen in order to do so?  File a test based on the OP to lock in the improved behavior?

**Comment by jabraham17** [comment] 2023-05-01 18:05
I think the existing tests in `functions/lambda/lambdaCapturing.chpl` and `users/engin/retInnerFunction.chpl` demonstrate this already. Since the issue is not related specifically to initializers, I don't think it needs a separate test

**Comment by bradcray** [comment] 2023-05-01 18:16
OK, is there anything else you think needs to happen before closing it then?  If not, have at it!  

(I don't think we'll get a confirmation from @BryantLam who hasn't had much time for Chapel programming lately, but it also looked like you weren't waiting for it on other issues of his you'd closed recently).

**Closed** 2023-05-01 18:20 UTC
Labels: type: Error Message, user issue
