### ISSUE TITLE
Clang prerequisite unclear in docs

### ISSUE THREAD

**Issue by ghbrown** [chapel-lang/chapel#19797] opened 2022-05-12 06:09 UTC
### Summary of Problem

setting `CHPL_ENV=system` then running `/util/printchplenv --all` gives error
```
Error: CHPL_LLVM=system but could not find an installed LLVM
with one of the supported versions: 13, 12, 11
```
even if LLVM is installed (from main Arch repositories).

I peaked into `chpl_llvm.py`, and I believe this happens because the way the LLVM version check works is by probing for Clang.
Perhaps it's my unfamiliarity with LLVM and Clang, but the [LLVM support page](https://chapel-lang.org/docs/technotes/llvm.html#readme-llvm) only mentioned having a system version of LLVM, as does the prose in the [prerequisite list](https://chapel-lang.org/docs/usingchapel/prereqs.html).
I now see that Clang is hiding in the *nix install commands, but that didn't help me (on Arch).

If Clang is indeed necessary with LLVM, I suggest that this be noted in at least the prerequisites list, but also perhaps elsewhere. Perhaps a prerequisites install line for Arch could also be useful?

```
sudo pacman -S gcc perl python bash make gawk git cmake llvm clang
```
I haven't tested that this covers all requirements, but these are the Arch names for the equivalent packages if they exist.

### Steps to Reproduce

```
sudo pacman -S llvm # will get version 13 as of this post
export CHPL_LLVM=system
${CHPL_HOME}/util/printchplenv --all
<get error in previous section>
sudo pacman -S clang
${CHPL_HOME}/util/printchplenv --all
<prints environment variables with "CHPL_LLVM: system *">
```

### Configuration Information

- pre-compile, but version 1.26.0
- output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_RE2: none
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
(after fix)

**Comment by mppf** [comment] 2022-05-12 13:47
I've done some limited testing with Arch in a VM and the below file includes the commands I used to get it working with LLVM:

https://github.com/chapel-lang/chapel/blob/main/util/devel/test/vagrant/provision-scripts/pacman-deps.sh

While I think it would be nice to improve the documentation (and somehow better maintain install lines for different OSes), in this case I think that the most useful thing to do would be to improve the error message to note that it found LLVM libraries but couldn't find clang dependencies.

**Comment by ghbrown** [comment] 2022-05-12 14:53
I agree the error message is the best first place to make Clang dependence clear, and would have saved me a bit of time searching the docs.

It could be good to have the same error message be reused when only system LLVM is present (no Clang) and the user doesn't manually set `CHPL_LLVM` (resulting in `CHPL_LLVM=unset` at compile time) if possible. Turns out you can run into essentially the same error in this case too, but you get the "set to supported value" error instead.

If I can help remedy things let me know.

On the packaging and install front, I'm hoping to update and improve the Chapel install in the Arch User Repository once I get things working smoothly on my end and get my feet a bit wetter in Chapel.

**Comment by stonea** [comment] 2022-05-27 17:48
Hi @ghbrown, I encountered a similiar issue as you (getting the message about a missing LLVM when the problem really had to do with a missing dependency) and submitted and merged this PR: https://github.com/chapel-lang/chapel/pull/19851

Unfortunatly, I didn't see this issue or your PR so I think I ended up reproducing your work about ensuring these missing dependency errors get to the user.

I wanted to make sure we now produce a better error message for Arch when clang isn't installed so I tried installing Chapel in a fresh Arch installation and it looks like now we'll (correctly) produce this error if you don't have LLVM installed:

`Error: CHPL_LLVM=system but could not find an installed LLVM with one of the supported versions: 14, 13, 12, 11`

And will now produce this error if you've installed `llvm` but not `clang`:

`Error: Missing clang command at /usr/bin/clang`

Here's more detailed notes showing the exact commands I ran:

<details>

```
-------------------------------------------------
Running without llvm installed produces an error about not having a supported LLVM
-------------------------------------------------

[stonea@archvm chapel]$ export CHPL_LLVM=system
[stonea@archvm chapel]$ make
Making the compiler...

Error: CHPL_LLVM=system but could not find an installed LLVM with one of the supported versions: 14, 13, 12, 11
/home/stonea/chapel/make/Makefile.base:106: *** error running util/printchplenv -- please see error above.  Stop.
make[1]: *** [Makefile:78: compiler] Error 2
make: *** [Makefile:59: comprt] Error 2

-------------------------------------------------
Install llvm and running make produces an error about missing clang at /usr/bin/clang
-------------------------------------------------

[stonea@archvm chapel]$ sudo pacman -S llvm
 ...
[stonea@archvm chapel]$ make
Making the compiler...

Error: Missing clang command at /usr/bin/clang
/home/stonea/chapel/make/Makefile.base:106: *** error running util/printchplenv -- please see error above.  Stop.
make[1]: *** [Makefile:78: compiler] Error 2
make: *** [Makefile:59: comprt] Error 2

-------------------------------------------------
After installing clang make will proceed as expected
-------------------------------------------------

[stonea@archvm chapel]$ sudo pacman -S clang
  ...
[stonea@archvm chapel]$ make
  ...
```

</details>

Let me know if you think this handles your issue.  If so I'll close this issue and PR.  Thanks!

**Comment by ghbrown** [comment] 2022-06-02 00:11
@stonea No problem.
If my memory serves, I just fed lower level errors that were already generated out to where they are reported on the command line, but I didn't write any extra checks, etc. I think your errors are perfectly reasonable and communicate the problem clearly, but I slightly prefer the ones I generate if I recall them properly.
I'm working on another PR tonight, but I'll make a comment reporting my errors in the two cases you gave, then we can discuss if anything should be changed, etc.

**Comment by ghbrown** [comment] 2022-06-03 22:57
@stonea No problem, and sorry for the delay. I was out of town and then focusing on another PR.

Just looked through both diffs, and the only difference a user would detect between our versions is the error message. In the case of compliant LLVM and missing Clang I give
```
Error: Found system LLVM but received error:
 Could not find the clang header /usr/include/clang/Basic/Version.h
Perhaps you need to install clang and llvm dev packages
```
which is a bit more verbose and direct. I added the first line, and the second two were hanging around but unused in some other functions.
However, I think the underlying problem is simple enough that such clarity is probably overkill. Also, your code looks less hacky than mine and is probably better integrated into the build/environment system for the long-term. I'm happy to close the issue and PR if you are.

**Closed** 2022-06-06 23:44 UTC
Labels: type: Error Message, area: Docs
