### ISSUE TITLE
Internal Chapel Error on Domain Query

### ISSUE THREAD

**Issue by upcrob** [chapel-lang/chapel#5231] opened 2017-01-25 03:27 UTC
### Summary of Problem

It looks like the Chapel compiler gives an internal error when you query an array's domain outside of a function header.  While I would expect to get an error in this case, I would expect it to be more informative (rather than the standard internal error that I get from the compiler).  If I set CHPL_DEVELOPER to true, it shows an assertion error being triggered on line 57 of `callInfo.cpp`.  Not a high priority issue, but it would probably be worth addressing eventually for user experience purposes.

### Steps to Reproduce

**Source Code:**

*foo.chpl*
```chapel
var x: [?D]int;
```

**Compile command:**

`chpl foo.chpl`

**Execution command:**

(not applicable)

### Configuration Information

chpl Version 1.14.0.5427d00

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none

gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by bradcray** [comment] 2017-01-25 18:43
This is a duplicate of issue #5140 which has already been fixed.

**Comment by ben-albrecht** [comment] 2017-01-25 18:46
@upcrob - thanks for the report. As noted, this is fixed on master. You can pull the latest changes from master to get the fix on your branch.

**Closed by ben-albrecht** 2017-01-25 18:46 UTC
Labels: stat: Duplicate, type: Error Message, user issue
