### ISSUE TITLE
Inconsistent behavior when using module's class/record without `use` statement

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#11868] opened 2018-12-12 00:00 UTC
Related #7857

Echoing [this statement](https://github.com/chapel-lang/chapel/issues/7857#issuecomment-363211386),
> It doesn't appear intuitive to allow constructing an object with the module prefix, but then prevent use of methods inside that object.

```chapel
module A {
  class C {
    var x: int;
    proc foo() { return x; }
  }
  record R {
    var x: int;
    proc foo() { return x; }
  }
}

// use A only;

var c1: A.C; // Ok
var c2 = new owned A.C(); // Ok

var r1: A.R; // error: unresolved call 'R.init()'
var r2 = new A.R(); // Ok
```

This behavior is inconsistent.
- `r1` is the only one that fails, and I didn't bring `module A` into scope with a `use` statement.

And non-intuitive.
- If I can define these variables, I should be allowed to use them. If I try to use the members of `C` and `R`, it predictably fails without a `use` statement.

```chapel
// c1 is nil; don't use it.

// These lines do not compile without `use A`.
writeln(c2.x);
writeln(c2.foo());

// r1 did not compile, so ignore it.

// These lines do not compile without `use A`.
writeln(r2.x);
writeln(r2.foo());
```
Of course, if I `use A only`, everything works.

Questions.
1. Why am I allowed to define a variable or construct an object, but not use its members when I do not have `use module [only]` active in the current scope?
2. What is the difference between `r1` and `r2` that allows `r2` to work when `r1`'s definition did not?

**Comment by mppf** [comment] 2018-12-12 13:31
@lydia-duncan - could it be that the special rules for method access outside the module aren't being applied to defaultOf?

**Comment by lydia-duncan** [comment] 2018-12-12 16:10
I believe @benharsh removed _defaultOf for records recently, so it might be that he missed adjusting the handling for records in this case (which is completely reasonable, I don't think it would be obvious to go look for it and we might not have added a record test when the initial support for creating a variable using a type defined in another module was added).

**Comment by lydia-duncan** [comment] 2018-12-12 16:14
As for the first question, it is a duplicate of #10397.  The short answer is I haven't gotten to it yet.

**Comment by mppf** [comment] 2020-02-05 18:14
Note that this is related to #14407

**Comment by mppf** [comment] 2020-03-19 20:11
@lydia-duncan - I would have expected PR #15003 to fix this but it does not

``` chapel
module A {
  record R {
    var x: int;
    proc foo() { return x; }
  }
}

var r1: A.R; // error: unresolved call 'R.init()'
var r2 = new A.R(); // Ok
```

do you happen to know more about this? Maybe we have to adjust the compiler-generated `R.init()` call in some way (say to indicate it comes from module A?)

**Comment by lydia-duncan** [comment] 2020-03-19 20:24
I didn't expect it to fix that, there's no use or import statement to follow when looking for calls.  If we're moving to a world where submodules need to be imported or used, I don't much see the point of fixing it (as the user is going to have to add an import or use, and doing so will resolve the problem)

**Comment by lydia-duncan** [comment] 2020-03-19 20:36
Additionally, I think looking into submodules when there isn't a use or import in the broad way we would need to for class and record methods is dangerous and defeats the point of following imports and uses for those symbols - everything is a submodule of the root module and we'll eventually get up to the root module's scope to look for symbols, so we'd always be looking in every module for methods.

**Comment by mppf** [comment] 2020-03-19 20:50
Before PR #10363, we used to sortof add an implicit 'use' statement for module mentions like this. It seems to me we would need to go back to doing something like that to resolve this issue if we didn't require submodules be imported/used.

**Comment by bradcray** [comment] 2020-03-20 18:06
Discussing with Michael, he proposed that if any mention of a sub-module caused an `import this.submodule;` to be inserted by the compiler at that point it would fix this issue without breaking anything else.  That seems compelling to me (though of course, we wouldn't want to insert this every time, just if it was necessary, or maybe once).

**Comment by lydia-duncan** [comment] 2020-06-05 22:40
So I've been thinking about this extension case for the last day or so, and figured I should run it by people:
```chapel
module Outer {
  module A {
    var x: int;
    record R { ... }
  }
  module B {
    use Outer; // or import Outer if the `A` was replaced with `Outer.A`

    proc main() {
      writeln(A.x); // This works today both for use and import
      var r : A.R;    // This does not work for either
    }
  }
}
```
Obviously the variable case and the record case should behave the same (and I believe they should both work).

Now, the solution of adding an import of a submodule to the scope where it is referenced would not help this case - the reference to A is not in a direct super module so checking on for if A is a submodule of the current scope won't detect it, but A *is* visible to that scope.  So I think we should still add an import of it and have that solution be implemented at the same time.  Thoughts?

**Comment by mppf** [comment] 2020-06-08 21:12
> Discussing with Michael, he proposed that if any mention of a sub-module caused an import this.submodule; to be inserted by the compiler at that point it would fix this issue without breaking anything else. That seems compelling to me (though of course, we wouldn't want to insert this every time, just if it was necessary, or maybe once).

> Now, the solution of adding an import of a submodule to the scope where it is referenced would not help this case - the reference to A is not in a direct super module so checking for if A is a submodule of the current scope won't detect it, but A is visible to that scope. So I think we should still add an import of it and have that solution be implemented at the same time. Thoughts?

I think you're saying that at

```
      var r : A.R;
```

it won't help to add `import this.A` (because A is not a submodule of the current module). And that if you add some sort of explicit import for A, it can work. Am I understanding correctly?

**Comment by lydia-duncan** [comment] 2020-06-08 21:50
Yup, that's exactly it

**Comment by lydia-duncan** [comment] 2020-06-08 22:05
Because we can resolve `A` due to the use (or `Outer.A` if we were instead using `import Outer`), the compiler could insert a direct import of A itself (we can make a SymExpr instead of an UnresolvedSymExpr that needs to get resolved).  However, that could potentially cause shadowing in more extreme applications, say:
```chapel
module A {
  module B {
    record R {
      var x: int;

      proc foo() {
        return x;
      }
    }
  }
}
var B = "blah";
{
  // if we inserted `import A.B;` to allow the following line, would that mean we can't
  // resolve B in the writeln after it?
  var r1: A.B.R;
  writeln(B);
}
```

**Comment by mppf** [comment] 2020-06-09 12:01
Alternatively, what if the method resolution strategy did it directly (looking into A.B as though it were imported, in this case)?

**Comment by lydia-duncan** [comment] 2020-06-09 15:18
The trouble is, the A.B portion isn't still around by the time function resolution occurs - we resolve module references during scope resolution and replace them with direct references to the symbols we found.  Otherwise when we inserted the automatic R.init call, we'd insert it with the A.B path as part of it

**Comment by mppf** [comment] 2020-06-09 15:35
Right, but we can solve that kind of thing by e.g. adding a primitive that keeps track of the modules named and finding it in resolution

**Comment by lydia-duncan** [comment] 2020-06-09 16:37
Hmm, you know what?  Maybe we could poke the ModuleSymbol's modUseList, since that already contains the modules referenced by the scope . . .

**Comment by lydia-duncan** [comment] 2020-06-09 21:52
Lol, nevermind, that grabs things that are made available due to use/import statements in inner scopes, e.g. this program that generated an error before the change

```chapel
module M1 {
  var a = 1;
  class C {
    var b = 2;
    proc foo() {
      return a+b;
    }
  }
}

module M2 {
  proc main {
    var c = bar();
    writeln(c.foo());
  }
  proc bar() {
    use M1;
    return new unmanaged C();
  }
}
```

**Comment by lydia-duncan** [comment] 2020-06-09 22:12
So I'm thinking I'll go back to your strategy of a new primitive, maybe attaching it to the BlockStmt like we do the useList field

**Closed** 2020-06-11 16:38 UTC
Labels: area: Compiler, area: Language, user issue
